src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AdditionalAccountFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-785 This field is a link to a 1:1 relations ship between Account and Additional Account Fields object.  It is created when a new account is created and is read only. The user can easily click on this field to see the related object.</description>
        <inlineHelpText>Created when a new account is created and is read only.</inlineHelpText>
        <label>Additional Account Fields</label>
        <referenceTo>AdditionalAccountFields__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AdditionalAccountFields__c.object
<CustomObject>
    <description>SFDC1-785 This is a separate Object created for capturing fields that are a 1:1 relationship with Account but are not attributes that we would consider governing. Many of these fields originated from the multitude of fields found on the account form in Legacy IHS.</description>
    <fields>
        <fullName>AccountReference__c</fullName>
        <inlineHelpText>Lookup Reference of the account connected to the Additional Account Fields</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Account Fields (Account)</relationshipLabel>
        <relationshipName>AdditionAccountFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Account Fields</label>
    <nameField>
        <label>Additional Account Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Account Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdditionalAccountFieldsMethods.cls
//-----------------------------
// @author: Uttam Arya
// @date: 22 Aug 2017
// @param: NA
// @description: SFDC1-2103 Class to hold Additional Account Fields trigger methods 
// @return: NA
//-----------------------------
public class AdditionalAccountFieldsMethods {

//-----------------------------
// @author: Uttam Arya
// @date: 22 Aug 2017
// @param: TriggerParameters tp
// @description: SFDC1-2103 Whenever an account is created, whether through an integration/data migration or manually created by a Data Governance user an "Additional Account Fields" 
//                          record belonging to the account is automatically created and a link to the record is populated in the "Additional Account Fields" field. 
//                          This function populate the Additional Fields lookup in Account.
//
// @return: None
//------------------------------
    public static void populateAdditionalFiledsLookupInAccount(TriggerParameters tp) {
    
        //List of Accounts that needs to be updated    
        List <Account> AccountsToUpdate = new List <Account>(); 
        
        for(AdditionalAccountFields__c aaf: (List <AdditionalAccountFields__c>) tp.newList) {
            if(aaf.AccountReference__c != null) {
                AccountsToUpdate.add(new Account(Id = aaf.AccountReference__c, AdditionalAccountFields__c = aaf.Id));
            }
        }
        
        //update if list has any records
        if(AccountsToUpdate != null && AccountsToUpdate.size() > 0) {
            update AccountsToUpdate;
        }
    }
}