src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GlobalUltimateAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-144 Lookup to the existing account that is the Global Ultimate account. Only updated by Customer Master Integration.</description>
        <inlineHelpText>Only updated by CDI Integration.</inlineHelpText>
        <label>Global Ultimate Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Ultimate Child Accounts</relationshipLabel>
        <relationshipName>GlobalUltimateChildAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AccountOverview__c.object
<CustomObject>
    <description>SFDC1-9063 Salesperson or a user in salesforce would be able to generate an Account Overview for a specific Account (and subsidiaries).</description>
    <fields>
        <fullName>Account1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-9063, Created for account overview report. This is a lookup field for account overview</description>
        <inlineHelpText>Lookup field for account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Overviews</relationshipLabel>
        <relationshipName>AccountOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExcludeSubsidiaries__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-9063, Created for account overview report. Shows Excluded contracts and opportunities for all subsidiaries.</description>
        <inlineHelpText>For showing excluded contracts and opportunities for all subsidiaries</inlineHelpText>
        <label>Exclude subsidiaries</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeAccountTeam__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-9063, Created for account overview report.</description>
        <inlineHelpText>Checkbox field to include account team</inlineHelpText>
        <label>Include Account Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeContractsatRisk__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-9063, Created for account overview report.</description>
        <inlineHelpText>Checkbox for report generator to show whether contracts are at risk or not</inlineHelpText>
        <label>Include Contracts at Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeKeyContacts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-9063, Created for account overview report. Checkbox to show whether to include key contacts</description>
        <inlineHelpText>Checkbox to show whether to include key contacts</inlineHelpText>
        <label>Include Key Contacts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeOpportunitiesOwner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-9063, Created for account overview report. Checkbox to include opportunity owner</description>
        <inlineHelpText>Checkbox to include opportunity owner</inlineHelpText>
        <label>Include Opportunities Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeRRRColumn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-9063, Created for account overview report.</description>
        <inlineHelpText>Checkbox to include Run Rate Revenue Column</inlineHelpText>
        <label>Include RRR Column</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeUpcomingTopRenewals__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-9063, Created for account overview report.</description>
        <inlineHelpText>Checkbox to include Top Renewals</inlineHelpText>
        <label>Include Upcoming Top Renewals</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OppQueryAmount__c</fullName>
        <description>SFDC1-9063, Created for account overview report. (Not visible to end users, for internal purpose only)</description>
        <formula>IF(ExcludeZeroValueOpportunities__c, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Query for opportunity amount</inlineHelpText>
        <label>Opp Query Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OppQueryProbabilty__c</fullName>
        <description>SFDC1-9063, Created for account overview report. (Not visible to end users, for internal purpose only)</description>
        <formula>IF(Exclude1Opportunities__c, 5, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Query for calculating probability of an opportunity</inlineHelpText>
        <label>Opp Query Probabilty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Account Overview</label>
    <nameField>
        <label>Account Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Overviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ApprovedContractSummary__c.object
<CustomObject>
    <description>SFDC1-9063, created for account overview report, Provides summary of approved contracts (Not visible to end user, for internal purpose only)</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>SFDC1-9063 Created for account overview report, Master-Detail for accounts</description>
        <inlineHelpText>Master-Detail for accounts</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Approved Contract Summaries</relationshipLabel>
        <relationshipName>ApprovedContractSummaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approved Contract Summary</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>Approved Contract Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Contract Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RenewalatRisk__c.object
<CustomObject>
    <description>SFDC1-4160 This object is used to identify a renewal at risk from an opportunity.
SFDC1-6706, label has been changed to &quot;Opportunity at Risk&quot;.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-4160 Auto populates with the Account from Opportunity</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity at Risk</relationshipLabel>
        <relationshipName>Renewals_at_Risk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractatRisk__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-4160 This field holds the contract at risk</description>
        <label>Contract at Risk</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Opportunity at Risk</relationshipLabel>
        <relationshipName>Renewals_at_Risk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityAtRisk__c</fullName>
        <description>SFDC1-4160 This field holds the Opportunity at Risk</description>
        <label>Opportunity At Risk</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity at Risk</relationshipLabel>
        <relationshipName>Renewals_at_Risk</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-4160 This field holds the status of risk,SFDC1-7668 Adding &apos;Closed - Opportunity Lost&apos; value</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Pending Resolution</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed - Risk Mitigated</fullName>
                </value>
                <value>
                    <fullName>Closed - Opportunity Lost</fullName>
                </value>
                <value>
                    <fullName>Closed - Non Renewal</fullName>
                </value>
                <value>
                    <fullName>Closed - Terminated</fullName>
                </value>
                <value>
                    <fullName>Closed - Downgraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity at Risk</label>
    <nameField>
        <displayFormat>OaR-{000000}</displayFormat>
        <label>Opportunity at Risk Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities at Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountOverviewData.cls
//-----------------------------
// @author: Harshit Singhal
// @date: 17 July 2018
// @description: SFDC1-5228 This class is used in some relationships under Account Overview Report DocGen package.
// @companyname: IHS Markit
//-----------------------------
global class AccountOverviewData implements Loop.IApexDataSource {
    
    //Interface Method 1 Implementation: getGlobalDescribe()
    public Set <String> getGlobalDescribe() {
        return new Set <String>{'AccountOverviewParameters','NoContracts','NoOppies','NoOppiesNoContract'};
    }
    
    //Interface Method 2 Implementation: describeObjects()
    public List <Loop.ExternalData.DataObject> describeObjects(List<String> objNames) {
        List <Loop.ExternalData.DataObject> output = new List <Loop.ExternalData.DataObject>();
        for (String objectName :objNames) {
            List <Loop.ExternalData.FieldInfo> outputFields = new List <Loop.ExternalData.FieldInfo>();
            if (objectName == 'AccountOverviewParameters') {
                outputFields.add(new Loop.ExternalData.FieldInfo('AccountIDS', Schema.DisplayType.String));
                outputFields.add(new Loop.ExternalData.FieldInfo('OppyswithoutOwnerSelectedIDS', Schema.DisplayType.String));
                outputFields.add(new Loop.ExternalData.FieldInfo('OppyswithOwnerSelectedIDS', Schema.DisplayType.String));
                outputFields.add(new Loop.ExternalData.FieldInfo('ContractswithoutRRSelectedIDS', Schema.DisplayType.String));
                outputFields.add(new Loop.ExternalData.FieldInfo('ContratswithRRSelectedIDS', Schema.DisplayType.String));
                outputFields.add(new Loop.ExternalData.FieldInfo('KeyContactsIDS', Schema.DisplayType.String));
                outputFields.add(new Loop.ExternalData.FieldInfo('ContractsAtRiskIDS', Schema.DisplayType.String));
                outputFields.add(new Loop.ExternalData.FieldInfo('AccountAndOppiesTop5IDS', Schema.DisplayType.String));
            }
            if (objectName == 'NoContracts' || objectName == 'NoOppies' || objectName == 'NoOppiesNoContract') {
                outputFields.add(new Loop.ExternalData.FieldInfo('Error', Schema.DisplayType.String));
            }
            output.add(new Loop.ExternalData.DataObject(objectName, outputFields));
        }
        return output;
    }
    
    //Interface Method 3 Implementation: getChildRelationships()
    public Set <String> getChildRelationships(String objectName) {
        return null;
    }
    
    //Interface Method 4 Implementation: query()
    public Loop.ExternalData.QueryResultSet query(Loop.ExternalData.QueryRequestInfo requestInfo) {
        
        Loop.ExternalData.QueryResultSet results = new Loop.ExternalData.QueryResultSet();
        
        Integer contractCount = 0;
        Integer oppiesCount = 0;
        Integer contractatRiskCount = 0;
        
        if (string.valueOf(requestInfo.RecordId).startswith(Schema.sObjectType.AccountOverview__c.keyprefix)) {
            AccountOverview__c rootAO = [SELECT  Id,Account1__c,Account1__r.Name,Account1__r.GlobalUltimateAccount__c,OppQueryAmount__c,OppQueryProbabilty__c, 
                                         ExcludeSubsidiaries__c,
                                         IncludeRRRColumn__c,IncludeOpportunitiesOwner__c,IncludeAccountTeam__c,IncludeContractsatRisk__c,IncludeKeyContacts__c,IncludeUpcomingTopRenewals__c                                          
                                         FROM AccountOverview__c 
                                         WHERE Id = :requestInfo.RecordId];
                        
            String idStringEmpty = '(\'\')';
            
            //HS
            String accIdStrings = '(\'\')';
            String accIdOpptyStrings = '(\'\')';
            List<String> accIdList = new List<String>();
            List<String> accIdOpptyList = new List<String>();
            
            if(rootAO != null) {
                if(!rootAO.ExcludeSubsidiaries__c && rootAO.Account1__c != null) {
                    System.debug('@HS Do not exclude Subsidiaries');
                    
                    Map <Id, Account > accountsSubsidaries = new Map <Id, Account>();
                    
                    if(rootAO.Account1__r.GlobalUltimateAccount__c != null) {
                        //For Level2,Level3,Level4, and so forth... accounts which have Global Ultimate not as null
                        accountsSubsidaries.putAll(new List<Account>([SELECT Id FROM Account WHERE GlobalUltimateAccount__c = :rootAO.Account1__r.GlobalUltimateAccount__c OR Id = :rootAO.Account1__r.GlobalUltimateAccount__c ]));
                    }
                    else {
                        //For Top-level accounts which have Global Ultimate as null
                        accountsSubsidaries.putAll(new List<Account>([SELECT Id FROM Account WHERE Id = :rootAO.Account1__c OR GlobalUltimateAccount__c = :rootAO.Account1__c]));
                    }
                    
                    
                    /*
                    //Get subsidiary Accounts' IDs
                    Map <Id, Account > accountsSubsidaries = new Map <Id, Account >([SELECT Id
                                                                                     FROM Account 
                                                                                     WHERE GlobalUltimateAccount__c = :rootAO.Account1__r.GlobalUltimateAccount__c ]);
                    */
                    
                    System.debug('@HS accountsSubsidaries Map size='+accountsSubsidaries.size());
                    for (Id thisId : accountsSubsidaries.keySet()) {                        
                        accIdList.add('\''+thisId+'\'');	//HS
                    }
                                        
                    //Get ApprovedContractSummary count
                    contractCount = [SELECT count() 
                                     FROM ApprovedContractSummary__c 
                                     WHERE Account__c in :accountsSubsidaries.keySet()];                      
                    //Get Opp at risk count
                    contractatRiskCount = [SELECT Count() FROM RenewalatRisk__c WHERE ContractatRisk__c != null and Account__c in :accountsSubsidaries.keySet() and Status__c = 'Open - Pending Resolution'];	//?? Some doubt between 'OpportunityAtRisk__c'/'ContractatRisk__c' lookup fields
                    
                    //Get Account IDs from valid new business opportunities
                    Map <Id, Opportunity> oppiesMap = new Map <Id, Opportunity>([SELECT AccountId 
                                                                                 FROM Opportunity 
                                                                                 WHERE RecordType.Name = 'New Business' 
                                                                                 AND IsClosed != true 
                                                                                 AND Probability >= :rootAO.OppQueryProbabilty__c 
                                                                                 AND Amount != null 
                                                                                 AND Amount >= :rootAO.OppQueryAmount__c 
                                                                                 AND AccountId in :accountsSubsidaries.keySet()]);
                    Set <Id> accountIds = new Set <Id>();
                    for(Opportunity opp :oppiesMap.values()) {
                        accountIds.add(opp.AccountId);
                    }
                    for (Id thisId : accountIds) {
                        accIdOpptyList.add('\''+thisId+'\'');	//HS
                    }                    
                                        
                    //HS                    
                    if(accIdList.size()>0) {
                        accIdStrings = String.valueOf(accIdList);
                    }
                    if(accIdOpptyList.size()>0) {
                        accIdOpptyStrings = String.valueOf(accIdOpptyList);
                    }                    
                    
                    oppiesCount = accountIds.size();
                }
                else if(rootAO.ExcludeSubsidiaries__c && rootAO.Account1__c != null) {
                    System.debug('@HS Exclude Subsidiaries');
                    //HS                    
                    accIdList.add('\''+rootAO.Account1__c+'\'');	//HS
                    
                    contractCount = [SELECT count() 
                                     FROM ApprovedContractSummary__c 
                                     WHERE Account__c = :rootAO.Account1__c];  
                    //Get Opp at risk count
                    contractatRiskCount = [SELECT Count() 
                                           FROM RenewalatRisk__c 
                                           WHERE ContractatRisk__c != null AND Account__c = :rootAO.Account1__c AND Status__c = 'Open - Pending Resolution'];		//?? Some doubt between 'OpportunityAtRisk__c'/'ContractatRisk__c' lookup fields
                    Map <Id, Opportunity> oppiesMap = new Map <Id, Opportunity>([SELECT AccountId 
                                                                                 FROM Opportunity
                                                                                 WHERE RecordType.Name = 'New Business' 
                                                                                 AND IsClosed != true 
                                                                                 AND Probability >= :rootAO.OppQueryProbabilty__c 
                                                                                 AND Amount != null 
                                                                                 AND Amount >= :rootAO.OppQueryAmount__c
                                                                                 AND AccountId = :rootAO.Account1__c]);
                    Set <Id> accountIds = new Set <Id>();
                    for(Opportunity opp:oppiesMap.values()) {
                        accountIds.add(opp.AccountId);
                    }
                    
                    for (Id thisId : accountIds) {
                        accIdOpptyList.add('\''+thisId+'\'');	//HS
                    }
                    
                    //HS                    
                    if(accIdList.size()>0) {
                        accIdStrings = String.valueOf(accIdList);
                    }
                    if(accIdOpptyList.size()>0) {
                        accIdOpptyStrings = String.valueOf(accIdOpptyList);
                    }
                    
                    oppiesCount = accountIds.size();
                }
                System.debug('@HS idStringEmpty='+idStringEmpty);
                System.debug('@HS accIdStrings='+accIdStrings);
                System.debug('@HS accIdOpptyStrings='+accIdOpptyStrings);
                //Prepare data for 'AccountOverviewParameters' fields
                String AccountIDSString = accIdStrings;
                
                String OppyswithoutOwnerSelectedIDSString = rootAO.IncludeOpportunitiesOwner__c == false ? accIdOpptyStrings : idStringEmpty;
                String OppyswithOwnerSelectedIDSString = rootAO.IncludeOpportunitiesOwner__c == true ? accIdOpptyStrings : idStringEmpty;
                
                String ContractswithoutRRSelectedIDSString = rootAO.IncludeRRRColumn__c == false ? accIdStrings : idStringEmpty;
                String ContratswithRRSelectedIDSString = rootAO.IncludeRRRColumn__c == true ? accIdStrings : idStringEmpty;
                
                String KeyContactsIDSString = rootAO.IncludeKeyContacts__c == true ? accIdStrings : idStringEmpty;
                
                String ContractsAtRiskIDSString = rootAO.IncludeContractsatRisk__c == true ? accIdStrings : idStringEmpty;
                
                String AccountAndOppiesTop5IDSString = rootAO.IncludeUpcomingTopRenewals__c == true ? accIdStrings : idStringEmpty;
                
                String NoContractsError = '';
                String NoOppiesError = '';
                String NoOppiesNoContractError = '';
                
                System.debug('@HS Debugging field values calculated for AccountOverviewParameters...');
                System.debug('@HS AccountIDSString=' + AccountIDSString );
                System.debug('@HS OppyswithoutOwnerSelectedIDSString=' + OppyswithoutOwnerSelectedIDSString );
                System.debug('@HS OppyswithOwnerSelectedIDSString=' + OppyswithOwnerSelectedIDSString );
                System.debug('@HS ContractswithoutRRSelectedIDSString=' + ContractswithoutRRSelectedIDSString );
                System.debug('@HS ContratswithRRSelectedIDSString=' + ContratswithRRSelectedIDSString );
                System.debug('@HS KeyContactsIDSString=' + KeyContactsIDSString);
                System.debug('@HS ContractsAtRiskIDSString=' + ContractsAtRiskIDSString);
                System.debug('@HS AccountAndOppiesTop5IDSString=' + AccountAndOppiesTop5IDSString );
                System.debug('@HS NoContractsError1=' + NoContractsError );
                System.debug('@HS NoOppiesError1=' + NoOppiesError );
                System.debug('@HS NoOppiesNoContractError1=' + NoOppiesNoContractError );
                
                if(contractCount == 0 && oppiesCount == 0 && rootAO.ExcludeSubsidiaries__c == true) {
                    NoOppiesNoContractError = 'IHS Markit currently does not have any active contracts or open opportunities with '+ rootAO.Account1__r.Name + '.';
                }
                else if(contractCount > 0 && oppiesCount == 0 && rootAO.ExcludeSubsidiaries__c == true) {
                    NoOppiesError = 'IHS Markit currently does not have any open opportunities with this customer.';
                }
                else if(contractCount == 0 && oppiesCount > 0 && rootAO.ExcludeSubsidiaries__c == true) {
                    NoContractsError = 'IHS Markit currently does not have any active contracts with this customer.';
                }
                else if(contractCount == 0 && oppiesCount == 0 && rootAO.ExcludeSubsidiaries__c == false) {
                    NoOppiesNoContractError = 'IHS Markit currently does not have any active contracts or open opportunities with '+ rootAO.Account1__r.Name + ' and any of its subsidiaries.';
                }
                else if(contractCount > 0 && oppiesCount == 0 && rootAO.ExcludeSubsidiaries__c == false) {
                    NoOppiesError = 'IHS Markit currently does not have any open opportunities with this customer and any of its subsidiaries.';
                }
                else if(contractCount == 0 && oppiesCount > 0 && rootAO.ExcludeSubsidiaries__c == false) {
                    NoContractsError = 'IHS Markit currently does not have any active contracts with this customer and any of its subsidiaries.';
                }
                
                System.debug('@HS NoContractsError2=' + NoContractsError );
                System.debug('@HS NoOppiesError2=' + NoOppiesError );
                System.debug('@HS NoOppiesNoContractError2=' + NoOppiesNoContractError );
                
                if (Schema.sObjectType.AccountOverview__c.isAccessible()) {
                    
                    for(string objectName :requestInfo.GetObjectNames()) {
                        
                        if (objectName == 'AccountOverviewParameters') {
                            Loop.ExternalData.QueryResult accountOverviewParameterResult = new Loop.ExternalData.QueryResult(objectName, new List <string >{'AccountIDS','OppyswithoutOwnerSelectedIDS','OppyswithOwnerSelectedIDS','ContractswithoutRRSelectedIDS','ContratswithRRSelectedIDS','KeyContactsIDS', 'ContractsAtRiskIDS','AccountAndOppiesTop5IDS'});
                            accountOverviewParameterResult.rows.add(new List <string>{AccountIDSString,OppyswithoutOwnerSelectedIDSString,OppyswithOwnerSelectedIDSString,ContractswithoutRRSelectedIDSString,ContratswithRRSelectedIDSString,KeyContactsIDSString,ContractsAtRiskIDSString,AccountAndOppiesTop5IDSString});      
                            results.add(accountOverviewParameterResult);
                            System.debug('@HS Results' + accountOverviewParameterResult);
                        }
                        
                        if (objectName == 'NoContracts' || objectName == 'NoOppies' || objectName == 'NoOppiesNoContract') {
                            Loop.ExternalData.QueryResult oppiesandContractsCountResult = new Loop.ExternalData.QueryResult(objectName, new List <string >{'Error'});
                            if(objectName == 'NoContracts' && NoContractsError != '') {
                                oppiesandContractsCountResult.rows.add(new List<string>{NoContractsError});
                            }
                            if(objectName == 'NoOppies' && NoOppiesError != '') {
                                oppiesandContractsCountResult.rows.add(new List<string>{NoOppiesError});
                            }
                            if(objectName == 'NoOppiesNoContract' && NoOppiesNoContractError != '') {
                                oppiesandContractsCountResult.rows.add(new List<string>{NoOppiesNoContractError});
                            }
                            
                            results.add(oppiesandContractsCountResult);                            
                            System.debug('@HS oppiesandContractsCountResult=' + oppiesandContractsCountResult);
                        }
                    }
                }
            }
            
        }
        System.debug('@HS results=' + results);
        return results;
    }
}