src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GlobalAccountManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-149 There will be Accounts that are GAM&apos;s and will be identified by the name of the GAM in the GAM Field on the account, this field is a lookup to users. Managing the GAM is in separate stories under the epic of adding the field.
SFDC1-4204 : Updated Lookup filter to allow only Salesforce Users.</description>
        <inlineHelpText>Please enter a Global Account Manager for this account.</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>GAMAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LostReasonCode__c</fullName>
        <description>SFDC1 -171 ; if the contract is Closed Lost then the Lost Reason Code from the Contract Should display. Otherwise the list of Lost Reason Codes for the Opportunity are listed here.
SFDC1-769 : Updated the Picklist Values and removed old Values.
SFDC1-6704 : Updated the Picklist Values and removed old Values.</description>
        <inlineHelpText>Choose a valid reason from the dropdown list</inlineHelpText>
        <label>Lost Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bankruptcy/Went out of business</fullName>
                </value>
                <value>
                    <fullName>Company Too Small/Retail/Commerce</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>Contact Non Responsive/Wrong Contact</fullName>
                </value>
                <value>
                    <fullName>Customer exiting business</fullName>
                </value>
                <value>
                    <fullName>Customer has merged / restructured</fullName>
                </value>
                <value>
                    <fullName>Customer Lost Bid</fullName>
                </value>
                <value>
                    <fullName>Cutting Costs/Lost Budget</fullName>
                </value>
                <value>
                    <fullName>Decided to do it Themselves</fullName>
                </value>
                <value>
                    <fullName>Duplicate/Existing Opp</fullName>
                </value>
                <value>
                    <fullName>IHSM Decision to Pass/No Bid</fullName>
                </value>
                <value>
                    <fullName>Key contact left company</fullName>
                </value>
                <value>
                    <fullName>Military Base Closure</fullName>
                </value>
                <value>
                    <fullName>No/low usage</fullName>
                </value>
                <value>
                    <fullName>No further interest, has all information needed</fullName>
                </value>
                <value>
                    <fullName>Non Payment</fullName>
                </value>
                <value>
                    <fullName>Out of business/Site Closure</fullName>
                </value>
                <value>
                    <fullName>Product/Solution does not match need</fullName>
                </value>
                <value>
                    <fullName>Product discontinued</fullName>
                </value>
                <value>
                    <fullName>Project completed/cancelled</fullName>
                </value>
                <value>
                    <fullName>Terms &amp; Conditions Issues</fullName>
                </value>
                <value>
                    <fullName>Unfavorable Pricing</fullName>
                </value>
                <value>
                    <fullName>Systematically Closed Lost - Past Due</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LostReasonDescription__c</fullName>
        <description>SFDC1 - 171 ; For lost contract/Deal; Describe the reason for lost deal</description>
        <inlineHelpText>Provide more information for losing this deal</inlineHelpText>
        <label>Lost Reason Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestBatchUpdateAccountOwnership.cls
//-----------------------------
// @author: Prachi Bhasin
// @date: 10th August 2017
// @description: SFDC1-1167  test class for BatchUpdateAccountOwnership and BatchUpdateAccountOwnershipScheduler
// @companyname: Vertiba
// @Last Modified By : Vinod Merwade
// @Last Modified Description : Corrected the Test class according to new validation rules on Opportunity
// @Last Modified Date : 19 Sept 2017
// @Last Modified By : Hemant Shukla
// @Last Modified Description : Removed the dependency of ContractExists__c field based on SFDC1-5701
// @Last Modified Date : 6-Nov-2017
//------------------------------
@isTest
private class TestBatchUpdateAccountOwnership {

    //-----------------------------
    // @author: Prachi Bhasin
    // @date: 10th August 2017
    // @param: NA
    // @description: SFDC1-1167  test method for BatchUpdateAccountOwnership class 
    // @return: NA
    // @lastmodifiedSprint : Sprint 9
    // @lastmodifiedBy : Prachi for SFDC1-1154 validation rule
    // @lastmodified description: Primary Contact roles needs to be created before updating opprtunity to stage 3 and above as per  SFDC1-5782 AND SFDC1-5029
    // @modifiedBy: Ankita Singh on 5th December,2017
	// @modifiedBy : Mohit Modi,11 June 2018, Updating Class as it is failing for 101 Query issue.
    //-----------------------------
    private static testMethod void testBatchUpdateAccountOwnershipClass() {
        //create test Data
        User owner1 = TestUtility.createTestUser('System Administrator','owner1@xyz11abc.com',false);
        User owner2 = TestUtility.createTestUser('System Administrator','owner2@xyz11abc.com',false);
        User owner3 = TestUtility.createTestUser('System Administrator','owner3@xyz11abc.com',false);
        insert new list<user> {owner1,owner2,owner3};
        
        Id standardId = Test.getStandardPricebookId();
        Account testAccount = TestUtility.createTestAccount('Account For Contract', true);
        
        Opportunity testOpportunity1 = TestUtility.createOpportunity(testAccount.Id, 'Closed Lost Opp', false);
        Opportunity testOpportunity2 = TestUtility.createOpportunity(testAccount.Id, 'Open Opp 1', false);
        Opportunity testOpportunity3 = TestUtility.createOpportunity(testAccount.Id, 'Open Opp 2 with Highest amount', false);
        testOpportunity1.Amount = 2000;
        testOpportunity1.ownerId = owner1.Id;
        testOpportunity2.Amount = 100;
        testOpportunity2.ownerId = owner2.Id;
        testOpportunity3.Amount = 1000;
        testOpportunity3.ownerId = owner3.Id;
        Test.startTest();
        insert new list<Opportunity> {testOpportunity1,testOpportunity2,testOpportunity3};
        
        testOpportunity1.StageName = '6L-Closed Lost';
        testOpportunity1.LostReasonCode__c = 'Project completed/cancelled';
        testOpportunity1.LostReasonDescription__c = 'test';
        update testOpportunity1;
        
        Database.QueryLocator QL;
        Database.BatchableContext BC;
        Set<String> closedOpportunityStages = new Set<String>{'6W-Closed Won', '6W-Renewal Won', '6L-Closed Lost'};
        BatchUpdateAccountOwnership batchObj = new BatchUpdateAccountOwnership();
        batchObj.query = 'SELECT Id,Name,OwnerId,Owner.Name,(Select Id, Name,OwnerId,Owner.Name, Amount, StageName from Opportunities where StageName NOT IN: closedOpportunityStages order by Amount DESC limit 1 ) FROM Account where GlobalAccountManager__c =null';
        Id batchId = Database.executeBatch(batchObj, 10);
        Test.stopTest();
        
        Account acc = [Select id,name,ownerId from account where id =: testAccount.Id];        
        System.assert(acc.ownerId==testOpportunity3.ownerId);        
  }
  
    //-----------------------------
    // @author: Prachi Bhasin
    // @date: 10th August 2017
    // @param: NA
    // @description: SFDC1-1167  test method for BatchUpdateAccountOwnershipScheduler class 
    // @return: NA
    //-----------------------------
    static testMethod void testBatchUpdateAccountOwnershipScheduler(){
        Test.StartTest();        
        BatchUpdateAccountOwnershipScheduler ba = new BatchUpdateAccountOwnershipScheduler(); //Schedule apex class name
        String sch = '0 0 8 13 2 ?'; //schedule interval time
        String jobId = system.schedule('Run Job for BatchUpdateAccountOwnershipScheduler', sch, ba); //system method to schedule apex class
        System.assert(jobId!=null);
        Test.stopTest();
  }
}