src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GlobalUltimateAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-144 Lookup to the existing account that is the Global Ultimate account. Only updated by Customer Master Integration.</description>
        <inlineHelpText>Only updated by CDI Integration.</inlineHelpText>
        <label>Global Ultimate Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Ultimate Child Accounts</relationshipLabel>
        <relationshipName>GlobalUltimateChildAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AccountOverview__c.object
<CustomObject>
    <description>SFDC1-9063 Salesperson or a user in salesforce would be able to generate an Account Overview for a specific Account (and subsidiaries).</description>
    <fields>
        <fullName>Account1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-9063, Created for account overview report. This is a lookup field for account overview</description>
        <inlineHelpText>Lookup field for account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Overviews</relationshipLabel>
        <relationshipName>AccountOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExcludeSubsidiaries__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-9063, Created for account overview report. Shows Excluded contracts and opportunities for all subsidiaries.</description>
        <inlineHelpText>For showing excluded contracts and opportunities for all subsidiaries</inlineHelpText>
        <label>Exclude subsidiaries</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Overview</label>
    <nameField>
        <label>Account Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Overviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <description>SFDC1-5807 : This field will hold the value of Comments</description>
        <inlineHelpText>Enter Comments related to Price Increase</inlineHelpText>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ContractApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-6735 : Field related  to Consulting Record Type</description>
        <inlineHelpText>Approval required if &gt;$100K or has Milestones or non-standard terms</inlineHelpText>
        <label>Contract Approved</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskProbability__c</fullName>
        <description>SFDC1-4163 This field is a roll up summary from renewal at risk object</description>
        <label>Risk Probability</label>
        <summarizedField>RenewalatRisk__c.RiskProbability__c</summarizedField>
        <summaryForeignKey>RenewalatRisk__c.OpportunityAtRisk__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RenewalatRisk__c.object
<CustomObject>
    <description>SFDC1-4160 This object is used to identify a renewal at risk from an opportunity.
SFDC1-6706, label has been changed to &quot;Opportunity at Risk&quot;.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-4160 Auto populates with the Account from Opportunity</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity at Risk</relationshipLabel>
        <relationshipName>Renewals_at_Risk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>SFDC1-4160 This field holds comments related to the renewal at risk</description>
        <label>Comments</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EstimatedValueatRisk__c</fullName>
        <description>SFDC1-4160 This field holds the estimated value at risk</description>
        <label>Estimated Value at Risk</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityAtRisk__c</fullName>
        <description>SFDC1-4160 This field holds the Opportunity at Risk</description>
        <label>Opportunity At Risk</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity at Risk</relationshipLabel>
        <relationshipName>Renewals_at_Risk</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RiskProbability__c</fullName>
        <description>SFDC1-4160 This field holds the risk probability</description>
        <label>Risk Probability</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Opportunity at Risk</label>
    <nameField>
        <displayFormat>OaR-{000000}</displayFormat>
        <label>Opportunity at Risk Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities at Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAccountOverviewData.cls
//-----------------------------
// @author: Jagadesh Kumar
// @date: 30 July 2018
// @param: NA
// @description: Test Class for AccountOverviewData
// @return: NA
//----------------------------
@isTest
public class TestAccountOverviewData {

    @isTest
    static void testAccountOverviewDataExclduleHierarchy() {
        Test.startTest();
        Account parentAccount = TestUtility.createTestAccount('BARCLAYS Parent',true);
        Account globalAcc = TestUtility.createTestAccount('Global Ultimate Account',true);
        Account a = TestUtility.createTestAccount('BARCLAYS PLC',false);
        a.ParentId = parentAccount.Id;
        a.GlobalUltimateAccount__c = globalAcc.Id;
        insert a;
        
        Opportunity opp = TestUtility.createOpportunity(a.id, 'BARCLAYS Opp',null,false);
        opp.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        opp.Probability = 0.50;
        opp.Amount = 100000;
        insert opp;
        
        Product2 testProd1 = TestUtility.createProduct('Test Product1', true);
        
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd1.Id, true);
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContractWithInsertOptional(a.Id, legalEntity.Id, country.Id, standardId,false);
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        contract1.recordtypeid = orderFormRecordTypeId;
        contract1.ContractApproved__c = true;
        insert contract1;
        
        RenewalatRisk__c opptyAtRisk = new RenewalatRisk__c();
        opptyAtRisk.OpportunityAtRisk__c = opp.Id;
        opptyAtRisk.Account__c = a.Id;
        opptyAtRisk.Comments__c = 'lost';
        opptyAtRisk.EstimatedValueatRisk__c = 500;
        opptyAtRisk.RiskProbability__c = 50;
        insert opptyAtRisk;
        
        AccountOverview__c ov = new AccountOverview__c();
        ov.Account1__c = a.Id;
        insert ov;
        
        Loop.ExternalData.QueryRequestInfo requestInfo = new Loop.ExternalData.QueryRequestInfo();
        requestInfo.RecordId = ov.Id;
        AccountOverviewData aod = new AccountOverviewData();
        aod.describeObjects(new List<String>(aod.getGlobalDescribe()));
        aod.getChildRelationships('AccountOverviewParameters');
        
        List<Loop.ExternalData.Relationship> Relationships = new List<Loop.ExternalData.Relationship>();
        for(String s: aod.getGlobalDescribe()){
            Loop.ExternalData.Relationship relationship = new Loop.ExternalData.Relationship();
            relationship.Name = s;
            Relationships.add(relationship);
        }
        requestInfo.Relationships = Relationships;
        
        Loop.ExternalData.QueryResultSet queryRS = aod.query(requestInfo);
        System.assert(queryRS!=null);
        
        Test.stopTest();
    }
    
    @isTest
    static void testAccountOverviewDataIncludeHierarchy() {
        Test.startTest();
        Account parentAccount = TestUtility.createTestAccount('BARCLAYS Parent',true);
        Account globalAcc = TestUtility.createTestAccount('Global Ultimate Account',true);
        Account a = TestUtility.createTestAccount('BARCLAYS PLC',false);
        a.ParentId = parentAccount.Id;
        a.GlobalUltimateAccount__c = globalAcc.Id;
        insert a;
        
        Opportunity opp = TestUtility.createOpportunity(a.id, 'BARCLAYS Opp',null,false);
        opp.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        opp.Probability = 0.50;
        opp.Amount = 100000;
        insert opp;
        
        Product2 testProd1 = TestUtility.createProduct('Test Product1', true);
        
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd1.Id, true);
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContractWithInsertOptional(a.Id, legalEntity.Id, country.Id, standardId,false);
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        contract1.recordtypeid = orderFormRecordTypeId;
        contract1.ContractApproved__c = true;
        insert contract1;
        
        RenewalatRisk__c opptyAtRisk = new RenewalatRisk__c();
        opptyAtRisk.OpportunityAtRisk__c = opp.Id;
        opptyAtRisk.Account__c = a.Id;
        opptyAtRisk.Comments__c = 'lost';
        opptyAtRisk.EstimatedValueatRisk__c = 500;
        opptyAtRisk.RiskProbability__c = 50;
        insert opptyAtRisk;
        
        AccountOverview__c ov = new AccountOverview__c();
        ov.Account1__c = a.Id;
        ov.ExcludeSubsidiaries__c = true;
        insert ov;
        
        Loop.ExternalData.QueryRequestInfo requestInfo = new Loop.ExternalData.QueryRequestInfo();
        requestInfo.RecordId = ov.Id;
        AccountOverviewData aod = new AccountOverviewData();
        aod.describeObjects(new List<String>(aod.getGlobalDescribe()));
        aod.getChildRelationships('AccountOverviewParameters');
        Loop.ExternalData.QueryResultSet queryRS = aod.query(requestInfo);
        System.assert(queryRS!=null);
        
        Test.stopTest();
    }
}