src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GlobalAccountManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-149 There will be Accounts that are GAM&apos;s and will be identified by the name of the GAM in the GAM Field on the account, this field is a lookup to users. Managing the GAM is in separate stories under the epic of adding the field.
SFDC1-4204 : Updated Lookup filter to allow only Salesforce Users.</description>
        <inlineHelpText>Please enter a Global Account Manager for this account.</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>GAMAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BatchUpdateAccountOwnership.cls
//-----------------------------
// @author: Prachi Bhasin
// @date: 9th August 2017
// @description: SFDC1-1167 This batch class will update account owners on the basis of highest value open 
//               opportunity owner for those accounts where GAM is not present
// @companyname: Vertiba
//------------------------------
global class BatchUpdateAccountOwnership implements Database.Batchable<sObject> {
    public String query;
    public Set<String> closedOpportunityStages = new Set<String>{'6W-Closed Won', '6W-Renewal Won', '6L-Closed Lost'};
    public List<Account> lstAccountsToBeUpdated = new List<Account>();
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        //String query = 'SELECT Id,Name,OwnerId,Owner.Name,(Select Id, Name,OwnerId,Owner.Name, Amount, StageName from Opportunities where StageName !=\'6L-Closed Lost\' order by Amount DESC limit 1 ) FROM Account where GlobalAccountManager__c =null';        
        return Database.getQueryLocator(query);   
    }
    global void execute(Database.BatchableContext BC, List<Account> scope) {       
        try {
            for(Account acc : scope)
            {
                if(acc.Opportunities != NULL) 
                {
                    for(Opportunity opp:acc.Opportunities)
                    {
                        acc.OwnerId = opp.ownerid;
                        lstAccountsToBeUpdated.add(acc);
                    }
                }
            }
            Database.update(lstAccountsToBeUpdated,false);
        }
        catch (Exception e) {
            System.debug('Error at line 33, method execute, class BatchUpdateAccountOwnership');
            ApexLogger__c apexLogRecord = new ApexLogger__c(ClassName__c='BatchUpdateAccountOwnership',ErrorDescription__c='Error at line 33',FunctionName__c='execute');
            insert apexLogRecord;
        }
    }
    global void finish(Database.BatchableContext BC) {
    }
}