src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Account Governance team.</inlineHelpText>
        <label>Account Governance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EmailUnknown__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-530 Allow user to enter a contact who will not provide their email address. When this field is checked, Business phone field is required. If this field is unchecked, email is mandatory.</description>
        <inlineHelpText>Please check this box if contact&apos;s email address is unknown. A phone number will be required in that case.</inlineHelpText>
        <label>Email Unknown</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReadyForProcessingContractExist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5701, this will be set to true by the process builder on Contract whenever Contract Status changes to &quot;Ready For Processing&quot;.</description>
        <label>Ready For Processing Contract Exist?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestCampaignInfluenceTrigger.cls
//-----------------------------
// @author: Anjani Shukla
// @company: VERTIBA
// @date: 08 Feb 2018
// @param: 
// @description:  This test class is used in SFDC1-6657 & 6636
//                used for CampaignInfluenceTrigger code coverage and validates 
//                Campaign & Opportunity 90 days from closed date to display error message.
// @return: NA
//----------------------------- 
@isTest
private class TestCampaignInfluenceTrigger {
    //-----------------------------
    // @author: Anjani Shukla
    // @company: VERTIBA
    // @date: 08 Feb 2018
    // @param: 
    // @description: This test class is used in SFDC1-6657 & 6636
    //               used for CampaignInfluenceTrigger code coverage and validates 
    //               Campaign & Opportunity 90 days from closed date to display error message.
    // @return: NA
    //----------------------------- 
    private static testMethod void testCampaignInfluenceMethods() {
        test.startTest();
         //create test data
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
                
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        User u = TestUtility.createTestUser('IHSMarkit Sales: General', 'testUSer.testuser123@ihsmarkit.com.user',true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Opppy', true);
        
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = testContact.Id;
        ocr.OpportunityId = testOpportunity.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;
         
        testOpportunity.StageName = '6W-Closed Won';
        testOpportunity.ContractId = contract1.id;
        testOpportunity.ContractStartDate__c = System.today();
        testOpportunity.ContractEndDate__c = System.today();
        testOpportunity.ActivityCreated__c = true;
        testOpportunity.ReadyForProcessingContractExist__c = true;
        testOpportunity.RecordTypeId = devRecordTypeId;
        testOpportunity.CloseDate = System.today()+90;
        update testOpportunity;         
        
        Id campaignRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Marketing Campaign').getRecordTypeId();
        Campaign Camp= new Campaign(Name='Test',recordTypeId=campaignRecordTypeId);
        insert Camp; 
        
        CampaignInfluenceModel testCampaignInfluenceModel = [SELECT DeveloperName FROM CampaignInfluenceModel limit 1];
        //insert testCampaignInfluenceModel;
        List<CampaignInfluence> campaignInfluLst = new List<CampaignInfluence>();
        CampaignInfluence testCampaignInfluence = new CampaignInfluence(ModelId = testCampaignInfluenceModel.id,CampaignId = Camp.id, OpportunityId = testOpportunity.id, ContactId = testContact.id); 
        campaignInfluLst.add(testCampaignInfluence);
        insert campaignInfluLst;
        system.assertEquals(1,campaignInfluLst.size());
        test.stopTest();
    }
    
    //-----------------------------
    // @author: Anjani Shukla
    // @company: VERTIBA
    // @date: 08 Feb 2018
    // @param: 
    // @description: This test class is used in SFDC1-6657 & 6636
    //               used for CampaignInfluenceTrigger duplicate 
    //               Campaign.
    // @return: NA
    //----------------------------- 
    private static testMethod void testCampaignInfluenceMethodsDupeCampInf() {
        test.startTest();
         //create test data
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
                
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        User u = TestUtility.createTestUser('IHSMarkit Sales: General', 'testUSer.testuser123@ihsmarkit.com.user',true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Opppy', true);
        
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = testContact.Id;
        ocr.OpportunityId = testOpportunity.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;
         
        testOpportunity.StageName = '6W-Closed Won';
        testOpportunity.ContractId = contract1.id;
        testOpportunity.ContractStartDate__c = System.today();
        testOpportunity.ContractEndDate__c = System.today();
        testOpportunity.ActivityCreated__c = true;
        testOpportunity.ReadyForProcessingContractExist__c = true;
        testOpportunity.RecordTypeId = devRecordTypeId;
        testOpportunity.CloseDate = System.today()+90;
        update testOpportunity;         
        
        Id campaignRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Marketing Campaign').getRecordTypeId();
        Campaign Camp= new Campaign(Name='Test',recordTypeId=campaignRecordTypeId);
        insert Camp; 
        
        CampaignInfluenceModel testCampaignInfluenceModel = [SELECT DeveloperName FROM CampaignInfluenceModel limit 1];
        //insert testCampaignInfluenceModel;
        List<CampaignInfluence> campaignInfluLst = new List<CampaignInfluence>();
        CampaignInfluence testCampaignInfluenceDupeContact = new CampaignInfluence(ModelId = testCampaignInfluenceModel.id,CampaignId = Camp.id, OpportunityId = testOpportunity.id, ContactId = testContact.id); 
        campaignInfluLst.add(testCampaignInfluenceDupeContact);
        try {
        	insert campaignInfluLst;
        }catch(DMLException e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains('This Campaign Influence Record already exists on this Opportunity.') ? true : false;
            System.AssertEquals(expectedExceptionThrown, false);    
        }
        campaignInfluLst.clear();
        test.stopTest();
    }
    
     //-----------------------------
    // @author: Anjani Shukla
    // @company: VERTIBA
    // @date: 08 Feb 2018
    // @param: 
    // @description: This test class is used in SFDC1-6657 & 6636
    //               used to check Opportunity 90 days from closed date to display error message.
    // @return: NA
    //----------------------------- 
    private static testMethod void testCampaignInfluenceMethodsOppty90Days() {
        
         //create test data
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
                
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        User u = TestUtility.createTestUser('IHSMarkit Sales: General', 'testUSer.testuser123@ihsmarkit.com.user',true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Opppy', true);
        
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = testContact.Id;
        ocr.OpportunityId = testOpportunity.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;
        test.startTest(); 
        testOpportunity.StageName = '6W-Closed Won';
        testOpportunity.ContractId = contract1.id;
        testOpportunity.ContractStartDate__c = System.today();
        testOpportunity.ContractEndDate__c = System.today();
        testOpportunity.ActivityCreated__c = true;
        testOpportunity.ReadyForProcessingContractExist__c = true;
        testOpportunity.RecordTypeId = devRecordTypeId;
        testOpportunity.CloseDate = System.today()+91;
        update testOpportunity;         
        
        Id campaignRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Marketing Campaign').getRecordTypeId();
        Campaign Camp= new Campaign(Name='Test',recordTypeId=campaignRecordTypeId);
        insert Camp; 
        
        CampaignInfluenceModel testCampaignInfluenceModel = [SELECT DeveloperName FROM CampaignInfluenceModel limit 1];
        //insert testCampaignInfluenceModel;
        List<CampaignInfluence> campaignInfluLst = new List<CampaignInfluence>();
        
        CampaignInfluence testCampaignInfluence = new CampaignInfluence(ModelId = testCampaignInfluenceModel.id,CampaignId = Camp.id, OpportunityId = testOpportunity.id, ContactId = testContact.id); 
        campaignInfluLst.add(testCampaignInfluence);
        insert campaignInfluLst;
        system.assertEquals(1,campaignInfluLst.size());
        
        CampaignInfluence testCampaignInfluenceDupeContact = new CampaignInfluence(ModelId = testCampaignInfluenceModel.id,CampaignId = Camp.id, OpportunityId = testOpportunity.id, ContactId = testContact.id); 
        campaignInfluLst.add(testCampaignInfluenceDupeContact);
        try {
        	insert campaignInfluLst;
        }catch(DMLException e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains('This Campaign Influence Record already exists on this Opportunity.') ? true : false;
            System.AssertEquals(expectedExceptionThrown, false);    
        }
        campaignInfluLst.clear();
        Account a = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', false);
        a.DataGovernanceStatus__c = 'Approved';
        insert a;
        
        Contact c = new Contact();
        c.firstname = 'Test';
        c.lastname = 'testSetCaseAdditionalFieldsObject';
        c.AccountId = a.Id;
        c.Phone = '12345';
        c.EmailUnknown__c = true;
		insert c;
        
        CampaignInfluence testCampaignInfluenceOpptyOver90Days = new CampaignInfluence(ModelId = testCampaignInfluenceModel.id,CampaignId = Camp.id, OpportunityId = testOpportunity.id, ContactId = c.id); 
        campaignInfluLst.add(testCampaignInfluenceOpptyOver90Days);
        try {
        	insert campaignInfluLst;
        }catch(DMLException e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains('Please verify - Opportunity Close Date is over 90 days. You cannot add New Campaign Influence Record') ? true : false;
            System.AssertEquals(expectedExceptionThrown, false);    
        }
        
        campaignInfluLst.clear();
        test.stopTest();
    }
    
    //-----------------------------
    // @author: Anjani Shukla
    // @company: VERTIBA
    // @date: 08 Feb 2018
    // @param: 
    // @description: This test class is used in SFDC1-8326
    //               when Campaign Influence record is created,then
    //               equal percentage attribution.
    // @return: NA
    //----------------------------- 
    private static testMethod void testCampaignInfluenceCreationwithEqualPercent() {
    	 //create test data
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
                
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        User u = TestUtility.createTestUser('IHSMarkit Sales: General', 'testUSer.testuser123@ihsmarkit.com.user',true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Opppy', true);
        
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = testContact.Id;
        ocr.OpportunityId = testOpportunity.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;
        test.startTest(); 
        
        
        List<Campaign> insertCampaign = New List<Campaign>();
        
        Id campaignRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Marketing Campaign').getRecordTypeId();
        Campaign Camp1 = new Campaign(Name='Test 1',recordTypeId=campaignRecordTypeId);
        insertCampaign.add(Camp1); 
        
        Campaign Camp2 = new Campaign(Name='Test 2',recordTypeId=campaignRecordTypeId);
        insertCampaign.add(Camp2); 
        
        insert insertCampaign;
        
        CampaignInfluenceModel testCampaignInfluenceModel = [SELECT DeveloperName FROM CampaignInfluenceModel limit 1];
        List<CampaignInfluence> campaignInfluLst = new List<CampaignInfluence>();
        
        CampaignInfluence testCampaignInfluence = new CampaignInfluence(ModelId = testCampaignInfluenceModel.id,CampaignId = insertCampaign[0].id, OpportunityId = testOpportunity.id, ContactId = testContact.id); 
        campaignInfluLst.add(testCampaignInfluence);
        
        CampaignInfluence testCampaignInfluenceDupeContact = new CampaignInfluence(ModelId = testCampaignInfluenceModel.id,CampaignId = insertCampaign[1].id, OpportunityId = testOpportunity.id, ContactId = testContact.id); 
        campaignInfluLst.add(testCampaignInfluenceDupeContact);
        insert campaignInfluLst;
        
        system.assertEquals(2,campaignInfluLst.size());
		Set<Id> campaignInflIds = new Set<Id>();        
        campaignInflIds.add(campaignInfluLst[0].id);
        campaignInflIds.add(campaignInfluLst[1].id);
        List<CampaignInfluence> getCampInflDetails = [select influence from CampaignInfluence 
                                                      where ID IN: campaignInflIds] ;
        
        
        system.assertEquals(50, getCampInflDetails[0].influence);
        system.assertEquals(50, getCampInflDetails[1].influence);
        test.stopTest();
    } 
    
     //-----------------------------
    // @author: Anjani Shukla
    // @company: VERTIBA
    // @date: 08 Feb 2018
    // @param: 
    // @description: This test class is used in SFDC1-8326
    //               when Campaign Influence record is deleted from an opportunity
    //               then, percentage should be recalculated based on number of Camp Influence record count.
    // @return: NA
    //----------------------------- 
    private static testMethod void testCampaignInfluenceCreationonDelete() {
    	 //create test data
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
                
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        User u = TestUtility.createTestUser('IHSMarkit Sales: General', 'testUSer.testuser123@ihsmarkit.com.user',true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Opppy', true);
        
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = testContact.Id;
        ocr.OpportunityId = testOpportunity.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;
        test.startTest(); 
        
        
        List<Campaign> insertCampaign = New List<Campaign>();
        
        Id campaignRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Marketing Campaign').getRecordTypeId();
        Campaign Camp1 = new Campaign(Name='Test 1',recordTypeId=campaignRecordTypeId);
        insertCampaign.add(Camp1); 
        
        Campaign Camp2 = new Campaign(Name='Test 2',recordTypeId=campaignRecordTypeId);
        insertCampaign.add(Camp2); 
        
        insert insertCampaign;
        
        CampaignInfluenceModel testCampaignInfluenceModel = [SELECT DeveloperName FROM CampaignInfluenceModel limit 1];
        List<CampaignInfluence> campaignInfluLst = new List<CampaignInfluence>();
        
        CampaignInfluence testCampaignInfluence = new CampaignInfluence(ModelId = testCampaignInfluenceModel.id,CampaignId = insertCampaign[0].id, OpportunityId = testOpportunity.id, ContactId = testContact.id); 
        campaignInfluLst.add(testCampaignInfluence);
        
        CampaignInfluence testCampaignInfluenceDupeContact = new CampaignInfluence(ModelId = testCampaignInfluenceModel.id,CampaignId = insertCampaign[1].id, OpportunityId = testOpportunity.id, ContactId = testContact.id); 
        campaignInfluLst.add(testCampaignInfluenceDupeContact);
        insert campaignInfluLst;
        
        system.assertEquals(2,campaignInfluLst.size());
        
        Set<Id> campaignInflIds = new Set<Id>();        
        campaignInflIds.add(campaignInfluLst[0].id);
        campaignInflIds.add(campaignInfluLst[1].id);
        
        List<CampaignInfluence> getCampInflDetails1 = [select influence from CampaignInfluence 
                                                      where ID IN: campaignInflIds] ;
        
        
        system.assertEquals(50, getCampInflDetails1[0].influence);
        system.assertEquals(50, getCampInflDetails1[1].influence);
        
        
        // Now delete
        delete campaignInfluLst[1];
        
        List<CampaignInfluence> getCampInflDetails2 = [select influence from CampaignInfluence 
                                                      where ID =: campaignInfluLst[0].id] ;
        
        
        system.assertEquals(100, getCampInflDetails2[0].influence);
        test.stopTest();
        
        
        
    }    
}