src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Account Governance team.</inlineHelpText>
        <label>Account Governance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Fastrack__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5851 Checkbox on &quot;Order From&quot; contracts</description>
        <inlineHelpText>Use Fast Track terms and conditions if under $100k</inlineHelpText>
        <label>Fastrack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-9301 : Fetching value from  Product Family on Opportunity</description>
        <inlineHelpText>Value coming from Product Family on Opportunity</inlineHelpText>
        <label>Product Family</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related product line items from opportunity at Contract record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SAPPGId__c</fullName>
        <description>SFDC1-8056 -This field is related to Onboarding process of implementation cases</description>
        <inlineHelpText>Please select SAP PGI’d value</inlineHelpText>
        <label>SAP PGI’d</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>NDA</fullName>
        <active>true</active>
        <description>A new record type for contract</description>
        <label>NDA</label>
    </recordTypes>
    <recordTypes>
        <fullName>OrderForm</fullName>
        <active>true</active>
        <description>A new record type for contract</description>
        <label>Order Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Trial</fullName>
        <active>true</active>
        <description>A new record type for contract</description>
        <label>Trial</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule</description>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContractBeingRenewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1357; Lookup field for Renewal contract. 
SFDC1-5242; Rename the Contract being Renewed field to Originating Contract
SFDC1-6627 Add a filter for this lookup so that only order form can be selected as originating contract.</description>
        <inlineHelpText>Please select a Contract</inlineHelpText>
        <label>Originating Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Order Form contracts can be added as originating contract.</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Order Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-7525 product family calculated from related products
SFDC1-8785 : updating the field type to Long Text Area</description>
        <inlineHelpText>Product family of related products automatically populated by system</inlineHelpText>
        <label>Product Family</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TotalDaysOfContinuation__c</fullName>
        <description>SFDC1-5520 Total Days of Continuation for opportunity</description>
        <inlineHelpText>Total Days of Continuation</inlineHelpText>
        <label>Total Days of Continuation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to schedule opportunity products in case of multi-year opportunities</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 Related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Product Schedule</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestContractRecordTypeSelection.cls
//-----------------------------
// @author: Prachi Bhasin
// @date: 14 Sept 2017
// @param: NA
// @description: Test Class for ContractRecordTypeSelectionController 
// @return: NA
// @company: VERTIBA
// @lastModifiedBy: Prachi 
// @lastModifiedSprint: Sprint 11 SFDC1-5282 - Removing NDA from create contract wizard & SFDC1-4576 Sync contact roles from Opp to Contract
// @lastModifiedSprint: Sprint 12 SFDC1-710 -  Continuation letter related updates to creation method
// @lastModifiedSprint: Sprint 12 SFDC1-5490 - Client legal entity to be populated with Account
// @lastModifiedSprint: Sprint 13 SFDC1-5520 - Continuation Letter Contract Record Entry
// @Last Modified By : Prachi Bhasin
// @Last Modified Description : Added new test methods for SFDC1-5520
// @Last Modified Date : 17-Nov-2017
// @Last Modified By : Vishnu Vardhan Chowdary Andra
// @Last Modified Description : Updated testFindRecordTypes for new validation check. SFDC1-5640
// @Last Modified Date : 22-Nov-2017
// @Last Modified By : Mohit Modi
// @Last Modified Description : SFDC1-5803 - updated Test Method for 'findRecordTypes' as related Class has been updated.
// @Last Modified Date : 23-Nov-2017
// @Last Modified By : Prachi Bhasin
// @Last Modified Description : Added new assertions for SFDC1-710
// @Last Modified Date : 8-Dec-2017
//-----------------------------
@isTest
private class TestContractRecordTypeSelection {

    @isTest
    static void testFindRecordTypes() {

            Id trialRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
            Account acc = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', false);
            acc.DataGovernanceStatus__c = 'Approved';
            insert acc;
            
            Opportunity testOpportunity = TestUtility.createOpportunity(acc.Id, 'test Opppy', true);
            Id contractRecId = ContractRecordTypeSelectionController.createDefaultRecord(trialRecordTypeId, testOpportunity.Id);
            
            String str = ContractRecordTypeSelectionController.findRecordTypes('Contract',testOpportunity.Id);
             
            Contract defaultContract = [Select id, accountId from contract where Id=: contractRecId];
            System.assertEquals(defaultContract.accountId,acc.id);

            Contact testContact = TestUtility.createContact(acc.Id, 'testihsmarkit@testihsmarkit.com',
                                                            true, 'Test', 'Contact');
            OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId = testOpportunity.Id, ContactId = testContact.Id, IsPrimary=false);
            insert ocr;
        
        Test.startTest();
            defaultContract.SAPPGId__c = 'New';
            defaultContract.Fastrack__c = true;
            update defaultContract;
            String returnstr = ContractRecordTypeSelectionController.findContractStartAndEndDate(testOpportunity.Id,trialRecordTypeId);
            System.assertEquals('NoPrimaryContactOnOpportunity', returnstr);
            ocr.IsPrimary=true;
            update ocr;
            returnstr = ContractRecordTypeSelectionController.findContractStartAndEndDate(testOpportunity.Id,trialRecordTypeId);
            System.assertEquals('NoProductOnOpportunity', returnstr);

            Product2 testProd = TestUtility.createProduct('Test Product', true);
            Id standardId = Test.getStandardPricebookId();
            PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);        
            OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
            update testOpportunity;
            
            Contact oppContact = TestUtility.createContact(acc.Id,'a@b.com',true,'first','last');
            
            OpportunityContactRole oppRole = new OpportunityContactRole(OpportunityId=testOpportunity.Id,ContactId=oppContact.Id, Role='Influencer');
            insert oppRole;
            
            OpportunityLineItemSchedule__c oppSchedule = new OpportunityLineItemSchedule__c(opportunity__c=testOpportunity.id);
            insert oppSchedule;
            contractRecId = ContractRecordTypeSelectionController.createDefaultRecord(trialRecordTypeId, testOpportunity.Id);
            
            List<ContractLineItem__c> lstContractLineItems = [Select id, name from ContractLineItem__c where contract__c =:contractRecId];
            System.assertEquals(lstContractLineItems.size(),1);
            
            String str1 = ContractRecordTypeSelectionController.setTrialRecordTypeId();
            String str2 = ContractRecordTypeSelectionController.findProductsRelatedToOpportunity(String.ValueOf(testOpportunity.Id));  
            String str3='["'+String.ValueOf(testOLI.id)+'"]';         
            String str4 = ContractRecordTypeSelectionController.createTrialContractRecord(testOpportunity.Id,str3);
            String str5 = ContractRecordTypeSelectionController.findContractStartAndEndDate(testOpportunity.Id,trialRecordTypeId);
            System.assertEquals(str5,'orderFormAlreadyPresent');
            
        Test.stopTest();
    }
    
    @isTest
    static void testDeleteExistingContractLineItemsAndSchedules() {

            Id trialRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
            Account acc = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', false);
            acc.DataGovernanceStatus__c = 'Approved';
            insert acc;
            
            Opportunity testOpportunity = TestUtility.createOpportunity(acc.Id, 'test Opppy', true);
            Id contractRecId = ContractRecordTypeSelectionController.createDefaultRecord(trialRecordTypeId, testOpportunity.Id);
            
            String str = ContractRecordTypeSelectionController.findRecordTypes('Contract',testOpportunity.Id);
            
            Contract defaultContract = [Select id, accountId from contract where Id=: contractRecId];
            System.assertEquals(defaultContract.accountId,acc.id);

        Test.startTest();   
            Product2 testProd = TestUtility.createProduct('Test Product', true);
            Id standardId = Test.getStandardPricebookId();
            PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);        
            OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
            update testOpportunity;
            
            OpportunityLineItemSchedule__c oppSchedule = new OpportunityLineItemSchedule__c(opportunity__c=testOpportunity.id);
            insert oppSchedule;
            contractRecId = ContractRecordTypeSelectionController.createDefaultRecord(trialRecordTypeId, testOpportunity.Id);
            
            List<ContractLineItem__c> lstContractLineItems = [Select id, name from ContractLineItem__c where contract__c =:contractRecId];
            System.assertEquals(lstContractLineItems.size(),1);
            ContractRecordTypeSelectionController.deleteExistingContractLineItemsAndSchedules(defaultContract.id);
            
        Test.stopTest();
    }
    
    @isTest
    static void testFindContractStartAndEndDate() {

            Id trialRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Trial').getRecordTypeId();
            Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
            Account acc = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', false);
            acc.DataGovernanceStatus__c = 'Approved';
            insert acc;
            
            Opportunity testOpportunity = TestUtility.createOpportunity(acc.Id, 'test Opppy', true);
            Id contractRecId = ContractRecordTypeSelectionController.createDefaultRecord(trialRecordTypeId, testOpportunity.Id);
            
            String str = ContractRecordTypeSelectionController.findRecordTypes('Contract',testOpportunity.Id);
            
            Contract defaultContract = [Select id, accountId from contract where Id=: contractRecId];
            System.assertEquals(defaultContract.accountId,acc.id);

        Test.startTest();   
            String result = ContractRecordTypeSelectionController.findContractStartAndEndDate(testOpportunity.Id,trialRecordTypeId);
            delete defaultContract;
            result = ContractRecordTypeSelectionController.findContractStartAndEndDate(testOpportunity.Id,orderFormRecordTypeId);
            result = ContractRecordTypeSelectionController.findContractStartAndEndDate(testOpportunity.Id,trialRecordTypeId);
            
        Test.stopTest();
    }
    
    @isTest
    static void testContractEndDateCalculation() {
        Test.startTest();
            String days = '3';
            String startDate = String.valueOf(System.Today());
            Date dateResult = ContractRecordTypeSelectionController.contractEndDateCalculation(days,startDate);            
        Test.stopTest();
    }
    
    @isTest
    static void testCreateContinuationContractRecord() {

            Id continuationRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Continuation Letter').getRecordTypeId();
            Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
            Account acc = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', false);
            acc.DataGovernanceStatus__c = 'Approved';
            insert acc;
            
            Opportunity testOpportunity = TestUtility.createOpportunity(acc.Id, 'test Opppy', false);
            testOpportunity.TotalDaysOfContinuation__c = 30;
            testOpportunity.ContractStartDate__c = System.Today();
            testOpportunity.ContractEndDate__c = System.Today()+30;
        	testOpportunity.ProductFamily__c = 'TEST'; //SFDC1-5228 JK : New
        	testOpportunity.ProductGroup__c = 'TEST';  //SFDC1-5228 JK : New
            insert testOpportunity;
            
            String str = ContractRecordTypeSelectionController.findRecordTypes('Contract',testOpportunity.id);            

        Test.startTest();
            Id orderForm = ContractRecordTypeSelectionController.createDefaultRecord(orderFormRecordTypeId, testOpportunity.Id);
            testOpportunity.ContractBeingRenewed__c = orderForm;
            update testOpportunity;
            
            Contract orderFormCreated = [Select id, RecordtypeId from Contract where  id= : orderForm limit 1];
            System.assertEquals(orderFormCreated.RecordtypeId,orderFormRecordTypeId);
            
            String startDate = String.valueOf(System.Today());
            String endDate = String.valueOf(System.Today() + 30);
            String status = '30';
            String acceptanceObtained = 'Yes';

            Id continuationRecordId = ContractRecordTypeSelectionController.createContinuationContractRecord(testOpportunity.Id,startDate,endDate,status,acceptanceObtained);                        
            Date contractStartDate = ContractRecordTypeSelectionController.setContractStartDateFromOppty(testOpportunity.Id);
            Date contractStartDateCalculation = ContractRecordTypeSelectionController.contractContinuationStartDateCalculation(testOpportunity.Id);

            Id continuationRecordId2 = ContractRecordTypeSelectionController.createContinuationContractRecord(testOpportunity.Id,String.valueOf(contractStartDateCalculation),endDate,status,acceptanceObtained);                        
            
            Contract continuationLetterContractCreated = [Select id, Recordtype.Id, startDate, endDate from Contract where Id= : continuationRecordId2 limit 1];
            System.assertEquals(continuationLetterContractCreated.Recordtype.Id,continuationRecordTypeId);
            System.assertNotEquals(continuationLetterContractCreated.startDate,NULL);
            System.assertNotEquals(continuationLetterContractCreated.startDate,NULL);
            
            String contractRecordType = ContractRecordTypeSelectionController.setConLetterRecordTypeId();
            String totalContinuationDays = ContractRecordTypeSelectionController.findTotalDaysOfContinuation(testOpportunity.Id,startDate,endDate);
            
        Test.stopTest();
    }
}