src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AdditionalAccountFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-785 This field is a link to a 1:1 relations ship between Account and Additional Account Fields object.  It is created when a new account is created and is read only. The user can easily click on this field to see the related object.</description>
        <inlineHelpText>Created when a new account is created and is read only.</inlineHelpText>
        <label>Additional Account Fields</label>
        <referenceTo>AdditionalAccountFields__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AdditionalAccountFields__c.object
<CustomObject>
    <description>SFDC1-785 This is a separate Object created for capturing fields that are a 1:1 relationship with Account but are not attributes that we would consider governing. Many of these fields originated from the multitude of fields found on the account form in Legacy IHS.</description>
    <fields>
        <fullName>AccountReference__c</fullName>
        <inlineHelpText>Lookup Reference of the account connected to the Additional Account Fields</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Account Fields (Account)</relationshipLabel>
        <relationshipName>AdditionAccountFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Account Fields</label>
    <nameField>
        <label>Additional Account Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Account Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAdditionalAccountFieldsMethods.cls
// @author: Uttam Arya
// @date: 22 June 2017
// @param: NA
// @description: Test class for Additional Account Fields trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestAdditionalAccountFieldsMethods {
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 25 Aug 2017
    // @param: NA
    // @description: SFDC1-2103 Test method for Additional Account Fields trigger methods populateAdditionalFiledsLookupInAccount on insert
    // @return: NA
    //-----------------------------
    private static testMethod void testpopulateAdditionalFiledsLookupInAccount() {
        
        Account testAccount = TestUtility.createTestAccount('Test subject testpopulateAdditionalFiledsLookupInAccount', true);
        
        list <Account> testAccountResult = [Select AdditionalAccountFields__c, Id from Account where Id = :testAccount.Id];
        //Assert if account is inserted
        System.assertEquals(1, testAccountResult.size());
        System.assert(testAccountResult[0].AdditionalAccountFields__c != null);
        
        //Assert if Adiitional Account Field is inserted
        list <AdditionalAccountFields__c> acfList = [Select Id from AdditionalAccountFields__c where AccountReference__c = :testAccount.Id];
        System.assertEquals(1, acfList.size());
        System.assertEquals(acfList[0].Id, testAccountResult[0].AdditionalAccountFields__c);
        
    }
    
}