src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Account Governance team.</inlineHelpText>
        <label>Account Governance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-200 Determines if the Contact is active or inactive</description>
        <inlineHelpText>Please select contact&apos;s status</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CrossPlantStatus__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 ,  This holds Cross Plant Status related to Products</description>
    <fields>
        <fullName>SAPCode__c</fullName>
        <label>SAP Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cross Plant Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross Plant Status</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractBeingRenewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1357; Lookup field for Renewal contract. 
SFDC1-5242; Rename the Contract being Renewed field to Originating Contract
SFDC1-6627 Add a filter for this lookup so that only order form can be selected as originating contract.</description>
        <inlineHelpText>Please select a Contract</inlineHelpText>
        <label>Originating Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Order Form contracts can be added as originating contract.</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Order Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalDaysOfContinuation__c</fullName>
        <description>SFDC1-5520 Total Days of Continuation for opportunity</description>
        <inlineHelpText>Total Days of Continuation</inlineHelpText>
        <label>Total Days of Continuation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines Availability/Sellability</inlineHelpText>
        <label>Product Status</label>
        <referenceTo>CrossPlantStatus__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCrossPlantStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestWarningMsgProductCrossPlantStatus.cls
//------------------------------------------------
// @author: Vertiba
// @company: VERTIBA
// @date: 13 Dec 2017
// @description:  SFDC1-5326 -Opportunity Behavior - when a Future Disconnect Product is on the Oppy.
// @return: 
// @Last Updated: 25 May 2018:Anjani Shukla : SFDC1-8147- New Cross Plat Status Addition for Renewal Opty
//------------------------------------------------
@isTest
public class TestWarningMsgProductCrossPlantStatus {
	//-----------------------------
    // @author: Veriba
    // @company: VERTIBA
    // @date: 14 Dec 2017
    // @param: 
    // @description:  Test method to check if functionality is working.
    // @return: NA
    // @Modification : Updated code for new methods added for edit fucntionality.
    // @Modification date : Anjani Shukla:14 Dec 2017
    //-----------------------------
    public static testMethod void testNoWarningNotification() {
        test.startTest();
            Account acnt = TestUtility.createTestAccountWithStreet('SFDC1-5326-OpporunityCrossPlantStatus','Test1',true);        	
        	CrossPlantStatus__c availableProd = new CrossPlantStatus__c();
            availableProd.Name='Available for Sale';
        	availableProd.SAPCode__c ='04';
        	availableProd.Status__c ='Active';
            insert availableProd;
        	Product2 testProd = TestUtility.createProduct('Test Product', true); 
            testProd.ProductStatus__c = availableProd.id;
            update testProd;
            Id standardId = Test.getStandardPricebookId();
            PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        	LegalEntity__c testLegalEntity = TestUtility.createLegalEntity('Test Legal Entity', 'USD');
            Opportunity o = TestUtility.createOpportunity(acnt.Id, 'test Opppy1', true);
            OpportunityLineItem testOLI1 = TestUtility.createOpportunityLineItem(o.Id, testPBE, true);
        	//List<sObject> testCrossPlantStatus = TestUtility.loadCrossPlantStatus();
        	List<String> lstforRecord = new List<String>();
        	//lstforRecord.add(testOLI1.name);
        	// test functionality.
        	WarningMsgProductCrossPlantStatus objWarnMsgProdCrossPlantStatus = new WarningMsgProductCrossPlantStatus();
        	WarningMsgProductCrossPlantStatus.getOptyProdLineDetails(o.id);
        	WarningMsgProductCrossPlantStatus.errorMsgRecord = lstforRecord;
            system.assertEquals(0, lstforRecord.size());
        test.stopTest(); 	
    }

	//-----------------------------
    // @author: Veriba
    // @company: VERTIBA
    // @date: 14 Dec 2017
    // @param: 
    // @description:  Test method to check if functionality is working.
    // @return: NA
    // @Modification : Updated code for new methods added for edit fucntionality.
    // @Modification date : Anjani Shukla:14 Dec 2017
    //-----------------------------
    public static testMethod void testWarningNotificationErrorMsg() {
        test.startTest();
            Account acnt = TestUtility.createTestAccountWithStreet('SFDC1-5326-OpporunityCrossPlantStatus','Test1',true);  
            CrossPlantStatus__c notavailableProd = new CrossPlantStatus__c();
            notavailableProd.Name='Discntnd w/o Rplcmnt';
        	notavailableProd.SAPCode__c ='05';
        	notavailableProd.Status__c ='Active';
            insert notavailableProd;
        	Product2 testProd = TestUtility.createProduct('Test Product', true); 
            testProd.ProductStatus__c = notavailableProd.id;
            update testProd;
            Id standardId = Test.getStandardPricebookId();
            PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        	LegalEntity__c testLegalEntity = TestUtility.createLegalEntity('Test Legal Entity', 'USD');
            Opportunity o = TestUtility.createOpportunity(acnt.Id, 'test Opppy1', true);
            OpportunityLineItem testOLI1 = TestUtility.createOpportunityLineItem(o.Id, testPBE, true);
        	List<sObject> testCrossPlantStatus = TestUtility.loadCrossPlantStatus();            
        	List<String> lstforRecord = new List<String>();
        	lstforRecord.add(testOLI1.name);
        	// test functionality.
        	WarningMsgProductCrossPlantStatus objWarnMsgProdCrossPlantStatus = new WarningMsgProductCrossPlantStatus();
        	WarningMsgProductCrossPlantStatus.getOptyProdLineDetails(o.id);
        	WarningMsgProductCrossPlantStatus.errorMsgRecord = lstforRecord;
            system.assertEquals(1, lstforRecord.size());
        test.stopTest(); 	
    }

	//-----------------------------
    // @author: Veriba
    // @company: VERTIBA
    // @date: 25 May 2018
    // @param: 
    // @description:  Test method to check if functionality is working.
    // @return: NA
    // @Modification : Updated code for new methods added for edit fucntionality.
    // @Modification date : Anjani Shukla:25 May 2018 - SFDC1-8147 - New Cross Plant Status Added.
    //-----------------------------
    public static testMethod void testNoWarningNotificationForRenewal() {
        test.startTest();
            Account acnt = TestUtility.createTestAccountWithStreet('SFDC1-5326-OpporunityCrossPlantStatus','Test1',true);        	
        	CrossPlantStatus__c availableProd = new CrossPlantStatus__c();
            availableProd.Name='Available for Sale';
        	availableProd.SAPCode__c ='05';
        	availableProd.Status__c ='Active';
            insert availableProd;
        	Product2 testProd = TestUtility.createProduct('Test Product', true); 
            testProd.ProductStatus__c = availableProd.id;
            update testProd;
            Id standardId = Test.getStandardPricebookId();
            PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        	LegalEntity__c testLegalEntity = TestUtility.createLegalEntity('Test Legal Entity', 'USD');
            Opportunity o = TestUtility.createOpportunity(acnt.Id, 'test Opppy1', true);
            OpportunityLineItem testOLI1 = TestUtility.createOpportunityLineItem(o.Id, testPBE, true);
        	//List<sObject> testCrossPlantStatus = TestUtility.loadCrossPlantStatus();
        	List<String> lstforRecord = new List<String>();
        	//lstforRecord.add(testOLI1.name);
        	// test functionality.
        	WarningMsgProductCrossPlantStatus objWarnMsgProdCrossPlantStatus = new WarningMsgProductCrossPlantStatus();
        	WarningMsgProductCrossPlantStatus.getOptyProdLineDetails(o.id);
        	WarningMsgProductCrossPlantStatus.errorMsgRecord = lstforRecord;
            system.assertEquals(0, lstforRecord.size());
        test.stopTest(); 	
    } 
    
    //-----------------------------
    // @author: Veriba
    // @company: VERTIBA
    // @date: 25 May 2018
    // @param: 
    // @description:  Test method to check if functionality is working.
    // @return: NA
    // @Modification : Updated code for new methods added for edit fucntionality.
    // @Modification date : Anjani Shukla:25 May 2018 - SFDC1-8147 - New Cross Plant Status Added.
    //-----------------------------
    public static testMethod void testWarningNotificationForRenewal() {
        test.startTest();
        //Order Management profile
        Profile p = [SELECT Id ,name FROM Profile WHERE Name like '%Order management%' limit 1];
        
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihsihs.com',ADID__c='test'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert u;
        Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        //Contact
        Contact con = TestUtility.createContact(testAccount.id,'testemail1@test.com',false,'TestFirstName','TestLastName');
        con.Phone = '123423';
        con.Fax = '321412321';
        insert con;
        
        //Opportunity
        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'test Opppy', false);
        testOpportunity.TotalDaysOfContinuation__c = 30;
        testOpportunity.ContractStartDate__c = System.Today();
        testOpportunity.ContractEndDate__c = System.Today()+30;
        insert testOpportunity;
        
        //Opportunity Contact role
        OpportunityContactRole oppContactRole = new OpportunityContactRole ();
            oppContactRole.OpportunityId = testOpportunity.id;
            oppContactRole.ContactId = con.id;
            oppContactRole.IsPrimary = true;
       insert  oppContactRole;
        //Product
        CrossPlantStatus__c availableProd = new CrossPlantStatus__c();
        availableProd.Name='Renewal Only';
        availableProd.SAPCode__c ='09';
        availableProd.Status__c ='Active';
        insert availableProd;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        //Creating Contract
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        contract.recordtypeid = orderFormRecordTypeId;
        insert contract;
        //creating an Opportunity 
        Id ofRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        Id OppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        //Opportunity testOpportunity = [SELECT Id,stageName FROM Opportunity WHERE Name='test Opppy' LIMIT 1];
        testOpportunity.ContractStartDate__c = System.today();
        testOpportunity.ContractEndDate__c = System.today().addDays(30);
        testOpportunity.CloseDate = System.today().addDays(35);
        testOpportunity.ActivityCreated__c = true;
        testOpportunity.RecordTypeId = OppRecordTypeId;
        testOpportunity.ContractBeingRenewed__c = contract.Id;
        update testOpportunity;
        
        
        OpportunityLineItem testOLI1 = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
        	//List<sObject> testCrossPlantStatus = TestUtility.loadCrossPlantStatus();
        	List<String> lstforRecord = new List<String>();
        	//lstforRecord.add(testOLI1.name);
        	// test functionality.
        	WarningMsgProductCrossPlantStatus objWarnMsgProdCrossPlantStatus = new WarningMsgProductCrossPlantStatus();
        	WarningMsgProductCrossPlantStatus.getOptyProdLineDetails(testOpportunity.id);
        	WarningMsgProductCrossPlantStatus.errorMsgRecord = lstforRecord;
            system.assertEquals(0, lstforRecord.size());        
        Test.stopTest(); 	
    } 
}