src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-200 Determines if the Contact is active or inactive</description>
        <inlineHelpText>Please select contact&apos;s status</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>RiskProbability__c</fullName>
        <description>SFDC1-4163 This field is a roll up summary from renewal at risk object</description>
        <label>Risk Probability</label>
        <summarizedField>RenewalatRisk__c.RiskProbability__c</summarizedField>
        <summaryForeignKey>RenewalatRisk__c.OpportunityAtRisk__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RenewalatRisk__c.object
<CustomObject>
    <description>SFDC1-4160 This object is used to identify a renewal at risk from an opportunity.
SFDC1-6706, label has been changed to &quot;Opportunity at Risk&quot;.</description>
    <fields>
        <fullName>Comments__c</fullName>
        <description>SFDC1-4160 This field holds comments related to the renewal at risk</description>
        <label>Comments</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EstimatedValueatRisk__c</fullName>
        <description>SFDC1-4160 This field holds the estimated value at risk</description>
        <label>Estimated Value at Risk</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityAtRisk__c</fullName>
        <description>SFDC1-4160 This field holds the Opportunity at Risk</description>
        <label>Opportunity At Risk</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity at Risk</relationshipLabel>
        <relationshipName>Renewals_at_Risk</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RiskCustomerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4160 This field holds the name of the Customer&apos;s Name</description>
        <label>Risk Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Renewals_at_Risk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskProbability__c</fullName>
        <description>SFDC1-4160 This field holds the risk probability</description>
        <label>Risk Probability</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-4160 This field holds the status of risk,SFDC1-7668 Adding &apos;Closed - Opportunity Lost&apos; value</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Pending Resolution</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed - Risk Mitigated</fullName>
                </value>
                <value>
                    <fullName>Closed - Opportunity Lost</fullName>
                </value>
                <value>
                    <fullName>Closed - Non Renewal</fullName>
                </value>
                <value>
                    <fullName>Closed - Terminated</fullName>
                </value>
                <value>
                    <fullName>Closed - Downgraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity at Risk</label>
    <nameField>
        <displayFormat>OaR-{000000}</displayFormat>
        <label>Opportunity at Risk Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities at Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestRenewalatRiskMethods.cls
// @author: Uttam Arya
// @date: 19 Jun 2018
// @param: NA
// @description: Test class for RenewalatRiskTrigger methods 
// @return: NA
//-----------------------------
@isTest
public class TestRenewalatRiskMethods {
	
    //-----------------------------
    // @author: Harshit Singhal
    // @date: 19 Jun 2018
    // @param: NA
    // @description: SFDC1-8545 Test method for RenewalatRiskTrigger method setRiskCustomerContactinOppatRisk() on insert
    // @return: NA
    //-----------------------------
    private static testMethod void testSetRiskCustomerContactinOppatRisk() {
        //Create test account
        Account testAccount = TestUtility.createTestAccount('Test Account 8545', true);
        //Create test Opportunity
        Opportunity testOpp = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity 8545', true);
        //Create test contacts
        List<Contact> testContactsList = new List<Contact>();
        Contact c1 = TestUtility.createContact(testAccount.Id,'testContact1@email.com',false,'TestFname1','TestLName1');
        Contact c2 = TestUtility.createContact(testAccount.Id,'testContact2@email.com',false,'TestFname2','TestLName2');
        testContactsList.add(c1);
        testContactsList.add(c2);
        if(testContactsList.size() > 0) {
            insert testContactsList;
        }            
        
        Test.startTest();        
        
        //Create test OpportunityContactRole records
        List<OpportunityContactRole> ocrList = new List<OpportunityContactRole>();
        OpportunityContactRole ocr1 = new OpportunityContactRole(OpportunityId=testOpp.Id,ContactId=testContactsList[0].Id,IsPrimary=true);
        OpportunityContactRole ocr2 = new OpportunityContactRole(OpportunityId=testOpp.Id,ContactId=testContactsList[1].Id,IsPrimary=false);
        ocrList.add(ocr1);
        ocrList.add(ocr2);
        if(ocrList.size()>0) {
            insert ocrList;
        }            
        
        //Create Opportunity at Risk records
        RenewalatRisk__c testRaR = new RenewalatRisk__c(OpportunityAtRisk__c=testOpp.Id,Status__c='Open - Pending Resolution',RiskProbability__c=12,Comments__c='Test Comments',EstimatedValueatRisk__c=100);
        insert testRaR;
        System.assertEquals(testContactsList[0].Id,[Select RiskCustomerContact__c From RenewalatRisk__c Where Id =:testRaR.Id].RiskCustomerContact__c);
        
        Test.stopTest();        
    }
}