src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Account Governance team.</inlineHelpText>
        <label>Account Governance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AdClaim__c.object
<CustomObject>
    <description>SFDC1-332: AdClaim Object will be used to Track the Opportunity Ad Claims.</description>
    <fields>
        <fullName>AdDurationEndDate__c</fullName>
        <description>SFDC1-332 : Ad Duration End Date</description>
        <inlineHelpText>The date the Ad Claim or other publication is requested to end (max of 1 year from start date)</inlineHelpText>
        <label>Ad Duration End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AdDurationStartDate__c</fullName>
        <description>SFDC1-332 : Ad Duration Start Date</description>
        <inlineHelpText>The date the Ad Claim or other publication is requested to start</inlineHelpText>
        <label>Ad Duration Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AdditionalValidationAssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Additional Validation Assigned To</description>
        <inlineHelpText>If the claim or publication requires additional validation, such as a press release that must be reviewed by our PR team, please note that person here</inlineHelpText>
        <label>Additional Validation Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AdditionalValidationAssignedTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AdditionalValidationRequired__c</fullName>
        <description>SFDC1-332 : Additional Validation Required</description>
        <inlineHelpText>Explain the additional validation needed</inlineHelpText>
        <label>Additional Validation Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AnnualSubscriptionOrContract__c</fullName>
        <description>SFDC1-332 : Annual Subscription or Contract</description>
        <inlineHelpText>Yes&apos; if this claim is purchased under a subscription package. &apos;No&apos; if not</inlineHelpText>
        <label>Annual Subscription or Contract</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ApprovalComments__c</fullName>
        <description>SFDC1-332 : Approval Comments</description>
        <inlineHelpText>Any comments that will be helpful to the account representative when discussing the claim with the requestor</inlineHelpText>
        <label>Approval Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovedClaimLanguage__c</fullName>
        <description>SFDC1-332 : Approved Claim Language</description>
        <inlineHelpText>Language that is approved to use in the claim. (This may be different from the proposed language)</inlineHelpText>
        <label>Approved Claim Language</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovedDate__c</fullName>
        <description>SFDC1-332 : Approved Date</description>
        <inlineHelpText>Date the claim is approved</inlineHelpText>
        <label>Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ApprovedDisclaimerLanguage__c</fullName>
        <description>SFDC1-332 : Approved Disclaimer Language</description>
        <inlineHelpText>Language that is approved to use in the disclaimer.  (This may be different from the proposed language)</inlineHelpText>
        <label>Approved Disclaimer Language</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovingParty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Approving Party</description>
        <inlineHelpText>Name of the person approving the claim</inlineHelpText>
        <label>Approving Party</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ApprovingParty</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClaimExpirationDate__c</fullName>
        <description>SFDC1-332 : Claim Expiration Date</description>
        <inlineHelpText>The date the claim must stop running. (max of 1 year from start date) Please see guidelines document for appropriate lengths</inlineHelpText>
        <label>Claim Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClaimTitle__c</fullName>
        <description>SFDC1-332 : Claim Title</description>
        <inlineHelpText>Title for the claim</inlineHelpText>
        <label>Claim Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimsStatus__c</fullName>
        <description>SFDC1-332 : Claims Status</description>
        <inlineHelpText>Current status of claim in the review process</inlineHelpText>
        <label>Claims Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>SFDC1-332 : Comments</description>
        <inlineHelpText>Any comments that will be helpful to the person reviewing the claim</inlineHelpText>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ContactName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Contact Name</description>
        <inlineHelpText>Name of contact at the requesting organization</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ad Claims</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrencyISOCode__c</fullName>
        <description>SFDC1-332 : Currency ISO Code</description>
        <label>Currency ISO Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australian Dollar</fullName>
                </value>
                <value>
                    <fullName>British Pound</fullName>
                </value>
                <value>
                    <fullName>Canadian Dollar</fullName>
                </value>
                <value>
                    <fullName>Chinese Yuan</fullName>
                </value>
                <value>
                    <fullName>Euro</fullName>
                </value>
                <value>
                    <fullName>Japanese Yen</fullName>
                </value>
                <value>
                    <fullName>Korean Won</fullName>
                </value>
                <value>
                    <fullName>U.S. Dollar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DataValidated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-332 : Data Validated</description>
        <inlineHelpText>Date claim validation is complete</inlineHelpText>
        <label>Data Validated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DataValidationCompletedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Data Validation Completed By</description>
        <inlineHelpText>Name of person who validates that our data supports the claim</inlineHelpText>
        <label>Data Validation Completed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DataValidator</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DoesSubstantiatingDataExist__c</fullName>
        <description>SFDC1-332 : Does Substantiating Data Exist?</description>
        <inlineHelpText>Yes or No. Data must be attached to the claim and should be clear whether the customer or IHS Markit created the data. (The claim cannot be validated until this is a yes)</inlineHelpText>
        <label>Does Substantiating Data Exist?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes (please attach)</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FeeForClaim__c</fullName>
        <description>SFDC1-332 : Fee for Claim</description>
        <inlineHelpText>The fee being charged for publication (This is in addition to the fee for licensing the data)</inlineHelpText>
        <label>Fee for Claim</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IHSAccountRepresentative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332: IHS Account Representative</description>
        <inlineHelpText>Name of account representative who created the claim</inlineHelpText>
        <label>IHS Account Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AcctRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Claim</label>
    <nameField>
        <displayFormat>AC{0000}</displayFormat>
        <label>Ad Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Claims</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EmailUnknown__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-530 Allow user to enter a contact who will not provide their email address. When this field is checked, Business phone field is required. If this field is unchecked, email is mandatory.</description>
        <inlineHelpText>Please check this box if contact&apos;s email address is unknown. A phone number will be required in that case.</inlineHelpText>
        <label>Email Unknown</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>GAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-412 Global Account Manager can only be updated by System Administrators and GAM Administrators.
SFDC1-4204 : Updated Lookup filter to allow only Salesforce Users.
SFDC1-6960:  Relabeling the GAM field to Account Manager</description>
        <inlineHelpText>Global Account Manager can only be updated by System Administrators and GAM Administrators.</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AdClaimsApprover__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-1059 This field should be checked for a user who is authorized to approve an Ad Claim records.</description>
        <inlineHelpText>Please check this field if current user is authorized to approve Ad Claim records.</inlineHelpText>
        <label>Ad Claims Approver</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestRejectAdClaim.cls
//-----------------------------
// @author: Prachi Bhasin
// @date: 31 July 2017
// @param: NA
// @description: SFDC1-366 Test class for ApproveAdClaim class 
// @companyname : VERTIBA 
// @lastmodifiedBy : Prachi Bhasin for SFDC1-2233
// @lastmodifiedSprint : Sprint 7
//-----------------------------

@isTest
private class TestRejectAdClaim {
    //-----------------------------
    // @author: Mohit Modi
    // @date: 31 July 2017
    // @param: NA
    // @description: Test method for approveAdClaim method
    // @return: NA
    //-----------------------------
    private static testMethod void testRejectAdClaim() {
        
        Account a = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', false);
        a.DataGovernanceStatus__c = 'Approved';
        insert a;
           
        Contact c = new Contact();
        c.firstname = 'Test';
        c.lastname = 'testSetCaseAdditionalFieldsObject';
        c.AccountId = a.Id;
        c.EmailUnknown__c = true;
        c.Phone = '1234532';
        insert c;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id,AdClaimsApprover__c = true, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihs456789.com',ADID__c='test'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert u;
        
        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName= '1-Sales Qualified';
        opp.RecordTypeId = devRecordTypeId;
        opp.CloseDate = System.today()+2;
        opp.Amount = 123;
        opp.GAM__c = u.id;
        opp.AccountId = a.id;
        insert opp;       
                      
        
        AdClaim__c AdClaimobj = new AdClaim__c();        
        AdClaimobj.AdditionalValidationAssignedTo__c  =  u.id    ;
        AdClaimobj.AdditionalValidationAssignedTo__c=u.id;
        AdClaimobj.AdditionalValidationRequired__c='Yes';
        AdClaimobj.AdDurationEndDate__c=System.Today();
        AdClaimobj.AdDurationStartDate__c=System.Today().addDays(-5);
        AdClaimobj.AnnualSubscriptionOrContract__c='Yes';
        AdClaimobj.ApprovalComments__c='Test Comments';
        AdClaimobj.ApprovedClaimLanguage__c='English';
        AdClaimobj.ApprovedDate__c=System.Today();
        AdClaimobj.ApprovedDisclaimerLanguage__c='English';
        AdClaimobj.ApprovingParty__c=u.id;
        AdClaimobj.ClaimExpirationDate__c=System.Today();
        AdClaimobj.ClaimsStatus__c='Submitted';
        AdClaimobj.ClaimTitle__c='Test Tittle';
        AdClaimobj.Comments__c='Test Comment';
        AdClaimobj.ContactName__c=c.id;
        AdClaimobj.CurrencyISOCode__c='U.S. Dollar';
        AdClaimobj.DataValidated__c=True;
        AdClaimobj.DataValidationCompletedBy__c=u.id;
        AdClaimobj.DoesSubstantiatingDataExist__c='Yes (please attach)';
        AdClaimobj.FeeForClaim__c=100;
        AdClaimobj.IHSAccountRepresentative__c=u.id;
        AdClaimobj.MediaType__c='Email';
        AdClaimobj.Opportunity__c=opp.id;
        AdClaimobj.OtherSourceFileUsed__c='Test';
        AdClaimobj.PhoneNumber__c='123456789';      
        AdClaimobj.ProposedClaimLanguage__c='English';
        AdClaimobj.ProposedDisclaimerLanguage__c='English';
        AdClaimobj.RejectionComments__c='Test Comment';
        AdClaimobj.RepresentedOrganization__c=a.id;
        AdClaimobj.RequestDate__c=System.Today();
        AdClaimobj.RequestingOrganization__c=a.id;
        AdClaimobj.SourceFileUsed__c='New';
        AdClaimobj.TypeOfClaim__c='Loyalty';
        AdClaimobj.UpdateOfAPriorClaim__c='No';    
        insert AdClaimobj;

        Set<Id> pIds = (new Map<Id, ProcessInstance>([SELECT Id,Status,TargetObjectId FROM ProcessInstance where Status='Pending' and TargetObjectId = :AdClaimobj.id])).keySet();
        Set<Id> pInstanceWorkitems;
        
        // Process Builder is Activated, send the Record in approval Process Manually in Test Class
        if(pIds.isEmpty())
        {
            // Create an approval request for the account
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request');
            req1.setObjectId(AdClaimobj.id);
            // Submit the record to specific process and skip the criteria evaluation
            req1.setProcessDefinitionNameOrId('AdClaimApprovalProcess');
            req1.setSkipEntryCriteria(true);
            // Submit the approval request for the account
            Approval.ProcessResult result = Approval.process(req1);
            
            // Verify the result
            System.assert(result.isSuccess());
        }
        
        System.RunAs(u){
            AdClaimobj.ClaimsStatus__c = 'Rejected';
            update AdClaimobj;
            
            // To Verify the Record has been Approverd
            pInstanceWorkitems = (new Map<Id, ProcessInstanceWorkitem>([SELECT Id,ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId in :pIds])).keySet();
            System.assert(pInstanceWorkitems.isEmpty());
        }
        // Process Builder is Activated, send the Record in approval Process Manually in Test Class
        pInstanceWorkitems = (new Map<Id, ProcessInstanceWorkitem>([SELECT Id,ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId in :pIds])).keySet();
        if(!pInstanceWorkitems.isEmpty())
        {
            ApproveAdClaim.approveAdClaimRecord(new List<id>{AdClaimobj.id});
            
            pInstanceWorkitems = (new Map<Id, ProcessInstanceWorkitem>([SELECT Id,ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId in :pIds])).keySet();
            // To Verify the Record has been Approverd
            System.assert(pInstanceWorkitems.isEmpty());
        }
    }           
    
}