src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-383 This field serves as a lookup to the Country object</description>
        <inlineHelpText>Read-only field, updated indirectly by a change of Company&apos;s Billing Country</inlineHelpText>
        <label>Account Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AdditionalAccountFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-785 This field is a link to a 1:1 relations ship between Account and Additional Account Fields object.  It is created when a new account is created and is read only. The user can easily click on this field to see the related object.</description>
        <inlineHelpText>Created when a new account is created and is read only.</inlineHelpText>
        <label>Additional Account Fields</label>
        <referenceTo>AdditionalAccountFields__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Account Governance team.</inlineHelpText>
        <label>Account Governance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GlobalAccountManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-149 There will be Accounts that are GAM&apos;s and will be identified by the name of the GAM in the GAM Field on the account, this field is a lookup to users. Managing the GAM is in separate stories under the epic of adding the field.
SFDC1-4204 : Updated Lookup filter to allow only Salesforce Users.</description>
        <inlineHelpText>Please enter a Global Account Manager for this account.</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>GAMAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SourceCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-965 and SFDC1-638 Lookup to Case object. This field will be systematically filled when the Account is created from a Case request to the Data Governance team.</description>
        <inlineHelpText>Case from which account was created</inlineHelpText>
        <label>Source Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>SFDC1-9133 : This field is being used to capture the State value from Case while creating the Accout using the Quick Action &apos;Create New Account&apos;</description>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AdditionalAccountFields__c.object
<CustomObject>
    <description>SFDC1-785 This is a separate Object created for capturing fields that are a 1:1 relationship with Account but are not attributes that we would consider governing. Many of these fields originated from the multitude of fields found on the account form in Legacy IHS.</description>
    <fields>
        <fullName>AccountReference__c</fullName>
        <inlineHelpText>Lookup Reference of the account connected to the Additional Account Fields</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Account Fields (Account)</relationshipLabel>
        <relationshipName>AdditionAccountFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Account Fields</label>
    <nameField>
        <label>Additional Account Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Account Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AccountCreated__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-309 Lookup to account, this is the account that is created when the type/subtype is Data Governance/New account</description>
        <inlineHelpText>This value is required to close the ticket when the Subtype=New account</inlineHelpText>
        <label>Account Created/Associated</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Account Created)</relationshipLabel>
        <relationshipName>AccountCreatedCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-309 Lookup to Accounts
SFDC1-8156: Relabeling related list label to &quot; Internal Cases&quot;</description>
        <inlineHelpText>Salesforce will populate when the case is spawned from an Account</inlineHelpText>
        <label>Account Reference</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Internal Cases</relationshipLabel>
        <relationshipName>AccountReferenceCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ComplianceRestrictions__c</fullName>
        <description>SFDC1-7738: New field for Order Management Case</description>
        <inlineHelpText>Compliance Restrictions</inlineHelpText>
        <label>Compliance Restrictions</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-965 &amp; SFDC1-638 Country field for new Account creation through Case</description>
        <inlineHelpText>Country for new Account creation through Case</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LostReasonCode__c</fullName>
        <description>SFDC1-7738: New field for Order Management Case</description>
        <inlineHelpText>Lost Reason Code</inlineHelpText>
        <label>Lost Reason Code</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LostReasonDescription__c</fullName>
        <description>SFDC1-7738: New field for Order Management Case</description>
        <inlineHelpText>Lost Reason Description</inlineHelpText>
        <label>Lost Reason Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>SFDC1-965 &amp; SFDC1-683 State field for new Account creation through Case</description>
        <inlineHelpText>State for new Account creation through Case</inlineHelpText>
        <label>State/Province</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>SFDC1-620 2-digit ISO code</description>
        <inlineHelpText>Please enter Country Code</inlineHelpText>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegacyAccountID__c.object
<CustomObject>
    <description>SFDC1-782 This is a custom object with a 1:M relationship from Account to this object.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>SFDC1-782 How Account Legacy ID record is related back to the Account</description>
        <inlineHelpText>The Account to which this legacy ID is related.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Legacy Account IDs</relationshipLabel>
        <relationshipName>LegacyAccountIDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Legacy Account ID</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legacy Account IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ComplianceRestrictions__c</fullName>
        <description>SFDC1-7602 Opportunity - Field for Legal and Compliance. This is a formula reference to the Account object &quot;Compliance Restrictions&quot; field.
SFDC1-8050 Update formula for Opportunity&apos;s Compliance Restriction field</description>
        <formula>Account.ComplianceRestriction__c</formula>
        <inlineHelpText>For accounts with restrictions compliance approval is required on opportunities before they can be moved to closed won.</inlineHelpText>
        <label>Compliance Restrictions</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-412 Global Account Manager can only be updated by System Administrators and GAM Administrators.
SFDC1-4204 : Updated Lookup filter to allow only Salesforce Users.
SFDC1-6960:  Relabeling the GAM field to Account Manager</description>
        <inlineHelpText>Global Account Manager can only be updated by System Administrators and GAM Administrators.</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LostReasonCode__c</fullName>
        <description>SFDC1 -171 ; if the contract is Closed Lost then the Lost Reason Code from the Contract Should display. Otherwise the list of Lost Reason Codes for the Opportunity are listed here.
SFDC1-769 : Updated the Picklist Values and removed old Values.
SFDC1-6704 : Updated the Picklist Values and removed old Values.</description>
        <inlineHelpText>Choose a valid reason from the dropdown list</inlineHelpText>
        <label>Lost Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bankruptcy/Went out of business</fullName>
                </value>
                <value>
                    <fullName>Company Too Small/Retail/Commerce</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>Contact Non Responsive/Wrong Contact</fullName>
                </value>
                <value>
                    <fullName>Customer exiting business</fullName>
                </value>
                <value>
                    <fullName>Customer has merged / restructured</fullName>
                </value>
                <value>
                    <fullName>Customer Lost Bid</fullName>
                </value>
                <value>
                    <fullName>Cutting Costs/Lost Budget</fullName>
                </value>
                <value>
                    <fullName>Decided to do it Themselves</fullName>
                </value>
                <value>
                    <fullName>Duplicate/Existing Opp</fullName>
                </value>
                <value>
                    <fullName>IHSM Decision to Pass/No Bid</fullName>
                </value>
                <value>
                    <fullName>Key contact left company</fullName>
                </value>
                <value>
                    <fullName>Military Base Closure</fullName>
                </value>
                <value>
                    <fullName>No/low usage</fullName>
                </value>
                <value>
                    <fullName>No further interest, has all information needed</fullName>
                </value>
                <value>
                    <fullName>Non Payment</fullName>
                </value>
                <value>
                    <fullName>Out of business/Site Closure</fullName>
                </value>
                <value>
                    <fullName>Product/Solution does not match need</fullName>
                </value>
                <value>
                    <fullName>Product discontinued</fullName>
                </value>
                <value>
                    <fullName>Project completed/cancelled</fullName>
                </value>
                <value>
                    <fullName>Terms &amp; Conditions Issues</fullName>
                </value>
                <value>
                    <fullName>Unfavorable Pricing</fullName>
                </value>
                <value>
                    <fullName>Systematically Closed Lost - Past Due</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LostReasonDescription__c</fullName>
        <description>SFDC1 - 171 ; For lost contract/Deal; Describe the reason for lost deal</description>
        <inlineHelpText>Provide more information for losing this deal</inlineHelpText>
        <label>Lost Reason Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestAccountMethods.cls
//-----------------------------
// @author Paras Dhingra adapted from Tran's code
// @date 28th Jun 2017
// @description Test class for unit testing on Account Triggers
// @Last Modified By : Prachi Bhasin
// @Last Modified Date: 15 March 2018
// @Last Modified Description: SFDC1-7199 - Commenting code related to NAICS hierarchy (TestNAICSUpdate method)
// @Last Modified By : Tran-Vu Tran
// @Last Modified Date : 12nd April 2018
// @Last Modified Description : SFDC1-7718 add method to update child accounts' Compliance Restriction value from Parent account if Exception is not checked
// @Last Modified By : Harshit Singhal
// @Last Modified Date : 12 Jun 2018
// @Last Modified Description : SFDC1-8537 convert Account process builder flows to Trigger
//-----------------------------

@isTest(seeAllData=false)
private class TestAccountMethods {    
    
    static testMethod void TestSyncAccountCountryWithCountryChange() {
        // Test data setup
        TestUtility.loadCountryData();
        Account acct = TestUtility.createTestAccount('Test Sync Country', true);
        
        // Verify that the AccountCountry reference to is Canada
        Account assertAccount1 = [Select Id, AccountCountry__r.Name, AccountCountry__r.CountryCode__c from Account where Id=: acct.Id];
        System.debug('TestSyncAccountCountryWithCountryChange method: Account Country Name=' + assertAccount1.AccountCountry__r.Name
                    + ', Account Country Code=' + assertAccount1.AccountCountry__r.CountryCode__c);
        // System.assertEquals('CA', assertAccount1.AccountCountry__r.Name, 'Checking account country name');
        System.assertEquals('CA', assertAccount1.AccountCountry__r.CountryCode__c, 'Checking account country code');
        
        // Perform Test on update
        Test.startTest();
        //acct.BillingCountry = 'India';
        acct.BillingCountryCode = 'IN';
        update acct;
        Test.stopTest();
        
        // Query the account again to get updated value
        Account assertAccount2 = [Select Id, AccountCountry__c from Account where Id=: acct.Id];
        
        // Country__c targetCountry = [SELECT Id from Country__c WHERE Name = 'India'];
        Country__c targetCountry = [SELECT Id from Country__c WHERE CountryCode__c = 'IN'];
        
        // Verify that the AccountCountry reference to is now showing India
        System.assert(assertAccount2.AccountCountry__c == targetCountry.Id);
    }
    
    //-----------------------------
    // @author Paras Dhingra
    // @Date 05 Jul 2017
    // @description Test class for AccountMethods.updateNAICSHierarchyLookup()
    // @param null
    // @return void
    //-----------------------------
    /*static testMethod void TestNAICSUpdate() {
        
        //create test Data
        Account acct = TestUtility.createTestAccount('Test Account', true);
        NAICSHierarchy__c testNaics = TestUtility.createNAICSData('1111','Agriculture, Forestry, Fishing and Hunting','Oilseed and Grain Farming',true);
        
        //start test
        Test.startTest();
        acct.NaicsCode = '111134';
        update acct;
        Test.stopTest();
        
        //assert 
        Account assertAcct = [Select Id, NAICSHierarchy__c from Account where id=:acct.Id];
        System.assertEquals(testNaics.Id, assertAcct.NAICSHierarchy__c, 'comparing NAICS');
    }*/
    
    //-----------------------------
    // @author Paras Dhingra
    // @Date 07 Jul 2017
    // @description Test class for Accountmethods.updateGAMOnOpenOppys
    // @param null
    // @return void
    //-----------------------------
    static testMethod void TestupdateGAMonOpenOppys() {
        
        User testGAM;
        System.runAs(new User(Id=userInfo.getUserId())) {
            testGAM = TestUtility.createAdminUser('parastest=example@test.com', true);
        }
        //create test data
        Account acct = TestUtility.createTestAccount('Test Account', false);
        acct.DataGovernanceStatus__c = 'Approved';
        insert acct;
        
        Opportunity oppy1 = new Opportunity();
        oppy1.AccountId = acct.Id;
        oppy1.Name = 'Test Oppy 1';
        oppy1.StageName= '1-Sales Qualified';
        oppy1.CloseDate = Date.today()+2;
        insert oppy1;
        
        Opportunity oppy2 = new Opportunity();
        oppy2.AccountId = acct.Id;
        oppy2.Name = 'Test Oppy 2';
        oppy2.StageName = '1-Sales Qualified';
        oppy2.CloseDate = Date.today()+2;
        insert oppy2;
        
        //add product to oppy2
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(oppy2.Id, testPBE, true);
        //Start test
        
        //close oppy 2.
        Test.startTest();
        oppy2.LostReasonCode__c = 'Customer Requirements Changed';
        oppy2.LostReasonDescription__c = 'Test description';
        oppy2.StageName = '6L-Closed Lost';
        update oppy2;
        
        //update GAM on account
        acct.GlobalAccountManager__c = testGAM.Id;
        update acct;
        //assert Opportunities
        Map<Id, Opportunity> mapAssertOppys = new Map<Id, Opportunity>([Select id, GAM__c from Opportunity where id=:oppy1.ID OR id=:oppy2.Id]);
        
        //assert Oppy1
        System.assertEquals(testGAM.Id, mapAssertOppys.get(oppy1.Id).GAM__c);
        System.assertEquals(null, mapAssertOppys.get(oppy2.Id).GAM__c);
        Test.stopTest();
    }
    
    //-----------------------------
    // @author Paras Dhingra
    // @Date 26 Jul 2017
    // @description Test class for Accountmethods.updateLegacyIdObject
    // @param null
    // @return void
    //-----------------------------
    static testMethod void testUpdateLegacyIdObject() {
		/* 2017-09-19 Tran-Vu Tran comment out because this is no longer needed per SFDC1-4517 
        Test.startTest();
        Account testAccount = TestUtility.createTestAccount('Test Account', false);
        testAccount.MarkitSFDC__c = 'A-11002';
        testAccount.IHSCRMGUID__c = 'IHS-23423';
        insert testAccount;
        // assert
        List<LegacyAccountID__c> assertLAI = [Select name from LegacyAccountID__c where Account__c=:testAccount.Id order by name];
        System.assertEquals(2, assertLAI.size(), 'two child records');
        System.assertEquals(testAccount.MarkitSFDC__c, assertLAI[0].name,'matching markit Id');
        System.assertEquals(testAccount.IHSCRMGUID__c, assertLAI[1].name,'matching IHS Id');
		*/
    }
    
    //-----------------------------
    // @author Paras Dhingra
    // @Date 1st Aug 2017
    // @description Test class for Accountmethods.updateAccountTeamMemberRole
    // @param null
    // @return void
    // @companyName IHS Markit
    //-----------------------------
    static testMethod void testUpdateAccountTeamMemberRole() {
        //create test data
        
        User testUser1 = TestUtility.createTestUser('IHSMarkit Data Governance', 'testUSer.testuser123@ihsmarkit.com.user',true);
        User testUser2 = TestUtility.createTestUser('IHSMarkit Data Governance', 'testUser.test22343@ihsmarkit.com.usertest',true);
        System.runAs(testUser1) {
            Test.startTest();
            Account acct = TestUtility.createTestAccount('Test Account', true);
            List<AccountTeamMember> lstAssertATM = [Select id,UserId from AccountTeamMember where  teamMemberRole = 'Account Owner' and accountId=:acct.Id];
            System.assertNotEquals(null, lstAssertATM,'Account Team member role created');
            System.assertEquals(testUser1.Id, lstAssertATM[0].userId);
            
            //update account owner
            acct.ownerId = testUser2.Id;
            update acct;
            lstAssertATM = [Select id,UserId from AccountTeamMember where  teamMemberRole = 'Account Owner' and accountId=:acct.Id];
            System.assertNotEquals(null, lstAssertATM,'Account Team member role created');
            System.assertEquals(testUser2.Id, lstAssertATM[0].userId);
            Test.stopTest();
        }
    }
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 25 Aug 2017
    // @param: NA
    // @description: SFDC1-2103 Test method for Additional Account Fields trigger method setAccountAdditionalFieldsObject on insert
    // @return: NA
    //-----------------------------
    private static testMethod void testSetAccountAdditionalFieldsObject() {
        
        Account testAccount = TestUtility.createTestAccount('TestSetAccountAdditionalFieldsObject', true);
        
        list <Account> testAccountResult = [Select AdditionalAccountFields__c, Id from Account where Id = :testAccount.Id];
        //Assert if account is inserted
        System.assertEquals(1, testAccountResult.size());
        System.assert(testAccountResult[0].AdditionalAccountFields__c != null);
        
        //Assert if Adiitional Account Field is inserted
        list <AdditionalAccountFields__c> acfList = [Select Id from AdditionalAccountFields__c where AccountReference__c = :testAccount.Id];
        System.assertEquals(1, acfList.size());
        System.assertEquals(acfList[0].Id, testAccountResult[0].AdditionalAccountFields__c);
        
    }
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 25 Aug 2017
    // @param: NA
    // @description: SFDC1-2103 Test method for Additional Account Fields trigger method changeAccountAdditionalFieldsObjectNameWhenAccountNameChanges on update. 
    //              To test if Account Additional Fields Object Name chnages when Account Name Changes
    // @return: NA
    //-----------------------------
    private static testMethod void testChangeAccountAdditionalFieldsObjectNameWhenAccountFieldChanges() {
        
        Account testAccount = TestUtility.createTestAccount('TestChangeAccountAdditionalFields', true);
        
        list <Account> testAccountResult = [Select AdditionalAccountFields__c, AdditionalAccountFields__r.Name, Id, Name  from Account where Id = :testAccount.Id];
        //Assert if account is inserted
        System.assertEquals(1, testAccountResult.size());
        System.assert(testAccountResult[0].AdditionalAccountFields__c != null);
        
        System.assertEquals(testAccountResult[0].AdditionalAccountFields__r.Name, 'Additional Fields - ' + testAccountResult[0].Name);
        
        //Update Account Name
        testAccount.Name = 'TestChangeAccountAdditionalFields2';
        update testAccount;
        
        list <Account> testAccountResult2 = [Select AdditionalAccountFields__c, AdditionalAccountFields__r.Name, Id, Name  from Account where Id = :testAccount.Id];
        //Assert if Additional Account Field name gets updated
        System.assertEquals(testAccountResult2[0].AdditionalAccountFields__r.Name, 'Additional Fields - ' + testAccountResult2[0].Name);
        
    }

/*
	// 20-April-2016 comment out codes - will be replaced by formula fields
    //-----------------------------
    // @author: Tran-Vu Tran
    // @created: 10 April 2018
    // @param: NA
    // @description: Test if Account ComplianceRestrictions 
    // @return: NA
    //-----------------------------
    static testMethod void TestAccountComplianceRestrictions() {

        Test.startTest();
        
        List<Account> testAccounts = new List<Account>();
        
        Account acc1 = TestUtility.createTestAccountWithStreet('One', 'Street One', true);
        acc1.ComplianceRestrictions__c = 'Russia Directive 1; Payment terms not > 14 days';
        acc1.CorporateRestrictionException__c = false;
        // testAccounts.add(acc1);
        update acc1;
        System.debug('Account Name: ' + acc1.Name + ', ID: ' + acc1.Id);
        System.debug('Compliance Restrictions: ' + acc1.ComplianceRestrictions__c + ', Exception: ' + acc1.CorporateRestrictionException__c);
        
        Account acc2 = TestUtility.createTestAccountWithStreet('Two', 'Lane Two', true);
        acc2.ParentId = acc1.Id;
        acc2.CorporateRestrictionException__c = false;
        acc2.ComplianceRestrictions__c = null;
        // testAccounts.add(acc2);
        update acc2;
        acc2 = [select Id, Name, ParentId, CorporateRestrictionException__c, ComplianceRestrictions__c
				From Account where Id =: acc2.Id limit 1];
        
        System.debug('Account Name: ' + acc2.Name + ', ID: ' + acc2.Id);
        System.debug('Compliance Restrictions: ' + acc2.ComplianceRestrictions__c + ', Exception: ' + acc2.CorporateRestrictionException__c);
        System.debug('Parent account Name: ' + acc1.Name + ', ID: ' + acc2.ParentId);
        System.debug('Parent Compliance Restrictions: ' + acc1.ComplianceRestrictions__c + ', Parent Exception: ' + acc1.CorporateRestrictionException__c);

        Account acc3 = TestUtility.createTestAccountWithStreet('Three', 'Blvd Three', true);
        acc3.ParentId = acc1.Id;
        acc3.CorporateRestrictionException__c = true;
        acc3.ComplianceRestrictions__c = null;
        // testAccounts.add(acc3);
        update acc3;
        acc3 = [select Id, Name, ParentId, CorporateRestrictionException__c, ComplianceRestrictions__c
				From Account where Id =: acc3.Id limit 1];
        
        System.debug('Account Name: ' + acc3.Name + ', ID: ' + acc3.Id);
        System.debug('Compliance Restrictions: ' + acc3.ComplianceRestrictions__c + ', Exception: ' + acc3.CorporateRestrictionException__c);
        System.debug('Parent account Name: ' + acc1.Name + ', ID: ' + acc3.ParentId);
        System.debug('Parent Compliance Restrictions: ' + acc1.ComplianceRestrictions__c + ', Parent Exception: ' + acc1.CorporateRestrictionException__c);
        
        Account acc4 = TestUtility.createTestAccountWithStreet('Four', 'Drive Four', true);
        acc4.ParentId = acc3.Id;
        acc4.CorporateRestrictionException__c = false;
        acc4.ComplianceRestrictions__c = null;
        // testAccounts.add(acc4);
        update acc4;
        acc4 = [select Id, Name, ParentId, CorporateRestrictionException__c, ComplianceRestrictions__c
				From Account where Id =: acc4.Id limit 1];
        
        System.debug('Account Name: ' + acc4.Name + ', ID: ' + acc4.Id);
        System.debug('Compliance Restrictions: ' + acc4.ComplianceRestrictions__c + ', Exception: ' + acc4.CorporateRestrictionException__c);
        System.debug('Parent account Name: ' + acc3.Name + ', ID: ' + acc4.ParentId);
        System.debug('Parent Compliance Restrictions: ' + acc3.ComplianceRestrictions__c + ', Parent Exception: ' + acc3.CorporateRestrictionException__c);
        
        // update testAccounts;

        System.assertEquals(acc2.ComplianceRestrictions__c, acc1.ComplianceRestrictions__c);
        System.assertNotEquals(acc3.ComplianceRestrictions__c, acc1.ComplianceRestrictions__c);
        System.assertEquals(acc4.ComplianceRestrictions__c, acc1.ComplianceRestrictions__c);

        Test.stopTest();
    }
*/
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 25 Aug 2017
    // @param: NA
    // @description: SFDC1-2103 Test method for Additional Account Fields trigger method deleteAccountAdditionalFieldsRecordWhenAccountGetsDeleted on Delete. 
    //               To test if Account Additional Fields Object gets deleted when Account gets deleted 
    // @return: NA
    //-----------------------------
    private static testMethod void testdeleteAccountAdditionalFieldsRecordWhenAccountGetsDeleted() {
        
        Account testAccount = TestUtility.createTestAccount('TestSetAccountAdditionalFieldsObject', true);
        
        list <Account> testAccountResult = [Select AdditionalAccountFields__c, Id from Account where Id = :testAccount.Id];
        //Assert if account is inserted
        System.assertEquals(1, testAccountResult.size());
        System.assert(testAccountResult[0].AdditionalAccountFields__c != null);
        
        //Assert if Adiitional Account Field is inserted
        AdditionalAccountFields__c acf = [Select Id from AdditionalAccountFields__c where AccountReference__c = :testAccount.Id];
        System.assert(acf != null);
        System.assertEquals(acf.Id, testAccountResult[0].AdditionalAccountFields__c);
        
        delete testAccount;
        
        list <AdditionalAccountFields__c> acfList = [Select Id from AdditionalAccountFields__c where Id = :acf.Id];
        
        ////Assert if Adiitional Account Field is deleted
        System.assertEquals(0, acfList.size());
    }
    
    //-----------------------------
    // @author Harshit Singhal
    // @Date 12 Jun 2018
    // @description Test class for AccountMethods.updateAccountCreatedOnParentCase()
    // @param null
    // @return void
    // @Lastmodified by : Mohit Modi
    // @lastmodified description : Added some more values to new Account co cover the changes in existing methods.
    //-----------------------------
    static testMethod void testUpdateAccountCreatedOnParentCase() {        
        TestUtility.loadCountryData();
        Account testAcc = TestUtility.createTestAccount('Test Account 123', true);
        Contact testContact = TestUtility.createContact(testAcc.Id, 'testContact@ihsmarkit.com', true, 'Test FirstName', 'Test LastName');
        Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Salesforce Helpdesk').getRecordTypeId();
        Case sourceCase = TestUtility.createCase(caseRecordTypeId, testAcc.Id, testContact.Id, UserInfo.getUserId(), 'Test Subject', false);
        sourceCase.Country__c = [SELECT Id from Country__c WHERE CountryCode__c = 'IN'].id;
        insert sourceCase;
        Test.startTest();
        Account newAcc = TestUtility.createTestAccount('Test Account 456', false);
        newAcc.BillingCity = 'Bangalore';
        newAcc.State__c = 'KA';
        newAcc.SourceCase__c = sourceCase.Id;
        Country__c tempCountry = [SELECT Id from Country__c WHERE CountryCode__c = 'IN' limit 1];
        newAcc.AccountCountry__c = tempCountry != NULL ? tempCountry.id : NULL;
        insert newAcc;
        System.assertEquals(newAcc.Id, [Select AccountCreated__c From Case Where Id=:sourceCase.Id LIMIT 1].AccountCreated__c);
        
        // Updating the Country and checking the Country Loopkup fields get updated with the same.
        newAcc.BillingStateCode = 'ON';
        newAcc.BillingCountryCode = 'CA';
        Update newAcc;
        System.assertEquals([SELECT Id from Country__c WHERE CountryCode__c = 'CA' limit 1].id,[SELECT Id,AccountCountry__c from Account WHERE id =: newAcc.id limit 1].AccountCountry__c);
        Test.stopTest();
    }
    
    //-----------------------------
    // @author Harshit Singhal
    // @Date 12 Jun 2018
    // @description Test class for AccountMethods.setAccountOwnerOnAccountManagerChangeAndUpdatePreviousOwner()
    // @param null
    // @return void
    //-----------------------------
    static testMethod void testSetAccountOwnerOnAccountManagerChangeAndUpdatePreviousOwner() {
        User testUser1 = TestUtility.createTestUser('IHSMarkit Data Governance', 'testUSer.testuser123@ihsmarkit.com.user',true);
        
        Test.startTest();
        Account newAcc = TestUtility.createTestAccount('Test Account 123', false);
        newAcc.GlobalAccountManager__c = testUser1.Id;
        insert newAcc;
        System.assertEquals(testUser1.Id, [Select OwnerId From Account Where Id=:newAcc.Id LIMIT 1].OwnerId);
        
        newAcc.GlobalAccountManager__c = UserInfo.getUserId();
        update newAcc;
        Account updatedAcc = [Select OwnerId,PreviousOwner__c From Account Where Id=:newAcc.Id LIMIT 1];
        System.assertEquals(UserInfo.getUserId(), updatedAcc.OwnerId);
        System.assertEquals(testUser1.Id, updatedAcc.PreviousOwner__c);
        Test.stopTest();
    }

}