src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Account Governance team.</inlineHelpText>
        <label>Account Governance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ApprovedContractSummary__c.object
<CustomObject>
    <description>SFDC1-9063, created for account overview report, Provides summary of approved contracts (Not visible to end user, for internal purpose only)</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>SFDC1-9063 Created for account overview report, Master-Detail for accounts</description>
        <inlineHelpText>Master-Detail for accounts</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Approved Contract Summaries</relationshipLabel>
        <relationshipName>ApprovedContractSummaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>SFDC1-9063, Created for account overview report. (Not visible to end users, for internal purpose only)</description>
        <externalId>true</externalId>
        <inlineHelpText>Key Field</inlineHelpText>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Approved Contract Summary</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>Approved Contract Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Contract Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-6735 : Field related  to Consulting Record Type</description>
        <inlineHelpText>Approval required if &gt;$100K or has Milestones or non-standard terms</inlineHelpText>
        <label>Contract Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related product line items from opportunity at Contract record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Consulting</fullName>
        <active>true</active>
        <description>SFDC1-6735: New Record Type Created for SOW/Consulting Usage</description>
        <label>Consulting</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule</description>
    <fields>
        <fullName>AssociatedProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4324 This field holds the product associated with &apos;Opportunity Line Item&apos;, to which contract line item is related.</description>
        <inlineHelpText>Product related to Opportunity Line Item</inlineHelpText>
        <label>Associated Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items (Associated Product)</relationshipLabel>
        <relationshipName>ContractLineItems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesPrice__c</fullName>
        <description>SFDC1-2298; Sales Price for Contract Line Item</description>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ContractLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-905 This is a custom object, which will be related to contract line item.</description>
    <fields>
        <fullName>ContractLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-380 This field holds the value of contract line item record to which contract line item schedule is related</description>
        <inlineHelpText>Contract Line Item</inlineHelpText>
        <label>Contract Line Item</label>
        <referenceTo>ContractLineItem__c</referenceTo>
        <relationshipLabel>Contract Line Item Schedules</relationshipLabel>
        <relationshipName>ContractLineItemSchedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InstallmentYear__c</fullName>
        <description>SFDC1-380 This is a text field which copies InstallmentYear__c from Opportunity Product Schedule</description>
        <inlineHelpText>Installment Year</inlineHelpText>
        <label>Installment Year</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesPrice__c</fullName>
        <description>SFDC1-380 This field gets populated from opportunity product schedule - sales price field when contract is created from wizard</description>
        <inlineHelpText>Sales Price</inlineHelpText>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Line Item Schedule</label>
    <nameField>
        <displayFormat>CLS-{0000000}</displayFormat>
        <label>Contract Line Item Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Item Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <description>SFDC1-7525 Profit center to be rolled up from opportunity product&apos;s related product
SFDC1-8785 : updating the field type to Long Text Area</description>
        <inlineHelpText>Profit center for related products automatically populated by system</inlineHelpText>
        <label>Profit Center</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProfitCenters__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-3837 field to establish relationship between product and it&apos;s profit center</description>
        <inlineHelpText>Reporting Profit Center</inlineHelpText>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProfitCenter__c.object
<CustomObject>
    <description>SFDC1-3837 Object to hold data for profit centers related to a product</description>
    <fields>
        <fullName>SaleType__c</fullName>
        <description>SFDC1-6146: This field stores the Sales Type</description>
        <label>Sale Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Onetime</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBatchCreateContractSummary.cls
//-----------------------------
// @author: Jagadesh Kumar
// @date: 30 July 2018
// @param: NA
// @description: Test Class for BatchCreateContractSummary
// @return: NA
//----------------------------
@isTest
private class TestBatchCreateContractSummary {
	
    @isTest
    static void testApprovalContractCreation() {
        Test.startTest();
        
        List<Account> accList = new List<Account>();
        Account acc = TestUtility.createTestAccount('Account testBatchCreateContract Summary', false);
        acc.DataGovernanceStatus__c = 'Approved';
        accList.add(acc);
        Account acc2 = TestUtility.createTestAccount('Account testBatchCreateContract Summary2', false);
        acc2.DataGovernanceStatus__c = 'Approved';
        accList.add(acc2);
        insert accList;
        
        Opportunity testOpportunity = TestUtility.createOpportunity(acc.Id, 'test Opppy', true);
        ApprovedContractSummary__c acs = new ApprovedContractSummary__c();
		acs.Account__c = acc.id;
		insert acs;
        
        //creating contract
        List<ProductGroup__C> listPG = new List<ProductGroup__C>();
        ProductGroup__C pg1 = new ProductGroup__C(name = 'Test PG1');
        listPG.add(pg1);
        ProductGroup__C pg4 = new ProductGroup__C(name = 'Test PG4');
        listPG.add(pg4);
        insert listPG;
        
        List<ProfitCenter__c> listPc = new List<ProfitCenter__c>();
        ProfitCenter__c pc1 = new ProfitCenter__c(SaleType__c='Onetime');
        listPc.add(pc1);
        ProfitCenter__c pc2 = new ProfitCenter__c(SaleType__c='Subscription');
        listPc.add(pc2);
        ProfitCenter__c pc3 = new ProfitCenter__c(SaleType__c='Consulting');
        listPc.add(pc3);
        insert listPc;
        
        List<Product2> listProducts = new List<Product2>(); 
        Product2 testProd1 = TestUtility.createProduct('Test Product1', false);
        testProd1.ProductGroup__c = pg1.Id;
        testProd1.ProfitCenters__c = pc1.Id;
        listProducts.add(testProd1);
        
        Product2 testProd2 = TestUtility.createProduct('Test Product2', false);
        testProd2.ProductGroup__c = pg1.Id;
        testProd2.ProfitCenters__c = pc2.Id;
        listProducts.add(testProd2);
        
        Product2 testProd3 = TestUtility.createProduct('Test Product3', false);
        testProd3.ProductGroup__c = pg1.Id;
        testProd3.ProfitCenters__c = pc3.Id;
        listProducts.add(testProd3);
        
        Product2 testProd4 = TestUtility.createProduct('Test Product4', false);
        testProd4.ProductGroup__c = pg4.Id;
        listProducts.add(testProd4);
        
        insert listProducts;
        
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd1.Id, true);
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContractWithInsertOptional(acc.Id, legalEntity.Id, country.Id, standardId,false);
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        contract1.recordtypeid = orderFormRecordTypeId;
        contract1.ContractApproved__c = true;
        insert contract1;
        Contract contract2 = TestUtility.createContractWithInsertOptional(acc2.Id, legalEntity.Id, country.Id, standardId,false);
        contract2.recordtypeid = orderFormRecordTypeId;
        contract2.ContractApproved__c = true;
        insert contract2;
        
        // Creating the CLI
        List<ContractLineItem__c> ListCLI = new List<ContractLineItem__c>();
        ContractLineItem__c  testCLI1 = TestUtility.createContractLineItem('TestCLI1',contract1.id,testProd1.id,false);
        testCLI1.AssociatedProduct__c = testProd1.id;
        ListCLI.add(testCLI1);
        
        ContractLineItem__c  testCLI2 = TestUtility.createContractLineItem('TestCLI2',contract1.id,testProd2.id,false);
        testCLI2.AssociatedProduct__c = testProd2.id;
        ListCLI.add(testCLI2);
        
        ContractLineItem__c  testCLI3 = TestUtility.createContractLineItem('TestCLI3',contract1.id,testProd3.id,false);
        testCLI3.AssociatedProduct__c = testProd3.id;
        ListCLI.add(testCLI3);
        
        ContractLineItem__c  testCLI4 = TestUtility.createContractLineItem('TestCLI4',contract2.id,testProd4.id,false);
        testCLI4.AssociatedProduct__c = testProd4.id;
        ListCLI.add(testCLI4);
        
        insert ListCLI;
        
        // Creating the CLIS
        List<ContractLineItemSchedule__c> listCLIS = new List<ContractLineItemSchedule__c>();
        String CURRENTYEAR = String.valueOf(System.today().year());
        ContractLineItemSchedule__c CLIS1 = TestUtility.createContractLineItemSchedule(contract1.id,testCLI1.Id,false);
        CLIS1.InstallmentYear__c = CURRENTYEAR;
        CLIS1.SalesPrice__c = 10000.00;
        listCLIS.add(CLIS1);
        
        ContractLineItemSchedule__c CLIS2 = TestUtility.createContractLineItemSchedule(contract1.id,testCLI2.Id,false);
        CLIS2.InstallmentYear__c = CURRENTYEAR;
        CLIS2.SalesPrice__c = 10000.00;
        listCLIS.add(CLIS2);
        ContractLineItemSchedule__c CLIS3 = TestUtility.createContractLineItemSchedule(contract1.id,testCLI3.Id,false);
        CLIS3.InstallmentYear__c = CURRENTYEAR;
        CLIS3.SalesPrice__c = 10000.00;
        listCLIS.add(CLIS3);
        
        ContractLineItemSchedule__c CLIS4 = TestUtility.createContractLineItemSchedule(contract2.id,testCLI4.Id,false);
        CLIS4.InstallmentYear__c = CURRENTYEAR+1;
        CLIS4.SalesPrice__c = 10000.00;
        listCLIS.add(CLIS4);
        
        insert listCLIS;
        
        String jobId = system.schedule('TestBatchCreateContractSummary2', '0 0 0 3 9 ? 2022' , new BatchCreateContractSummaryScheduler());
        String batchId = Database.executeBatch(new BatchUpdateOpportunityPrimaryContact(),2);
        Test.stopTest();
		List<ApprovedContractSummary__c> assertACS = [Select id,key__c from ApprovedContractSummary__c];
        System.debug('--assertACS--'+assertACS);
		System.assert(assertACS.size()>0);
    }
}