src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Account Governance team.</inlineHelpText>
        <label>Account Governance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityAttachment__c.object
<CustomObject>
    <description>SFDC1-661 Object to define what kind of attachment users are adding to an Opportunity</description>
    <label>Opportunity Attachment</label>
    <nameField>
        <label>Opportunity Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCreateOpportunityAttachment.cls
/**
* @author: Uttam Arya
* @date: 26th Oct 2017 
* @description: SFDC1-5493 Test Controller class for Opportunity Attachment Aura Component
* @company: IHS Markit
*/
@isTest
public class TestCreateOpportunityAttachment {
    @isTest
    static void testConntroller() {
        Test.startTest();
        Id newBusinessRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Account acc = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', false);
        acc.DataGovernanceStatus__c = 'Approved';
        insert acc;
        Opportunity testOpportunity = TestUtility.createOpportunity(acc.Id, 'test Opppy', true);
        testOpportunity.RecordTypeId = newBusinessRecordTypeId;
        
        update testOpportunity;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);        
        OpportunityLineItem testOLI = TestUtility.createOpportunityLineItem(testOpportunity.Id, testPBE, true);
        update testOpportunity;
        
        System.assertEquals((String) Schema.SObjectType.OpportunityAttachment__c.getRecordTypeInfosByName().get('New Business').getRecordTypeId(), CreateOpportunityAttachmentController.getRecordTypeId(testOpportunity.Id));

        Test.stopTest();
    }
    
}