src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Account Governance team.</inlineHelpText>
        <label>Account Governance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Commissionable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-1955;checkbox field for Marketing Campaign</description>
        <inlineHelpText>Checkbox to mark if sales campaign is commisionable.</inlineHelpText>
        <label>Commissionable</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7738: New field for Order Management Case</description>
        <inlineHelpText>Contract End Date</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7738: New field for Order Management Case</description>
        <inlineHelpText>Contract Start Date</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-965 &amp; SFDC1-638 Country field for new Account creation through Case</description>
        <inlineHelpText>Country for new Account creation through Case</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-88 Opportunity related to the issue. If there are many, pick 1 and mention additional in the detailed description, at this time we are only making a 1:1 relationship</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractBeingRenewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1357; Lookup field for Renewal contract. 
SFDC1-5242; Rename the Contract being Renewed field to Originating Contract
SFDC1-6627 Add a filter for this lookup so that only order form can be selected as originating contract.</description>
        <inlineHelpText>Please select a Contract</inlineHelpText>
        <label>Originating Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Order Form contracts can be added as originating contract.</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Order Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReadyForProcessingContractExist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5701, this will be set to true by the process builder on Contract whenever Contract Status changes to &quot;Ready For Processing&quot;.</description>
        <label>Ready For Processing Contract Exist?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCreateCaseForSalesLedCampaign.cls
//-----------------------------
// @author: Hemant Shukla
// @date: 12-oct-2017
// @param: NA
// @description: Test class for CreateCaseForSalesLedCampaign class. SFDC1-4630, This class is used to create Case when Opportunity gets closes and it has Sales Led Commissionable campaign
// @Last Modified By : Hemant Shukla
// @Last Modified Description : Removed the dependency of ContractExists__c field based on SFDC1-5701
// @Last Modified Date : 6-Nov-2017
// @Last Modified By : Prachi Bhasin
// @Last Modified Date: 20 Dec 2017 Sprint 15
// @Last Modified Description: SFDC1-6411, Test class fix for OpportunityMethods class update
// @Last Modified By : Sruti Srivastava
// @Last Modified Date: 25 June 2018
// @Last Modified Description: Test class fixes
// 
// @Last Modified By : Vishnu Vardhan Chowdary Andra
// @Last Modified Date: 08 Aug 2018
// @Last Modified Description: Code is deleted/commented out as part of stories SFDC1-9677/78/80/81/82/83/84.
// 		Accordingly commenting out test class. 
//-----------------------------

@isTest
public class TestCreateCaseForSalesLedCampaign {
    
    
    
    //-----------------------------
    // @author Hemant Shukla
    // @date 12-oct-2017
    // @description SFDC1-4630, test method for createCase method
    // @param NA
    // @lastmodified description: Primary Contact roles needs to be created before updating opprtunity to stage 3 and above as per  SFDC1-5782 AND SFDC1-5029
    // @modifiedBy: Ankita Singh on 5th December,2017
    // @lastmodified description: Removing Internal partner record types and changing it to Sales Support and also account Name.
    // @modifiedBy: Vishnu Vardhan on 4th April,2018, SFDC1-7120
    // @modifiedBy: sruti srivastava on 25th june,2018, test class fixes
    //-----------------------------
    
    static testMethod void testCreateCase() {
    
        //create test data
        /*Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        
        Account testAccount = TestUtility.createTestAccount('IHS Markit', false);
        testAccount.DataGovernanceStatus__c = 'Approved';
        insert testAccount;
        
        Contact testcontact1 = TestUtility.createContact(testAccount.id, 'h@ihsmarkit.com', true, 'h', 's');
        Contact testcontact2 = TestUtility.createContact(testAccount.id, 'p@ihsmarkit.com', true, 'p', 't');
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        
        
        Id newBusinessRecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Id renewalRecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        Contract contract = TestUtility.createContractWithInsertOptional(testAccount.Id, legalEntity.Id, country.Id, standardId,FALSE);
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        contract.recordtypeid = orderFormRecordTypeId;
        insert contract;
        
        List<Opportunity> listOpportunities = new List<Opportunity>();
        //create related opportunity
        Opportunity testOpportunity1 = TestUtility.createOpportunity(testAccount.Id, 'test Opppy1', false);
        testOpportunity1.RecordTypeId = newBusinessRecordTypeId;
        testOpportunity1.StageName= '1-Sales Qualified';
        listOpportunities.add(testOpportunity1);
        
        Opportunity testOpportunity2 = TestUtility.createOpportunity(testAccount.Id, 'test Opppy2', false);
        testOpportunity2.RecordTypeId = renewalRecordTypeId;
        testOpportunity2.StageName= '3-Renewal Pending';
        testOpportunity2.ContractBeingRenewed__c = contract.Id;
        listOpportunities.add(testOpportunity2);
        
        insert listOpportunities;
        List<OpportunityLineItem> listOpportunityLineItem = new List<OpportunityLineItem>();
        OpportunityLineItem testOLI1 = TestUtility.createOpportunityLineItem(listOpportunities[0].Id, testPBE, false);
        OpportunityLineItem testOLI2 = TestUtility.createOpportunityLineItem(listOpportunities[1].Id, testPBE, false);
        listOpportunityLineItem.add(testOLI1);
        listOpportunityLineItem.add(testOLI2);
        insert listOpportunityLineItem;
        
        List<Campaign> lstCampaigns = new List<Campaign>();
        Campaign testCampaign1 = new Campaign(Name='test campaign1', 
                                              IsActive = true,
                                              Status = 'In Progress',
                                              startdate = System.today() - 30,
                                              EndDate = System.today() + 30,
                                              Type = 'Sales Led',
                                              Commissionable__c = true);
                                              
        Campaign testCampaign2 = new Campaign(Name='test campaign1', 
                                              IsActive = true,
                                              Status = 'In Progress',
                                              startdate = System.today() - 30,
                                              EndDate = System.today() + 30,
                                              Type = 'Sales Led',
                                              Commissionable__c = true);                                      
        
        lstCampaigns.add(testCampaign1);
        lstCampaigns.add(testCampaign2);
        
        insert lstCampaigns;
        System.assertEquals(2, [select id from Campaign].size());
        
        Id CIMId = [Select Id from CampaignInfluenceModel where IsDefaultModel = true].Id;
        
        list<CampaignInfluence> lstCI = New List<CampaignInfluence>();
        CampaignInfluence ci1 = new CampaignInfluence(CampaignId = testCampaign1.id,
                                                      ContactId = testcontact1.id,
                                                      OpportunityId = testOpportunity1.id,
                                                      ModelId = CIMId
                                                      );
                                                      
        CampaignInfluence ci2 = new CampaignInfluence(CampaignId = testCampaign2.id,
                                                      ContactId = testcontact2.id,
                                                      OpportunityId = testOpportunity1.id,
                                                      ModelId = CIMId
                                                      );     
                                                      
        CampaignInfluence ci3 = new CampaignInfluence(CampaignId = testCampaign1.id,
                                                      ContactId = testcontact1.id,
                                                      OpportunityId = testOpportunity2.id,
                                                      ModelId = CIMId
                                                      );
                                                      
        CampaignInfluence ci4 = new CampaignInfluence(CampaignId = testCampaign2.id,
                                                      ContactId = testcontact2.id,
                                                      OpportunityId = testOpportunity2.id,
                                                      ModelId = CIMId
                                                      );                                                   
        
        lstCI.add(ci1);
        lstCI.add(ci2);
        lstCI.add(ci3);
        lstCI.add(ci4);
        
        insert lstCI;
        
        List<OpportunityContactRole> ocrList = new List<OpportunityContactRole>();
        OpportunityContactRole ocr1 = new OpportunityContactRole();
        ocr1.ContactId = testContact1.Id;
        ocr1.OpportunityId = testOpportunity1.Id;
        ocr1.IsPrimary = TRUE;
        ocr1.Role = 'Decision Maker';
        
        OpportunityContactRole ocr2 = new OpportunityContactRole();
        ocr2.ContactId = testContact2.Id;
        ocr2.OpportunityId = testOpportunity2.Id;
        ocr2.IsPrimary = TRUE;
        ocr2.Role = 'Decision Maker';
        ocrList.add(ocr1);
        ocrList.add(ocr2);
        insert ocrList;
        
        Test.startTest();
       
        List<Opportunity> lstToUpdate = new List<Opportunity>();
        lstToUpdate.add(new Opportunity(id = testOpportunity1.id,
                                        StageName = '6W-Closed Won',
                                        ContractId = contract1.id,
                                        ContractStartDate__c = System.today(),
                                        ContractEndDate__c = System.today(),
                                        ActivityCreated__c = true,
                                        ReadyForProcessingContractExist__c  = true
                                        )
                        );
                        
        lstToUpdate.add(new Opportunity(id = testOpportunity2.id,
                                        StageName = '6W-Closed Won',
                                        ContractId = contract1.id,
                                        ContractStartDate__c = System.today(), 
                                        ContractEndDate__c = System.today(),
                                        ActivityCreated__c = true,
                                        ReadyForProcessingContractExist__c  = true
                                        )
                        );                
        
        
        update lstToUpdate;
        
        //Do assert check if process builder fires. 
        if(GlobalConstants.hasCreateCaseForSalesLedCampaignprocessfired){
            
            List<Case> lCases = [Select Id, Subject, origin, RecordTypeId, ownerId from case];
            
            System.assertEquals(4, lCases.size(), 'Total number of cases');
            System.assertEquals(2, [Select Id from case where Opportunity__c = :testOpportunity1.id].size(), 'Total number of cases for Opp1');
            System.assertEquals(2, [Select Id from case where Opportunity__c = :testOpportunity2.id].size(), 'Total number of cases for Opp1');
            
            Id salesSupportRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Sales Support').getRecordTypeId();
            List<Group> queues = [select Id from Group where Name = 'Sales Claims Team' and Type = 'Queue'];
            
            //checking for field value for created case.
            Case objCase = [Select Id, Subject, origin, RecordTypeId, ownerId from case where Opportunity__c = :testOpportunity1.id][0];
            System.assertEquals('Sales Claim Request', objCase.Subject , 'subject check');
            System.assertEquals('Internal', objCase.origin , 'origin check');
            System.assertEquals(salesSupportRecordTypeId, objCase.RecordTypeId , 'RecordTypeId check');
        }
        
        Test.stopTest();*/
    }        

}