src/objects/AccountRanking__c.object
<CustomObject>
    <description>SFDC1-7592 Lift &amp; Shift from Legacy Markit</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>SFDC1-7592 Lookup to the account that this ranking is related</description>
        <inlineHelpText>Lookup to the account that this ranking is related</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Rankings</relationshipLabel>
        <relationshipName>AccountRankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <description>SFDC1-7592 Criteria of the Value</description>
        <label>Criteria</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Assets on Balance Sheet</fullName>
                </value>
                <value>
                    <fullName>AUM</fullName>
                </value>
                <value>
                    <fullName>Equity Assets</fullName>
                </value>
                <value>
                    <fullName>Equity Trades</fullName>
                </value>
                <value>
                    <fullName>Wilshire Index</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RankCountry__c</fullName>
        <defaultValue>&apos;Global&apos;</defaultValue>
        <description>SFDC1-7592 Rank Country picklist values</description>
        <label>Rank Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountriesPicklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>SFDC1-7592 Read-only as this is a calculated field, should be triggered on record add or edit.</description>
        <inlineHelpText>Read-only calculated field</inlineHelpText>
        <label>Rank</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>SFDC1-7592 Source of where the value was received</description>
        <inlineHelpText>Source of where the value was received</inlineHelpText>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reuters</fullName>
                </value>
                <value>
                    <fullName>Factset</fullName>
                </value>
                <value>
                    <fullName>Data.com</fullName>
                </value>
                <value>
                    <fullName>BigDough</fullName>
                </value>
                <value>
                    <fullName>Investor Relations</fullName>
                </value>
                <value>
                    <fullName>PREQIN</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ValueAsOf__c</fullName>
        <description>SFDC1-7592 Value to be considered in ranking</description>
        <inlineHelpText>Value to be considered in ranking</inlineHelpText>
        <label>Value as of</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>SFDC1-7592 Account Ranking Value</description>
        <inlineHelpText>Account Ranking Value</inlineHelpText>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Account Ranking</label>
    <nameField>
        <displayFormat>AR-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAccountRankings.cls
//-----------------------------
// @author: Uttam Arya
// @date: unknown
// @param: NA
// @description: Class to hold unit test methods for Account Ranking
// @return: NA
// @updated: 30 March 2018
// @updated by: Tran-Vu Tran
// @update reason: SFDC1-7592 migrated from Markit legacy codes
//-----------------------------

@isTest
public class TestAccountRankings {
    
    static testMethod void TestAccountRankingCalculation() {

        Test.startTest();
        
        Account acc1 = TestUtility.createTestAccountWithStreet('One', 'Street One', true);
        Account acc2 = TestUtility.createTestAccountWithStreet('Two', 'Lane Two', true);
        Account acc3 = TestUtility.createTestAccountWithStreet('Three', 'Blvd Three', true);
        Account acc4 = TestUtility.createTestAccountWithStreet('Four', 'Drive Four', true);
        
        list <Account> AccountList = [Select id from account];
        
        list <AccountRanking__c> rrListToUpdate = new list <AccountRanking__c>();
        
        AccountRanking__c rr1 = createAccountRanking(acc1.id, 'India', 'AUM', 100000); 
        AccountRanking__c rr2 = createAccountRanking(acc1.id, 'Nepal', 'Assets', 100000); 
        AccountRanking__c rr3 = createAccountRanking(acc1.id, 'Japan', 'Assets', 200000); 
        AccountRanking__c rr4 = createAccountRanking(acc1.id, 'Belgium', 'AUM', 100000); 
        AccountRanking__c rr5 = createAccountRanking(acc1.id, 'Congo', 'AUM', 100000); 
        AccountRanking__c rr6 = createAccountRanking(acc1.id, 'United Kingdom', 'AUM', 100000); 
        AccountRanking__c rr7 = createAccountRanking(acc1.id, 'United States', 'AUM', 100000); 
        AccountRanking__c rr8 = createAccountRanking(acc2.id, 'India', 'AUM', 100000); 
        AccountRanking__c rr9 = createAccountRanking(acc3.id, 'India', 'AUM', 200000); 
        
        rr2.Value__c = 300000;
        
        rrListToUpdate.add(rr2);
        
        rr8.Value__c = 150000;
        
        rrListToUpdate.add(rr8);
        GlobalVariables.skipAccountRanking = false;
        update rrListToUpdate;
        Map<Id, AccountRanking__c> mapAccount = new Map<Id, AccountRanking__c>(rrListToUpdate);
        // assert Account ranking
        List<AccountRanking__c> acctRanking = [Select id, Rank__c from AccountRanking__c where Id in:mapAccount.keySet() ];
        Map<Id, Decimal> mapAccountRanking = new Map<Id, Decimal>();
        for (AccountRanking__c ar: acctRanking) {
            mapAccountRanking.put(ar.Id, ar.Rank__c);
        }
        System.assertEquals(1, mapAccountRanking.get(rr2.Id));
        System.assertEquals(2, mapAccountRanking.get(rr8.Id));
        
        Test.stopTest();
    }
    
    static AccountRanking__c createAccountRanking(Id accountID, String country, String criteria, Integer value) {
        AccountRanking__c rr = new AccountRanking__c();
        rr.Account__c = accountID; 
        rr.Value__c = value;
        rr.RankCountry__c = country;
        rr.Source__c = 'Factset';
        rr.Criteria__c = criteria;
        rr.ValueAsOf__c = Date.today();
        insert rr;
        return rr;
    }
     
}