src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DataGovernanceStatus__c</fullName>
        <description>SFDC1-144 Signifies if the account has been validated by the Data Governance Team</description>
        <inlineHelpText>Maintained by the Account Governance team.</inlineHelpText>
        <label>Account Governance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-144 Determines if the Account is Active or inactive.</description>
        <inlineHelpText>Please select account status.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>InactiveOutOfBusiness</fullName>
                </value>
                <value>
                    <fullName>InactiveInvalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Commissionable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-1955;checkbox field for Marketing Campaign</description>
        <inlineHelpText>Checkbox to mark if sales campaign is commisionable.</inlineHelpText>
        <label>Commissionable</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-965 &amp; SFDC1-638 Country field for new Account creation through Case</description>
        <inlineHelpText>Country for new Account creation through Case</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PORequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-8434 PO Required field will need to be added to the case.</description>
        <inlineHelpText>PO Required? is populated from the Auto Renewal Opportunity</inlineHelpText>
        <label>PO Required?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-200 Determines if the Contact is active or inactive</description>
        <inlineHelpText>Please select contact&apos;s status</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -105, Look up field for a related Account</description>
        <inlineHelpText>This is the account record associated to the Company Name. If a new Account is requested from the lead, this field will be populated once the case to request the new account is marked as closed complete.</inlineHelpText>
        <label>Requested Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account must be active to be associated to lead.</errorMessage>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>Account must be active to be associated to lead.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetRange__c</fullName>
        <description>SFDC1-551; This field represent budget for a Lead which on conversion populate same field on opportunity</description>
        <inlineHelpText>Amount that has been set aside for purchase.</inlineHelpText>
        <label>Budget Range</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&lt; 25,000</fullName>
                </value>
                <value>
                    <fullName>25,000-50,000</fullName>
                </value>
                <value>
                    <fullName>50,000-100,000</fullName>
                </value>
                <value>
                    <fullName>&gt; 100,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessLineInterest__c</fullName>
        <description>SFDC1-1033</description>
        <inlineHelpText>Sales/Marketing BL that product of interest falls under.</inlineHelpText>
        <label>Business Line Interest</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallingCountryCode__c</fullName>
        <description>SFDC1- 105 ; Country code of contact , Ex - +44 (UK)</description>
        <inlineHelpText>Calling Country code for the Contact.</inlineHelpText>
        <label>Calling Country Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-1081 Country lookup field to enforce prohibited country validations.
SFDC1-7580 - Country isn&apos;t Required for Lead Creation.</description>
        <inlineHelpText>Country of Contact.</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExistingOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFCD1- 105 ; Lookup field for associated existing opportunity</description>
        <inlineHelpText>Select if you would like to associate this lead to an existing opportunity.</inlineHelpText>
        <label>Existing Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leads (Existing Opportunity)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedInteraction__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1 - 105 ; A check box field for client</description>
        <inlineHelpText>Contact has requested follow up from Sales</inlineHelpText>
        <label>Requested Interaction</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BudgetRange__c</fullName>
        <description>This field captures the budget range for the opportunity</description>
        <inlineHelpText>Please provide the Budget Range.</inlineHelpText>
        <label>Budget Range</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt; 25,000</fullName>
                </value>
                <value>
                    <fullName>25,000-50,000</fullName>
                </value>
                <value>
                    <fullName>50,000-100,000</fullName>
                </value>
                <value>
                    <fullName>&gt; 100,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PORequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1- 535 ;Checkbox fields on opportunity which is automatically populated from Account, SFDC1-959 : Added &apos;?&apos; to the Label.</description>
        <label>PO Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SourceSystem__c</fullName>
        <description>SFDC1 -171; Describe source of the lead/opportunity
SFDC1-2219; Rename Source System to External Source System
SFDC1-8491: Updated picklist values</description>
        <inlineHelpText>Please select a value</inlineHelpText>
        <label>External Source System</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>Manually Generated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>IHS CRM</fullName>
                </value>
                <value>
                    <fullName>Clone</fullName>
                </value>
                <value>
                    <fullName>Lead Generated</fullName>
                </value>
                <value>
                    <fullName>Third Party System</fullName>
                </value>
                <value>
                    <fullName>Polk Salesforce</fullName>
                </value>
                <value>
                    <fullName>Markit Salesforce</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Markit SFDC</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Markit Salesforce.com</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Polk SFDC</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Polk Salesforce.com</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestConvertLeadController.cls
//-----------------------------
// @author: Vinod Merwade
// @date: 19 July 2017
// @param: NA
// @description: SFDC1-45 and SFDC1-186 Test class for ConvertLeadController
// @return: NA
// @Company: Vertiba
// @Last Modified Date : 8 Sept 2017
// @Modification -Anjani Shukla - SFDC1-7580 - Country isn't Required for Lead Creation
//-----------------------------
@isTest
public class TestConvertLeadController {

     //-----------------------------
    // @author: Vinod Merwade
    // @date: 19 July 2017
    // @param: NA
    // @description:SFDC1-45 and SFDC1-186 Test data for the test class
    // @return: NA
    // @Company: Vertiba
    //-----------------------------
    @testSetup public static void setup() {
        
        TestUtility.loadLeadConversionFieldMapping();
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Account accSobj = TestUtility.createTestAccount('Test Account', false);
        accSobj.Status__c = 'Active';                                              
        accSobj.DataGovernanceStatus__c = 'Approved';
        insert accSobj;
        Opportunity oppSobj = new Opportunity(
            Amount = 100.00,
            Name = 'Test opportunity',
            CloseDate = system.Today(),
            StageName = '1-Sales Qualified', 
            Probability = 10,
            AccountId = accSobj.id,
            ForecastCategoryName = 'Pipeline',
            // Modified by Sonam Raju : Moved PORequired__c field to deletion list as per SFDC1-959
            // PORequired__c = false,
            SourceSystem__c = 'Manually Generated',
            budgetRange__c = '< 25,000'
        );
        insert oppSobj;
        Campaign campSobj = new Campaign(
            Name = 'camp1 ',
            StartDate = system.today(), 
            Status = 'In Progress', 
            Description = 'camp1', 
            IsActive = true,
            Commissionable__c = true
        );
        insert campSobj;
       
       
        List<Lead> leadSobjList = new List<Lead>();
        for(integer i=0;i<5;i++){
        Lead leadSobj = new Lead(
            Status = 'New', 
            Company = 'ABC Company'+i, 
            Account__c = accSobj.id,
            Email = 'care@abc'+i+'.com', 
            Phone = '1234567890', 
            BusinessLineInterest__c = 'Test Opportunity ABC',   
            Description = 'This is test Lead',
            RequestedInteraction__c = false,
            LastName =i+'TestLastName'+i,
            FirstName=i+'TestFirstName'+i,
            BudgetRange__c ='< 25,000',
            Country__c = lstCountry[0].id,
            CallingCountryCode__c = 'IN',
            CountryCode = 'IN'
        );
            leadSobjList.add(leadSobj);
        }        
        system.debug('leadSobjList==>'+leadSobjList);
        insert leadSobjList;
        
         CampaignMember memberSobj = new CampaignMember(
            CampaignId = campSobj.id, 
            LeadId = leadSobjList[4].id,
            Status = 'Sent' 
        );
        insert memberSobj;
        Lead FalseLeadSobj = new Lead(
            Status = 'New', 
            Company = 'flase', 
            Email = 'false@false.com', 
            Phone = '1234567890', 
            BusinessLineInterest__c = 'Test Opportunity False',   
            Description = 'This is test Lead',
            RequestedInteraction__c = false,
            LastName ='TestLastName',
            FirstName='TestFirstName',
            Account__c = accSobj.id,
            Country__c = lstCountry[0].id,
            CountryCode = 'IN'
        );
        
        insert FalseLeadSobj;
    }
    
     //-----------------------------
    // @author: Vinod Merwade
    // @date: 19 July 2017
    // @param: NA
    // @description:SFDC1-45 and SFDC1-186 Test method for convertLead on conversion convert the Lead
    // @return: NA
    // @Company: Vertiba
    //-----------------------------
    
    public static testmethod void converLeadControllerTest() {
        
        List<Lead> leadObject = [select id,Name from Lead  ];
        Account accountObject = [select id,Name from Account where Name =:'Test Account'  Limit 1];
        Opportunity opportunityObject = [select id,Name from Opportunity where Name =: 'Test opportunity' Limit 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(leadObject[0]);
        ConvertLeadController cLC4 =  new ConvertLeadController(sc);
        cLC4.selectedValue = 'Activity';
        cLC4.leadOpportunity.ExistingOpportunity__c=opportunityObject.id;
        cLC4.convertLead();
        List<Task> taskCreated = [Select id,subject from Task] ;
        system.assertEquals(taskCreated.size(),1,'Task Created');
        
        test.startTest();
        ApexPages.StandardController sc1 = new ApexPages.StandardController(leadObject[1]);
        ConvertLeadController cLC1 =  new ConvertLeadController(sc1);
        cLC1.selectedValue = 'Case';
        cLC1.convertLead();
        List<Case> caseCreated = [Select id,subject from Case] ;
        system.assertEquals(caseCreated.size(),1,'Case Created');
         
        ApexPages.StandardController sc3 = new ApexPages.StandardController(leadObject[3]);
        ConvertLeadController cLC3 =  new ConvertLeadController(sc3);
        cLC3.selectedValue = 'Contact';
        cLC3.convertLead();
        Lead converted = [select id,name,isConverted from lead where isConverted=true and id=:leadObject[3].id];
        system.assertEquals(converted.id, leadObject[3].id, 'Lead Converted');
        
        ApexPages.StandardController sc4 = new ApexPages.StandardController(leadObject[4]);  
        ConvertLeadController cLC5 =  new ConvertLeadController(sc4);
        cLC5.selectedValue = 'OppCont';
        cLC5.convertLead();
        converted = [select id,name,isConverted from lead where isConverted=true and id=:leadObject[3].id];
        system.assertEquals(converted.IsConverted, true);
        test.stopTest();
    }
    
     //-----------------------------
    // @author: Vinod Merwade
    // @date: 19 July 2017
    // @param: NA
    // @description: SFDC1-45 and SFDC1-186 Test method for convertLead on conversion convert the Lead
    // @return: NA
    // @Company: Vertiba
    //-----------------------------

    public static testmethod void converLeadControllerTest2() {
        
        Lead FalseLeadSobj = [select id,Name from Lead where Company =:'flase' limit 1];
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        Account accountObject = [select id,Name from Account where Name =:'Test Account'  Limit 1];
        Opportunity opportunityObject = [select id,Name from Opportunity where Name =: 'Test opportunity' Limit 1];
        
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(FalseLeadSobj);
        ConvertLeadController cLC4 =  new ConvertLeadController(sc);
        cLC4.selectedValue = 'Activity';
        cLC4.leadOpportunity.ExistingOpportunity__c=opportunityObject.id;
        cLC4.convertLead();
        List<Task> taskCreated = [Select id,subject from Task] ;
        system.assertEquals(taskCreated.size(),1,'Task  Created');
        
        ApexPages.StandardController sc1 = new ApexPages.StandardController(FalseLeadSobj);
        ConvertLeadController cLC1 =  new ConvertLeadController(sc1);
        cLC1.selectedValue = 'Case';
        cLC1.convertLead();
        List<Case> caseCreated = [Select id,subject from Case] ;
      //  system.assertEquals(caseCreated.size(),1,'Case Created');
              
        ApexPages.StandardController sc3 = new ApexPages.StandardController(FalseLeadSobj);
        ConvertLeadController cLC3 =  new ConvertLeadController(sc3);
        cLC3.selectedValue = 'Contact';
        cLC3.convertLead();
        System.assertEquals(0, pageMessages.size());
        
        ApexPages.StandardController sc4 = new ApexPages.StandardController(FalseLeadSobj);  
        ConvertLeadController cLC5 =  new ConvertLeadController(sc4);
        cLC5.selectedValue = 'OppCont';
        cLC5.convertLead();
        System.assertEquals(0, pageMessages.size());
        cLC5.backToLead();
        test.stopTest();
    }
    
     //-----------------------------
    // @author: Vinod Merwade
    // @date: 25 October 2017
    // @param: NA
    // @description: Test Method to cover the duplicate contacts while conversion.
    // @return: NA
    // @Company: Vertiba
    //-----------------------------
    
    public static testmethod void converLeadControllerTest3() {
        Lead FalseLeadSobj = [select id,Name from Lead where Company =:'flase' limit 1];
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        Account accountObject = [select id,Name from Account where Name =:'Test Account'  Limit 1];
        Opportunity opportunityObject = [select id,Name from Opportunity where Name =: 'Test opportunity' Limit 1];
        contact con = new contact();
        con.FirstName = 'TestFirstName';
        con.LastName = 'TestLastName';
        con.Email = 'false@false.com';
        con.Phone = '123456789';
        con.AccountId =accountObject.id;
        insert con;
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(FalseLeadSobj);
        ConvertLeadController cLC4 =  new ConvertLeadController(sc);
        cLC4.selectedValue = 'Contact';
        cLC4.convertLead();
        cLc4.selectedContact = con.Id;
        cLC4.convertLead();
        test.stopTest();
        
    }
    
}