src/objects/AccountRanking__c.object
<CustomObject>
    <description>SFDC1-7592 Lift &amp; Shift from Legacy Markit</description>
    <fields>
        <fullName>MetricsKey__c</fullName>
        <description>SFDC1-7592 concatenation of Rank Country and Criteria value</description>
        <formula>TEXT(RankCountry__c) &amp; TEXT(Criteria__c)</formula>
        <label>Metrics Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>SFDC1-7592 Account Ranking Value</description>
        <inlineHelpText>Account Ranking Value</inlineHelpText>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Account Ranking</label>
    <nameField>
        <displayFormat>AR-{000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountRankingMethods.cls
//***************************************************************************************************************
// @author Tran-Vu Tran (adapted from Uttam's code in Markit Legacy AccountRankingTrigger class)
// @date 02nd April 2018
// @description SFDC1-7592 Account Ranking Lift & Shift from Legacy Markit
// Class created to add common methods to be used by Account Ranking trigger handler classes
//***************************************************************************************************************

public class AccountRankingMethods {

    public static void CalculateRanking (TriggerParameters tp) {
        
        if (tp.tEvent == TriggerParameters.TriggerEvent.afterInsert ||
            tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate) {
            
            Boolean recalculateAccountrankings = false;
                
            set <String> countryMetricKeys = new set <String>();
            
            List <AccountRanking__c> newList = tp.newList;
                
            if (!GlobalVariables.skipAccountRanking) {
                
                if (tp.tEvent == TriggerParameters.TriggerEvent.afterInsert) {
                    for (AccountRanking__c arr : newList) {

                        if (arr.Value__c != null && arr.MetricsKey__c != null) {
                            recalculateAccountrankings = true;
                            countryMetricKeys.add(arr.MetricsKey__c);
                            //System.debug('@@@@@@UA arr' + arr);
                        }
                    }
                }
                else if (tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate) {
                    for (AccountRanking__c arr : newList) {
                        
                        AccountRanking__c oldAR = (AccountRanking__c) tp.oldMap.get(arr.id);
                        
                        if (arr.Value__c != null && arr.MetricsKey__c != null
                            && (arr.Value__c <> oldAR.Value__c
                                || arr.MetricsKey__c <> oldAR.MetricsKey__c
                               )
                           ) {
                               recalculateAccountrankings = true;
                               countryMetricKeys.add(arr.MetricsKey__c);
                               //System.debug('@@@@@@UA arr' + arr);
                               
                               if (oldAR.MetricsKey__c != null) {
                                   countryMetricKeys.add(oldAR.MetricsKey__c);
                                   //System.debug('@@@@@@UA arr' + arr);
                               }
                           } else {
                               continue;
                           }
                    }
                }
            }
            
            if (recalculateAccountrankings) {
                AccountMethods.recalculateAccountRankings(countryMetricKeys);
            }
        }
    }
    
}