src/objects/AdClaim__c.object
<CustomObject>
    <description>SFDC1-332: AdClaim Object will be used to Track the Opportunity Ad Claims.</description>
    <fields>
        <fullName>ContactName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Contact Name</description>
        <inlineHelpText>Name of contact at the requesting organization</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ad Claims</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Opportunity</description>
        <inlineHelpText>Opportunity number of the publication fee to which this claim is related</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ad Claims</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Claim</label>
    <nameField>
        <displayFormat>AC{0000}</displayFormat>
        <label>Ad Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Claims</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MeetingAttendee__c.object
<CustomObject>
    <description>SFDC1-863; Meeting Attendee Object to Capture details of the Attendees</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IHSMarkitEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IHS Markit Employee?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>When__c</fullName>
        <formula>MeetingNote__r.When__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>When</label>
        <type>Date</type>
    </fields>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>MAT-{000000000}</displayFormat>
        <label>Meeting Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MeetingNote__c.object
<CustomObject>
    <fields>
        <fullName>AttendeeNames__c</fullName>
        <inlineHelpText>Please Enter Client Attendee&apos;s Name</inlineHelpText>
        <label>Client Attendee Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ContactLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Attendees</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IHSMarkitAttendeeNames__c</fullName>
        <inlineHelpText>Please Enter IHS Markit Attendee&apos;s Name</inlineHelpText>
        <label>IHS Markit Attendee Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InternalContactLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Add non-salesforce users</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only send meeting notes to internal customers.</errorMessage>
            <filterItems>
                <field>Contact.Email</field>
                <operation>contains</operation>
                <value>@ihsmarkit.com</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meeting Notes (Add non-salesforce users)</relationshipLabel>
        <relationshipName>MeetingNotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Recipients</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>When__c</fullName>
        <label>When</label>
        <type>Date</type>
    </fields>
    <label>Meeting Note</label>
    <nameField>
        <label>Meeting Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Notes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RelatedOpportunity__c.object
<CustomObject>
    <description>SFDC1-863; Related Opportunity Object is a Junction Object between Opportunities and Meeting Note</description>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>When__c</fullName>
        <formula>MeetingNote__r.When__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>When</label>
        <type>Date</type>
    </fields>
    <label>Related Opportunity</label>
    <nameField>
        <displayFormat>RO-{000000000}</displayFormat>
        <label>Related Opportunity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendMeetingNoteToOpportunityTeam.cls
/**
 * @author Modified By: Vinod Merwade
 * @description: Migrated class from existing Markit System and added comments. 
 * 		 Sending meeting notes to opportunity team
 * @date 7th Jul 2017
 */
public with sharing class SendMeetingNoteToOpportunityTeam {
        
    public MeetingNote__c meeting {get;set;}
    //Our collection of the class/wrapper objects cContact
    public List<cRecipient> recipientList {get; set;}
    public Integer deleteNum {get;set;}
    public List<RelatedOpportunity__c> relatedOppyList {get;set;}
    public Set<Id> oppyIds = new Set<Id>();
    
    public SendMeetingNoteToOpportunityTeam() {
        meeting = [select Id, Name, When__c, InternalContactLookup__c, UserLookup__c, ContactLookup__c, Opportunity__c from MeetingNote__c where Id =: System.currentPageReference().getParameters().get('meetingId')];
        relatedOppyList = [select Opportunity__c from RelatedOpportunity__c where MeetingNote__c =: System.currentPageReference().getParameters().get('meetingId')];
        for(RelatedOpportunity__c ro : relatedOppyList) {
            oppyIds.add(ro.Opportunity__c);
        }
    }    
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method return a List of recipients for a given opportunity
     * @param: null
     * @return: List<cReceipent>
     */
    public List<cRecipient> getRecipients() {
        if(recipientList == null) {
            recipientList = new List<cRecipient>();
			Map<Id,OpportunityTeamMember> uniqueTeamMembers = new Map<Id,OpportunityTeamMember>();
            
            for(OpportunityTeamMember otm: [SELECT Id,Name,OpportunityId,TeamMemberRole,UserId, User.Name, User.Email FROM OpportunityTeamMember WHERE OpportunityId IN: oppyIds]) {
                // avoid duplication over multiple opportunities
                if(uniqueTeamMembers.get(otm.UserId) == null) {
                    uniqueTeamMembers.put(otm.UserId,otm);
                }                
            }            
            for(OpportunityTeamMember otm: uniqueTeamMembers.values()) {
                // As each contact is processed we create a new cContact object and add it to the contactList
                recipientList.add(new cRecipient(otm));
                recipientList[recipientList.size()-1].emailOfUser = recipientList[recipientList.size()-1].oppyTeamMember.User.Email;
                recipientList[recipientList.size()-1].numberInList = recipientList.size();
            }            
        }
        return recipientList;
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method deletes a recipient from the list.
     * @param: null
     * @return: void
     */
    public void deleteRow() {
        System.debug('Now deleting number: '+deleteNum);
        System.debug('Which is Recipient: '+recipientList[deleteNum-1]);        
        recipientList.remove(deleteNum-1);
        
        for(cRecipient c : recipientList) {
            if(c.numberInList >= deleteNum) {
                c.numberInList--;
            }   
        }
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method adds a recipient to the list.
     * @param: null
     * @return: void
     */
    public void addRow() {
        if(meeting.UserLookup__c != null){
           User tempUser = [select Email from User where Id =: meeting.UserLookup__c];
           recipientList.add(new cRecipient(new OpportunityTeamMember(UserId = meeting.UserLookup__c)));
           recipientList[recipientList.size()-1].emailOfUser = tempUser.Email; 
           recipientList[recipientList.size()-1].numberInList = recipientList.size();
           meeting.UserLookup__c = null;       
        }   
    
        if(meeting.InternalContactLookup__c != null){
            Contact tempUser = [select Email, Name from Contact where Id =: meeting.InternalContactLookup__c];
            recipientList.add(new cRecipient(tempUser));
            recipientList[recipientList.size()-1].emailOfUser = tempUser.Email; 
            recipientList[recipientList.size()-1].numberInList = recipientList.size();
            meeting.ContactLookup__c = null;        
        } 

    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method is called when cancelled button is clicked on the page.
     * @param: null
     * @return: pageReference
     */
    public pageReference cancel() {
        PageReference pRef = new PageReference('/'+meeting.Id);
        return pRef.setRedirect(true);
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method is sends email to receipients/meeting attendes.
     * @param: null
     * @return: pageReference
     */
    public pageReference sendEmail() {
        
        // set up the attendees 
        List<MeetingAttendee__c> maList = [Select Id, MeetingNote__c, Contact__r.Name, Contact__r.Title, IHSMarkitEmployee__c  from MeetingAttendee__c where MeetingNote__c =:meeting.Id];
    	
        meeting.IHSMarkitAttendeeNames__c = '';
        meeting.AttendeeNames__c = '';
            
		for(MeetingAttendee__c ma : maList) {
            if(ma.IHSMarkitEmployee__c) {
                meeting.IHSMarkitAttendeeNames__c += ma.contact__r.Name+', ';
            } else {
                meeting.AttendeeNames__c += ma.contact__r.Name +', ';
            }
        }
        
        if( meeting.AttendeeNames__c != '') {
            meeting.AttendeeNames__c = meeting.AttendeeNames__c.substring(0, meeting.AttendeeNames__c.length() - 2);
        }
        if(meeting.IHSMarkitAttendeeNames__c != '') {
            meeting.IHSMarkitAttendeeNames__c = meeting.IHSMarkitAttendeeNames__c.substring(0, meeting.IHSMarkitAttendeeNames__c.length() - 2);
        }
        
        update meeting;
        
        // Get the email template
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        EmailTemplate template = [select id, HtmlValue, Body from EmailTemplate where DeveloperName = 'MeetingNotesTemplate' LIMIT 1];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
        list<String> toAddresses = new List<String>(); 
        // need dummy contact
        Contact dummy = [select id, email from Contact where email = 'sfadmin@markit.com' limit 1];
        
        for(cRecipient rec : recipientList) {
            if(rec.emailOfUser != null) {
                toAddresses.add(rec.emailOfUser);
            }
        }
        
        toAddresses.add(UserInfo.getUserEmail());
        
        if(toAddresses.size() > 0) {
            mail.setTargetObjectId(dummy.id);
            mail.setTemplateId(template.Id);            
            mail.setToAddresses(toAddresses);
            mail.setWhatId(meeting.Id);
            mails.add(mail);
        }
        
        // Send the emails in a transaction, then roll it back, doesn't actually send email that way
        Savepoint sp = Database.setSavepoint();
        // This actually populates the template into the email message (#winning http://opfocus.com/blog/sending-emails-in-salesforce-to-non-contacts-using-apex/)
        Messaging.sendEmail(mails);
        Database.rollback(sp);
        
         List<Messaging.SingleEmailMessage> lstMsgsToSend = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage emailToSend = new Messaging.SingleEmailMessage();
        emailToSend.setToAddresses(mail.getToAddresses());
        emailToSend.setPlainTextBody(mail.getPlainTextBody());
        emailToSend.setHTMLBody(mail.getHTMLBody());
        emailToSend.setSubject(mail.getSubject());
        emailToSend.setSaveAsActivity(false);

        lstMsgsToSend.add(emailToSend);
        Messaging.sendEmail(lstMsgsToSend);
        
        PageReference pRef = new PageReference('/'+meeting.Id);
        return pRef.setRedirect(true);
    }
    
    /**
     * @author Modified By: Vinod Merwade
     * @description Wrapper class
     * @date 7th Jul 2017
     */
    public class cRecipient {
        public OpportunityTeamMember oppyTeamMember {get;set;}
        public Contact contact{get;set;}
        public Integer numberInList {get;set;}
        public String emailOfUser {get;set;}
        
        public cRecipient(OpportunityTeamMember otm) {
            oppyTeamMember = otm;
        }
        
        public cRecipient(Contact c) {
            contact = c;
        }
    }
}