src/objects/AdClaim__c.object
<CustomObject>
    <description>SFDC1-332: AdClaim Object will be used to Track the Opportunity Ad Claims.</description>
    <fields>
        <fullName>ContactName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Contact Name</description>
        <inlineHelpText>Name of contact at the requesting organization</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ad Claims</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Opportunity</description>
        <inlineHelpText>Opportunity number of the publication fee to which this claim is related</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Ad Claims</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Claim</label>
    <nameField>
        <displayFormat>AC{0000}</displayFormat>
        <label>Ad Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Claims</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>JobTitle__c</fullName>
        <description>Creating Job Title as of SFDC1-863; Titles have been taken from Markit QA org</description>
        <inlineHelpText>If you are unable to find a suitable job title please contact your Salesforce Administrator</inlineHelpText>
        <label>Job Title</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Assistant Vice President</fullName>
                </value>
                <value>
                    <fullName>Associate</fullName>
                </value>
                <value>
                    <fullName>CCO - Chief Compliance Officer</fullName>
                </value>
                <value>
                    <fullName>CDO - Chief Data Officer</fullName>
                </value>
                <value>
                    <fullName>CEO - Chief Executive Officer</fullName>
                </value>
                <value>
                    <fullName>CFO - Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Analyst</fullName>
                </value>
                <value>
                    <fullName>CIO - Chief Investment Officer</fullName>
                </value>
                <value>
                    <fullName>COO - Chief Operating Officer</fullName>
                </value>
                <value>
                    <fullName>CTO - Chief Technology Officer</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Executive Director</fullName>
                </value>
                <value>
                    <fullName>Executive Vice President</fullName>
                </value>
                <value>
                    <fullName>Intern</fullName>
                </value>
                <value>
                    <fullName>Managing Director</fullName>
                </value>
                <value>
                    <fullName>Portfolio Manager</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Senior Analyst</fullName>
                </value>
                <value>
                    <fullName>Senior Director</fullName>
                </value>
                <value>
                    <fullName>Senior Managing Director</fullName>
                </value>
                <value>
                    <fullName>Senior Vice President</fullName>
                </value>
                <value>
                    <fullName>Vice President</fullName>
                </value>
                <value>
                    <fullName>CRO - Chief Risk Officer</fullName>
                </value>
                <value>
                    <fullName>DirectorExecutive Director</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>InternManaging Director</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MeetingAttendee__c.object
<CustomObject>
    <description>SFDC1-863; Meeting Attendee Object to Capture details of the Attendees</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IHSMarkitEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IHS Markit Employee?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>MAT-{000000000}</displayFormat>
        <label>Meeting Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MeetingNote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-863; Lookup to the Account</description>
        <inlineHelpText>Please Select the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttendeeNames__c</fullName>
        <inlineHelpText>Please Enter Client Attendee&apos;s Name</inlineHelpText>
        <label>Client Attendee Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IHSMarkitAttendeeNames__c</fullName>
        <inlineHelpText>Please Enter IHS Markit Attendee&apos;s Name</inlineHelpText>
        <label>IHS Markit Attendee Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NumberOfOpportunities__c</fullName>
        <label>Number of Opportunities</label>
        <summaryForeignKey>RelatedOpportunity__c.MeetingNote__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Note</label>
    <nameField>
        <label>Meeting Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Notes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RelatedOpportunity__c.object
<CustomObject>
    <description>SFDC1-863; Related Opportunity Object is a Junction Object between Opportunities and Meeting Note</description>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Opportunity</label>
    <nameField>
        <displayFormat>RO-{000000000}</displayFormat>
        <label>Related Opportunity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendMeetingNoteEmailToTeamMembers.cls
/**
 * @Author:  Hemant Shukla
 * @Date:    30-Nov-2017
 * @description: Apex class which is being used as controller for Quick Actions on Meeting Note to Send email.
 * @lastModifiedSprint: Sprint 16 SFDC1-710 -  Modified method sendEmail, to update the MN record link with Org base URL And to avoid the Null entry into To address set.
 * @lastModifiedBy : Hemant Shukla in Sprint 16
 * @lastModifiedSprint: Sprint 16 SFDC1-710 -  Removed the cRecipient inner class and made it separate class after issue on winter 18 for inner wrapper class taken as LC attribute. 
 * @lastModifiedBy : Hemant Shukla in Sprint 16
**/
public with sharing class SendMeetingNoteEmailToTeamMembers {
	
	/**
     * @Author: Hemant Shukla
     * @date: 30-Nov-2017
     * @description: To validate if Email could be send to Team members based on current MN record
     * @param: mnId, Meeting Note Id
     * @param: launchedFrom,  action it launched from
     * @return: String, appropriate message
    */
    @AuraEnabled
    public static String validateEmailSending (String mnId, String launchedFrom) {
        
    	MeetingNote__c meetingNote = [Select Id, Account__c, NumberOfOpportunities__c, (Select Id From RelatedOpportunities__r) 
    								  From MeetingNote__c 
    								  Where Id = :mnId 
    								  Limit 1
    								  ];
    	String message = 'SendEmail';							  
    	if(launchedFrom == 'AccountTeam' && meetingNote.Account__c == null) {							  
    		message = 'Please link an Account to this Meeting note to send an email to Account Team.';
    	}	
    	else if(launchedFrom == 'OpportunityTeam' && meetingNote.NumberOfOpportunities__c < 1) {
    		message = 'Please link any Opportunity to this Meeting note to send an email to Opportunity Team.';
    	}
    	
    	return message;							
    }

    /**
     * @Author: Hemant Shukla
     * @date: 30-Nov-2017
     * @description: This method return a List of recipients for a given Account
     * @param: mnId, Meeting Note Id
     * @param: launchedFrom,  action it launched from
     * @return: List<cReceipent>, AccountTeamMembers or OpportunityTeamMembers based on selected action. 
    */
    @AuraEnabled
    public static List<cRecipient> getRecipientsOnLoad(String mnId, String launchedFrom) {

    	MeetingNote__c meetingNote = [Select Id, Account__c, NumberOfOpportunities__c, (Select Id, Opportunity__c From RelatedOpportunities__r) 
    								  From MeetingNote__c 
    								  Where Id = :mnId 
    								  Limit 1
    								  ];
    	
    	List<cRecipient> recipients = new List<cRecipient>();

    	if(launchedFrom == 'AccountTeam') {
						          
	        for(AccountTeamMember atm: [Select Id,AccountId,TeamMemberRole,UserId, User.Name, User.Email 
	        							From AccountTeamMember 
	        							Where AccountId =: meetingNote.Account__c]) {

	            recipients.add(new cRecipient(atm.User.Name, atm.User.Email));
	        }
	    }
        else if(launchedFrom == 'OpportunityTeam') {

            Set<Id> setAlreadyAddedUsers = new Set<Id>();
            Set<Id> oppIds = new Set<Id>();
            for(RelatedOpportunity__c ro : meetingNote.RelatedOpportunities__r) {
                oppIds.add(ro.Opportunity__c);
            }   
            for(OpportunityTeamMember otm:  [Select Id,Name,OpportunityId,TeamMemberRole,UserId, User.Name, User.Email 
                                              From OpportunityTeamMember 
                                              Where OpportunityId IN: oppIds]) {
                
                //To avoid same users to get added twice in list. As one user can be a part of Two Opportunity team.
                if(!setAlreadyAddedUsers.contains(otm.UserId)) {
                    recipients.add(new cRecipient(otm.User.Name, otm.User.Email));
                    setAlreadyAddedUsers.add(otm.UserId);
                }
            }
        }     	
	    
	    return recipients;
    }

    /**
     * @Author: Hemant Shukla
     * @date: 30-Nov-2017
     * @description: This method creates a intance of recipient to add into final list
     * @param: mnId, Meeting Note Id
     * @return: cReceipent, instance of recently added Recipien
    */
    @AuraEnabled
    public static cRecipient addEmailRecipient(String contactId) {
    	
        List<Contact> cList = [select Id, Name, JobTitle__c, Title, Email, Account.Name 
        					   From Contact 
        					   where Id =: contactId AND 
        					   		 Email != null	
        					   limit 1		 
        					   ];
        
        cRecipient recipient;

        if(!cList.isEmpty()) {
            Contact c = cList[0];
            recipient = new cRecipient(c.Name, c.Email);
        }

        return recipient;
    }

    /**
     * @Author: Hemant Shukla
     * @date: 1-Dec-2017
     * @description: This method adds a recipient into list to send an email
     * @param: mnId, Meeting Note Id
     * @param: jsonLstRecipients, Json list of all recipients to whom email need to be sent
     * @return: List<cReceipent>
    */
    @AuraEnabled
    public static String sendEmail(String mnId, String jsonLstRecipients) {

        MeetingNote__c mn = [Select Id, Account__c, Account__r.Owner.Email
                             From  MeetingNote__c
                             Where Id = :mnId];

        List<cRecipient> lstRecipients = new List<cRecipient>();
        if(!String.isEmpty(jsonLstRecipients)) {
            lstRecipients = (List<cRecipient>) JSON.deserializeStrict(jsonLstRecipients, List<cRecipient>.class);
        }    
        else {
            return 'No Recipients';
        }    
        
        try {   

            List<MeetingAttendee__c> attendees = [Select Id, MeetingNote__c, Contact__r.Name, Contact__r.Title, IHSMarkitEmployee__c 
                                                  From MeetingAttendee__c 
                                                  where MeetingNote__c =:mn.Id
                                                 ];

            Set<String> markitAttendees = new Set<String>();
            Set<String> nonMarkitAttendees = new Set<String>();

            for(MeetingAttendee__c ma : attendees) {
                if(ma.IHSMarkitEmployee__c) {
                    markitAttendees.add(ma.contact__r.Name);
                } else {
                    nonMarkitAttendees.add(ma.contact__r.Name);
                }
            }
            
            mn.IHSMarkitAttendeeNames__c = !(new List<String>(markitAttendees)).isEmpty() ? 
                                                 String.join((new List<String>(markitAttendees)), ',') : '';
            mn.AttendeeNames__c = !(new List<String>(nonMarkitAttendees)).isEmpty() ? 
                                                 String.join((new List<String>(nonMarkitAttendees)), ',') : '';                                     
            
            update mn;

            // Get the email template
            EmailTemplate template = [select id, HtmlValue, Body 
                                      From EmailTemplate 
                                      Where DeveloperName = 'MeetingNotesTemplate' 
                                      LIMIT 1];

            set<String> toAddressesSet = new set<String>(); 
            // need dummy contact
            Contact dummy = [select id, email from Contact limit 1]; /* where email = 'sfadmin@markit.com' */

            for(cRecipient rec : lstRecipients) {
                toAddressesSet.add(rec.email);
            }
            
            //Adding the additional users into set to send the email. Current user and Owner of Associated account to MN. 
            toAddressesSet.add(UserInfo.getUserEmail());
            if(mn.Account__c != null) {
                toAddressesSet.add(mn.Account__r.Owner.Email);
            }
            
            List<String> toAddresses = new List<String>(toAddressesSet);

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
            if(toAddresses.size() > 0) {
                mail.setTargetObjectId(dummy.id);
                mail.setTemplateId(template.Id);            
                mail.setToAddresses(toAddresses);
                mail.setWhatId(mn.Id);
            }
            
            // Send the emails in a transaction, then roll it back, doesn't actually send email that way
            Savepoint sp = Database.setSavepoint();
            // This actually populates the template into the email message (#winning http://opfocus.com/blog/sending-emails-in-salesforce-to-non-contacts-using-apex/)
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
            Database.rollback(sp);

            Messaging.SingleEmailMessage emailToSend = new Messaging.SingleEmailMessage();
            emailToSend.setToAddresses(mail.getToAddresses());
            emailToSend.setPlainTextBody(mail.getPlainTextBody());
            String emailBody = mail.getHTMLBody();
            emailBody = emailBody.replace('BASE__URL', URL.getSalesforceBaseUrl().toExternalForm());
            emailToSend.setHTMLBody(emailBody);
            emailToSend.setSubject(mail.getSubject());
            emailToSend.setSaveAsActivity(true);

            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{emailToSend});

            return 'Success';
        }
        Catch(exception e) {
            System.debug('=================Error:' + e.getMessage());
            return e.getMessage();
        }    
    }	
		
}