src/objects/AdClaim__c.object
<CustomObject>
    <description>SFDC1-332: AdClaim Object will be used to Track the Opportunity Ad Claims.</description>
    <fields>
        <fullName>ContactName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-332 : Contact Name</description>
        <inlineHelpText>Name of contact at the requesting organization</inlineHelpText>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ad Claims</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Claim</label>
    <nameField>
        <displayFormat>AC{0000}</displayFormat>
        <label>Ad Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Claims</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>OIDTicket__c</fullName>
        <description>SFDC1-1351: Field to store service now ticket number
SFDC1-4998: Rename of field label OID Ticket # to INC Ticket</description>
        <inlineHelpText>Enter ServiceNow ticket number for the related Outage Incident (INC0123456)</inlineHelpText>
        <label>INC Ticket</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceLink__c</fullName>
        <description>SFDC1-1351: Stores URL to ServiceNow ticket
SFDC1-4998: Rename of field label Service Link to ServiceNow Link</description>
        <inlineHelpText>Copy Then Paste URL from ServiceNow for this Outage Incident</inlineHelpText>
        <label>ServiceNow Link</label>
        <type>Url</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SurveyResponse__c.object
<CustomObject>
    <description>SFDC1-254: Customer Care - Survey Response Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-6010: account id of responded</description>
        <inlineHelpText>Account related to the Survey Response.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CESScore__c</fullName>
        <description>SFDC1-6010: Carlos&apos; team to calculate and present as a whole number</description>
        <inlineHelpText>Calculated Customer Engagement Score.  This score is provided by the survey team on a scale from 0-7.</inlineHelpText>
        <label>CES Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-254: contactid of responded</description>
        <inlineHelpText>Contact related to the Survey Response.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyType__c</fullName>
        <description>SFDC1-254: describes if the survey response is Customer Care,Training or Customer First</description>
        <inlineHelpText>Identifies the type of Survey that was sent to the Contact.</inlineHelpText>
        <label>Survey Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Care</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Customer First</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SurveyRatingController.cls
//-----------------------------
// @author: Ankita Singh
// @date: 20 Feb 2018
// @param: NA
// @description: SFDC1-6011 --Survey Response - Display CES on case console for Contact and Account
// @return: NA
// @company: VERTIBA
//-----------------------------
public class SurveyRatingController {
     //-----------------------------
    // @author: Ankita Singh
    // @date: 20 Feb 2018 
    // @param:case Id 
    // @description:This method retrieves CE Score for Contact associated with the case
    // @return:CE Score for associated with the case id  
    //------------------------------
	@AuraEnabled
        public static SurveyResponse__c getContactScore(Id caseId) {
        String SurveyType = 'Customer Care';
        String conId = [Select id,contactid from Case where  id=:caseId Limit 1].ContactId;
        list<SurveyResponse__c> cesContact = [select Contact__c,Contact__r.FirstName,Contact__r.LastName,CreatedDate,CESScore__c from SurveyResponse__c where Contact__c =:conId AND CESScore__c!=NULL AND SurveyType__c=:SurveyType ORDER BY CreatedDate DESC LIMIT 1];  
        if(cesContact.size() >0 && !cesContact.isEmpty()) {
        	return cesContact[0];
         }
         else {
           return null; 
         }
    }
    //-----------------------------
    // @author: Ankita Singh
    // @date: 20 Feb 2018 
    // @param:case Id 
    // @description:This method retrieves CE Score for all surveys for the account associated with the case
    // @return:Average CE Score ,Account id and Account Name(of type wrapper class AccountScoreWrapper)for all surveys for the account associated with the case id  
    //------------------------------
	@AuraEnabled
        public static SurveyRatingController.AccountScoreWrapper getAccountScore(Id caseId) {
        String SurveyType = 'Customer Care';
		double avgCESScore =0;
		AccountScoreWrapper asw = new AccountScoreWrapper();
        List<Case> acc = [Select id,accountid,Account.Name from Case where  id=:caseId  AND accountid!=NULL Limit 1]; 
		if(acc.size() > 0 && acc != null) {
			AggregateResult[] groupedResults = [SELECT AVG(CESScore__c) averageScore FROM SurveyResponse__c where Account__c = :acc[0].accountid and CESScore__c!=null and SurveyType__c ='Customer Care' and CreatedDate = LAST_90_DAYS];
            if(double.valueOf(groupedResults[0].get('averageScore')) != null && double.valueOf(groupedResults[0].get('averageScore'))>0) {
                avgCESScore = double.valueOf(groupedResults[0].get('averageScore'));
            }
			asw.avgscore = avgCESScore;
			asw.accountId= acc[0].accountid;
            asw.accName= acc[0].Account.Name;
			return asw;
		}
		else {
            asw.avgscore = avgCESScore;
            asw.accountId= '';
            asw.accName= '';
			return asw;
		}
    }
   
    //-----------------------------
    // @author: Ankita Singh
    // @date: 23 Feb 2018 
    // @param:case Id 
    // @description:This method retrieves Last Incident Ticket associated with the account
    // @return:Case related to Last Incident Ticket associated with the account
    //------------------------------
	@AuraEnabled
        public static Case getLastIncidentTicket(Id caseId) {
        String SurveyType = 'Customer Care';
        String accId = [Select id,accountid from Case where  id=:caseId Limit 1].AccountId;
		if(accId!=null && accId!='') {
			List<Case> lastIncidentTicket = [select Id, OIDTicket__c,ServiceLink__c from Case where AccountId = :accId AND OIDTicket__c != null order by LastModifiedDate desc limit 1];
			if(lastIncidentTicket.size()>0 && lastIncidentTicket!=null) {
				return lastIncidentTicket[0];
			}
			else {
				return null;
			}
		}
		else {
			return null;
		}
    }
    //-----------------------------
    // @author: Ankita Singh
    // @date: 28 Feb 2018 
    // @param:NA 
    // @description:This is a wrapper class
    // @return:NA
    //------------------------------	
	public class AccountScoreWrapper {
        @AuraEnabled public double avgscore;
        @AuraEnabled public String accountId;
        @AuraEnabled public String accName;

    }
}