src/objects/AdditionalCaseTypeLinking__c.object
<CustomObject>
    <description>SFDC1-6246 Used in Additional Case Fields object process to identify the record type of additional case fields</description>
    <fields>
        <fullName>AdditionalCaseRecordType__c</fullName>
        <description>SFDC1-6376: Adding Polk in the pick list</description>
        <label>Additional Case Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Receivable</fullName>
                </value>
                <value>
                    <fullName>CDN Data</fullName>
                </value>
                <value>
                    <fullName>Corporate Actions</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivery Helpdesk</fullName>
                </value>
                <value>
                    <fullName>Enerdeq</fullName>
                </value>
                <value>
                    <fullName>Energy-ETA</fullName>
                </value>
                <value>
                    <fullName>Equities-Data and Analytics</fullName>
                </value>
                <value>
                    <fullName>Equities-Reg</fullName>
                </value>
                <value>
                    <fullName>FieldDirect</fullName>
                </value>
                <value>
                    <fullName>Goldfire</fullName>
                </value>
                <value>
                    <fullName>Kingdom</fullName>
                </value>
                <value>
                    <fullName>Legacy Distribution</fullName>
                </value>
                <value>
                    <fullName>Loan Settlement</fullName>
                </value>
                <value>
                    <fullName>NRG</fullName>
                </value>
                <value>
                    <fullName>Order Management</fullName>
                </value>
                <value>
                    <fullName>Order Management Helpdesk</fullName>
                </value>
                <value>
                    <fullName>OTC DD</fullName>
                </value>
                <value>
                    <fullName>OTC Services</fullName>
                </value>
                <value>
                    <fullName>PETRA</fullName>
                </value>
                <value>
                    <fullName>Polk</fullName>
                </value>
                <value>
                    <fullName>Power Tools</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Pricing Operations</fullName>
                </value>
                <value>
                    <fullName>Processing - Customer Care</fullName>
                </value>
                <value>
                    <fullName>Processing - Onboarding</fullName>
                </value>
                <value>
                    <fullName>Reference Data</fullName>
                </value>
                <value>
                    <fullName>Reg and Compliance</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Sales Ops</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseRecordType__c</fullName>
        <description>SFDC1-6246 Case Record Type for additional Case Fields object process. SFDC1-7120: Removing Internal Partner pick list. SFDC1-9290 Adding Implementation Value</description>
        <label>Case Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Care</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Order Management/Delivery Help Desk</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Internal Partner</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6246: Additional case fields record should get spawned based on Product Group record</description>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Additional Case Type Linkings</relationshipLabel>
        <relationshipName>AdditionalCaseTypeLinkings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Additional Case Type Linking</label>
    <nameField>
        <displayFormat>ACTL-{0000}</displayFormat>
        <label>Additional Case Type Linking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Case Type Linkings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AdditionalFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for the Additional Case Fields Setup</description>
        <inlineHelpText>Updated by Salesforce for certain Product Groups</inlineHelpText>
        <label>Additional Fields</label>
        <referenceTo>AdditionalCaseFields__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for Case Additional Fields Setup.
SFDC1-7120 Field used in filter condition is deleted. So Removing from here.</description>
        <inlineHelpText>Examples - Jane&apos;s Online - Petra - World Market Monitor</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Cases (Product Group)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestAdditionalCaseFieldsMethods.cls
//-----------------------------
// @author: Uttam Arya
// @date: 22 June 2017
// @param: NA
// @description: Test class for Additional Case Fields trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestAdditionalCaseFieldsMethods {

    //-----------------------------
    // @author: Uttam Arya
    // @date: 22 June 2017
    // @param: NA
    // @description: Test method for Additional Case Fields trigger methods populateAdditionalFiledsLookupInCase on insert
    // @return: NA
    //-----------------------------
	private static testMethod void testpopulateAdditionalFiledsLookupInCase() {
	    
	    Account a = TestUtility.createTestAccount('Account testpopulateAdditionalFiledsLookupInCase', true);
        
        Contact c = new Contact();
        c.firstname = 'Test';
        c.lastname = 'testpopulateAdditionalFiledsLookupInCase';
        c.AccountId = a.Id;
        
        //Assuming NRG recordtype exist in system
        
        ProductGroup__c pg = new ProductGroup__c();
        pg.Name = 'NRG';
        insert pg;
        
        Case testCase = new Case();
        testCase.subject = 'Test subject testpopulateAdditionalFiledsLookupInCase';
        testCase.AccountId = a.Id;
        testCase.contactId = c.Id;
        insert testCase;
        
        AdditionalCaseFields__c acf = new AdditionalCaseFields__c();
        acf.Case__c = testCase.Id;
        insert acf;
        
        list <Case> testCaseResult = [Select AdditionalFields__c, Id from case where Id = :testCase.Id];
         System.assertEquals(1, testCaseResult.size());
        System.assertEquals(acf.Id, testCaseResult[0].AdditionalFields__c);

	}
    //-----------------------------
    // @author: Vishnu vardhan Chowdary Andra
    // @date: 19 June 2018
    // @description: This method tests that case is assigned to queue mentioned in Delivery Queue field 
    // 				of Delivery Case record type.
    // @companyname: VERTIBA 
    //----------------------------- 
    @isTest
    private static void testDeliveryCaseOwnerAssignment() {
        Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        Id deliveryRecordTypeId = Schema.Sobjecttype.AdditionalCaseFields__c.getRecordTypeInfosByName().
        								get('Delivery').getRecordTypeId();
        Account testAccount = TestUtility.createTestAccount('testAccount', true);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        ProductGroup__c testProductgroup = TestUtility.createProductGroup('Delivery', true, false);
        
        AdditionalCaseTypeLinking__c aCaseTypeLinkingDelivery = new AdditionalCaseTypeLinking__c();
        aCaseTypeLinkingDelivery.CaseRecordType__c = 'Customer Care';
        aCaseTypeLinkingDelivery.AdditionalCaseRecordType__c = 'Delivery';
        aCaseTypeLinkingDelivery.ProductGroup__c = testProductgroup.Id;
        insert aCaseTypeLinkingDelivery;
        
        System.debug('aCaseTypeLinkingDelivery:' + aCaseTypeLinkingDelivery);
        
        Case testCase = new Case();
        testCase.RecordTypeId = caseRecordTypeId;
        testCase.ProductGroup__c = testProductgroup.id;
        testCase.subject = 'Test subject';
        testCase.AccountId = testAccount.Id;
        testCase.contactId = testContact.Id;
        insert testCase;
        
        Map<String,Id> queueIdMap = new map<String,Id>();
        for(Group queue : [Select Name, Id From Group where Type = 'Queue'
                                      and name in ('Erights', 'Online Delivery')]) {
            queueIdMap.put(queue.Name, queue.id);
        }

        Test.startTest();
        testCase = [Select id, OwnerId, AdditionalFields__c from case where id =: testCase.Id];
        //updating delivery queue field to Erights. Case owner should be changed to Erights. 
        AdditionalCaseFields__c acf = new AdditionalCaseFields__c(id=testCase.AdditionalFields__c);
        acf.DeliveryQueue__c='Erights';
        update acf;
        
        testCase = [Select id, OwnerId, AdditionalFields__c from case where id =: testCase.Id];
        System.assertEquals(queueIdMap.get(acf.DeliveryQueue__c), testCase.OwnerId);
        Test.stopTest();
    }
}