src/objects/AdditionalContactFields__c.object
<CustomObject>
    <description>SFDC1-2301 Additional Contact Fields Object with custom fields from Markit legacy system</description>
    <fields>
        <fullName>ContactReference__c</fullName>
        <description>SFDC1-2299 Master-Detail reference to Contact record</description>
        <inlineHelpText>Lookup Reference of the contact connected to the Additional Contact Fields</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Additional Contact Fields</relationshipLabel>
        <relationshipName>AdditionalContactFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Contact Fields</label>
    <nameField>
        <label>Additional Contact Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Contact Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AdditionalContactFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2301 reference to Additional Contact Fields object for this Contact record</description>
        <inlineHelpText>Reference to Additional Contact Fields object for this Contact record</inlineHelpText>
        <label>Additional Contact Fields</label>
        <referenceTo>AdditionalContactFields__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AdditionalContactFieldsMethods.cls
//-----------------------------
// @author: Tran-Vu Tran
// @date: 25 Sep 2017
// @param: NA
// @description: SFDC1-2299 Class to hold Additional Contact Fields trigger methods 
// @return: NA
//-----------------------------
public class AdditionalContactFieldsMethods {

//-----------------------------
// @author: Tran-Vu Tran
// @date: 25 Sep 2017
// @param: TriggerParameters tp
// @description: SFDC1-2299 Whenever a contact is created, whether manually by a user or through an integration/data migration, 
// 				an "Additional Contact Fields" record is automatically created and a link to this record is populated in the contact record.
// 				This function populate the AdditionalContactFields lookup in Contact.
// @return: None
//------------------------------
    public static void populateAdditionalContactFieldsLookupInContact(TriggerParameters tp) {

        //List of Contacts that needs to be updated    
        List <Contact> ContactsToUpdate = new List <Contact>(); 
        List <AdditionalContactFields__c> acfList = tp.newList;
        for(AdditionalContactFields__c acf: acfList) {
            if(acf.ContactReference__c != null) {
                ContactsToUpdate.add(new Contact(Id = acf.ContactReference__c, AdditionalContactFields__c = acf.Id));
            }
        }
        
        //update if list has any records
        if(ContactsToUpdate != null && ContactsToUpdate.size() > 0) {
            update ContactsToUpdate;
        }
    }
}