src/objects/AdditionalProductLoginFields__c.object
<CustomObject>
    <description>SFDC1-7972 This is a separate object created for capturing additional product login fields which are more specific to the product requirement. Many of these fields are originated from L-Markit.</description>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-6347: Parent of Additional Product Login Information.</description>
        <inlineHelpText>Parent of Additional Product Login Information.</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Additional Product Login Fields</relationshipLabel>
        <relationshipName>AdditionalProductLoginFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>SFDC1-6785 Username or Login name for this user. This is copied over from Product Login via workflow</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique username or login name for this user automatically copied over from Product Login via workflow</inlineHelpText>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Additional Product Login Fields</label>
    <nameField>
        <label>Additional Product Login Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Product Login Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductLogin__c.object
<CustomObject>
    <description>SFDC1-7972 This object will be used to store the information related to the user of the IHS Markit product.  Until the user has a usage they will never be converted to a contact.  The user record mostly will be created/updated by the integration system.</description>
    <fields>
        <fullName>AdditionalProductLoginFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6785 Required for the Additional Product Login Fields Setup</description>
        <inlineHelpText>Additional Product Login Fields record gets auto-generated whenever the user record is created. This object holds more product specific fields.</inlineHelpText>
        <label>Additional Product Login Fields</label>
        <referenceTo>AdditionalProductLoginFields__c</referenceTo>
        <relationshipLabel>Product Logins</relationshipLabel>
        <relationshipName>ProductLogins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>SFDC1-6785 Email of the user used for Product Login.</description>
        <inlineHelpText>Email of the user used for Product Login.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>SFDC1-6785 First Name of the user used for Product Login.</description>
        <inlineHelpText>First Name of the user used for Product Login.</inlineHelpText>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>SFDC1-6785 Source of the user data. Data can be uploaded automatically from external entitlement and authentications systems or entered manually. If the User is manually entered this should be defaulted to Manual and cannot be overwritten.</description>
        <inlineHelpText>Source of the user data.</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>UserXS</fullName>
                </value>
                <value>
                    <fullName>MSF</fullName>
                </value>
                <value>
                    <fullName>USERXS-MARKIT</fullName>
                </value>
                <value>
                    <fullName>USERXS-TRADE-MANAGER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>SFDC1-6785 Username or Login name for this user</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the unique username or login name for this user.</inlineHelpText>
        <label>Username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Login</label>
    <nameField>
        <displayFormat>PLN-{000000}</displayFormat>
        <label>Product Login Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductLoginContactAssociation__c.object
<CustomObject>
    <description>SFDC1-7972 This object links the Product Login to the related contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>SFDC1-4386 Contact related to this Product Login</description>
        <inlineHelpText>Link the related Contact to this Product Login</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product Login Contact Associations</relationshipLabel>
        <relationshipName>ProductLoginContactAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-4386 Product Login related to this Contact</description>
        <inlineHelpText>Link the related to Product Login to this Contact</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Product Login Contact Associations</relationshipLabel>
        <relationshipName>ProductLoginContactAssociations1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Login Contact Association</label>
    <nameField>
        <displayFormat>PLContact-{000000}</displayFormat>
        <label>Product Login Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Login Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestProductLoginMethods.cls
// @author: Uttam Arya
// @date: 13 April 2018
// @param: NA
// @description: Test class for Additional ProductLogin__c Fields trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestProductLoginMethods {
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 13 April 2018
    // @param: NA
    // @description: SFDC1-6347 Test method for Additional ProductLogin__c Fields trigger method changeProductLoginAdditionalFieldsObjectNameWhenAccountNameChanges on update. 
    //              To test if ProductLogin__c Additional Fields Object Name chnages when ProductLogin__c username Changes
    // @return: NA
    //-----------------------------
    private static testMethod void testchangeProductLoginAdditionalFieldsObjectNameWhenUsernameChanges() {
        
        Test.startTest();
        
        ProductLogin__c testProductLogin = TestUtility.createProductLogin('testchangeProductLoginAdditionalFieldsObjectNameWhenUsernameChanges@test.com', true);
        
        list <ProductLogin__c> testProductLoginResult = [Select AdditionalProductLoginFields__c, Id, AdditionalProductLoginFields__r.Name, username__c from ProductLogin__c where Id = :testProductLogin.Id];
        //Assert if Product Login is inserted
        System.assertEquals(1, testProductLoginResult.size());
        System.assert(testProductLoginResult[0].AdditionalProductLoginFields__c != null);
        
        System.assertEquals(testProductLoginResult[0].AdditionalProductLoginFields__r.Name, testProductLoginResult[0].username__c);
        
        //Update ProductLogin__c Name
        testProductLogin.username__c = 'testchangeProductLoginAdditionalFieldsObjectNameWhenUsernameChanges@test.com2';
        update testProductLogin;
        
        list <ProductLogin__c> testProductLoginResult2 = [Select AdditionalProductLoginFields__c, Id, AdditionalProductLoginFields__r.Name, Name, Username__c  from ProductLogin__c where Id = :testProductLogin.Id];
        //Assert if Additional ProductLogin__c Field name gets updated
        System.assertEquals(testProductLoginResult2[0].AdditionalProductLoginFields__r.Name, testProductLoginResult2[0].username__c);
        
        Test.stopTest();
        
    }


    //-----------------------------
    // @author: Uttam Arya
    // @date: 13 April 2018
    // @param: NA
    // @description: SFDC1-6347 Test method for Additional ProductLogin__c Fields trigger method setProductLoginAdditionalFieldsObject on insert
    // @return: NA
    //-----------------------------
    private static testMethod void testSetAccountAdditionalFieldsObject() {
        
        Test.startTest();
        
        ProductLogin__c testProductLogin = TestUtility.createProductLogin('testSetAccountAdditionalFieldsObject@test.com', true);
        
        list <ProductLogin__c> testProductLoginResult = [Select AdditionalProductLoginFields__c, Id, AdditionalProductLoginFields__r.Name, username__c from ProductLogin__c where Id = :testProductLogin.Id];
        //Assert if Product Login is inserted
        System.assertEquals(1, testProductLoginResult.size());
        System.assert(testProductLoginResult[0].AdditionalProductLoginFields__c != null);
        
        //Assert if Adiitional Product Login Field is inserted
        list <AdditionalProductLoginFields__c> aucfList = [Select Id from AdditionalProductLoginFields__c where ProductLogin__c = :testProductLogin.Id];
        System.assertEquals(1, aucfList.size());
        System.assertEquals(aucfList[0].Id, testProductLoginResult[0].AdditionalProductLoginFields__c);
        
        Test.stopTest();
        
    }
    //-----------------------------
    // @author: Jagadesh Kumar
    // @date: 06 Aug 2018
    // @param: NA
    // @description: SFDC1-9572 Test method for ProductLogin__c trigger method insertPLContactAssociationWhenEmailChanges on update
    // @return: NA
    //-----------------------------
    private static testMethod void testInsertPLContactAssociationWhenEmailChanges() {
        Test.startTest();
        Account a = TestUtility.createTestAccount('Unknown Account', true);
       
        List<ProductLogin__c> plList = new List<ProductLogin__c>();
        ProductLogin__c testProductLogin = TestUtility.createProductLogin('testPLEmail@test.com', false);
        testProductLogin.Email__c = 'testPLEmail@ihsmarkit.com';
        testProductLogin.Source__c = 'Manual';
        testProductLogin.FirstName__c= 'testPLEmail';
        plList.add(testProductLogin);
        
        ProductLogin__c testProductLogin2 = TestUtility.createProductLogin('testPLEmail2@test.com', false);
        testProductLogin2.Email__c = 'testPLEmail2@ihsmarkit.com';
        testProductLogin2.Source__c = 'Manual';
        testProductLogin2.FirstName__c= 'testPLEmail2';
        plList.add(testProductLogin2);
        
        ProductLogin__c testProductLogin3 = TestUtility.createProductLogin('testPLEmail3@test.com', false);
        testProductLogin3.Email__c = 'testPLEmail3@ihsmarkit.com';
        testProductLogin3.Source__c = 'Manual';
        testProductLogin3.FirstName__c= 'testPLEmail3';
        plList.add(testProductLogin3);
        
        insert plList;
        
        List<Contact> conList = new List<Contact>();
        Contact c1 = new Contact();
        c1.firstname = 'Test1';
        c1.lastname = 'Test1';
        c1.Email = 'pl.contactExists@ihsmarkit.com';
        c1.AccountId = a.Id;
        conList.add(c1);
        insert conList;
        
        ProductLoginContactAssociation__c lcAsso = new ProductLoginContactAssociation__c();
        lcAsso.ProductLogin__c = testProductLogin.Id;
        lcAsso.Contact__c = c1.Id;
		insert lcAsso;
        
        testProductLogin.Email__c = 'pl.contactExists@ihsmarkit.com';
        testProductLogin2.Email__c = 'testPLEmailUpdate@test.com';
        testProductLogin3.Email__c = 'pl.contactExists@ihsmarkit.com';
        update plList;
        List<ProductLogin__c> productloginList = [SELECT Id,
                                             (SELECT Contact__c,ProductLogin__c FROM ProductLoginContactAssociations1__r) 
                                             FROM ProductLogin__c];
        System.assertEquals(1,productloginList.get(0).ProductLoginContactAssociations1__r.size());
        System.assertEquals(1,productloginList.get(1).ProductLoginContactAssociations1__r.size());
        System.assertEquals(1,productloginList.get(2).ProductLoginContactAssociations1__r.size());
        Test.stopTest();
    }
}