src/objects/AdditionalContactFields__c.object
<CustomObject>
    <description>SFDC1-2301 Additional Contact Fields Object with custom fields from Markit legacy system</description>
    <fields>
        <fullName>ContactReference__c</fullName>
        <description>SFDC1-2299 Master-Detail reference to Contact record</description>
        <inlineHelpText>Lookup Reference of the contact connected to the Additional Contact Fields</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Additional Contact Fields</relationshipLabel>
        <relationshipName>AdditionalContactFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Contact Fields</label>
    <nameField>
        <label>Additional Contact Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Contact Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AdditionalContactFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2301 reference to Additional Contact Fields object for this Contact record</description>
        <inlineHelpText>Reference to Additional Contact Fields object for this Contact record</inlineHelpText>
        <label>Additional Contact Fields</label>
        <referenceTo>AdditionalContactFields__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAdditionalContactFieldsMethods.cls
// @author: Uttam Arya
// @date: 22 June 2017
// @param: NA
// @description: Test class for AdditionalContactFields trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestAdditionalContactFieldsMethods {
    
    //-----------------------------
    // @author: Tran-Vu Tran
    // @date: 25 Sep 2017
    // @param: NA
    // @description: SFDC1-2299 Test method for AdditionalContactFields trigger methods populateAdditionalContactFieldsLookupInContact on insert
    // @return: NA
    //-----------------------------
    private static testMethod void testAdditionalContactFieldsLookupInContact() {

        Account testAccount = TestUtility.createTestAccount('Test Account', true);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'Test.ChangeAdditionalContactFields@ihsmarkit.com', true,
                                                        'Test', 'AdditionalContactFields');
        System.debug('testContact.Id=' + testContact.Id);
        System.debug('testContact.FirstName=' + testContact.FirstName);
        System.debug('testContact.LastName=' + testContact.LastName);
        
        List <Contact> testContactResult = [Select AdditionalContactFields__c, Id, Name from Contact where Id =: testContact.Id];
        System.debug('testContactResult[0].Name=' + testContactResult[0].Name);
        System.debug('testContactResult[0].AdditionalContactFields__c=' + testContactResult[0].AdditionalContactFields__c);

        //Assert if Contact is inserted
        System.assertEquals(1, testContactResult.size());
        System.assert(testContactResult[0].AdditionalContactFields__c != null);
        
        //Assert if Additional Contact Field is inserted
        List <AdditionalContactFields__c> acfList = [Select Id from AdditionalContactFields__c where ContactReference__c =: testContact.Id];
		System.debug('acfList.Size()=' + acfList.Size());
        
        System.assertEquals(1, acfList.size());
        System.assertEquals(acfList[0].Id, testContactResult[0].AdditionalContactFields__c);
        
    }
    
}