src/objects/AdditionalProductLoginFields__c.object
<CustomObject>
    <description>SFDC1-7972 This is a separate object created for capturing additional product login fields which are more specific to the product requirement. Many of these fields are originated from L-Markit.</description>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-6347: Parent of Additional Product Login Information.</description>
        <inlineHelpText>Parent of Additional Product Login Information.</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Additional Product Login Fields</relationshipLabel>
        <relationshipName>AdditionalProductLoginFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Product Login Fields</label>
    <nameField>
        <label>Additional Product Login Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Product Login Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductLogin__c.object
<CustomObject>
    <description>SFDC1-7972 This object will be used to store the information related to the user of the IHS Markit product.  Until the user has a usage they will never be converted to a contact.  The user record mostly will be created/updated by the integration system.</description>
    <fields>
        <fullName>AdditionalProductLoginFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6785 Required for the Additional Product Login Fields Setup</description>
        <inlineHelpText>Additional Product Login Fields record gets auto-generated whenever the user record is created. This object holds more product specific fields.</inlineHelpText>
        <label>Additional Product Login Fields</label>
        <referenceTo>AdditionalProductLoginFields__c</referenceTo>
        <relationshipLabel>Product Logins</relationshipLabel>
        <relationshipName>ProductLogins</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Login</label>
    <nameField>
        <displayFormat>PLN-{000000}</displayFormat>
        <label>Product Login Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAdditionalProductLoginFieldsMethods.cls
// @author: Uttam Arya
// @date: 13 April 2018
// @param: NA
// @description: Test class for Additional Account Fields trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestAdditionalProductLoginFieldsMethods {
    
    //-----------------------------
// @author: Uttam Arya
// @date: 13 April 2018
    // @param: NA
    // @description: SFDC1-6347 Test method for Additional Account Fields trigger methods populateAdditionalFiledsLookupInAccount on insert
    // @return: NA
    //-----------------------------
    private static testMethod void testpopulateAdditionalFieldsLookupInProductLogin() {
        
        Test.startTest();
        
        ProductLogin__c testProductLogin = TestUtility.createProductLogin('populateAdditionalFiledsLookupInAccount@test.com', true);
        
        list <ProductLogin__c> testProductLoginResult = [Select AdditionalProductLoginFields__c, Id from ProductLogin__c where Id = :testProductLogin.Id];
        //Assert if Product Login is inserted
        System.assertEquals(1, testProductLoginResult.size());
        System.assert(testProductLoginResult[0].AdditionalProductLoginFields__c != null);
        
        //Assert if Adiitional Product Login Field is inserted
        list <AdditionalProductLoginFields__c> aucfList = [Select Id from AdditionalProductLoginFields__c where ProductLogin__c = :testProductLogin.Id];
        System.assertEquals(1, aucfList.size());
        System.assertEquals(aucfList[0].Id, testProductLoginResult[0].AdditionalProductLoginFields__c);
        
        Test.stopTest();
        
    }
    
}