src/objects/AdditionalProductLoginFields__c.object
<CustomObject>
    <description>SFDC1-7972 This is a separate object created for capturing additional product login fields which are more specific to the product requirement. Many of these fields are originated from L-Markit.</description>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-6347: Parent of Additional Product Login Information.</description>
        <inlineHelpText>Parent of Additional Product Login Information.</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Additional Product Login Fields</relationshipLabel>
        <relationshipName>AdditionalProductLoginFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Product Login Fields</label>
    <nameField>
        <label>Additional Product Login Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Product Login Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductLogin__c.object
<CustomObject>
    <description>SFDC1-7972 This object will be used to store the information related to the user of the IHS Markit product.  Until the user has a usage they will never be converted to a contact.  The user record mostly will be created/updated by the integration system.</description>
    <fields>
        <fullName>AdditionalProductLoginFields__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6785 Required for the Additional Product Login Fields Setup</description>
        <inlineHelpText>Additional Product Login Fields record gets auto-generated whenever the user record is created. This object holds more product specific fields.</inlineHelpText>
        <label>Additional Product Login Fields</label>
        <referenceTo>AdditionalProductLoginFields__c</referenceTo>
        <relationshipLabel>Product Logins</relationshipLabel>
        <relationshipName>ProductLogins</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Login</label>
    <nameField>
        <displayFormat>PLN-{000000}</displayFormat>
        <label>Product Login Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AdditionalProductLoginFieldsMethods.cls
//-----------------------------
// @author: Uttam Arya
// @date: 13 April 2018
// @param: NA
// @description: Class to hold Additional Product Login Fields trigger methods 
// @return: NA
//-----------------------------
public class AdditionalProductLoginFieldsMethods { 
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 13 April 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-6347 Whenever an Product Login is created, whether through an integration/data migration or manually created by a user an "Additional Product Login Fields" 
    //                          record belonging to the Product Login is automatically created and a link to the record is populated in the "Additional Product Login Fields" field. 
    //                          This function populate the Additional Fields lookup in Product Login.
    // @return: None
    //------------------------------
    public static void populateAdditionalFiledsLookupInProductLogin(TriggerParameters tp) {
        try {
            //List of Product Logins that needs to be updated    
            List <ProductLogin__c> ProductLoginsToUpdate = new List <ProductLogin__c>(); 
            
            for(AdditionalProductLoginFields__c auaf: (List <AdditionalProductLoginFields__c>) tp.newList) {
                if(auaf.ProductLogin__c != null) {
                    ProductLoginsToUpdate.add(new ProductLogin__c(Id = auaf.ProductLogin__c, AdditionalProductLoginFields__c = auaf.Id));
                }
            }
            //update if list has any records
            if(ProductLoginsToUpdate != null && ProductLoginsToUpdate.size() > 0) {
                update ProductLoginsToUpdate;
            }
        } catch(Exception ex) {
            //this will happen if any exception apart from DML exception has occurred
            UtilityClass.createApexLogRecord(ex, 'AdditionalProductLoginFieldsMethods', 'populateAdditionalFiledsLookupInProductLogin');
        }
    }
}