src/objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-88 Opportunity related to the issue. If there are many, pick 1 and mention additional in the detailed description, at this time we are only making a 1:1 relationship</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for Case Additional Fields Setup.
SFDC1-7120 Field used in filter condition is deleted. So Removing from here.</description>
        <inlineHelpText>Examples - Jane&apos;s Online - Petra - World Market Monitor</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Cases (Product Group)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunitynum__c</fullName>
        <description>SFDC1 -171 (alphanumeric - Read Only);Automatic generated - OP+10 digits (OP-#####);
SFDC1-3816 Rename Opportunity ID field to Opportunity Num</description>
        <displayFormat>OP{0000000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>System generated opportunity number</inlineHelpText>
        <label>Opportunity Num</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <description>SFDC1-529 This field shows the Opportunity Owner&apos;s Region on Opportunity</description>
        <formula>TEXT(Owner.UserRegion__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sales Region of Opportunity Owner</inlineHelpText>
        <label>Sales Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SubmitToSalesProcessController.cls
//-----------------------------
// @author Vinod Merwade
// @date 10 Oct 2017
// @description:  SFDC1-550 Sales team to create a Case on click of quick action button and assign the case to the appropriate Sales Ops
// @return: Redirects to the converted record
// @Company: Vertiba
// @Last Modified By : Prachi Bhasin
// @Last Modified Date: 27 Dec 2017
// @Last Modified Description: Fixing queries for Group and Product Group in submitToSalesProcessingQueue method
// 
// @Last Modified By : Vishnu Vardhan Chowdary Andra
// @Last Modified Date: 08 Aug 2018
// @Last Modified Description: Code is called by a lightning component, which again is called from quick action.
// 		While changing RT type from Sales Support to Sales Operations realized this logic is not used anywhere. 
// 		So, it has been decided to comment out the code, instead of deleting logic. SFDC1-9677/78/80/81/82/83/84
//-----------------------------
public without sharing class SubmitToSalesProcessController {
    //-----------------------------
    // @author: Vinod Merwade
    // @date: 10 Oct 2017
    // @param: Opportunity Id from Lightning component
    // @description: SFDC1-550 Method which creates the case and assigns it to Sales Ops depending on the Sales Region of the Opportunity
    // @return: Id of the created case
    // @Company: Vertiba
    // @lastmodified description: Removing Internal partner record types and changing it to Sales Support. 
    // 			Also adding account to case as sales support requires account value
    // @lastmodifiedBy: Vishnu Vardhan on 4th April,2018, SFDC1-7120
    //------------------------------
    @AuraEnabled
    public static Id submitToSalesProcessingQueue(Id oppRecordId) {
       /* try {
            case salesOpsCase = new Case();
            Opportunity opp = [SELECT Id, AccountId,Opportunitynum__c, SalesRegion__c FROM Opportunity WHERE Id =:oppRecordId];
            Id rt = case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Sales Support').getRecordTypeId();
            OpportunityContactRole cont = [select Id,OpportunityId,contactId from OpportunityContactRole where isPrimary= true and OpportunityId=:opp.Id Limit 1];
            salesOpsCase.Opportunity__c = oppRecordId;
            salesOpsCase.Origin='Internal';
            salesOpsCase.RecordTypeId= rt;
            salesOpsCase.AccountId=opp.AccountId;
            if (cont != NULL) {
                salesOpsCase.ContactId=cont.ContactId;
            }
            salesOpsCase.Subject = 'Opportunity '+opp.Opportunitynum__c+': Ready for Sales Support Processing';
            string region = 'Sales - '+opp.SalesRegion__c;
            
            List<Group> ownerQueue = new List<Group>();
            ownerQueue = [select Id,Name from Group where  Type = 'Queue' and Name =:region Limit 1];
            if(ownerQueue != NULL && ownerQueue.size()>0) {
                salesOpsCase.OwnerId = ownerQueue[0].Id;
            }
            
            ProductGroup__c prodGroupRecord = [select Id,Name from ProductGroup__c where Name ='Sales Ops' Limit 1];
            if(prodGroupRecord != NULL) {
                salesOpsCase.ProductGroup__c = prodGroupRecord.id;
            }
            insert salesOpsCase;
            system.debug('created case'+salesOpsCase);
            return salesOpsCase.id;
        }
        catch(Exception e) {
            System.debug('Error, method submitToSalesProcessingQueue, class SubmitToSalesProcessController '+e.getMessage());
            ApexLogger__c apexLogRecord = new ApexLogger__c(ClassName__c='SubmitToSalesProcessController ',ErrorDescription__c='Error '+e.getStackTraceString(),FunctionName__c='submitToSalesProcessingQueue');
            insert apexLogRecord;  
            return null;
        }*/
        return null;
    }
    //-----------------------------
    // @author: Vinod Merwade
    // @date: 10 Oct 2017
    // @param: Opportunity Id from Lightning component
    // @description: SFDC1-550 Method which check for the sales region on the Opportunity
    // @return: Boolean
    // @Company: Vertiba
    // @Last Modified : 16 Aug 2017
    //------------------------------
    @AuraEnabled
    public static Boolean regionExist(Id oppRecordId) {
       /* Opportunity opp =  [Select SalesRegion__c from Opportunity where Id = :oppRecordId];
        List<OpportunityContactRole> cont = [select Id,OpportunityId,contactId from OpportunityContactRole where isPrimary= true and OpportunityId=:oppRecordId ];
        if(opp.SalesRegion__c != NULL && !cont.isEmpty()) {
            return true;
        }
        else {
            return false;
        }*/
        return null;
    }
    
}