src/objects/ApexLogger__c.object
<CustomObject>
    <description>The custom object that could store the error details when processing Apex and Visualforce code.</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <description>Name of the class that generated the error</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <description>Description of the error</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionName__c</fullName>
        <description>Name of the function that generated the error</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Logger</label>
    <nameField>
        <displayFormat>APEXLOG-{00000}</displayFormat>
        <label>Apex Logger Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BillingScheduleLineItem__c.object
<CustomObject>
    <description>SFDC1-4488 This object is used to create a billing schedule for variable billing products.This object will be a child object to Variable Billing Schedule Object.</description>
    <fields>
        <fullName>ContractLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-7471 This field will hold Contract Line Item #</description>
        <inlineHelpText>System populated reference to the Contract Line Item being billed</inlineHelpText>
        <label>Contract Line Item</label>
        <referenceTo>ContractLineItem__c</referenceTo>
        <relationshipLabel>Billing Schedule Line Items</relationshipLabel>
        <relationshipName>BillingScheduleLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsCreatedfromQuickAction__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-7472 : This is an technical field only. This field will be an identifier whether this record is created using the quick action on Contract Line Item or using the Apex Clone based on the Billing period on Contract line Item.</description>
        <inlineHelpText>Only for DEV purpose. This field will be an identifier whether this record is created using the quick action on Contract Line Item or using the Apex Clone based on the Billing period on Contract line Item.</inlineHelpText>
        <label>Is Created from Quick Action?</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Schedule Line Item</label>
    <nameField>
        <displayFormat>BSL{000000}</displayFormat>
        <label>Billing Schedule Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule</description>
    <fields>
        <fullName>BillingPeriods__c</fullName>
        <description>SFDC1-7471 This field holds the Billing Period</description>
        <inlineHelpText>Please enter the Billing Period</inlineHelpText>
        <label>Billing Periods</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BillingScheduleLineItemMethods.cls
//-----------------------------
// @author: Mohit Modi
// @date: 16 April 2018
// @description: This Class will hold all the methods related to Billing Schedule Line Items.
// @return: None
//------------------------------
public class BillingScheduleLineItemMethods {

    //-----------------------------
    // @author: Mohit Modi
    // @date: 16 April 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-7472 : This Method is used to create the Billing Schedule Line Item records based on the Contract line Item's Biiling Period Value. Called from After Insert and before Insert trigger.
    // @return: None
    //------------------------------
    public static void CreateCloneBillingScheduleLIFromCLIandPreventBSLICreation(TriggerParameters tp) {

        // List of new values
        list<BillingScheduleLineItem__c> listNewBillingScheduleLI = (List<BillingScheduleLineItem__c>)tp.newlist;
        // Map of Old values
        Map<Id,BillingScheduleLineItem__c> mapOldBillingScheduleLI = (Map<Id,BillingScheduleLineItem__c>)tp.oldMap;
        // Map of CLI Id and BillingScheduleLineItem
        Map<id,BillingScheduleLineItem__c> mapContractLIIdBillingScheduleLI = new Map<id,BillingScheduleLineItem__c>();
        // Map of CLI Id and Count of Billing Period on CLI, based on whcih BillingScheduleLineItem records will be created
        Map<id,Decimal> mapCLIIBillingPeriod = new Map<id,Decimal>();
        // Map of CLI Id and Count of Existing BillingScheduleLineItem records
        Map<id,Decimal> mapCLIIBillingScheduleLICount = new Map<id,Decimal>();
        
        if (tp.tEvent == TriggerParameters.TriggerEvent.afterInsert || tp.tEvent == TriggerParameters.TriggerEvent.beforeInsert) {
            for(BillingScheduleLineItem__c bslObj : listNewBillingScheduleLI) {
                // This will be run only for the BillingScheduleLineItem created from quick action
                if(bslObj.IsCreatedfromQuickAction__c == true && bslObj.ContractLineItem__c != NULL) {
                    mapContractLIIdBillingScheduleLI.put(bslObj.ContractLineItem__c,bslObj);
                }   
            }
        }
        
        if(!mapContractLIIdBillingScheduleLI.isEmpty()) {
            //Query for the Count of BillingPeriods__c on CLI and to check the existing count of BillingScheduleLineItem records
            for(BillingScheduleLineItem__c bslObj : [select id,ContractLineItem__r.BillingPeriods__c, ContractLineItem__c,IsCreatedfromQuickAction__c from BillingScheduleLineItem__c where ContractLineItem__c in : mapContractLIIdBillingScheduleLI.keyset() ]) {
                // This map will hold the values of CLI and its BillingPeriods value
                mapCLIIBillingPeriod.put(bslObj.ContractLineItem__c,bslObj.ContractLineItem__r.BillingPeriods__c);
                
                //This map will hold the count of existing BillingScheduleLineItem records on CLI including the existing which is created from quick action.
                Decimal bslCount = 0;
                if(mapCLIIBillingScheduleLICount.containskey(bslObj.ContractLineItem__c)) {
                    bslCount = mapCLIIBillingScheduleLICount.get(bslObj.ContractLineItem__c);
                }
                mapCLIIBillingScheduleLICount.put(bslObj.ContractLineItem__c,bslCount+1);
            }
        }
        
        if(!mapCLIIBillingPeriod.isEmpty()) {
            
            // After Insert is to create the Addition BillingScheduleLineItem record from Billing Period on CLI using Clone
            if (tp.tEvent == TriggerParameters.TriggerEvent.afterInsert ) {
            
                try {
                List<BillingScheduleLineItem__c> listBillingScheduleLineItemtobeCreated = new List<BillingScheduleLineItem__c> ();
            
                for(Id cliId : mapCLIIBillingPeriod.keyset()) {
                    // Checking if Exiting record count of BillingScheduleLineItem is less then the BillingPeriods on CLI, if Yes, then create the remaining BillingScheduleLineItem records.
                    if(mapCLIIBillingPeriod.get(cliId) > mapCLIIBillingScheduleLICount.get(cliId)) {
                        Decimal remainingBSLI = mapCLIIBillingPeriod.get(cliId) - mapCLIIBillingScheduleLICount.get(cliId) ;
                        
                        for( integer i = 0 ; i < remainingBSLI ; i++) {
                            
                            BillingScheduleLineItem__c objBsliNew = new BillingScheduleLineItem__c();
                            // Object clone Parameters (preserveId, isDeepClone, preserveReadonlyTimestamps, preserveAutonumber)
                            objBsliNew = mapContractLIIdBillingScheduleLI.get(cliId).clone(false,false,false,false);
                            objBsliNew.id = null;
                            objBsliNew.IsCreatedfromQuickAction__c = false;
                            listBillingScheduleLineItemtobeCreated.add(objBsliNew);
                        }   
                    }
                }
                if(!listBillingScheduleLineItemtobeCreated.isEmpty())
                {
                    // Insert the newly Cloned records.
                    insert listBillingScheduleLineItemtobeCreated;
                }
                } catch (exception ex) {
                    ApexLogger__c apexLogRecord = new ApexLogger__c(ClassName__c='BillingScheduleLineItemMethods',ErrorDescription__c=ex.getmessage(),FunctionName__c='CreateCloneBillingScheduleLIFromCLIandPreventBSLICreation');
                    insert apexLogRecord;     
                }
            }
            
            // Before Insert is to prevent the Addition BillingScheduleLineItem record creation from Billing Period on CLI
            if (tp.tEvent == TriggerParameters.TriggerEvent.beforeInsert) {
                for(Id cliId : mapCLIIBillingPeriod.keyset()) {
                    // Checking if Exiting record count of BillingScheduleLineItem is greater than the BillingPeriods on CLI, if Yes, then show error.
                    if(mapCLIIBillingPeriod.get(cliId) <= mapCLIIBillingScheduleLICount.get(cliId)) {
                        mapContractLIIdBillingScheduleLI.get(cliId).addError(label.BSLIErrorOnQuickActionOnCLI);
                    }
                }
            }
        }
    }
}