src/objects/ApprovedContractSummary__c.object
<CustomObject>
    <description>SFDC1-9063, created for account overview report, Provides summary of approved contracts (Not visible to end user, for internal purpose only)</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>SFDC1-9063 Created for account overview report, Master-Detail for accounts</description>
        <inlineHelpText>Master-Detail for accounts</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Approved Contract Summaries</relationshipLabel>
        <relationshipName>ApprovedContractSummaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AnnualContractValue__c</fullName>
        <description>SFDC1-9063, Created for account overview report. Annual Contract value in native currency.</description>
        <inlineHelpText>Annual Contract value in native currency</inlineHelpText>
        <label>Annual Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <description>SFDC1-9063, Created for account overview report. Frequency of billing (monthly / Quarterly / Annually).</description>
        <inlineHelpText>Frequency of billing (monthly / Quarterly / Annually)</inlineHelpText>
        <label>Billing Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractNumber__c</fullName>
        <description>SFDC1-9063, Created for account overview report. This field is used to populate unique contract number.</description>
        <inlineHelpText>This field is used to populate unique contract number.</inlineHelpText>
        <label>Contract Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EarliestContractEndDate__c</fullName>
        <description>SFDC1-9063, Created for account overview report. End date of contract.</description>
        <inlineHelpText>End date of contract.</inlineHelpText>
        <label>Earliest Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>SFDC1-9063, Created for account overview report. (Not visible to end users, for internal purpose only)</description>
        <externalId>true</externalId>
        <inlineHelpText>Key Field</inlineHelpText>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-9063, Created for account overview report. Field to show product family.</description>
        <inlineHelpText>Field to show product family</inlineHelpText>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RevenueType__c</fullName>
        <description>SFDC1-9063, Created for account overview report. Filed created to show type of revenue (recurring / non recurring) of a particular contract.</description>
        <inlineHelpText>Filed created to show type of revenue (recurring / non recurring) of a particular contract.</inlineHelpText>
        <label>Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approved Contract Summary</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>Approved Contract Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Contract Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMRelationship__c.object
<CustomObject>
    <description>SFDC1-2455 CM Relationships is used to track the Live CM Brokers on the Account Additional fields object</description>
    <fields>
        <fullName>BrokerContract__c</fullName>
        <description>SFDC1-2455 CM Relationships&apos; Broker Contract</description>
        <label>Broker Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>CM Clients</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CM Relationship</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>CM #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <description>SFDC1-718;Only on Contract Type = Order Form</description>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Montly on the Last Day of the Month</fullName>
                </value>
                <value>
                    <fullName>Montly on the First day of the month</fullName>
                </value>
                <value>
                    <fullName>Last day of the month,</fullName>
                </value>
                <value>
                    <fullName>Consulting Agreement</fullName>
                </value>
                <value>
                    <fullName>Multi Year</fullName>
                </value>
                <value>
                    <fullName>Multi Year for Prof Svcs</fullName>
                </value>
                <value>
                    <fullName>One time</fullName>
                </value>
                <value>
                    <fullName>Quarterly last day of the month</fullName>
                </value>
                <value>
                    <fullName>Semi Annual</fullName>
                </value>
                <value>
                    <fullName>Two Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContractApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-6735 : Field related  to Consulting Record Type</description>
        <inlineHelpText>Approval required if &gt;$100K or has Milestones or non-standard terms</inlineHelpText>
        <label>Contract Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-9301 : Fetching value from  Product Family on Opportunity</description>
        <inlineHelpText>Value coming from Product Family on Opportunity</inlineHelpText>
        <label>Product Family</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related product line items from opportunity at Contract record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Consulting</fullName>
        <active>true</active>
        <description>SFDC1-6735: New Record Type Created for SOW/Consulting Usage</description>
        <label>Consulting</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule</description>
    <fields>
        <fullName>AssociatedProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4324 This field holds the product associated with &apos;Opportunity Line Item&apos;, to which contract line item is related.</description>
        <inlineHelpText>Product related to Opportunity Line Item</inlineHelpText>
        <label>Associated Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items (Associated Product)</relationshipLabel>
        <relationshipName>ContractLineItems1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentContractLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contract Line Item</label>
        <referenceTo>ContractLineItem__c</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2298;Product Lookup field on Contract Line Item</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesPrice__c</fullName>
        <description>SFDC1-2298; Sales Price for Contract Line Item</description>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ContractLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-905 This is a custom object, which will be related to contract line item.</description>
    <fields>
        <fullName>ContractLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-380 This field holds the value of contract line item record to which contract line item schedule is related</description>
        <inlineHelpText>Contract Line Item</inlineHelpText>
        <label>Contract Line Item</label>
        <referenceTo>ContractLineItem__c</referenceTo>
        <relationshipLabel>Contract Line Item Schedules</relationshipLabel>
        <relationshipName>ContractLineItemSchedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-380 This is a lookup to Contract record, to which contract line item schedule is related</description>
        <inlineHelpText>Related Contract</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Item Schedules</relationshipLabel>
        <relationshipName>ContractLineItemSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InstallmentYear__c</fullName>
        <description>SFDC1-380 This is a text field which copies InstallmentYear__c from Opportunity Product Schedule</description>
        <inlineHelpText>Installment Year</inlineHelpText>
        <label>Installment Year</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesPrice__c</fullName>
        <description>SFDC1-380 This field gets populated from opportunity product schedule - sales price field when contract is created from wizard</description>
        <inlineHelpText>Sales Price</inlineHelpText>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Line Item Schedule</label>
    <nameField>
        <displayFormat>CLS-{0000000}</displayFormat>
        <label>Contract Line Item Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Item Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProfitCenters__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-3837 field to establish relationship between product and it&apos;s profit center</description>
        <inlineHelpText>Reporting Profit Center</inlineHelpText>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProfitCenter__c.object
<CustomObject>
    <description>SFDC1-3837 Object to hold data for profit centers related to a product</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCreateContractSummary.cls
//-----------------------------
// @author: Harshit Singhal
// @date: 12 July 2018
// @description: SFDC1-5228 This class creates Approved Contract Summary data for all accounts.
//-----------------------------
global class BatchCreateContractSummary implements Database.Batchable<sObject> {
    global String errorMsgs = '';
    public Database.QueryLocator start(Database.BatchableContext BC) {
        //return Database.getQueryLocator('SELECT Id FROM Account WHERE Number_of_Approved_Contracts__c >= 0');
        System.debug('@HS BATCH START()');
        return Database.getQueryLocator('SELECT Id FROM Account');
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        System.debug('@HS BATCH EXECUTE() BEGINS');
        //PART 1 Variables
        Set<id> accountIDs = new Set<Id>();
        Map<String, ApprovedContractSummary__c> acsMap = new Map<String, ApprovedContractSummary__c>();
        List<ApprovedContractSummary__c> acsMapBillingSchedule = new List<ApprovedContractSummary__c>();
        
        //PART 1
        System.debug('@HS scope size='+scope.size());
        for(sObject acc: scope) {
            Account a = (Account) acc;
            accountIDs.add(a.id);
        }
        
        if(accountIDs != null && accountIDs.size() > 0) {
            //Pre clean all the Aproved Contract Summary data
            List<ApprovedContractSummary__c> acsToDeletePreClean = [SELECT id FROM ApprovedContractSummary__c WHERE Account__c in :accountIDs];            
            System.debug('@HS acsToDeletePreClean='+acsToDeletePreClean);
            if(acsToDeletePreClean != null && acsToDeletePreClean.size() > 0) {
                delete acsToDeletePreClean;
            }
			
			//Fetch valid Contract records            
            List<Contract> contractsList = [SELECT Id, AccountId, EndDate, ContractNumber, BillingFrequency__c, 
                                            (SELECT ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name FROM ContractLineItemSchedules__r), 
                                            (Select Id From Contract_Line_Items__r)                                            
                                            FROM Contract 
                                            WHERE Account.Id in :accountIDs AND ContractApproved__c = true
                                            ORDER BY EndDate DESC
                                           ];
            System.debug('@HS contractsList size='+contractsList.size());
            System.debug('@HS contractsList='+contractsList);
            
            Map<Id, Contract> mapContracts =  new Map <Id, Contract>();            
            //Prepare unique Approved Contract Summary records from CLI Schedules
            for (Contract con : contractsList) {
                if(con.Contract_Line_Items__r != null && con.Contract_Line_Items__r.size() > 0) {							//Added a condition to check atleast one child line item to properly implement ContractAprroved=true condition in new org
                    mapContracts.put(con.Id,con);
                    for(ContractLineItemSchedule__c  cbs: con.ContractLineItemSchedules__r) {
                        String prodGroupName = cbs.ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name;		//?? Add null checkS
                        String Key = con.AccountId + prodGroupName;
                        System.debug('@HS Contract Id: ' + Con.Id + 'Product Group: ' + prodGroupName);
                        acsMap.put(key, new ApprovedContractSummary__c( Account__c = con.AccountId, AnnualContractValue__c = null, ProductFamily__c = prodGroupName
                                                                       , EarliestContractEndDate__c = con.EndDate, BillingFrequency__c = con.BillingFrequency__c
                                                                       , Key__c = Key,ContractNumber__c = con.ContractNumber));
                    }
                }
            }
            System.debug('@HS mapContracts size='+mapContracts.size());
            System.debug('@HS mapContracts='+mapContracts);
            System.debug('@HS acsMap size='+acsMap.size());
            System.debug('@HS acsMap='+acsMap);
            
            //Insert Approved Contract Summary records
            if(acsMap != null && acsMap.size() > 0) {
                Schema.SObjectField f = ApprovedContractSummary__c.Fields.Key__c;
                List<Database.UpsertResult> upsertResult = Database.upsert(acsMap.values(), f, false);
                for(Integer i=0;i< upsertResult.size();i++) {
                    if(!upsertResult.get(i).isSuccess()) {
                        Database.Error error = upsertResult.get(i).getErrors().get(0);
                        String failedDML = error.getMessage();
                        errorMsgs += 'ACS rec: '+', '+failedDML+'<\br>';
                        System.debug('@HS Error during acs record upsert. DML Error='+failedDML);
                    }
                }
                System.debug('@HS After acsMap upsert Error Messages='+errorMsgs);
                System.debug('@HS UPSERT1 complete.');                
            }
            
            //PART 2: Fetch current year Schedules
            /*
            AggregateResult[] groupedContractsBillingScheduleMaxDatePast = [SELECT Contract__c contractId, ContractLineItem__r.AssociatedProduct__c productid
                                                                            	//, MAX(Billing_Date__c) billingDate					//??
                                                                            FROM   ContractLineItemSchedule__c 
                                                                            WHERE  Contract__r.AccountId = :accountIDs 
                                                                            //AND Contract__r.RecordType_Name__c = 'Approved Contract' 	//??
                                                                            //AND Billing_Date__c <= Today								//??
                                                                            //AND Revenue_Type_del__c= 'Recurring'						//??
                                                                            GROUP BY Contract__c, ContractLineItem__r.AssociatedProduct__c]; 
            AggregateResult[] groupedContractsBillingScheduleMinDateFuture = [SELECT Contract__c contractId, ContractLineItem__r.AssociatedProduct__c productid
                                                                              	//,MIN(Billing_Date__c) billingDate						//??
                                                                              FROM   ContractLineItemSchedule__c 
                                                                              WHERE  Contract__r.AccountId = :accountIDs 
                                                                              //AND Contract__r.RecordType_Name__c = 'Approved Contract' 	//??
                                                                              //AND Billing_Date__c > Today									//??
                                                                              //AND Revenue_Type_del__c= 'Recurring'						//??
                                                                              GROUP BY Contract__c, ContractLineItem__r.AssociatedProduct__c];
            
            for (AggregateResult ar : groupedContractsBillingScheduleMaxDatePast) {
                Date MaxBillingDate = ar.get('billingDate') != null? Date.valueOf(ar.get('billingDate')): null;
                String ContractId  = ar.get('contractId') != null? String.valueof(ar.get('contractId')): '';
                String ProductId  = ar.get('productid') != null? String.valueof(ar.get('productid')): '';
                if(billingDateMap.get(ContractId + ProductId) == null) {
                    billingDateMap.put(ContractId + ProductId, MaxBillingDate);
                    System.debug('Contract Id: ' + ContractId + ' Billing date: ' + MaxBillingDate); 
                }
            }            
            for (AggregateResult ar : groupedContractsBillingScheduleMinDateFuture) {                
                Date MinBillingDate = ar.get('billingDate') != null? Date.valueOf(ar.get('billingDate')): null;
                String ContractId  = ar.get('contractId') != null? String.valueof(ar.get('contractId')): '';
                String ProductId  = ar.get('productid') != null? String.valueof(ar.get('productid')): '';
                if(billingDateMap.get(ContractId + ProductId) == null) {
                    billingDateMap.put(ContractId + ProductId, MinBillingDate);
                    System.debug('Contract Id: ' + ContractId + ' Billing date: ' + MinBillingDate); 
                }
            }
            */
			String CURRENTYEAR = String.valueOf(System.today().year());
            
            /*
            List<ContractLineItemSchedule__c> cbsList = [SELECT Id, Contract__c, ContractLineItem__r.AssociatedProduct__c, ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name                                                         
                                                         FROM ContractLineItemSchedule__c 
                                                         WHERE Contract__r.AccountId = :accountIDs                                                         
                                                         AND ContractLineItem__c != null                                                         
                                                         AND Contract__r.ContractApproved__c = true
                                                         AND ContractLineItem__r.AssociatedProduct__r.ProfitCenters__r.SaleType__c = 'Subscription'			//'Subscription' in new org means 'Recurring' in LMarkit
                                                         AND InstallmentYear__c = :CURRENTYEAR];
            System.debug('@HS current year cbsList='+cbsList);
            for(ContractLineItemSchedule__c cbs: cbsList){
                billigScheduleIds.add(cbs.Id);                
            }
            System.debug('@HS Current Year billigScheduleIds= ' + billigScheduleIds);
            */
            
            //PART 3:
            //Fetch totals of Recurring and Non-Recurring CLIS records
            Map<String, ApprovedContractSummary__c> mapACSContractValue = new Map<String, ApprovedContractSummary__c>();
            AggregateResult[] groupedContractsBillingScheduleTotalsRecurring = [SELECT SUM(SalesPrice__c) sumAnnualRev, Contract__r.AccountId accountid,  ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name pf
                                                                                FROM ContractLineItemSchedule__c 
                                                                                WHERE Contract__r.AccountId = :accountIDs 
                                                                                AND Contract__r.ContractApproved__c = true
                                                                                AND ContractLineItem__c != null    
                                                                                AND ContractLineItem__r.AssociatedProduct__r.ProfitCenters__r.SaleType__c = 'Subscription' 
                                                                                AND InstallmentYear__c = :CURRENTYEAR
                                                                                GROUP BY Contract__r.AccountId, ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name];
            
            AggregateResult[] groupedContractsBillingScheduleTotalsNonRecurring = [SELECT SUM(SalesPrice__c) sumAnnualRev, Contract__r.AccountId accountid,  ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name pf
                                                                                   FROM ContractLineItemSchedule__c 
                                                                                   WHERE Contract__r.AccountId = :accountIDs 
                                                                                   AND Contract__r.ContractApproved__c = true
                                                                                   AND ContractLineItem__c != null    
                                                                                   AND ContractLineItem__r.AssociatedProduct__r.ProfitCenters__r.SaleType__c = 'Onetime'
                                                                                   //AND InstallmentYear__c <= Today		//??
                                                                                   AND InstallmentYear__c = :CURRENTYEAR
                                                                                   GROUP BY Contract__r.AccountId, ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name];
                                                                                   
           AggregateResult[] groupedContractsBillingScheduleTotalsConsulting = [SELECT SUM(SalesPrice__c) sumAnnualRev, Contract__r.AccountId accountid,  ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name pf
                                                                                   FROM ContractLineItemSchedule__c 
                                                                                   WHERE Contract__r.AccountId = :accountIDs 
                                                                                   AND Contract__r.ContractApproved__c = true
                                                                                   AND ContractLineItem__c != null   
                                                                                   AND ContractLineItem__r.AssociatedProduct__r.ProfitCenters__r.SaleType__c = 'Consulting'
                                                                                   //AND InstallmentYear__c <= Today		//??
                                                                                   AND InstallmentYear__c = :CURRENTYEAR
                                                                                   GROUP BY Contract__r.AccountId, ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name];
            
            //Process Contracts that contain Subscription/Recurring type products
            for (AggregateResult ar : groupedContractsBillingScheduleTotalsRecurring) {
                Decimal SumAnnualRevenue = ar.get('sumAnnualRev') != null? Decimal.valueOf(double.valueOf(ar.get('sumAnnualRev'))): 0;
                String AccountId = ar.get('accountid') != null? String.valueof(ar.get('accountid')): '';
                String PFamlies = ar.get('pf') != null? String.valueof(ar.get('pf')): '';
                List<String> familyList  = PFamlies.split(',');					//?? Is this split on prod group name required?
                for(String pf: familyList) {
                    String Key = AccountId + pf;
                    mapACSContractValue.put(Key, new ApprovedContractSummary__c(RevenueType__c= 'Subscription', Account__c=AccountId,AnnualContractValue__c=SumAnnualRevenue,ProductFamily__c=pf, Key__c = Key));
                }                
                System.debug('@HS PF: ' + PFamlies + ' Subscription Amount: ' + SumAnnualRevenue);            
            }
            
            //Process Contracts that contain One off/Non-Recurring type products
            for(AggregateResult ar : groupedContractsBillingScheduleTotalsNonRecurring) { 
                
                Decimal SumAnnualRevenue = ar.get('sumAnnualRev') != null? Decimal.valueOf(double.valueOf(ar.get('sumAnnualRev'))): 0;
                String AccountId = ar.get('accountid') != null? String.valueof(ar.get('accountid')): '';
                String PFamlies = ar.get('pf') != null? String.valueof(ar.get('pf')): '';
                List<String> familyList  = PFamlies.split(',');
                for(String pf: familyList) {
                    String Key = AccountId + pf;
                    if(mapACSContractValue.get(Key) == null){
                        mapACSContractValue.put(Key, new ApprovedContractSummary__c(RevenueType__c= 'Onetime',Account__c=AccountId,AnnualContractValue__c=SumAnnualRevenue,ProductFamily__c=pf, Key__c = Key));
                    }
                    else {
                        String revenueTypeStr = mapACSContractValue.get(Key).RevenueType__c;
                        revenueTypeStr += ' & Onetime';
                        mapACSContractValue.put(Key, new ApprovedContractSummary__c(RevenueType__c= revenueTypeStr,Account__c=AccountId,AnnualContractValue__c= (SumAnnualRevenue + mapACSContractValue.get(Key).AnnualContractValue__c),ProductFamily__c=pf, Key__c = Key));
                    }
                }                
                System.debug('PF: ' + PFamlies + ' Onetime Amount: ' + SumAnnualRevenue);             
            }
            
            //Process Contracts that contain Consulting type products
            for(AggregateResult ar : groupedContractsBillingScheduleTotalsConsulting) { 
                
                Decimal SumAnnualRevenue = ar.get('sumAnnualRev') != null? Decimal.valueOf(double.valueOf(ar.get('sumAnnualRev'))): 0;
                String AccountId = ar.get('accountid') != null? String.valueof(ar.get('accountid')): '';
                String PFamlies = ar.get('pf') != null? String.valueof(ar.get('pf')): '';
                List<String> familyList  = PFamlies.split(',');
                for(String pf: familyList) {
                    String Key = AccountId + pf;
                    if(mapACSContractValue.get(Key) == null){
                        mapACSContractValue.put(Key, new ApprovedContractSummary__c(RevenueType__c= 'Consulting',Account__c=AccountId,AnnualContractValue__c=SumAnnualRevenue,ProductFamily__c=pf, Key__c = Key));
                    }
                    else {
                        String revenueTypeStr = mapACSContractValue.get(Key).RevenueType__c;
                        revenueTypeStr += ' & Consulting';
                        mapACSContractValue.put(Key, new ApprovedContractSummary__c(RevenueType__c= revenueTypeStr,Account__c=AccountId,AnnualContractValue__c= (SumAnnualRevenue + mapACSContractValue.get(Key).AnnualContractValue__c),ProductFamily__c=pf, Key__c = Key));
                    }
                }                
                System.debug('PF: ' + PFamlies + ' Consulting Amount: ' + SumAnnualRevenue);             
            }
            
            //Fetch Remaining Contracts
            Set<Id> contractProcessed = new Set<Id>();
            Set<Id> remainingContract = new Set<Id>();
            list <ContractLineItemSchedule__c> cbsRecurring = [SELECT Contract__r.Id
                                                                FROM ContractLineItemSchedule__c 
                                                                WHERE Contract__r.AccountId = :accountIDs 
                                                                AND Contract__r.ContractApproved__c = true
                                                                AND ContractLineItem__c != null    
                                                                AND InstallmentYear__c = :CURRENTYEAR 
                                                                AND ContractLineItem__r.AssociatedProduct__r.ProfitCenters__r.SaleType__c = 'Subscription'];
            System.debug('@HS cbsRecurring='+cbsRecurring);
            
            list <ContractLineItemSchedule__c> cbsNonRecurring = [SELECT Contract__r.Id
                                                                  FROM     ContractLineItemSchedule__c 
                                                                  WHERE    Contract__r.AccountId = :accountIDs 
                                                                  AND Contract__r.ContractApproved__c = true 
                                                                  AND ContractLineItem__c != null    
                                                                  AND ContractLineItem__r.AssociatedProduct__r.ProfitCenters__r.SaleType__c = 'Onetime'		////'Onetime' in new org means 'Non-recurring' in LMarkit
                                                                  //AND Billing_Date__c <= Today					//??
                                                                  AND InstallmentYear__c = :CURRENTYEAR];      
            System.debug('@HS cbsNonRecurring='+cbsNonRecurring);
            
            list <ContractLineItemSchedule__c> cbsConsulting = [SELECT Contract__r.Id
                                                                  FROM     ContractLineItemSchedule__c 
                                                                  WHERE    Contract__r.AccountId = :accountIDs 
                                                                  AND Contract__r.ContractApproved__c = true 
                                                                  AND ContractLineItem__c != null    
                                                                  AND ContractLineItem__r.AssociatedProduct__r.ProfitCenters__r.SaleType__c = 'Consulting'		////'Consulting' is new 3rd category in new org
                                                                  //AND Billing_Date__c <= Today					//??
                                                                  AND InstallmentYear__c = :CURRENTYEAR];      
            System.debug('@HS cbsConsulting='+cbsConsulting);
            
            for(ContractLineItemSchedule__c cbs : cbsRecurring) {
                contractProcessed.add(cbs.Contract__r.Id);
            }
            
            for(ContractLineItemSchedule__c cbs : cbsNonRecurring) {
                contractProcessed.add(cbs.Contract__r.Id);
            }
            
            for(ContractLineItemSchedule__c cbs : cbsConsulting) {
                contractProcessed.add(cbs.Contract__r.Id);
            }
            
            System.debug('@HS contractProcessed='+contractProcessed);
            
            for (Id conId : mapContracts.keySet()) {
                if(!contractProcessed.contains(conId)) {
                    remainingContract.add(conId);
                }
            }
            System.debug('@HS remainingContract='+remainingContract);
            
            //Fetch totals of remaining CLIS records		//?? Why are we calculating SUM of remaining records as they are not used anywhere?
            AggregateResult[] groupedContractsBillingScheduleRemining = [SELECT  SUM(SalesPrice__c) sumAnnualRev, Contract__r.AccountId accountid,  ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name pf
                                                                         FROM ContractLineItemSchedule__c 
                                                                         WHERE Contract__r.Id = :remainingContract 
                                                                         AND Contract__r.ContractApproved__c = true
                                                                         GROUP BY Contract__r.AccountId, ContractLineItem__r.AssociatedProduct__r.ProductGroup__r.Name];  
            //Process Remaining Contracts
            for (AggregateResult ar : groupedContractsBillingScheduleRemining) {                
                Decimal SumAnnualRevenue = ar.get('sumAnnualRev') != null? Decimal.valueOf(double.valueOf(ar.get('sumAnnualRev'))): 0;
                String AccountId = ar.get('accountid') != null? String.valueof(ar.get('accountid')): '';
                String PFamlies = ar.get('pf') != null? String.valueof(ar.get('pf')): '';
                List<String> familyList  = PFamlies.split(',');						//??
                for(String pf: familyList) {
                    String Key = AccountId + pf;
                    if(mapACSContractValue.get(Key) == null) {
                        mapACSContractValue.put(Key, new ApprovedContractSummary__c(RevenueType__c = 'Remaining', Account__c = AccountId, AnnualContractValue__c = 0, ProductFamily__c = pf, Key__c = Key));
                    }
                }                
                System.debug('PF: ' + PFamlies + ' Remaining Amount: ' + SumAnnualRevenue);          
            }
            System.debug('@HS mapACSContractValue size='+mapACSContractValue.size());
            System.debug('@HS mapACSContractValue='+mapACSContractValue);
            
            //Finally Update ACS records
            acsMapBillingSchedule.addAll(mapACSContractValue.values());
            
            if(acsMapBillingSchedule != null && acsMapBillingSchedule.size() > 0) {
                Schema.SObjectField f = ApprovedContractSummary__c.Fields.Key__c;
                List<Database.UpsertResult> upsertResult = Database.upsert(acsMapBillingSchedule, f, false);
                for(Integer i=0;i< upsertResult.size();i++) {
                    if(!upsertResult.get(i).isSuccess()) {
                        Database.Error error = upsertResult.get(i).getErrors().get(0);
                        String failedDML = error.getMessage();
                        errorMsgs += 'ACS rec: ' + acsMapBillingSchedule.get(i).Id+', '+failedDML+'<\br>';
                        System.debug('@HS Failure in acsMapBillingSchedule Map UPSERT2. Error='+failedDML);
                    }
                }
                System.debug('@HS UPSERT2 complete.');                
            }
        }
        System.debug('@HS BATCH EXECUTE() ENDS');
    }
    
    public void finish(Database.BatchableContext BC) {
        System.debug('@HS BATCH FINISH()');
        //Call Support Overview Batch here in next phase
        //Database.executeBatch(new BatchCalCasesSummarySupportOverview(), 1);        
    }
}