src/objects/BillingScheduleLineItem__c.object
<CustomObject>
    <description>SFDC1-4488 This object is used to create a billing schedule for variable billing products.This object will be a child object to Variable Billing Schedule Object.</description>
    <fields>
        <fullName>AUMBPS__c</fullName>
        <description>SFDC1-4488 This field holds the AUM BPS</description>
        <inlineHelpText>AUM Basis Point (BPS)  value provided</inlineHelpText>
        <label>AUM BPS</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AUMValue__c</fullName>
        <description>SFDC-4488 This field holds the AUM Value</description>
        <inlineHelpText>AUM value provided</inlineHelpText>
        <label>AUM Value</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-7471 This field will hold Contract Line Item #</description>
        <inlineHelpText>System populated reference to the Contract Line Item being billed</inlineHelpText>
        <label>Contract Line Item</label>
        <referenceTo>ContractLineItem__c</referenceTo>
        <relationshipLabel>Billing Schedule Line Items</relationshipLabel>
        <relationshipName>BillingScheduleLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsCreatedfromQuickAction__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-7472 : This is an technical field only. This field will be an identifier whether this record is created using the quick action on Contract Line Item or using the Apex Clone based on the Billing period on Contract line Item.</description>
        <inlineHelpText>Only for DEV purpose. This field will be an identifier whether this record is created using the quick action on Contract Line Item or using the Apex Clone based on the Billing period on Contract line Item.</inlineHelpText>
        <label>Is Created from Quick Action?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>SFDC1-4488: This field will be user-filled and holds the quantity</description>
        <inlineHelpText>Enter quantity being billed</inlineHelpText>
        <label>Quantity</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Billing Schedule Line Item</label>
    <nameField>
        <displayFormat>BSL{000000}</displayFormat>
        <label>Billing Schedule Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedule Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>Trial</fullName>
        <active>true</active>
        <description>A new record type for contract</description>
        <label>Trial</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule</description>
    <fields>
        <fullName>BillingPeriods__c</fullName>
        <description>SFDC1-7471 This field holds the Billing Period</description>
        <inlineHelpText>Please enter the Billing Period</inlineHelpText>
        <label>Billing Periods</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>SFDC1-2298</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBillingScheduleLineItemMethods.cls
//-----------------------------
    // @author: Mohit Modi
    // @date: 16 April 2018
    // @description: SFDC1-7472 : Test method for BillingScheduleLineItemMethods Class
    // @return: None
    //------------------------------
@isTest
private class TestBillingScheduleLineItemMethods {

    //-----------------------------
    // @author: Mohit Modi
    // @date: 16 April 2018
    // @description: SFDC1-7472 : Test method for CreateCloneBillingScheduleLIFromCLIandPreventBSLICreation
    // @return: None
    //------------------------------
    @isTest
    static void testCreateCloneBillingScheduleLIFromCLIandPreventBSLICreation() {
    
        Account a = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', true);
        Contact c = TestUtility.createContact(a.Id,'1test.2test@3test.com' ,true,'Test', 'testSetCaseAdditionalFieldsObject');
        
        //creating contract
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        PricebookEntry testPBE = TestUtility.createPriceBookEntry(standardId, testProd.Id, true);
        
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        Id trailRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Trial').getRecordTypeId();
        
        test.startTest();
        
        Contract contract1 = TestUtility.createContractWithInsertOptional(a.Id, legalEntity.Id, country.Id, standardId,true);
        // Creating the CLI with Billing Period
        ContractLineItem__c  testCLI = TestUtility.createContractLineItem('TestCLI',contract1.id,testProd.id,false);
        testCLI.BillingPeriods__c = 4;
        insert testCLI;
        
        // Creating the BSLI record with IsCreatedfromQuickAction__c = true as equal to be created by Quick Action
        BillingScheduleLineItem__c testBSLI = new BillingScheduleLineItem__c (IsCreatedfromQuickAction__c = true,AUMBPS__c = 'test',AUMValue__c = 'test',Quantity__c = 4,ContractLineItem__c = testCLI.id);
        insert testBSLI ;
        
        // Checking that the remaing BSLI record has to be created equal to CLI's Billing Period
        integer BSLIcreated = [select count() from BillingScheduleLineItem__c where ContractLineItem__c = : testCLI.id ];
        System.assertEquals(BSLIcreated ,testCLI.BillingPeriods__c);
        
        // Reducing the Billing Period on CLI
        testCLI.BillingPeriods__c = 1;
        update testCLI;
        
        try {
            // Trying to insert new BSLI using Quick action after reducing the CLI Billing Period, Error Should be thrown.
            BillingScheduleLineItem__c testBSLI1 = new BillingScheduleLineItem__c (IsCreatedfromQuickAction__c = true,AUMBPS__c = 'test',AUMValue__c = 'test',Quantity__c = 4,ContractLineItem__c = testCLI.id);
            insert testBSLI1 ;
        } catch (exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.BSLIErrorOnQuickActionOnCLI) ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
    }
}