src/objects/BusinessLine__c.object
<CustomObject>
    <description>SFDC1-8429: Creating a new object that will be used in products</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-8429: This field will be used for holding Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CrossPlantStatus__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 ,  This holds Cross Plant Status related to Products</description>
    <fields>
        <fullName>SAPCode__c</fullName>
        <label>SAP Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cross Plant Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross Plant Status</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Family__c.object
<CustomObject>
    <description>SFDC1-131: This object holds Family related to Products</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-5469 To set if the active/inactive status of family record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <description>SFDC1-173 This formula field pulls in the material code from the related product.</description>
        <formula>PricebookEntry.Product2.MaterialCode__c</formula>
        <inlineHelpText>Material Code from Product Master</inlineHelpText>
        <label>Material Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>BusinessLine2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-8429: This Field is created to hold business line lookup</description>
        <inlineHelpText>Business Line</inlineHelpText>
        <label>Business Line</label>
        <referenceTo>BusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Reporting Product Family</inlineHelpText>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsFamily</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalProductName__c</fullName>
        <inlineHelpText>Extended Name, Internal-Facing Only</inlineHelpText>
        <label>Internal Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MediaType__c</fullName>
        <inlineHelpText>Format of Deliverable</inlineHelpText>
        <label>Media Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines Availability/Sellability</inlineHelpText>
        <label>Product Status</label>
        <referenceTo>CrossPlantStatus__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCrossPlantStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProfitCenters__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-3837 field to establish relationship between product and it&apos;s profit center</description>
        <inlineHelpText>Reporting Profit Center</inlineHelpText>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubBusinessLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 - 2170 : Lookup field to Sub Business Line Object</description>
        <inlineHelpText>Reference to Sub Business Line Record</inlineHelpText>
        <label>Sub Business Line</label>
        <referenceTo>SubBusinessLine__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductExtensions__c.object
<CustomObject>
    <description>SFDC1-134 : This Object will be used to Track the Product Extensions between Product and Legal Entities</description>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-134 : This field will be used to store the value of Legal Entity</description>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Product Extensions</relationshipLabel>
        <relationshipName>Product_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-134 : This field will be used to store the Product Value</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Extensions</relationshipLabel>
        <relationshipName>Product_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Extensions</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Product Extensions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProfitCenter__c.object
<CustomObject>
    <description>SFDC1-3837 Object to hold data for profit centers related to a product</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SubBusinessLine__c.object
<CustomObject>
    <description>SFDC1-2170 : This holds Sub Business Line related to Products</description>
    <label>Sub Business Line</label>
    <nameField>
        <label>Sub Business Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Business Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <description>SFDC1-5853 : This field will hold the value of Legal Entity of the user and will be editable only by System Admin and  Sales Ops</description>
        <inlineHelpText>Legal Entity of the user</inlineHelpText>
        <label>Legal Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/productSearchController.cls
//
//@Author : Paras Dhingra
//@date: 17th Aug 2017
//@description : SFDC1-2043 product selector controller for multi-year oppys
//@modified date: 09th Mar 2017
//@modified reason: SFDC1-7092 fixing inconsistent search behavior by adding recursion and soql limit check
//@modified by: Paras Dhingra
//
public without sharing class productSearchController {
    
    //
    //@Author : Paras Dhingra
    //@date: 17th Aug 2017
    //@description : SFDC1-2043 fetch search products based on user filters
    //@company : IHS Markit
    //@param : String , List<String>, String,String, String, String,String, String, String, String
    //@return : List<ProductEditController.ProductLineItemWrapper>
    //
    @auraEnabled
    public static List<productSelectorWrapperClass> getProducts (String familyName, String productName,
                                                                 String materialNumber, String businessLine, String subBusinessLine, 
                                                                 String profitCenter, String mediaType, String internalProductName, String legalEntity, String lastMaterialCode, List<productSelectorWrapperClass> lstSearchedSoFar) {
                                                                     List<productSelectorWrapperClass> lstProductsToReturn = new List<productSelectorWrapperClass>();
                                                                     System.debug('--familyName--'+ familyName);
                                                                     List<Product2> lstProductsLegal = new List<Product2>();
                                                                     Map<Id,Product2> mapProductsLegalEntity = new Map<Id,Product2>();
                                                                     Set<Id> setLegaLEntityProductIds = new Set<Id>();
                                                                     
                                                                     String availableForSale = '04';
                                                                     String queryBase = 'Select id, name, family__c, family__r.Name, MaterialCode__c, BusinessLine2__r.name, SubBusinessLine__r.name, ProfitCenters__r.Name, InternalProductName__c, MediaType__c, LegalEntity__c from Product2 where';
                                                                     //String queryLegalFilter = ' (LegalEntity__c=:legalEntity OR ID IN: setLegaLEntityProductIds) ';
                                                                     String queryCommonFilter = ' isActive=true AND ProductStatus__r.SAPCode__c=:availableForSale';
                                                                     if(familyName!=null && !String.IsBlank(familyName)) {
                                                                         queryCommonFilter += ' AND family__r.Name like \'%'+familyName+'%\'';
                                                                     }
                                                                     if(productName!=null && !String.IsBlank(productName)) {                                                                         
                                                                         queryCommonFilter+= ' AND Name like \'%'+productName+'%\'';
                                                                     }
                                                                     if(materialNumber!=null && !String.IsBlank(materialNumber)) {
                                                                         queryCommonFilter+= ' AND  MaterialCode__c like \'%'+materialNumber+'%\'';
                                                                     }
                                                                     if(businessLine!=null && !String.IsBlank(businessLine)) {
                                                                         queryCommonFilter += ' AND BusinessLine2__r.name like \'%'+businessLine+'%\'';
                                                                     }
                                                                     if(subBusinessLine!=null && !String.IsBlank(subBusinessLine)) {
                                                                         queryCommonFilter += ' AND SubBusinessLine__r.name like \'%'+subBusinessLine+'%\'';
                                                                     }
                                                                     if(profitCenter!=null && !String.IsBlank(profitCenter)) {
                                                                         queryCommonFilter += ' AND ProfitCenters__r.name like \'%'+profitCenter+'%\'';
                                                                     }
                                                                     if(mediaType!=null && !String.IsBlank(mediaType)) {
                                                                         queryCommonFilter += ' AND MediaType__c like \'%'+mediaType+'%\'';
                                                                     }
                                                                     if(internalProductName!=null && !String.IsBlank(internalProductName)) {
                                                                         queryCommonFilter += ' AND internalProductName__c like \'%'+internalProductName+'%\'';
                                                                     }
                                                                     if(lastMaterialCode!=null && !String.IsBlank(lastMaterialCode)) {
                                                                         queryCommonFilter += ' AND MaterialCode__c > \''+lastMaterialCode+'\'';
                                                                     }
                                                                    
                                                                     String queryFinalLegal = queryBase + queryCommonFilter + ' ORDER BY MaterialCode__c ASC LIMIT 100' ;
                                                                     System.debug('--queryFinalLegal--'+ queryFinalLegal);
                                                                     //lstProductsLegal = Database.query(queryFinalLegal);
                                                                     mapProductsLegalEntity = new Map<Id,Product2>((List<Product2>)Database.query(queryFinalLegal)); 
                                                                     
                                                                     //for recursive call carry forward the already searched products
                                                                     if(lstSearchedSoFar!=null) {
                                                                         lstProductsToReturn = lstSearchedSoFar;
                                                                     }
                                                                     //check if products are extended in product extensions
                                                                     //query the product extenstions and fetch related extensions only
                                                                     if(mapProductsLegalEntity!=null && !mapProductsLegalEntity.isEmpty()) {
                                                                         for(ProductExtensions__c pe : [Select Product__c from ProductExtensions__c where LegalEntity__c =:legalEntity AND Product__r.isActive=true
                                                                                                    AND Status__c='Active' AND Product__c IN: mapProductsLegalEntity.keySet() ] ) {
                                                                         setLegaLEntityProductIds.add(pe.Product__c);
                                                                        }
                                                                         for(Product2 prod : mapProductsLegalEntity.values()) {
                                                                             productSelectorWrapperClass pswc = new productSelectorWrapperClass();
                                                                             if(prod.LegalEntity__c ==legalEntity|| setLegaLEntityProductIds.contains(prod.Id)) {                                                                              
                                                                                 pswc.isSelected = false;
                                                                                 pswc.ProductName = prod.Name;
                                                                                 pswc.productId = prod.Id;
                                                                                 pswc.product = prod;
                                                                                 lstProductsToReturn.add(pswc);
                                                                                 
                                                                                    
                                                                             }
                                                                             // the last material code added in the loop will be the marker for offset    
                                                                             if( prod.MaterialCode__c!=null) {
                                                                                 lastMaterialCode = prod.MaterialCode__c;
                                                                             }
                                                                         }
                                                                     }
                                                                     System.debug('--getQueries--'+Limits.getQueries());
                                                                     //check if queried results have been filtered out and reduced the size of return payload
                                                                     System.debug('--lstProductsToReturn.size before recursion--'+lstProductsToReturn.size());
                                                                     if(lstProductsToReturn.size()<50 && mapProductsLegalEntity!=null && mapProductsLegalEntity.size()==100 ) {
                                                                         //make a recursive call to the method only if soql limit allowance is within range
                                                                         if(Limits.getQueries()<=94) {
                                                                            lstProductsToReturn = getProducts(familyName, productName,materialNumber, businessLine, subBusinessLine,profitCenter, mediaType, internalProductName, legalEntity, lastMaterialCode,lstProductsToReturn); 
                                                                         }
                                                                         
                                                                        
                                                                     }
                                                                     System.debug('--lstProductsToReturn.size--'+lstProductsToReturn.size());
                                                                     return lstProductsToReturn;
                                                                 }
    //
    //@Author : Paras Dhingra
    //@date: 17th Aug 2017
    //@description : SFDC1-2043 fetch productIds already on opportunity
    //@company : IHS Markit
    //@param : String 
    //@return : List<String>
    //
    @auraEnabled
    public static List<String> getProductsAlreadyInOppy(String oppyId) {
        List<String> lstProductId = new List<String>();
        List<OpportunityLineItem> lstOppyProduct = [Select Product2Id from OpportunityLineItem where OpportunityId=:oppyId];
        if(lstOppyProduct!=null && !lstOppyProduct.isEmpty()) {
            for(OpportunityLineItem oli : lstOppyProduct) {
                lstProductId.add(oli.Product2Id);
            }
        }
        return lstProductId;
    }
    //
    //@Author : Paras Dhingra
    //@date: 20 Sep 2017
    //@description : SFDC1-4353 fetch list of all legal entities in the system
    //@company : IHS Markit
    //@param : String 
    //@return : List<LegalEntity__c>
    //
    @auraEnabled 
    public static OpportunityLegalEntityWrapper getAllLegalEntities(String oppyId) {
        System.debug('--OppyId--'+ oppyId);
        OpportunityLegalEntityWrapper  oleWrapObj= new OpportunityLegalEntityWrapper();
        List<LegalEntity__c> lstLegalEntity = [Select Id, Name from LegalEntity__c where Status__c='Active' order by Name asc];
        Map<String,Id> mapLegalEntityNameId = new Map<String,Id>();
        if(lstLegalEntity!=null && !lstLegalEntity.isEmpty()) {
            for(LegalEntity__c legEnt : lstLegalEntity) {
                mapLegalEntityNameId.put(legEnt.Name,legEnt.Id);
            }
        }
        List<Opportunity> lstOppy = new List<Opportunity> ();
        oleWrapObj.oppyLegalEntity = '--None--';
        if(oppyId!=null && oppyId!='') {
            lstOppy = [Select id, LegalEntity__c,Owner.LegalEntity__c, (Select id from opportunityLineItems) from Opportunity where id=:oppyId];
            if(lstOppy!=null && !lstOppy.isEmpty() ) {
                if(lstOppy[0].LegalEntity__c!=null) {
                    
                    oleWrapObj.oppyLegalEntity = lstOppy[0].LegalEntity__c;    
                }
                else if(lstOppy[0].Owner.LegalEntity__c!=null && lstOppy[0].Owner.LegalEntity__c!='' && mapLegalEntityNameId.containsKey(lstOppy[0].Owner.LegalEntity__c)) {
                    
                    oleWrapObj.oppyLegalEntity = mapLegalEntityNameId.get(lstOppy[0].Owner.LegalEntity__c);
                    System.debug('--oleWrapObj.oppyLegalEntity--'+oleWrapObj.oppyLegalEntity);
                }
                
            }
        }
       
        
        oleWrapObj.lstLegalEntity = lstLegalEntity;
        return oleWrapObj;
    }
    //
    //@Author : Paras Dhingra
    //@date: 21 Sep 2017
    //@description : SFDC1-4353 delete related oppy products and oppy product schedules
    //@company : IHS Markit
    //@param : String
    //@return : String
    //
    @auraEnabled public static  String deleteProductsOnOppy (String oppyId, String newLegalEntity) {
        
        String message = '';
        Savepoint sp = Database.setSavepoint();
        try {
            GlobalConstants.hasAllowedOpportunityProductDeletion = true;
            List<Opportunity> lstOppy = [Select Id, LegalEntity__c, (Select Id, Product2.LegalEntity__c, Product2Id from OpportunityLineItems where Status__c='New') 
                                            from Opportunity where Id=:oppyId];
            
            if(lstOppy!=null && !lstOppy.isEmpty()) {
                Opportunity oppy = new Opportunity(id=lstOppy[0].Id);
                oppy.LegalEntity__c = newLegalEntity!=null?newLegalEntity:null;
                update oppy;
                
                if(lstOppy[0].OpportunityLineItems!=null && !lstOppy[0].OpportunityLineItems.isEmpty()) {
                    //collate product ids
                    Set<Id> setOppyProductIdsToDel = new Set<Id>();
                    Set<Id> setValidProducts = new Set<Id>();
                    for(OpportunityLineItem oli : lstOppy[0].OpportunityLineItems) {
                        setOppyProductIdsToDel.add(oli.Product2Id);
                        if(oli.Product2.LegalEntity__c == newLegalEntity) {
                            setValidProducts.add(oli.Product2Id);
                        }
                        
                    }
                    //query product extensions which are related to new legal entity
                    List<ProductExtensions__c> lstProductExtension = [Select Product__c from ProductExtensions__c where LegalEntity__c=:newLegalEntity
                                                                        and Product__c IN:setOppyProductIdsToDel ];
                    if(lstProductExtension!=null && !lstProductExtension.isEmpty()) {
                        for(ProductExtensions__c prodEx : lstProductExtension) {
                            setValidProducts.add(prodEx.Product__c);
                        }
                    }
                    if(setValidProducts!=null && !setValidProducts.isEmpty()) {
                        //remove valid products from the list
                        setOppyProductIdsToDel.removeAll(setValidProducts);
                    }
                    //check if deletion list still has products 
                    if(setOppyProductIdsToDel!=null && !setOppyProductIdsToDel.isEmpty()) {
                        //create a list of opportunity line items to delete
                        List<OpportunityLineItem> lstOppyLineItemToDelete = new List<OpportunityLineItem>();
                        for(OpportunityLineItem oli : lstOppy[0].OpportunityLineItems) {
                            if(setOppyProductIdsToDel.contains(oli.Product2Id)) {
                                lstOppyLineItemToDelete.add(oli);
                            }
                        }
                        if(lstOppyLineItemToDelete!=null && !lstOppyLineItemToDelete.isEmpty()) {
                            delete lstOppyLineItemToDelete;
                        }
                    }
                }
            }
            message = 'Related products updated!!';
            GlobalConstants.hasAllowedOpportunityProductDeletion = false;
        }
        catch(Exception ex) {
            System.debug('Exception caught in deleteProductsOnOppy');
            message = 'Error Occurred ' +ex; 
            Database.rollback(sp);
        }
        return message;
    }
    
    //
    //@Author : Paras Dhingra
    //@date: 21 Sep 2017
    //@description : SFDC1-4353 Wrapper class for Opportunity legal entity
    //@company : IHS Markit
    //
    public class OpportunityLegalEntityWrapper {
        @auraEnabled public string oppyLegalEntity;
        @auraEnabled public List<LegalEntity__c> lstLegalEntity;
    }
}