src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7738: New field for Order Management Case</description>
        <inlineHelpText>Contract End Date</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7738: New field for Order Management Case</description>
        <inlineHelpText>Contract Start Date</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-965 &amp; SFDC1-638 Country field for new Account creation through Case</description>
        <inlineHelpText>Country for new Account creation through Case</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for Case Additional Fields Setup.
SFDC1-7120 Field used in filter condition is deleted. So Removing from here.</description>
        <inlineHelpText>Examples - Jane&apos;s Online - Petra - World Market Monitor</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Cases (Product Group)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ActivityCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-547 - To check the Activity is been created on Opportunity</description>
        <label>Activity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReadyForProcessingContractExist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5701, this will be set to true by the process builder on Contract whenever Contract Status changes to &quot;Ready For Processing&quot;.</description>
        <label>Ready For Processing Contract Exist?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <description>SFDC1-529 This field shows the Opportunity Owner&apos;s Region on Opportunity</description>
        <formula>TEXT(Owner.UserRegion__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sales Region of Opportunity Owner</inlineHelpText>
        <label>Sales Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestSubmitToSalesProcessController.cls
//-----------------------------
// @author: Vinod Merwade
// @date: 10 Oct 2017
// @param: NA
// @description: SFDC1-550 Test class for SubmitToSalesProcessController
// @return: NA
// @Company: Vertiba
// @Last Modified By : Hemant Shukla
// @Last Modified Description : Removed the dependency of ContractExists__c field based on SFDC1-5701
// @Last Modified Date : 6-Nov-2017
// @lastModifiedBy: Vishnu
// @LastModifiedDate: 29 Mar 2018
// @LastModifiedDescription: SFDC1-7721: Internal__C was used to indicate if a product group was part of Internal Case
// 						  record type, Since that record type is deleted, we are removing fields used specifically for it
// 						  
// 						  
// @Last Modified By : Vishnu Vardhan Chowdary Andra
// @Last Modified Date: 08 Aug 2018
// @Last Modified Description: Code is deleted/commented out as part of stories SFDC1-9677/78/80/81/82/83/84.
// 		Accordingly commenting out test class. 
//-----------------------------
@isTest
public class TestSubmitToSalesProcessController {
    //-----------------------------
    // @author: Vinod Merwade
    // @date: 19 July 2017
    // @param: NA
    // @description:SFDC1-550 Test method for SubmitToSalesProcessController
    // @return: NA
    // @Company: Vertiba
    //-----------------------------
    private static testmethod void testSubmitSalesprocess() {
        /*Account testAccount = TestUtility.createTestAccount('testAccount', false);
        testAccount.Type = 'Place Holder - General Service Account';
        insert testAccount;
        Country__c country = (Country__c)TestUtility.loadCountryData().get(0);
        opportunity opp = TestUtility.createOpportunity(testAccount.id, 'Test opportunity',country.id,true);
          // Commented By : Mohit : 16Oct2017 : as this field is in Deletion List and replaced by Formula field.
          //opp.SalesRegion__c = 'APAC';
        opp.ContractStartDate__c = System.today();
        opp.ContractEndDate__c = System.today();
        opp.ActivityCreated__c = true;
        opp.ReadyForProcessingContractExist__c  = true;
        update opp;
        contact cont = new contact (
            Email = 'false@ihsmarkit.com', 
            Phone = '1234567890',
            LastName ='TestLastName',
            FirstName='TestFirstName'
        );
        insert cont;
        OpportunityContactRole oppContactPrimary = new OpportunityContactRole();
        oppContactPrimary.OpportunityID = opp.Id;
        oppContactPrimary.IsPrimary = TRUE;
        oppContactPrimary.ContactId = cont.Id;  
        Insert oppContactPrimary;
        ProductGroup__c prdGrp = new ProductGroup__c(
            Name = 'Sales Ops'
            //Internal__c = true
        );
        insert prdGrp;
        
        Boolean flag =SubmitToSalesProcessController.regionExist(opp.Id);
        if(flag) {
            Id caseId = SubmitToSalesProcessController.submitToSalesProcessingQueue(opp.Id);
            system.debug('caseid============'+caseId);
            system.assert(caseId != NULL);
        }*/
    }
}