src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ContractProductList__c</fullName>
        <description>SFDC1-593 This field is concatenated list of Products from the list of Contracts</description>
        <label>Contract Product List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-88 This field represents SAP Contract Number(s)</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-965 &amp; SFDC1-638 Country field for new Account creation through Case</description>
        <inlineHelpText>Country for new Account creation through Case</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <description>SFDC1-593 This is the sum of Annual revenue from the list of contracts related</description>
        <label>Revenue</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Onboarding</fullName>
        <active>true</active>
        <businessProcess>Onboarding</businessProcess>
        <description>Auto-Generated - tracks the customer onboarding process and proof of delivery attachments related to the contracting process.</description>
        <label>Onboarding</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CaseContracts__c.object
<CustomObject>
    <description>SFDC1-593 - Junction object between Case and Contracts</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>SFDC1-593 - Master detail relationship to Case</description>
        <inlineHelpText>Select the Case you wish to relate to a Contract.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Contracts</relationshipLabel>
        <relationshipName>CaseContracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-593 - Lookup to contract</description>
        <inlineHelpText>Select the Contract you wish to relate to a Case.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Case Contracts</relationshipLabel>
        <relationshipName>CaseContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <formula>Contract__r.TotalContractValue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Contracts</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Case Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule</description>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCaseContractsMethods.cls
/**
* @author: Vishnu vardhan Chowdary Andra
* @date: 29 August 2017
* @description: Class to test CaseContractsMethods.
* @companyname: VERTIBA
*/
@isTest
private class TestCaseContractsMethods {
	/**
     * @author: Vishnu vardhan Chowdary Andra
     * @date: 29 August 2017
     * @description: This method tests the CaseContractsMethods by creating/updating/deleting Case Contracts objects.
     * @companyname: VERTIBA 
     * @Last Modified Date : 23-Nov-2017
     * @lastmodifiedBy : Vishnu 
     * @Last Modified Description : fixing the errors in bitbucket
     */ 
    @isTest
    private static void testUpdateRollupSummariesInCase() {
        //create test data
        List<Product2> prodList = new List<Product2>();
        prodList.add(TestUtility.createProduct('Test Product', false));
        prodList.add(TestUtility.createProduct('Product Test', false));
        insert prodList;
        Id standardId = Test.getStandardPricebookId();
        Account testAccount = TestUtility.createTestAccount('testAccount', true);
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        Country__c country = (Country__c)TestUtility.loadCountryData().get(0);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        
        Contract contract1 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        Contract contract2 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        List<ContractLineItem__c> cliList = new List<ContractLineItem__c>();
        cliList.add(TestUtility.createContractLineItem('CLI1', contract1.Id, prodList.get(0).Id, false));
        cliList.add(TestUtility.createContractLineItem('CLI2', contract1.Id, prodList.get(1).Id, false));
        cliList.add(TestUtility.createContractLineItem('CLI3', contract2.Id, prodList.get(1).Id, false));
        insert cliList;
        
        Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
        Case testCase = new Case();
        testCase.RecordTypeId = caseRecordTypeId;
        testCase.subject = 'Test subject';
        testCase.AccountId = testAccount.Id;
        testCase.contactId = testContact.Id;
        insert testCase;
        
        Test.startTest();
        //Case Contract is not added so values should be empty
        Case case1 = getCaseFromDatabase(testCase.id);
        System.debug(case1.Revenue__c+' case1 '+case1.ContractProductList__c); 
        System.assertEquals(null, case1.ContractProductList__c);
        System.assertEquals(null, case1.Revenue__c);
        
        //Creating case Contract, so case should be updated
        CaseContracts__c testCaseContracts1 = createCaseContracts(case1.id,contract1.id);
        case1 = getCaseFromDatabase(testCase.id);
        System.debug(case1.Revenue__c+' case2 '+case1.ContractProductList__c); 
        System.assert(case1.ContractProductList__c.contains('Test Product'));
        System.assert(case1.ContractProductList__c.contains('Product Test'));
        System.assertEquals(case1.Revenue__c, 2000.0);

        //Modifying Contract with different Contract
        testCaseContracts1.Contract__c = contract2.id;
        update testCaseContracts1;
        case1 = getCaseFromDatabase(testCase.id);
        System.debug(case1.Revenue__c+' case3 '+case1.ContractProductList__c); 
        System.assert(case1.ContractProductList__c.contains('Product Test'));
		System.assertEquals(false,case1.ContractProductList__c.contains('Test Product'));
        System.assertEquals(case1.Revenue__c, 1000.0);
        
        //Test by adding a new record to existing one.
        CaseContracts__c testCaseContracts2 = createCaseContracts(case1.id,contract1.id);
        case1 = getCaseFromDatabase(testCase.id);
        System.debug(case1.Revenue__c+' case4 '+case1.ContractProductList__c); 
        System.assert(case1.ContractProductList__c.contains('Product Test'));
        System.assert(case1.ContractProductList__c.contains('Test Product')); 
        System.assertEquals(case1.Revenue__c, 3000.0);
        
        //Test by deleting record.
        delete testCaseContracts2;
        case1 = getCaseFromDatabase(testCase.id);
        System.debug(case1.Revenue__c+' case5 '+case1.ContractProductList__c); 
        System.assert(case1.ContractProductList__c.contains('Product Test'));
		System.assertEquals(false,case1.ContractProductList__c.contains('Test Product'));
        System.assertEquals(case1.Revenue__c, 1000.0);
        
        Test.stopTest();
    }

    /**
     * @author: Vishnu vardhan Chowdary Andra
     * @date: 12 September 2017
     * @description: helper method to get case object from database.
     * @companyname: VERTIBA 
     */ 
    private static Case getCaseFromDatabase(Id caseId) {
        Case testCase = [Select id, ContractProductList__c, Revenue__c from case where id =: caseId];
        return testCase;
    }

    /**
     * @author: Vishnu vardhan Chowdary Andra
     * @date: 12 September 2017
     * @description: Helper method to insert case contract objects.
     * @companyname: VERTIBA 
     */ 
    private static CaseContracts__c createCaseContracts(id caseId, id contractId) {
        try {
            CaseContracts__c testCaseContracts = new CaseContracts__c();
            testCaseContracts.Case__c = caseId;
            testCaseContracts.Contract__c = contractId;
            insert testCaseContracts;
            return testCaseContracts;
        } catch (Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.CaseContractDuplicateCheck) ? true : false;
            // Assert to check correct Error is thrown
            System.AssertEquals(expectedExceptionThrown, true);
            return null;
        }
    }
    
    /**
     * @author: Vishnu vardhan Chowdary Andra
     * @date: 25 September 2017
     * @description: This method tests the ValidateIfCaseProductAlreadyExist by creating/updating Case Contract objects.
     * @companyname: VERTIBA 
     * @lastmodifiedSprint : Sprint 9
     */ 
    @isTest
    private static void testValidateIfCaseProductAlreadyExist() {
        //Create test data
        Id standardId = Test.getStandardPricebookId();
        Account testAccount = TestUtility.createTestAccount('testAccount', true);
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        Country__c country = (Country__c)TestUtility.loadCountryData().get(0);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        
        Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
        Case testCase = new Case();
        testCase.RecordTypeId = caseRecordTypeId;
        testCase.subject = 'Test subject';
        testCase.AccountId = testAccount.Id;
        testCase.contactId = testContact.Id;
        insert testCase;
        
        Contract contract1 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        Contract contract2 = TestUtility.createContract(testAccount.Id, legalEntity.Id, country.Id, standardId);
        
        Test.startTest();
        //Creating case Contract, record to be inserted successfully
        CaseContracts__c testCaseContracts1 = createCaseContracts(testCase.id,contract1.id);
        System.assertNotEquals(null,testCaseContracts1.id); 
        
        //Adding second case Contract, record to be inserted successfully 
        CaseContracts__c testCaseContracts2 = createCaseContracts(testCase.id,contract2.id);
        System.assertNotEquals(null,testCaseContracts2.id); 
        
        //Add same case again, it should fail, Exception is caught and returned null.
		testCaseContracts1 = createCaseContracts(testCase.id,contract1.id);
        System.assertEquals(null,testCaseContracts1); 
        
        //Modifying Contract with different Contract
        testCaseContracts2.Contract__c = contract1.id;
        try {
            update testCaseContracts2;
        } catch (Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.CaseContractDuplicateCheck) ? true : false;
            // Assert to check correct Error is thrown
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        Test.stopTest();
    }
}