src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ContractProductList__c</fullName>
        <description>SFDC1-593 This field is concatenated list of Products from the list of Contracts</description>
        <label>Contract Product List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-88 This field represents SAP Contract Number(s)</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <description>SFDC1-593 This is the sum of Annual revenue from the list of contracts related</description>
        <label>Revenue</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CaseContracts__c.object
<CustomObject>
    <description>SFDC1-593 - Junction object between Case and Contracts</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>SFDC1-593 - Master detail relationship to Case</description>
        <inlineHelpText>Select the Case you wish to relate to a Contract.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Contracts</relationshipLabel>
        <relationshipName>CaseContracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-593 - Lookup to contract</description>
        <inlineHelpText>Select the Contract you wish to relate to a Case.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Case Contracts</relationshipLabel>
        <relationshipName>CaseContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <formula>Contract__r.TotalContractValue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Contracts</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Case Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-718;Look up field for Product on Contract Line</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ContractLineItem__c.object
<CustomObject>
    <description>SFDC1-2298; A custom object for contract billing schedule</description>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-2298; Master-Detail relationship on Contract</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentContractLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contract Line Item</label>
        <referenceTo>ContractLineItem__c</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2298;Product Lookup field on Contract Line Item</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseContractsMethods.cls
/**
* @author: Vishnu vardhan Chowdary Andra
* @date: 23 August 2017
* @description: SFDC1-593. After insert dispatcher event handler class that calls the functions in CaseContractsMethods.
* @companyname: VERTIBA
*/
public class CaseContractsMethods {
    /** 
    * @author: Vishnu vardhan Chowdary Andra
    * @date: 23 August 2017
    * @description: SFDC1-593.  When a CaseContracts object is created/updated/deleted then the parent case object will be
    *		updated (simillar to rollup summary). Contract product list and revenue are the fields in case object.
    *		Products and Annual Revenue are the fields in Contract object. 
    * @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got created.
    * @companyname: VERTIBA
    * @return: void
    * 
    * @author: Vishnu vardhan Chowdary Andra
    * @date: 3 November 2017
    * @description: SFDC1-593. Updating try catch block and adding revenue part.
    */
    public static void updateRollupSummariesInCase(TriggerParameters tp) {
        try {
            if(tp.tEvent == TriggerParameters.TriggerEvent.afterInsert ||
               tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate ||
               tp.tEvent == TriggerParameters.TriggerEvent.afterDelete) {
                   //1. Collect all the caseId's(parent id) from the case Contracts and get required fields, also create a 
                   //		 map of key as caseId and list of case Contracts as values. 
                   Set<id> caseIds = new Set<id>();
                   Map<Id,CaseContracts__c> newMapCaseContracts = (Map<Id,CaseContracts__c>) tp.newMap;
                   Map<Id,CaseContracts__c> oldMapCaseContracts = (Map<Id,CaseContracts__c>) tp.oldMap;
                   Map<Id,CaseContracts__c> mapCaseContracts = newMapCaseContracts;
                   if(tp.tEvent == TriggerParameters.TriggerEvent.afterDelete) {
                       mapCaseContracts = oldMapCaseContracts;
                   }
                   for(CaseContracts__c caseContracts : mapCaseContracts.values()) {
                       CaseContracts__c oldCaseContract = new CaseContracts__c();
                       if(tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate) {
                           oldCaseContract = oldMapCaseContracts.get(caseContracts.id);
                       } 
                       if(caseContracts.Contract__c != oldCaseContract.Contract__c) {
                           caseIds.add(caseContracts.Case__c);
                       }
                   }
                   System.debug('Get Cases for updation:'+caseIds);
                   List<Case> caseList = [select id, ContractProductList__c, Revenue__c,
                                          (select id, Contract__c, Revenue__c from CaseContracts__r) 
                                          from case where id in :caseIds ];
                   //2. Collect all the contracts from the case object and get the product names. Create a map.
                   Set<id> ContractsIds = new Set<id>();
                   for(case cas : caseList) {
                       for(CaseContracts__c caseContracts : cas.CaseContracts__r) {
                           ContractsIds.add(caseContracts.Contract__c);
                       }
                   }
                   List<Contract> ContractsList = [SELECT Id, (Select Product__r.Name From Contract_Line_Items__r) 
                                                   FROM Contract WHERE Id in :ContractsIds];
                   System.debug('Got Contracts and product map'+ContractsList);
                   Map<id,List<String>> ContractsProductMap = new Map<Id,List<String>>();
                   System.debug('Before actual logic begins');
                   for(Contract contract:ContractsList) {
                       List<String> productNames = new List<String>();
                       for(ContractLineItem__c cli:contract.Contract_Line_Items__r) {
                           productNames.add(cli.Product__r.Name);
                       }
                       ContractsProductMap.put(contract.id, productNames);
                   }
                   //3. Loop through each case object and each case Contracts object, and calculate revenue, product text.
                   for(case cas : caseList) {
                       Decimal revenue = 0;
                       //If a product is available in more than one contract line item then set will remove the duplicate name.
                       Set<String> productNameSet = new Set<String>();
                       for(CaseContracts__c caseContracts : cas.CaseContracts__r) {
                           revenue+=caseContracts.Revenue__c;
                           if(ContractsProductMap.containsKey(caseContracts.Contract__c)) {
                               productNameSet.addAll(ContractsProductMap.get(caseContracts.Contract__c));
                           }
                       }
                       cas.Revenue__c = revenue;
                       cas.ContractProductList__c = String.join(new List<String>(productNameSet), ',');
                   }
                   System.debug('Before update of cases:'+caseList);
                   //4. Update case 
                   update caseList;
               }
        } catch (Exception e) {
            UtilityClass.createApexLogRecord(e,'CaseContractsMethods','updateRollupSummariesInCase');
        }
    }

    /** 
    * @author: Vishnu vardhan Chowdary Andra
    * @date: 25 September 2017
    * @description: SFDC1-593. When a CaseContracts object is created/updated verify that same case and 
	* 		Contract record is not there in database. If exists then dont allow the insert.
    * @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got created.
    * @companyname: VERTIBA
    * @return: void
    * 
    * @author: Vishnu vardhan Chowdary Andra
    * @date: 3 November 2017
    * @description: SFDC1-593. Updating try catch block
    */
    public static void validateIfCaseContractAlreadyExist(TriggerParameters tp) {
        try {
            if(tp.tEvent == TriggerParameters.TriggerEvent.beforeInsert ||
               tp.tEvent == TriggerParameters.TriggerEvent.beforeUpdate) {
                   //1. Collect all the caseId's(parent id) from the case Contract and get records from database
                   Set<id> caseIds = new Set<id>();
                   List<CaseContracts__c> listCaseContracts = (List<CaseContracts__c>) tp.newList;
                   
                   for(CaseContracts__c caseContract : listCaseContracts) {
                       caseIds.add(caseContract.Case__c);
                   }
                   System.debug('Get Cases for verification:'+caseIds);
                   Map<id,List<CaseContracts__c>> existingCaseContractMap = new Map<id, List<CaseContracts__c>>();
                   for(CaseContracts__c caseContract : [select Case__c, Contract__C, id from 
                                                        CaseContracts__c where case__c in :caseIds]) {
                       if(!existingCaseContractMap.containsKey(caseContract.Case__c)) {
                           existingCaseContractMap.put(caseContract.Case__c, new List<CaseContracts__c>());
                       }
                       existingCaseContractMap.get(caseContract.case__c).add(caseContract);
                   }
                   System.debug('Case and Contract map:'+existingCaseContractMap);
                   //2. verify from the records if the record is already present.
                   for(CaseContracts__c caseContract : listCaseContracts) {
                       if(existingCaseContractMap.containsKey(caseContract.Case__c)) {
                           //One or more than one Contracts are there for this case.
                           List<CaseContracts__c> caseConts = existingCaseContractMap.get(caseContract.Case__c);
                           for(CaseContracts__c caseCont : caseConts) {
                               //Case Contracts should be same but id should not be same for raising error
                               if(caseCont.Contract__C == caseContract.Contract__C && 
                                  caseContract.id != caseCont.id) {
                                      caseContract.addError(System.Label.CaseContractDuplicateCheck);
                                  }
                           }
                       }
                   }
               }
        } catch (Exception e) {
            UtilityClass.createApexLogRecord(e,'CaseContractsMethods','validateIfCaseContractAlreadyExist');
        }
    } 
}