src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ClosedReason__c</fullName>
        <description>SFDC1-251 Closed reason for when the case gets closed.</description>
        <inlineHelpText>Please populate the reason for case closure.</inlineHelpText>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completeness</fullName>
                </value>
                <value>
                    <fullName>Consistency</fullName>
                </value>
                <value>
                    <fullName>Correctness</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Customer Usage Error</fullName>
                </value>
                <value>
                    <fullName>Data Republished</fullName>
                </value>
                <value>
                    <fullName>Documentation Provided</fullName>
                </value>
                <value>
                    <fullName>Documentation Updated</fullName>
                </value>
                <value>
                    <fullName>Duplicates</fullName>
                </value>
                <value>
                    <fullName>Expected Behavior</fullName>
                </value>
                <value>
                    <fullName>Fixed in New Version</fullName>
                </value>
                <value>
                    <fullName>General Question</fullName>
                </value>
                <value>
                    <fullName>Incident Resolved</fullName>
                </value>
                <value>
                    <fullName>Issue on Client Side</fullName>
                </value>
                <value>
                    <fullName>Known Issue/Bug</fullName>
                </value>
                <value>
                    <fullName>No Action Required</fullName>
                </value>
                <value>
                    <fullName>Outage Resolved</fullName>
                </value>
                <value>
                    <fullName>Permissions Updated</fullName>
                </value>
                <value>
                    <fullName>Product Limitation</fullName>
                </value>
                <value>
                    <fullName>Query Answered</fullName>
                </value>
                <value>
                    <fullName>Referred to Sales</fullName>
                </value>
                <value>
                    <fullName>Resolution Steps Provided</fullName>
                </value>
                <value>
                    <fullName>Technical Issue</fullName>
                </value>
                <value>
                    <fullName>Training Provided</fullName>
                </value>
                <value>
                    <fullName>Workaround Provided</fullName>
                </value>
                <value>
                    <fullName>Referred to Training</fullName>
                </value>
                <value>
                    <fullName>Data Corrected</fullName>
                </value>
                <value>
                    <fullName>Data Corrected.</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreviousQueue__c</fullName>
        <description>SFDC1-5943, to store the previous queue to which case was allocated to. Will be always populated via workflow.</description>
        <inlineHelpText>Updated by Salesforce if case has moved Queues</inlineHelpText>
        <label>Previous Queue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for Case Additional Fields Setup.
SFDC1-7120 Field used in filter condition is deleted. So Removing from here.</description>
        <inlineHelpText>Examples - Jane&apos;s Online - Petra - World Market Monitor</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Cases (Product Group)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResolutionDescription__c</fullName>
        <description>SFDC1-251 A long description on how the case was resolved.</description>
        <inlineHelpText>Please populate a detailed description of how the case was resolved.</inlineHelpText>
        <label>Resolution Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SkillLevel__c</fullName>
        <description>SFDC1-251 Skill level that was required for case resolution.</description>
        <label>Skill</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - General</fullName>
                </value>
                <value>
                    <fullName>2 - Technical</fullName>
                </value>
                <value>
                    <fullName>3 - Technical Expert</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>2</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>3</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestEmailMessageMethods.cls
//-------------------------------------
//@author: Sruti Srivastava
//@date: 25 June 2018
//@description: Test class to test EmailMessageMethods
//@companyname: VERTIBA
//-------------------------------------

@isTest
private class TestEmailMessageMethods {

    //-------------------------------------
    //@author: Sruti Srivastava
    //@date: 25 June 2018
    //@description: Test class to test EmailMessageMethods
    //@param: NA
    //@return: void
    ////-------------------------------------
    testmethod static void testReexecuteCaseAssignmentRulesAndCaseStatusUpdate() {
        Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        ProductGroup__c testProductgroup = TestUtility.createProductGroup('FieldDirect', true, false);
        Group queue = [Select id, name from group where type = 'Queue' and developerName = 'FMMSERV' limit 1];
        Account testAccount = TestUtility.createTestAccount('testAccount', true);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        Case cas1 = TestUtility.createCase(caseRecordTypeId, testAccount.Id, testContact.Id, 
                                           UserInfo.getUserId(), 'Case1', false);
        cas1.ProductGroup__c = testProductgroup.id;
        cas1.SkillLevel__c = '2 - Technical';
        cas1.Status = 'Waiting - Customer';
        cas1.PreviousQueue__c = queue.Name;
        Case cas2 = TestUtility.createCase(caseRecordTypeId, testAccount.Id, testContact.Id, 
                                           UserInfo.getUserId(), 'Case2', false);
        cas2.ProductGroup__c = testProductgroup.id;
        cas2.SkillLevel__c = '1 - General';
        cas2.Status='Closed - Canceled';
        cas2.ClosedReason__c = 'No Action Required';
        cas2.ResolutionDescription__c = 'test';
        cas2.PreviousQueue__c = queue.Name;
        
        Case cas3 = TestUtility.createCase(caseRecordTypeId, testAccount.Id, testContact.Id, 
                                           UserInfo.getUserId(), 'Case3', false);
        cas3.ProductGroup__c = testProductgroup.id;
        cas3.SkillLevel__c = '1 - General';
        cas3.Status='Closed - Canceled';
        cas3.ClosedReason__c = 'No Action Required';
        cas3.ResolutionDescription__c = 'test';
        
        List<case> caseList = new List<Case>();
        caseList.add(cas1);
        caseList.add(cas2);
        caseList.add(cas3);
        insert caseList;
        
		List<EmailMessage> listEmails = new List<EmailMessage>();
		listEmails.add(new EmailMessage(FromAddress = 'test@abc.org', Incoming = True, ToAddress= 'test@xyz.org', 
										Subject = 'Test email', HtmlBody = 'Test email body', ParentId = cas2.Id));
        listEmails.add(new EmailMessage(FromAddress = 'test@abc1.org', Incoming = True, ToAddress= 'test@xyz.org', 
										Subject = 'Test email', HtmlBody = 'Test email body', ParentId = cas1.Id));
        listEmails.add(new EmailMessage(FromAddress = 'test@abc2.org', Incoming = True, ToAddress= 'test@xyz.org', 
										Subject = 'Test email', HtmlBody = 'Test email body', ParentId = cas3.Id));
        Test.startTest();
        insert listEmails;
        Test.stopTest();
        
        //Verifying if status on cases have been updated 
        Map<Id,Case> updatedListCase = new Map<Id, case>([select id, ownerId, status, PreviousQueue__c from Case where status like 'In Progress' or status like 'Re-opened']);
        System.assertEquals(updatedListCase.size(), 3);
        Case testCase = updatedListCase.get(cas1.id); // Status should be inProgress
        System.assertEquals(testCase.Status, 'In Progress');
        System.assertEquals(testCase.ownerId, UserInfo.getUserId());//User shouldnt be changed
        
        //verifying if Case owner is updated as expected
        testCase = updatedListCase.get(cas3.id); // Status should be Reopened
        System.assertEquals(testCase.Status, 'Re-opened');
        System.assertNotEquals(testCase.ownerId.getsobjecttype(), User.sobjecttype);//Should not be user
        //In case this queue is used in settings as default queue in Case settings then below condition will fail.
        //So, commenting it out.
        //System.assertNotEquals(testCase.ownerId.getsobjecttype(), queue.Id);
        
        testCase = updatedListCase.get(cas2.id); // Status should be Reopened
        System.assertEquals(testCase.Status, 'Re-opened');
        System.assertEquals(testCase.ownerId, queue.Id);//Owner should be previous owner queue
	}  
}