src/objects/CaseTriageExecutionOrder__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SFDC1-7557 This custom setting will help Admins to change/ revert the order of execution of Triage records</description>
    <fields>
        <fullName>ASC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-7557 Check this checkbox if field1 needs to be sorted in ascending order, else leave unchecked.</description>
        <inlineHelpText>Check this checkbox if field1 needs to be sorted in ascending order, else leave unchecked.</inlineHelpText>
        <label>ASC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DESC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-7557 Check this checkbox if field1 needs to be sorted in descending order, else leave unchecked.</description>
        <inlineHelpText>Check this checkbox if field1 needs to be sorted in descending order, else leave unchecked.</inlineHelpText>
        <label>DESC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <description>SFDC1-7557 Enter the field API name which needs to be considered for Triage sorting</description>
        <inlineHelpText>Enter the field API name which needs to be considered for Triage sorting</inlineHelpText>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CaseTriageExecutionOrder</label>
</CustomObject>

src/objects/TriageCriteria__c.object
<CustomObject>
    <description>SFDC1-7557, This object is to store Case routing criteria and subsequent actions.</description>
    <label>Triage Criteria</label>
    <nameField>
        <displayFormat>TRC-{000000}</displayFormat>
        <label>Triage Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Triage Criteria</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/caseMethodHelperForQueries.cls
//-----------------------------
// @author: Uttam Arya
// @date: 22 June 2017
// @param: NA
// @description: Class to hold trigger methods 
// @return: NA
//-----------------------------
global class caseMethodHelperForQueries { 
//
    // @author: Prachi Bhasin
    // @date: 15 May 2018
    // @description: SFDC1-7574 method returns a query with all fields of sobject
    // @param: String - name of object
    // @return:  String
    // @companyname: Vertiba
    //
    global static List<TriageCriteria__c> allTriageList {
          get {
               if (allTriageList == null) {
                List<CaseTriageExecutionOrder__c> listSortOrderFields = new List<CaseTriageExecutionOrder__c>();
                listSortOrderFields = CaseTriageExecutionOrder__c.getall().values();
                    //Dynamic query building starts here
                    String SELECTClause = UtilityClass.queryBuilder('TriageCriteria__c');
                    String SORTINGClause ='';
                    if(!listSortOrderFields.isEmpty()) {
                        SORTINGClause =' ORDER BY ';
                        for(CaseTriageExecutionOrder__c sortObj :listSortOrderFields ) { 
                            if(sortObj.ASC__c) {
                                SORTINGClause = SORTINGClause + sortObj.Field__c +' ASC,';
                            }
                            else if(sortObj.DESC__c) {
                                SORTINGClause = SORTINGClause + sortObj.Field__c +' DESC,';
                            }
                        }
                        SORTINGClause =SORTINGClause.removeEnd(',');
                    }
                    String query = SELECTClause + SORTINGClause;
                    System.debug('query--'+query);
                    allTriageList = Database.query(query);
                    //Dynamic query building ends here  
                                  
               }
                 return allTriageList;   
               
          }
          set;
     }
}