src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for Case Additional Fields Setup.
SFDC1-7120 Field used in filter condition is deleted. So Removing from here.</description>
        <inlineHelpText>Examples - Jane&apos;s Online - Petra - World Market Monitor</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Cases (Product Group)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-200 Determines if the Contact is active or inactive</description>
        <inlineHelpText>Please select contact&apos;s status</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-5469 To set if the active/inactive status of Product Group record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VisibleInLiveChat__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5540 Check if the Product Group is visible in LiveChat.</description>
        <label>Visible in LiveChat</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LiveChatPreChatController.cls
//-----------------------------
// @author: Uttam Arya
// @date: 22 June 2017
// @param: NA
// @description: SFDC1-834, SFDC1-281 LiveChatPreChatController for Pre chat page. Remote action serach for the contact match based on supplied email
// @return: NA
// @lastModifiedBy: Vishnu
// @LastModifiedDate: 29 Mar 2018
// @LastModifiedDescription: SFDC1-7721: Internal__C=false was used in SOQL while fetching prodcut group. Since the field was created as
// 						part of Internal Case record type, and not valid any more, So deleting the field and related code.
//-----------------------------
global without sharing class LiveChatPreChatController {
    
    public String suppliedemail { get; set; }
    public static Contact contact { get; set; }
    public String selectedProduct {get; set;}
    public List<SelectOption> productFamily {get;set;}
    public Map <Id, ProductGroup__c> productGroupMap {get; set;}
    public String productIdSecuritiesFinance {get;set;}
    
    public LiveChatPreChatController() {
        
        productFamily = new List<SelectOption>();
        productFamily.add(new SelectOption('none','Choose item from the list'));
        productGroupMap = new Map <Id, ProductGroup__c>([SELECT Id, Name FROM ProductGroup__c WHERE VisibleInLiveChat__c = true AND Status__c  = 'Active' ORDER BY Name ASC NULLS LAST]);
        
        for (ProductGroup__c pg : productGroupMap.values()) {
            productFamily.add(new SelectOption(pg.Id,pg.name));
            if(pg.name == 'Securities Finance-Equity') {
                productIdSecuritiesFinance = pg.Id;
            }
        }
    } 
    
    @RemoteAction
    global static Contact getContact(String suppliedemail) {
        System.debug('@@@UA' + suppliedemail);
        Contact = [select firstname, lastname, name, email from contact where email = :suppliedemail limit 1];
        return Contact;
    }
    
    @RemoteAction
    global static String getProductId(String prodName) {
        System.debug('@@@UA' + prodName);
        ProductGroup__c prd = [select Id, name from ProductGroup__c where Name = :prodName limit 1];
        if(prd != null) {
            return prd.Id;
        } else {
            return 'none';
        }
    }
}