src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6246 Lookup to Product Family</description>
        <label>Product Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-652 Required for Case Additional Fields Setup.
SFDC1-7120 Field used in filter condition is deleted. So Removing from here.</description>
        <inlineHelpText>Examples - Jane&apos;s Online - Petra - World Market Monitor</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Cases (Product Group)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Onboarding</fullName>
        <active>true</active>
        <businessProcess>Onboarding</businessProcess>
        <description>Auto-Generated - tracks the customer onboarding process and proof of delivery attachments related to the contracting process.</description>
        <label>Onboarding</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CaseProducts__c.object
<CustomObject>
    <description>SFDC1-593 - Junction object between Case and Products</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>SFDC1-593 - Master Detail relationship to Case</description>
        <inlineHelpText>Select the Case you wish to relate to additional Products</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>CaseProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-7599: Adding product family related record</description>
        <inlineHelpText>Select a Product Family (if known). Field will be auto-completed if Product is selected.</inlineHelpText>
        <label>Product Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Case Product Families</relationshipLabel>
        <relationshipName>CaseProductFamily</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-7599: Adding product family related record</description>
        <inlineHelpText>Select a Product Group. Field will be auto-completed if Product or Product Family is selected.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Case Product Groups</relationshipLabel>
        <relationshipName>CaseProductGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-593 - Lookup to Product</description>
        <inlineHelpText>Select a Product (if known).</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>CaseProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Products</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-9301 : Fetching value from  Product Family on Opportunity</description>
        <inlineHelpText>Value coming from Product Family on Opportunity</inlineHelpText>
        <label>Product Family</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related product line items from opportunity at Contract record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-718;Look up field for Product on Contract Line</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Family__c.object
<CustomObject>
    <description>SFDC1-131: This object holds Family related to Products</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-7599 -Response Management - Missing Related Product Famliy</description>
        <inlineHelpText>Please select Case.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Product Families</relationshipLabel>
        <relationshipName>ProductFamilies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipName>Families</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Reporting Product Family</inlineHelpText>
        <label>Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsFamily</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestCaseProductsMethods.cls
/**
* @author: Vishnu vardhan Chowdary Andra
* @date: 29 August 2017
* @description: Class to test CaseProductsMethods.
* @companyname: VERTIBA
*/
@isTest
private class TestCaseProductsMethods {

    /**
     * @author: Vishnu vardhan Chowdary Andra
     * @date: 26 September 2017
     * @description: Helper method to insert case Product objects, adding product group and family as parameters
     * @companyname: VERTIBA 
     */ 
    private static CaseProducts__c createCaseProducts(id caseId, id ProductId, id productFamily, id productgroup) {

            CaseProducts__c testCaseProducts = new CaseProducts__c();
            testCaseProducts.Case__c = caseId;
            testCaseProducts.Product__c = ProductId;
            testCaseProducts.ProductFamily__c = productFamily;
            testCaseProducts.ProductGroup__c = productgroup;
            insert testCaseProducts;
            return testCaseProducts;
    }
    
    /**
     * @author: Vishnu vardhan Chowdary Andra
     * @date: 25 September 2017
     * @description: This method tests the ValidateIfCaseProductAlreadyExist by creating/updating Case Contract objects.
     * @companyname: VERTIBA 
     * @lastmodifiedSprint : Sprint 9
     */ 
    @isTest
    private static void testValidateIfCaseProductAlreadyExist() {
        //Create test data
        Product2 testProd1 = TestUtility.createProduct('Test Product', true);
        Product2 testProd2 = TestUtility.createProduct('Product Test', true);
        Account testAccount = TestUtility.createTestAccount('testAccount', true);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        
        Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
        Case testCase = new Case();
        testCase.RecordTypeId = caseRecordTypeId;
        testCase.subject = 'Test subject';
        testCase.AccountId = testAccount.Id;
        testCase.contactId = testContact.Id;
        insert testCase;

        Test.startTest();
        //Creating case Product, record to be inserted successfully
        CaseProducts__c testCaseProducts1 = createCaseProducts(testCase.id,testProd1.id, null, null);
        System.assertNotEquals(null,testCaseProducts1.id); 
        
        //Adding second case Product, record to be inserted successfully 
        CaseProducts__c testCaseProducts2 = createCaseProducts(testCase.id,testProd2.id, null, null);
        System.assertNotEquals(null,testCaseProducts2.id); 
        
        //Add same case again, it should fail, Exception is caught and returned null.
        try {
            testCaseProducts1 = createCaseProducts(testCase.id,testProd1.id, null, null);
        } catch (Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.CaseProductDuplicateCheck) ? true : false;
            // Assert to check correct Error is thrown
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        //Modifying Product with different Product
        testCaseProducts2.Product__c = testProd1.id;
        try {
            update testCaseProducts2;
        } catch (Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.CaseProductDuplicateCheck) ? true : false;
            // Assert to check correct Error is thrown
            System.AssertEquals(expectedExceptionThrown, true);
        }
        Test.stopTest();
    }

    //-----------------------------------------
    // @author: Vishnu vardhan Chowdary Andra
    // @date: 24 April 2018
    // @description: Testing the mandatory product related fields and auto population 
    // @companyname: VERTIBA 
    //-----------------------------------------   
    @isTest
    private static void testValidateAndAutoPopulateProductValues() {
        //Create test data
        List<ProductGroup__C> pgList = new List<ProductGroup__c>();
        ProductGroup__C pg1 = new ProductGroup__C(name = 'Test PG1');
        ProductGroup__C pg2 = new ProductGroup__C(name = 'Test PG2');
        pgList.add(pg1);
        pgList.add(pg2);
        insert pgList;
        Family__C pf = new Family__c(ProductGroup__C = pgList.get(0).id);
        insert pf;
        
        Product2 testProd1 = TestUtility.createProduct('Test Product', false);
        testProd1.ProductGroup__C = pgList.get(0).id;
        testProd1.Family__c = pf.id;
        insert testProd1;
        
        Account testAccount = TestUtility.createTestAccount('testAccount', true);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        
        Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
        Case testCase = new Case();
        testCase.RecordTypeId = caseRecordTypeId;
        testCase.subject = 'Test subject';
        testCase.AccountId = testAccount.Id;
        testCase.contactId = testContact.Id;
        insert testCase;

        Test.startTest();
        CaseProducts__c testCaseProducts1 = null;
        try {
            testCaseProducts1 = createCaseProducts(testCase.id,null, null, null);
        } catch (Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.CaseProductMandatoryCheck) ? true : false;
            // Assert to check correct Error is thrown
            System.AssertEquals(expectedExceptionThrown, true);
        }
        //sending product group wrongly, so pg will be replaced with correct one and even the PF will be updated
        testCaseProducts1 = createCaseProducts(testCase.id,testProd1.id, null, pgList.get(1).id);
        System.assertNotEquals(null,testCaseProducts1.id); 
        testCaseProducts1 = [select id, productGroup__c, ProductFamily__c, product__C from 
                             caseProducts__C where id =: testCaseProducts1.id];
        System.assertEquals(testCaseProducts1.product__C,testProd1.id); 
        System.assertEquals(testCaseProducts1.productGroup__c,pgList.get(0).id); 
        System.assertEquals(testCaseProducts1.ProductFamily__c,pf.id); 
        
        Test.stopTest();
    }
    
    //-----------------------------------------
    // @author: Vishnu vardhan Chowdary Andra
    // @date: 26 June 2018
    // @description: Earlier the duplicate check was done only on products. If there are more than one case product, with
    // 				Null as product then system was throwing error. Fixed it and this test class is to test it.
    // @companyname: VERTIBA 
    //-----------------------------------------   
    @isTest
    private static void testProductsCanBeEmpty() {
        //Create test data
        List<ProductGroup__C> pgList = new List<ProductGroup__c>();
        ProductGroup__C pg1 = new ProductGroup__C(name = 'Test PG1');
        ProductGroup__C pg2 = new ProductGroup__C(name = 'Test PG2');
        pgList.add(pg1);
        pgList.add(pg2);
        insert pgList;
        
        Account testAccount = TestUtility.createTestAccount('testAccount', true);
        Contact testContact = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test', 'Contact');
        
        Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
        Case testCase = new Case();
        testCase.RecordTypeId = caseRecordTypeId;
        testCase.subject = 'Test subject';
        testCase.AccountId = testAccount.Id;
        testCase.contactId = testContact.Id;
        insert testCase;

        Test.startTest();
        System.assertNotEquals(null,createCaseProducts(testCase.id, null, null, pgList.get(1).id)); 
        System.assertNotEquals(null,createCaseProducts(testCase.id, null, null, pgList.get(0).id)); 
        try {
            createCaseProducts(testCase.id, null, null, pgList.get(1).id);
        } catch (Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.CaseProductDuplicateCheck) ? true : false;
            // Assert to check correct Error is thrown
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        List<CaseProducts__c> caseProductsList = [select id from caseProducts__C where Case__c =: testCase.id];
        System.assertEquals(2, caseProductsList.size());
        Test.stopTest();
    }
}