src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-88 This field represents SAP Contract Number(s)</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POAttached__c</fullName>
        <formula>TEXT(Contract__r.POAttached__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PO Attached</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>POAttached__c</fullName>
        <description>SFDC1-8559 : PO Attached field for OM on the Contract</description>
        <inlineHelpText>Gives information on whether a user has attached the PO to  Contract.</inlineHelpText>
        <label>PO Attached</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-662 to define what kind of attachment users are adding to a Contract
SFDC1-7080: Updating Attachment Type picklist field on the Contract Attachments object,</description>
        <inlineHelpText>Please select the kind of attachment you are adding to a Contract</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Certificate of Purge</fullName>
                </value>
                <value>
                    <fullName>Client Signed Contract</fullName>
                </value>
                <value>
                    <fullName>Client Usage Reports</fullName>
                </value>
                <value>
                    <fullName>Contribution Addendum</fullName>
                </value>
                <value>
                    <fullName>Contribution Schedule</fullName>
                </value>
                <value>
                    <fullName>Countersigned Contract</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Fee Waiver</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Amended Annex Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Fee Letter</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Super Access Coordinators Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Supplemental Agreement Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User/Broker Terms</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User Agreement / Key Contacts</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Notice of Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Novation Letter</fullName>
                </value>
                <value>
                    <fullName>Online Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price Increase Letter</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Sales RAD Approval Form</fullName>
                </value>
                <value>
                    <fullName>Signed Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Signed Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Signed NDA</fullName>
                </value>
                <value>
                    <fullName>Signed Trial</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt Certificate</fullName>
                </value>
                <value>
                    <fullName>Termination Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-662 Contract to which this contact attachment is associated</description>
        <inlineHelpText>Please select the contract to which this contact attachment is associated</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>ContractAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContractAttachmentMethods.cls
/**
* @author: Ankita Singh
* @date: 18 June 2018
* @description: SFDC1-8559. After insert and After delete dispatcher event handler class that calls the functions in ContractAttachmentMethods.
* @companyname: VERTIBA
*/

public class ContractAttachmentMethods {
    
    //-----------------------------
    // @author: Ankita Singh
    // @date: 18 June 2018
    // @description: SFDC1-8559- Once the salesperson attaches the PO in custom attachments - and chooses the type 
    // 				"Purchase Order" then a trigger will update  yes/no on field called "PO Attached" on the Contract and OM case
    // @param: TriggerParameters Contains the trigger parameters which includes the record(s) that got updated.
    // @companyname: VERTIBA
    //-----------------------------
    public static void updateFieldOnContract(TriggerParameters tp) {     
        if(tp.tEvent == TriggerParameters.TriggerEvent.afterInsert) {            
            try {
                Set<Id> contractIds = new Set<Id>();
                Boolean isChanged = FALSE;
                List<Contract> contractList = new List<Contract>();
                for(ContractAttachment__c c :(List<ContractAttachment__c>) tp.newList) {
                    if(c.AttachmentType__c == 'Purchase Order') {
                        // collecting associated contract id
                        contractIds.add(c.Contract__c); 
                    }
                }
                if(contractIds != null && contractIds.size() > 0) {
                    // fetching contract PO Attached Info for newly added attachment
                    Map<Id,Contract> contractMap = new Map<Id,Contract>([Select Id,POAttached__c from Contract where Id In:contractIds AND recordtype.Name='Order Form' AND POAttached__c !='Yes']);
                    if(contractMap != null && contractMap.size() > 0) {
                        for(Id c : contractMap.keySet()) {
                            // setting PO Attached to Yes since they have new attachment added
                            contractMap.get(c).POAttached__c = 'Yes';
                            isChanged = TRUE;       
                        }
                        if(isChanged == TRUE) {
                            update contractMap.values();    
                        }
                    }
                }   
            } catch (Exception e) {
                UtilityClass.createApexLogRecord(e,'ContractAttachmentMethods','updateFieldOnContract'); 
            }     
        }
        if(tp.tEvent == TriggerParameters.TriggerEvent.afterDelete) {   
            try {
                Set<Id> contractIds = new Set<Id>();
                Map<Id,ContractAttachment__c> mapOldContract =  (Map<Id,ContractAttachment__c>)tp.oldMap;
                List<Contract> contractList = new List<Contract>();
                for(ContractAttachment__c c : mapOldContract.values()) {
                    if(c.AttachmentType__c == 'Purchase Order') {
                        // collecting associated contract id
                        contractIds.add(c.Contract__c); 
                    }
                }
                if(contractIds != null && contractIds.size() > 0) {
                    // fetching contract PO Attached Info for deleted attachment
                    List<Contract> contractAttachmentList = [Select Id,POAttached__c,(Select Id from ContractAttachments__r where AttachmentType__c = 'Purchase Order' ) from Contract where Id In:contractIds AND recordtype.Name='Order Form'];
                    if(contractAttachmentList != null && contractAttachmentList.size() > 0) {
                        for(Contract c : contractAttachmentList) {
                            if(c.ContractAttachments__r == null || c.ContractAttachments__r.size() == 0) {
                                // updating the field PO Attachment to no since they dont have any assciated attachment
                                c.POAttached__c = 'No';
                                contractList.add(c);
                            }
                        }
                        if(contractList != null && contractList.size()>0) {
                            update contractList;
                        }
                    }
                }   
            } catch (Exception e) {
                UtilityClass.createApexLogRecord(e,'ContractAttachmentMethods','updateFieldOnContract'); 
            }     
        } 
        
    }
}