src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>OIDTicket__c</fullName>
        <description>SFDC1-1351: Field to store service now ticket number
SFDC1-4998: Rename of field label OID Ticket # to INC Ticket</description>
        <inlineHelpText>Enter ServiceNow ticket number for the related Outage Incident (INC0123456)</inlineHelpText>
        <label>INC Ticket</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Onboarding</fullName>
        <active>true</active>
        <businessProcess>Onboarding</businessProcess>
        <description>Auto-Generated - tracks the customer onboarding process and proof of delivery attachments related to the contracting process.</description>
        <label>Onboarding</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SurveyResponse__c.object
<CustomObject>
    <description>SFDC1-254: Customer Care - Survey Response Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-6010: account id of responded</description>
        <inlineHelpText>Account related to the Survey Response.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CESScore__c</fullName>
        <description>SFDC1-6010: Carlos&apos; team to calculate and present as a whole number</description>
        <inlineHelpText>Calculated Customer Engagement Score.  This score is provided by the survey team on a scale from 0-7.</inlineHelpText>
        <label>CES Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-254: contactid of responded</description>
        <inlineHelpText>Contact related to the Survey Response.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponseDate__c</fullName>
        <description>SFDC1-254: Date on which survey was taken</description>
        <inlineHelpText>Date the survey response was received</inlineHelpText>
        <label>Response Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SurveyType__c</fullName>
        <description>SFDC1-254: describes if the survey response is Customer Care,Training or Customer First</description>
        <inlineHelpText>Identifies the type of Survey that was sent to the Contact.</inlineHelpText>
        <label>Survey Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Care</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Customer First</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestSurveyRatingController.cls
//-----------------------------
// @author: Ankita Singh
// @date: 20 Feb 2018
// @param: NA
// @description: Test class for SurveyRatingController 
// @return: NA
//-----------------------------
@isTest
public class TestSurveyRatingController {
    //-----------------------------
    // @author: Ankita Singh
    // @date: 20 Feb 2018
    // @param: NA
    // @description: Test method for SurveyRatingController WITH CE Score 
    // @return: NA
    //-----------------------------
    
   private static testMethod void testCEScore() {
       Account testAccount = TestUtility.createTestAccount('testAccount', true);
       Contact testContact1 = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        false, 'Test1', 'Contact1');
       Contact testContact2 = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        false, 'Test2', 'Contact2');
       List<Contact> conList = new List<Contact>();
       conList.add(testContact2);
       conList.add(testContact1);
       insert conList;
       
       Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
       List<case> caseList = new List<case>();
       Case testCase = new Case();
       testCase.RecordTypeId = caseRecordTypeId;
       testCase.subject = 'Test subject CE SCORE';
       testCase.AccountId = testAccount.Id;
       testCase.contactId = testContact1.Id;
       caseList.add(testCase);
       
       Case testCase2 = new Case();
       testCase2.RecordTypeId = caseRecordTypeId;
       testCase2.subject = 'Test subject CE SCORE INC';
       testCase2.AccountId = testAccount.Id;
       testCase2.contactId = testContact1.Id;
       testCase2.OIDTicket__c ='INC1234567';
       caseList.add(testCase2);
       
       insert caseList;
       
       List<SurveyResponse__c> srList = new List<SurveyResponse__c>();
       SurveyResponse__c sr1 = new SurveyResponse__c();
       sr1.SurveyType__c = 'Customer Care';
       sr1.ResponseDate__c= System.today();
       sr1.Account__c = testAccount.id;
       sr1.Contact__c = testContact1.id;
       sr1.CESScore__c= 2;
       
       SurveyResponse__c sr2 = new SurveyResponse__c();
       sr2.SurveyType__c = 'Customer Care';
       sr2.ResponseDate__c= System.today();
       sr2.Account__c = testAccount.id;
       sr2.Contact__c = testContact2.id;
       sr2.CESScore__c =6;
       srList.add(sr1);
       srList.add(sr2);
       insert srList;
       
       SurveyResponse__c sr3 = SurveyRatingController.getContactScore(testCase.id);
       System.assertEquals(sr3.CESScore__c,sr1.CESScore__c);
       SurveyRatingController.AccountScoreWrapper ces = SurveyRatingController.getAccountScore(testCase.Id); 
       System.assertEquals(4,ces.avgscore);
       Case c = SurveyRatingController.getLastIncidentTicket(testCase.Id); 
       System.assertEquals('INC1234567',c.OIDTicket__c);
   }
   
   //-----------------------------
    // @author: Ankita Singh
    // @date: 20 Feb 2018
    // @param: NA
    // @description: Test method for SurveyRatingController Without CE Score
    // @return: NA
    //-----------------------------
   private static testMethod void testCEScoreWithNullScore() {
       Account testAccount = TestUtility.createTestAccount('testAccount', true);
       Contact testContact1 = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test1', 'Contact1');
       
       Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
       Case testCase = new Case();
       testCase.RecordTypeId = caseRecordTypeId;
       testCase.subject = 'Test subject CE SCORE';
       testCase.AccountId = testAccount.Id;
       testCase.contactId = testContact1.Id;
       insert testCase;
       
       SurveyResponse__c sr3 = SurveyRatingController.getContactScore(testCase.id);
       System.assertEquals(null,sr3);
       SurveyRatingController.AccountScoreWrapper ces = SurveyRatingController.getAccountScore(testCase.Id);
       System.assertEquals(0.0,ces.avgscore);
		
       
   }
    
    //-----------------------------
    // @author: Ankita Singh
    // @date: 26 Feb 2018
    // @param: NA
    // @description: Test method for SurveyRatingController Without Account
    // @return: NA
    //-----------------------------
   private static testMethod void testCEScoreWithNullAccount() {
       
       Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
       Case testCase = new Case();
       testCase.RecordTypeId = caseRecordTypeId;
       testCase.subject = 'Test subject CE SCORE';
      // testCase.contactId = testContact1.Id;
       insert testCase;
       
       SurveyResponse__c sr3 = SurveyRatingController.getContactScore(testCase.id);
       System.assertEquals(null,sr3);
       SurveyRatingController.AccountScoreWrapper ces = SurveyRatingController.getAccountScore(testCase.Id);
       System.assertEquals(0.0,ces.avgscore);
       Case c = SurveyRatingController.getLastIncidentTicket(testCase.Id);
       System.assertEquals(null,c);
		
       
   }
    
       //-----------------------------
    // @author: Ankita Singh
    // @date: 28 Feb 2018
    // @param: NA
    // @description: Test method for SurveyRatingController Without INC Ticket
    // @return: NA
    //-----------------------------
   private static testMethod void testCEScoreWithNullTicket() {
       Account testAccount = TestUtility.createTestAccount('testAccount', true);
       Contact testContact1 = TestUtility.createContact(testAccount.Id, 'testihsmarkit@testihsmarkit.com',
                                                        true, 'Test1', 'Contact1');
       
	   Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
       List<case> caseList = new List<case>();
       Case testCase = new Case();
       testCase.RecordTypeId = caseRecordTypeId;
       testCase.subject = 'Test subject CE SCORE';
       testCase.AccountId = testAccount.Id;
       testCase.contactId = testContact1.Id;
       caseList.add(testCase);
       
       Case testCase2 = new Case();
       testCase2.RecordTypeId = caseRecordTypeId;
       testCase2.subject = 'Test subject CE SCORE INC';
       testCase2.AccountId = testAccount.Id;
       testCase2.contactId = testContact1.Id;
       caseList.add(testCase2);
       
       insert caseList;
       
       Case c = SurveyRatingController.getLastIncidentTicket(testCase.Id);
       System.assertEquals(null,c);
		
       
   }
}