src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>OIDTicket__c</fullName>
        <description>SFDC1-1351: Field to store service now ticket number
SFDC1-4998: Rename of field label OID Ticket # to INC Ticket</description>
        <inlineHelpText>Enter ServiceNow ticket number for the related Outage Incident (INC0123456)</inlineHelpText>
        <label>INC Ticket</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SurveyResponse__c.object
<CustomObject>
    <description>SFDC1-254: Customer Care - Survey Response Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-6010: account id of responded</description>
        <inlineHelpText>Account related to the Survey Response.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-254: contactid of responded</description>
        <inlineHelpText>Contact related to the Survey Response.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>SFDC1-254: Score given for the training provided/Customer satisfcation</description>
        <inlineHelpText>Calculated Overall Score.  This score is provided by the survey team.</inlineHelpText>
        <label>Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SurveyType__c</fullName>
        <description>SFDC1-254: describes if the survey response is Customer Care,Training or Customer First</description>
        <inlineHelpText>Identifies the type of Survey that was sent to the Contact.</inlineHelpText>
        <label>Survey Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Care</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Customer First</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceCloudSurveyScoreController.cls
//-----------------------------
// @author: Uttam Arya
// @date: 14 Sept 2017
// @param: NA
// @description: SFDC1-442 Used in custom console component, provides Account and Contact average quality ratings (past 3 months) 
//                    and link  to lastest Account OID record
// @return: NA
//-----------------------------
public class ServiceCloudSurveyScoreController {
    private final Case c;
    public String accountOID {get; set;}
    public Integer accountOverallQuality {get; set;}
    public Integer customerOverallQuality {get; set;}
    
    public ServiceCloudSurveyScoreController(ApexPages.StandardController stdController) {
        accountOverallQuality = 0;
        customerOverallQuality = 0;
        this.c = (Case)stdController.getRecord();
        if(this.c.AccountId != null) {
            List<Case> tmpList = [select Id, OIDTicket__c from Case where AccountId = :this.c.AccountId and OIDTicket__c != null order by LastModifiedDate desc limit 1];
            if(!tmpList.isEmpty()) {
                accountOID = tmpList[0].OIDTicket__c;
            }
            AggregateResult[] groupedResults = [SELECT AVG(Score__c) averageScore FROM SurveyResponse__c where Account__c = :this.c.AccountId and SurveyType__c ='Customer Care' and CreatedDate = LAST_90_DAYS];
            accountOverallQuality = Integer.valueOf(groupedResults[0].get('averageScore'));
            List<SurveyResponse__c> lastcustomercase = [SELECT Score__c FROM SurveyResponse__c where Contact__c  = :this.c.ContactId and Score__c != null and SurveyType__c = 'Customer Care' order by CreatedDate limit 1];
            if(lastcustomercase != null && !lastcustomercase.isEmpty()){
                customerOverallQuality = Integer.valueOf(lastcustomercase[0].Score__c);
            }
            if(accountOverallQuality == null) {
                accountOverallQuality = 0;
            }
            
            if(customerOverallQuality == null) {
                customerOverallQuality = 0;
            }
            
        }
    }
}