src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>OIDTicket__c</fullName>
        <description>SFDC1-1351: Field to store service now ticket number
SFDC1-4998: Rename of field label OID Ticket # to INC Ticket</description>
        <inlineHelpText>Enter ServiceNow ticket number for the related Outage Incident (INC0123456)</inlineHelpText>
        <label>INC Ticket</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SurveyResponse__c.object
<CustomObject>
    <description>SFDC1-254: Customer Care - Survey Response Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-6010: account id of responded</description>
        <inlineHelpText>Account related to the Survey Response.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-254: populated and required when type is Customer Care, else null and read only</description>
        <inlineHelpText>Case related to this Survey Response.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>SFDC1-254: contactid of responded</description>
        <inlineHelpText>Contact related to the Survey Response.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>SurveyResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponseDate__c</fullName>
        <description>SFDC1-254: Date on which survey was taken</description>
        <inlineHelpText>Date the survey response was received</inlineHelpText>
        <label>Response Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>SFDC1-254: Score given for the training provided/Customer satisfcation</description>
        <inlineHelpText>Calculated Overall Score.  This score is provided by the survey team.</inlineHelpText>
        <label>Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SurveyType__c</fullName>
        <description>SFDC1-254: describes if the survey response is Customer Care,Training or Customer First</description>
        <inlineHelpText>Identifies the type of Survey that was sent to the Contact.</inlineHelpText>
        <label>Survey Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Care</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Customer First</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestServiceCloudSurveyScoreController.cls
//-----------------------------------------------------------------
// @author: Uttam Arya
// @date: 9 Sept 2017
// @param: NA
// @description: SFDC1-442 Test Class for ServiceCloudSurveyScoreController
// @return: NA
// @author: Vishnu Vardhan
// @date: 18 Dec 2017
// @description: SFDC-6010: Response date was mandatory, because of which test case was failing. 
//				So, Fixed it.
//-----------------------------------------------------------------
@isTest
public class TestServiceCloudSurveyScoreController {
    public static testMethod void test1() {
        String oid = 'INC0101200';
        // create test Account
        Account ihsMarkitAccount = TestUtility.createTestAccountWithAddress('IHS Markit', 
                                                                            '4th floor Ropemaker Place, 25 Ropemaker Street',
                                                                            'London', '', 'GB', true);
        Contact myTestContact = TestUtility.createContact(ihsMarkitAccount.Id, 'TestServiceCloudSurveyScoreController@test.com', true, 'Test', 'Contact');
        // insert an case with an oid
        Case c = new Case (AccountId = ihsMarkitAccount.id, OIDTicket__c = oid, ContactId = myTestContact.Id);
        insert c;
        
        SurveyResponse__c sc = new SurveyResponse__c(Contact__c = myTestContact.Id, 
                                                     Account__c = ihsMarkitAccount.Id, 
                                                     SurveyType__c ='Customer Care', 
                                                     Case__c = c.Id,
                                                     Score__c = 9,
                                                     ResponseDate__c=System.today());
        
        insert sc;
        
        // check that the oid is retrieved in controller
        ServiceCloudSurveyScoreController controller = new ServiceCloudSurveyScoreController(new ApexPages.StandardController(c));
        System.assertEquals(controller.accountOID, oid);
    }
}