src/objects/ChannelProgramContact__c.object
<CustomObject>
    <description>For Channel Partner Community changes.  Contacts are displayed to Channel Partner community users in the Channel Partner Community.</description>
    <fields>
        <fullName>SalesforceUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is being used in Community related changes</description>
        <inlineHelpText>Specify a Salesforce user to automatically pull the user&apos;s contact information</inlineHelpText>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ChannelProgramContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SystemFullPhotoURL__c</fullName>
        <description>Updated by Process builder using the User&apos;s Full Profile Photo URL

This field is being used in Community related changes</description>
        <label>System - Full Photo URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Channel Program Contact</label>
    <nameField>
        <displayFormat>CPC-{000}</displayFormat>
        <label>Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Program Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestChannelProgramContactMethods.cls
//-----------------------------
// @author: Mohit Modi
// @date: 18 June 2018
// @param: NA
// @description: Test Class for methods related to Channel Program Contact 
//----------------------------------

@isTest
private class TestChannelProgramContactMethods {
    
    private static testMethod void testChannelProgramContactGeneralAutomation() {
        
        list<User> listUser = new list<user>();
        listUser.add(TestUtility.createAdminUser('testeamil1@ihsmarkit.com',false));
        listUser.add(TestUtility.createAdminUser('testeamil2@ihsmarkit.com',false));
        
        insert listUser;
        
        Test.startTest();
        
            ChannelProgramContact__c Cobj = new ChannelProgramContact__c();
            Cobj.SalesforceUser__c = listUser[0].id;
            insert Cobj;
            system.assertequals([select id, FullPhotoUrl,MediumPhotoUrl, SmallPhotoUrl from user where id =: listUser[0].id][0].FullPhotoUrl,[select id, SystemFullPhotoURL__c from ChannelProgramContact__c where id =: Cobj.id][0].SystemFullPhotoURL__c );
            
            Cobj.SalesforceUser__c = listUser[1].id;
            update Cobj;
            system.assertequals([select id, FullPhotoUrl,MediumPhotoUrl, SmallPhotoUrl from user where id =: listUser[1].id][0].FullPhotoUrl,[select id, SystemFullPhotoURL__c from ChannelProgramContact__c where id =: Cobj.id][0].SystemFullPhotoURL__c );
        
        Test.stopTest();
    
    }           
    
}