src/objects/ChangeLog__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all Work Request change log data.</description>
    <fields>
        <fullName>ChangeDescription__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Change Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ChangeDocumentedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Change Documented By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Change_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmittedDateTime__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WRStatus__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>text(WorkRequestForm__r.RequestStatus__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WR Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Change Logs</relationshipLabel>
        <relationshipName>ChangeLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Log</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Change Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderRequest__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmittedDateTime__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Order Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to store all Production Team queues for the Work Request process.</description>
    <fields>
        <fullName>Queues__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Queues</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>APAC WRF</fullName>
                </value>
                <value>
                    <fullName>Australia WRF</fullName>
                </value>
                <value>
                    <fullName>Autonews</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>European WRF</fullName>
                </value>
                <value>
                    <fullName>Market Reporting - Analytics</fullName>
                </value>
                <value>
                    <fullName>Market Reporting - CAP</fullName>
                </value>
                <value>
                    <fullName>Market Reporting - Loyalty</fullName>
                </value>
                <value>
                    <fullName>Market Reporting - OEM Stat</fullName>
                </value>
                <value>
                    <fullName>MCM - Analytics</fullName>
                </value>
                <value>
                    <fullName>PolkConnect Analytics</fullName>
                </value>
                <value>
                    <fullName>PolkConnect System</fullName>
                </value>
                <value>
                    <fullName>VFACTS</fullName>
                </value>
                <value>
                    <fullName>VINtelligence - Recall</fullName>
                </value>
                <value>
                    <fullName>VINtelligence - SWS</fullName>
                </value>
                <value>
                    <fullName>Visualization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Queues</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkRequestForm__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.  Work Request Form Table</description>
    <fields>
        <fullName>FormType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Form Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobNumber__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>if( Internal__c = True, &quot;I&quot;+InternalJob__c, RIGHT( OpportunityName__r.Opportunitynum__c , 8) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Internal Job Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimarySalesContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Primary Sales Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestStatus__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequestedDueDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>This is the date the customer requested the delivery</inlineHelpText>
        <label>Customer Requested Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubmittedDateTime__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Work Request Form</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QueueViewCE.cls
//----------------------------- 
// @Author : Legacy POLK 
// @date: 11 Oct 2017 
// @description: Migrated from Legacy POLK 
// @PROGRAMMER: Anjani Shukla 
//-----------------------------
public with sharing class QueueViewCE {
    
    private queue__c q;
    private final ApexPages.StandardController controller;
    
    public QueueViewCE(ApexPages.StandardController controller) {
        this.controller = controller;
        q= (Queue__c)controller.getRecord();
        if(q.queues__c == null) { 
                q.queues__c = 'All';
        }
        System.Debug(':::::InTheConstructor');
    }
    
    public id searchID;

    public PageReference updateView() {
        if (q.Queues__c <> 'All') {
            List<Group> queues = [Select id From Group where Type='Queue' and name =: q.Queues__c LIMIT 1 ];
            
            if(queues.size() > 0) {
                searchID = queues[0].id;
            } else {
                searchID = null;
            }
        }
                System.Debug('InUpdateView:::' + q.Queues__c);
        return null;
    }
    
    public list<WorkRequestForm__C> getWRFRecords() {
                
                List<WorkRequestForm__C> wrfResults = new list<WorkRequestForm__C>();
                
                if (q.Queues__c <>  'All') {
                    if(searchID <> null)
                        wrfResults=[select id, name, ownerid, SubmittedDateTime__c, PrimarySalesContact__c, RequestedDueDate__c, RequestStatus__c,
                            JobNumber__c, FormType__c from WorkRequestForm__C where ownerid =: searchID order by SubmittedDateTime__c asc];
                }       
        
        else {
                wrfResults=[select id, name, ownerid, SubmittedDateTime__c, PrimarySalesContact__c, RequestedDueDate__c, RequestStatus__c,
                JobNumber__c, FormType__c from WorkRequestForm__C where RequestStatus__c = 'Submitted' order by SubmittedDateTime__c asc];
        }
        return wrfResults;

    }
    
    public list<changelog__c> getCLRecords(){
        list<changelog__c> clResults = new list<changelog__c>();
        if (q.Queues__c <> 'All') {
            if(searchID <> null)
                clResults = [select id, name, ownerid, changedescription__c, changedocumentedby__c, SubmittedDateTime__c,
                    workrequestform__c, status__c, wrstatus__c from changelog__c where ownerid =: searchID order by SubmittedDateTime__c ];
        }
        else {
                    clResults = [select id, name, ownerid, changedescription__c, changedocumentedby__c, SubmittedDateTime__c,
                workrequestform__c, status__c, wrstatus__c from changelog__c where status__c = 'Submitted' order by SubmittedDateTime__c ];
        }
        return clResults;
    }
    
    public list<OrderRequest__c> getORRecords(){
        list<OrderRequest__c> orResults = new list<OrderRequest__c>();
        System.Debug('QQues:::' + q.Queues__c);
        System.Debug('SID:::' + searchID);
        if (q.Queues__c <> 'All') {
            if(searchID <> null) {
                orResults = [select id, name, ownerid, SubmittedDateTime__c,
                    workrequestform__c, status__c from OrderRequest__c where ownerid =: searchID order by SubmittedDateTime__c ];
                System.Debug(':IntheIf:::Not All');
            }
        }
        else {
                orResults = [select id, name, ownerid, SubmittedDateTime__c,
                workrequestform__c, status__c from OrderRequest__c where status__c = 'Submitted' order by SubmittedDateTime__c ];
                System.Debug(':::Else');
        }
        return orResults;
    }
 
}