src/objects/ChangeLog__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all Work Request change log data.</description>
    <fields>
        <fullName>WRStatus__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>text(WorkRequestForm__r.RequestStatus__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WR Status</label>
        <type>Text</type>
    </fields>
    <label>Change Log</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Change Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChangeLogMethods.cls
//-----------------------------
// @author: Anjani Shukla
// @date: 29 Sept 2017
// @param: NA
// @description: Class to hold trigger methods 
// @return: NA
//-----------------------------
public class ChangeLogMethods {


    //-----------------------------
    // @author: Anjani Shukla
    // @date: 29 Sept 2017
    // @param: TriggerParameters tp
    // @description: Update Start Date or Negotiated Date if differs.
    // @return: None
    //------------------------------
    public static void notificationEmail(TriggerParameters tp) {
        list<changelog__c> c = (list<changelog__c>)tp.newList;    
        for(changelog__c cl : c) {
            if (cl.wrstatus__c == 'Approved') {
                c.add(cl);
        
            }
        }    

    //SendEmail.sendMail(c);
    }
}