src/objects/ChatSurvey__c.object
<CustomObject>
    <description>SFDC1-834 Capture whether to send or not live chat transcripts.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-834 Linking Chat Surveys to case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Chat Surveys</relationshipLabel>
        <relationshipName>ChatSurveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChatKey__c</fullName>
        <description>SFDC1-834 Unique key to identify and link back the chat results</description>
        <inlineHelpText>System populated field.  Unique key to identify and link back the chat results.</inlineHelpText>
        <label>ChatKey</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>SFDC1-834 Customer Email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LiveChatTranscript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Live Chat Transcript</description>
        <label>Live Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>Chat Surveys</relationshipLabel>
        <relationshipName>ChatSurveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SendTranscript__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Transcript</label>
        <type>Checkbox</type>
    </fields>
    <label>Chat Survey</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>Chat Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LiveChatTranscript.object
<CustomObject>
    <fields>
        <fullName>SendTranscript__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Transcript</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SuppliedEmail__c</fullName>
        <label>Supplied Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ChatSurveyMethods.cls
//-----------------------------
// @author: Uttam Arya
// @date: 22 June 2017
// @param: NA
// @description: SFDC1-834  Class to hold trigger methods 
// @return: NA
//-----------------------------
public class ChatSurveyMethods {
	
//-----------------------------
// @author: Uttam Arya
// @date: 22 June 2017
// @param: TriggerParameters tp
// @description: SFDC1-834 ChatSurvey__c BEFORE INSERT - called from ChatSurveyTrigger
//				 finds the transcript records(if exists) that matches the chatKey of the inserted ChatSurvey__c
//				 Note! it is feasible for ChatSurvey__c to be created before the transcript has been inserted, so we also have trigger on transcript object to search for ChatSurvey__c to cover this

// @return: None
//------------------------------
	
    public static void surveyInitiatedTranscriptSearch(TriggerParameters tp) {
    	
    	//Map<Id,ChatSurvey__c> mapChatSurveys = new Map<Id,ChatSurvey__c>();
    	//mapChatSurveys = (Map<Id,ChatSurvey__c>) tp.newMap;
        Set<Id> caseIds = new Set<Id>();
        Map<String, ChatSurvey__c> mChatKeyToSurvey = new Map<String,ChatSurvey__c>();
        
        for(ChatSurvey__c cs : (list<ChatSurvey__c>) tp.newList) {
            mChatKeyToSurvey.put(cs.ChatKey__c, cs);
            System.debug('@@@UA' + mChatKeyToSurvey);
        }
        // now find all transcripts that match the chatkey and update lookups to transcript and case record on the survey
        if(!mChatKeyToSurvey.isEmpty()) {
            for(LiveChatTranscript lct : [select id, CaseId, ChatKey from LiveChatTranscript where ChatKey IN :mChatKeyToSurvey.keySet()]) {
                mChatKeyToSurvey.get(lct.ChatKey).LiveChatTranscript__c = lct.id;
                mChatKeyToSurvey.get(lct.ChatKey).Case__c  = lct.CaseId;
                System.debug('@@@UA' + mChatKeyToSurvey);
            }
        }
    }
    
//-----------------------------
// @author: Uttam Arya
// @date: 22 June 2017
// @param: TriggerParameters tp
// @description: SFDC1-834 ChatSurvey__c AFTER INSERT, UPDATE - called from ChatSurveyTrigger
//				 if the Case field has been populated on the ChatSurvey__c then push the values up to the case
// @return: None
//------------------------------

    public static void copySurveyResultsToLiveChatTranscript(TriggerParameters tp) {
        
        Map<Id,ChatSurvey__c> mapOldSurveys = (Map<Id,ChatSurvey__c>) tp.oldMap;
        Map<Id,ChatSurvey__c> mapNewSurveys = (Map<Id,ChatSurvey__c>) tp.newMap;
        
        List<LiveChatTranscript> transcriptsToUpdate = new List<LiveChatTranscript>();
        
        for(ChatSurvey__c cs : mapNewSurveys.values()) {
            System.debug('ChatSurvey__c' + cs);
            if(cs.LiveChatTranscript__c != null && (mapOldSurveys == null || (mapOldSurveys != null && mapOldSurveys.get(cs.Id).LiveChatTranscript__c != cs.LiveChatTranscript__c))) {
                System.debug('Chat Survey' + cs.Email__c);
                if(Test.isRunningTest()) {
                    transcriptsToUpdate.add(new LiveChatTranscript(id = cs.LiveChatTranscript__c,
                                                               SendTranscript__c = cs.SendTranscript__c));
                }else{
                    transcriptsToUpdate.add(new LiveChatTranscript(id = cs.LiveChatTranscript__c,
                                                               SuppliedEmail__c = cs.Email__c,
                                                               SendTranscript__c = cs.SendTranscript__c));
                }
            }
        }

        if(!transcriptsToUpdate.isEmpty()) {
        	update transcriptsToUpdate;
        }
            
    }
}