src/objects/ChatSurvey__c.object
<CustomObject>
    <description>SFDC1-834 Capture whether to send or not live chat transcripts.</description>
    <fields>
        <fullName>ChatKey__c</fullName>
        <description>SFDC1-834 Unique key to identify and link back the chat results</description>
        <inlineHelpText>System populated field.  Unique key to identify and link back the chat results.</inlineHelpText>
        <label>ChatKey</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>SFDC1-834 Customer Email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LiveChatTranscript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Live Chat Transcript</description>
        <label>Live Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>Chat Surveys</relationshipLabel>
        <relationshipName>ChatSurveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SendTranscript__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Transcript</label>
        <type>Checkbox</type>
    </fields>
    <label>Chat Survey</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>Chat Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LiveChatTranscript.object
<CustomObject>
    <fields>
        <fullName>SendTranscript__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Transcript</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestChatSurveyMethods.cls
//-----------------------------
// @author: Uttam Arya
// @date: 22 June 2017
// @param: NA
// @description: Test class for Chat Survey methods 
// @return: NA
//-----------------------------
@isTest
public with sharing class TestChatSurveyMethods {
	//-----------------------------
    // @author: Uttam Arya
    // @date: 22 June 2017
    // @param: NA
    // @description: SFDC1-834 check that if LiveChatTranscript is already created then upon ChatSurvey__c insert with matching
    // 				chatkey the transcript lookup field on ChatSurvey__c is populated
    // 				ALSO ENSURE that ratings are copied to associated Case
    // @return: NA
    //-----------------------------
    static testMethod void testInsert() {
        String ck = 'test01072016';     
        Case c = new Case(SuppliedEmail = 'test01072016@markit.com');
        insert c;
        
        LiveChatVisitor v = new LiveChatVisitor();
        insert v;
        
        String body = 'Hello, Test Chat';

        
        LiveChatTranscript t = new LiveChatTranscript(ChatKey = ck, LiveChatVisitorId = v.Id, CaseId = c.Id, body = body);
        insert t;
        
        ChatSurvey__c cs = new ChatSurvey__c(ChatKey__c = ck,
                                                    Email__c = 'test01072016@markit.com',
                                                    SendTranscript__c = true);
        insert cs;
        
        cs = [select id, LiveChatTranscript__c from ChatSurvey__c where Id = :cs.Id];
        System.assertEquals(t.Id, cs.LiveChatTranscript__c);
    }
    
    static testMethod void testUpdate() {
        String ck = 'test01072016';     
        Case c = new Case(SuppliedEmail = 'test01072016@markit.com');
        insert c;
        
        LiveChatVisitor v = new LiveChatVisitor();
        insert v;
        
        String body = 'Hello, Test Chat';
        
        ChatSurvey__c cs = new ChatSurvey__c(ChatKey__c = ck,
                                                    Email__c = 'test01072016@markit.com',
                                                    SendTranscript__c = true);
        insert cs;
        
        LiveChatTranscript t = new LiveChatTranscript(ChatKey = ck, LiveChatVisitorId = v.Id, CaseId = c.Id, body = body);
        insert t;

        cs = [select id, LiveChatTranscript__c from ChatSurvey__c where Id = :cs.Id];
        System.assertEquals(t.Id, cs.LiveChatTranscript__c);
    }
}