src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractOwner__c</fullName>
        <description>SFDC1-8125: Used in &quot;Contract Management&quot; case lightning layout</description>
        <formula>Owner.FirstName + &apos; &apos; + Owner.LastName</formula>
        <inlineHelpText>Contract Owner</inlineHelpText>
        <label>Contract Owner</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/InternalApproval__c.object
<CustomObject>
    <description>SFDC1-6282: New custom junction object to provide many-to-many relationship between Contracts and Contacts</description>
    <fields>
        <fullName>ContractOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6282: Contract Owner</description>
        <inlineHelpText>Contract Created By</inlineHelpText>
        <label>Contract Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Internal_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-6282: Contract</description>
        <inlineHelpText>Contract Number</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Internal Approvals</relationshipLabel>
        <relationshipName>Internal_Approvals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Internal Approval</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>Internal Approval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InternalApprovalMethods.cls
//-----------------------------
// @author: Jagadesh Kumar
// @date: 06 June 2018
// @param: NA
// @description: Class to hold trigger methods 
// @return: NA
//-----------------------------
public class InternalApprovalMethods {
    //-----------------------------
    // @author: Jagadesh Kumar
    // @date: 06 June 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-8542,SFDC1-6282: Populate the Contract Owner field of the new Internal Approval record with 
    // the Owner of the Contract on which it is created and send notification.
    // @return: NA
    //------------------------------
    public static void populateContractOwner(TriggerParameters tp) {
        Set<Id> contractIds = new Set<Id>();
        if(tp.tEvent==TriggerParameters.TriggerEvent.beforeInsert) {
            for (InternalApproval__c inApproval : (List<InternalApproval__c>)tp.newList) {
                contractIds.add(inApproval.Contract__c);
            }
            if(contractIds.size() > 0) {
                Map<Id,Contract> contractUserIdMap = new Map<Id,Contract>([SELECT Id,OwnerId FROM Contract 
                                                                           WHERE Id IN : contractIds]);
                for (InternalApproval__c inApproval : (List<InternalApproval__c>)tp.newList) {
                    if(contractUserIdMap.get(inApproval.Contract__c) != null) {
                    	inApproval.ContractOwner__c = contractUserIdMap.get(inApproval.Contract__c).OwnerId;    
                    }
                }
            }
        }
    }

}