src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>MarkitGeneralAgreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2209 This field help user select Contract when General Agreement Type is  Markit General Agreement</description>
        <label>Markit General Agreement</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contracts (Markit General Agreement)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReplacementContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1357; Contract Data Model,Related with Contract</description>
        <label>Replacement Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Replaced Contracts</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContractBeingRenewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1357; Lookup field for Renewal contract. 
SFDC1-5242; Rename the Contract being Renewed field to Originating Contract
SFDC1-6627 Add a filter for this lookup so that only order form can be selected as originating contract.</description>
        <inlineHelpText>Please select a Contract</inlineHelpText>
        <label>Originating Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Order Form contracts can be added as originating contract.</errorMessage>
            <filterItems>
                <field>Contract.RecordTypeId</field>
                <operation>equals</operation>
                <value>Order Form</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UpdateActiveContractOnRenewalOpp6W.cls
/**
*@author: Hemant Shukla
*@date: 20-Oct-2017
*@description: SFDC1-5421, This class is used to update Originating contarct of Renewal Opportunity when stage changed to 6w - Renewal one
*@companyname : VERTIBA 
**/
global class UpdateActiveContractOnRenewalOpp6W {
    
    //-----------------------------
    //@author: Hemant Shukla
    //@date: 20-Oct-2017
    //@param: List of ID of the Opportunity, which will trigger this class. Will be passed from process builder 
    //@description: SFDC1-5421, This class is used to update Originating contarct of Renewal Opportunity when stage changed to 6w - Renewal one
    //@return: void
    //@companyname : VERTIBA 
    //-----------------------------
    @InvocableMethod(label='Update Originating Contract' 
                    description='update Originating contarct of Renewal Opportunity when stage changed to 6w - Renewal one') 
    global static void updateOriginatingContract(List<Id> oppIds) {
        
        //Set the process builder flag to true once its fired. Used for Test class
        GlobalConstants.hasUpdateActiveContractOnRenewalOpp6WProcessFired = true; 
        
        Id orderFormRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Order Form').getRecordTypeId();
        
        List<Contract> originatingContracts = new List<Contract>();
        
        For(Opportunity opp : [Select Id, ContractBeingRenewed__c, (Select Id from Contracts__r where RecordTypeId = :orderFormRecordTypeId limit 1) 
                             From Opportunity 
                             where Id In:oppIds]){
                                 
            if(!opp.Contracts__r.isEmpty()){
                originatingContracts.add(new Contract(Id = opp.ContractBeingRenewed__c,ReplacementContract__c = opp.Contracts__r[0].Id));               
            }     
        }
        
        try{
            update originatingContracts;
        }
        catch(Exception e){
            system.debug('----------------exception message' + e.getMessage());
        }
        
    }    

}