src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-718;Look up field for Product on Contract Line</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract End Date will feed the Contract End Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract End Date on the Opportunity will update the Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-653 Opportunity Contract Start Date will feed the Contract Start Date on Contract Object
SFDC1-7027: Updated help text</description>
        <inlineHelpText>Updates to Contract Start Date on the Opportunity will update the Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsProRated__c</fullName>
        <description>SFDC1-7082 check at the opportunity level if the underlying subscription products are pro-rated or not</description>
        <inlineHelpText>Checked if opportunity has subscription products which are pro-rated</inlineHelpText>
        <label>Is Pro-Rated?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4353 Legal entity determines the products which are available for selling for an Opportunity</description>
        <inlineHelpText>Legal Entity related to this opportunity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Gratis</fullName>
        <active>true</active>
        <businessProcess>Gratis Opportunity</businessProcess>
        <description>Opportunity with Zero Cost</description>
        <label>Gratis</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract End Date</description>
        <inlineHelpText>Updates to the Contract End Date on the Opportunity will overwrite Contract End Date on the Opportunity Product</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <description>SFDC1-7027: Date field to store Opportunity’s Contract Start Date</description>
        <inlineHelpText>Updates to the Contract Start Date on the Opportunity will overwrite Contract Start Date on the Opportunity Product</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FirstYear__c</fullName>
        <description>SFDC1-905 This fields holds the first year price for opportunity line items</description>
        <inlineHelpText>First Year Value</inlineHelpText>
        <label>First Year Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IsProRated__c</fullName>
        <description>SFDC1-7082 flag to determine if the underlying product is pro-rated or not</description>
        <inlineHelpText>Internal Flag to handle pro-ration of subscription products</inlineHelpText>
        <label>Is Pro-Rated?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ListPrice__c</fullName>
        <description>SFDC1-173 Currency Field populated with the List Price from the Price Book at when a Product is added to an Opportunity. Used in customization for Pricing and Discounting.</description>
        <inlineHelpText>First Year Price Book List Price from Product Schedules</inlineHelpText>
        <label>PriceBook List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <description>SFDC1-173 This formula field pulls in the material code from the related product.</description>
        <formula>PricebookEntry.Product2.MaterialCode__c</formula>
        <inlineHelpText>Material Code from Product Master</inlineHelpText>
        <label>Material Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/OpportunityLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to schedule opportunity products in case of multi-year opportunities</description>
    <fields>
        <fullName>InstallmentYear__c</fullName>
        <description>SFDC1-1837 Field to fetch installment year from Product Schedule</description>
        <formula>ProductSchedule__r.InstallmentYear__c</formula>
        <label>Installment Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ListPrice__c</fullName>
        <description>SFDC1-2043 List price derived from related Product schedule</description>
        <formula>TEXT(ProductSchedule__r.ListPrice__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>List Price of Product</inlineHelpText>
        <label>List Price</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 related product schedule</description>
        <label>Product Schedule</label>
        <referenceTo>ProductSchedule__c</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1843 Product related to Opportunity product schedule</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-487 Ghost status field to store status of related opportunity product</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Product Schedule</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenters__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-3837 field to establish relationship between product and it&apos;s profit center</description>
        <inlineHelpText>Reporting Profit Center</inlineHelpText>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to hold multi-year product information</description>
    <fields>
        <fullName>InstallmentYear__c</fullName>
        <description>SFDC1-2043 the year for which this Product schedule is valid</description>
        <inlineHelpText>Year for which this Product Schedule is applicable</inlineHelpText>
        <label>Installment Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-2043 mark whether the product schedule is active or not</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ListPrice__c</fullName>
        <description>SFDC1-2043 list price for the product</description>
        <inlineHelpText>List Price for the product schedule</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PricingYear__c</fullName>
        <description>SFDC1-2043 Pricing year of the product schedule</description>
        <label>Pricing Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductTerm__c</fullName>
        <description>SFDC1-2043 The term for which related Product can be scheduled</description>
        <inlineHelpText>Tenure of product schedule</inlineHelpText>
        <label>Product Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 Year</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2 Years</fullName>
                </value>
                <value>
                    <fullName>3 Years</fullName>
                </value>
                <value>
                    <fullName>4 Years</fullName>
                </value>
                <value>
                    <fullName>5 Years</fullName>
                </value>
                <value>
                    <fullName>Evergreen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 Product for which product schedule is created</description>
        <inlineHelpText>Related Product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Schedules</relationshipLabel>
        <relationshipName>ProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>SFDC1-2043 current running year of the Product schedule</description>
        <formula>&quot;Year &quot; + TEXT(VALUE(InstallmentYear__c) - VALUE( PricingYear__c ) + 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Current Year</inlineHelpText>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Product Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProfitCenter__c.object
<CustomObject>
    <description>SFDC1-3837 Object to hold data for profit centers related to a product</description>
    <fields>
        <fullName>SaleType__c</fullName>
        <description>SFDC1-6146: This field stores the Sales Type</description>
        <label>Sale Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Onetime</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductEditController.cls
//
// @Author : Paras Dhingra
// @date: 17th Aug 2017
// @description : SFDC1-2043 product selector controller for multi-year oppys
// @company : IHS Markit
// @Modified : Paras Dhingra
// @Modified Reason: SFDC1-7082 commenting out pro-ration code will be uncommented for phase 1.3 IHS release
// @Modified date: 18th Jul 2018
//
public without sharing  class ProductEditController {
    
    /**
    * @Author : Paras Dhingra
    * @date: 17th Aug 2017
    * @description : SFDC1-2043 fetch product schedules and convert into wrapper
    * @company : IHS Markit
    * @param : List<ID>
    * @return : List<ProductEditController.ProductLineItemWrapper>
    */
    public static Map<String, Decimal> mapCurrencyType = UtilityClass.mapCurrencyIsoCodeConversionRate;
    @AuraEnabled
    public static List<ProductEditController.ProductLineItemWrapper> getProductDetails(List<Id> productIds, String oppyId) {
    try {
		    List<Opportunity> oppy = [Select id, CurrencyIsoCode, CloseDate,ContractStartDate__c,RecordType.Name from Opportunity where Id=:oppyId];
		    //close date is a required field on oppy and cannot be null
		    Date pricingDate = oppy[0].CloseDate;
		    if(oppy[0].ContractStartDate__c!=null) {
		        pricingDate = oppy[0].ContractStartDate__c;
		    }
            String currentFiscalYear = [SELECT FiscalYearSettings.Name FROM Period WHERE Type = 'Year' AND StartDate <=:pricingDate AND EndDate >=:pricingDate].FiscalYearSettings.Name;
            List<Product2> lstProductsWithSchedules = [Select Id, Name ,MaterialCode__c,ProfitCenters__c,ProfitCenters__r.SaleType__c,
                                                        (SELECT Id, Name, ListPrice__c, PricingYear__c, Product__c, ProductTerm__c, 
                                                                         InstallmentYear__c, Year__c,CurrencyIsoCode FROM ProductSchedules__r where isactive__c = true
                                                                         AND PricingYear__c=:currentFiscalYear order by InstallmentYear__c,ProductTerm__c asc ) 
                                                       from Product2 where id in :productIds];
            System.debug('oppy'+oppy);
            Map<Id, Product2> mapProductsWithSchedules = new Map<Id,Product2>(lstProductsWithSchedules);
            List<ProductLineItemWrapper> lstProductLineItemWrapper = new List<ProductLineItemWrapper>();
            for(Id prodId : productIds) {
                ProductLineItemWrapper prodWrapper = new ProductLineItemWrapper();
                Product2 prod = mapProductsWithSchedules.get(prodId);
                prodWrapper.productName = prod.Name;
                prodWrapper.productId = prod.Id;
                prodWrapper.materialCode = prod.MaterialCode__c;
                prodWrapper.productType = prod.ProfitCenters__r!=null?prod.ProfitCenters__r.SaleType__c:'';
                prodWrapper.currencyCode = oppy[0].CurrencyIsoCode;
                prodWrapper.recordTypeName = oppy[0].RecordType.Name;
                prodWrapper.licenseType = '';
                prodWrapper.lstProductsSelected = new List<OpportunityLineItemScheduleWrapper>();
                prodWrapper.mapProductsAll = new Map<String, List<OpportunityLineItemScheduleWrapper>>();
                //traverse the prodschedules and prepare opportunity line items schedules
                for(ProductSchedule__c ps :prod.ProductSchedules__r) {
                    Decimal psListPrice = ps.ListPrice__c>0?ps.ListPrice__c:0.0;
                    if(ps.ListPrice__c!=null && ps.ListPrice__c>0 && ps.CurrencyIsoCode!=oppy[0].CurrencyIsoCode) {
                        psListPrice = getConvertedCurrencyRate(ps.CurrencyIsoCode,oppy[0].CurrencyIsoCode,ps.ListPrice__c);
                    }
                    
                    OpportunityLineItemScheduleWrapper wrapperObj = new OpportunityLineItemScheduleWrapper();
                    wrapperObj.installmentYear = ps.InstallmentYear__c;
                    wrapperObj.priceBookListPrice = psListPrice;
                    wrapperObj.externalListPrice = prodWrapper.recordTypeName=='Gratis'?0:psListPrice;
                    wrapperObj.discountPercent = 0.0;
                    wrapperObj.discountAmount = 0.00;
                    wrapperObj.salesPrice = prodWrapper.recordTypeName=='Gratis'?0:psListPrice;
                    wrapperObj.totalPrice= prodWrapper.recordTypeName=='Gratis'?0:psListPrice;
                    wrapperObj.productScheduleId = ps.Id;
                    //populate product term map
                    String productTerm = '';
                    productTerm= ps.ProductTerm__c!='Evergreen'?ps.ProductTerm__c.subString(0,1):ps.ProductTerm__c;
                    if(prodWrapper.mapProductsAll.containsKey(productTerm)) {
                        prodWrapper.mapProductsAll.get(productTerm).add(wrapperObj);
                    } else {
                        List<OpportunityLineItemScheduleWrapper> tempListWrapObj = new List<OpportunityLineItemScheduleWrapper>();
                        tempListWrapObj.add(wrapperObj);
                        prodWrapper.mapProductsAll.put(productTerm,tempListWrapObj);
                    }
                    
                }
                if(prodWrapper.mapProductsAll!=null && !prodWrapper.mapProductsAll.isEmpty()) {
                    prodWrapper.lstMapProductIndex = new List<String>();
                    prodWrapper.lstMapProductIndex.addAll(prodWrapper.mapProductsAll.keySet());
                    prodWrapper.lstMapProductIndex.sort();
                    prodWrapper.productTermSelected = prodWrapper.lstMapProductIndex[0];
                    prodWrapper.lstProductsSelected = prodWrapper.mapProductsAll.get(prodWrapper.productTermSelected);
                }
                
                prodWrapper.productQty = 1;
                lstProductLineItemWrapper.add(prodWrapper);
        }
            return lstProductLineItemWrapper;
            
        } catch(exception e) {
		
            List<ProductLineItemWrapper> lstProductLineItemWrapper = new List<ProductLineItemWrapper>();
            return lstProductLineItemWrapper;
        }
        
    }
    
    /**
    * @Author : Paras Dhingra
    * @date: 17th Aug 2017
    * @description : SFDC1-2043 fetch updated productSchedules and save them
    * @company : IHS Markit
    * @param : String, String, String
    * @return : String
    */
    @AuraEnabled
    public static String saveProductsOnOpportunity(String stringProductWrapper, String opportunityId, String legalEntity) {
        System.debug('--stringProductWrapper--'+ stringProductWrapper);
        List<ProductEditController.ProductLineItemWrapper> lstProductWrapper = (List<ProductEditController.ProductLineItemWrapper>)JSON.deserialize(stringProductWrapper, List<ProductEditController.ProductLineItemWrapper>.class);
        String message = '';
        System.debug('--lstProductWrapper--'+lstProductWrapper);
        System.debug('Oppy Id' + opportunityId);
        //query the Opportunity
        Opportunity oppy = [Select id, CurrencyIsoCode, LegalEntity__c, Name,IsProRated__c,ContractStartDate__c,ContractEndDate__c from Opportunity where Id=:opportunityId limit 1 ];
        System.debug('--Opportunity--'+ oppy);
        //Initialise the records to be inserted
        List<OpportunityLineItemSchedule__c> lstOpportunityProductSchedules = new List<OpportunityLineItemSchedule__c>();
        Map<Id,OpportunityLineItem> mapOpportunityProducts = new Map<Id,OpportunityLineItem>();
        Map<Integer,OpportunityLineItem> mapOppyLineItem = new Map<Integer,OpportunityLineItem>();
        Map<Integer,List<OpportunityLineItemSchedule__c>> mapOppyLineItemSchedules = new Map<Integer,List<OpportunityLineItemSchedule__c>>();
        //traverse and fetch products to query pricebookentry.
        List<Id>lstProductIds = new List<Id>();
        System.debug('--Control reached here--');
        for( Integer i=0; i<lstProductWrapper.size();i++) {
            lstProductIds.add(lstProductWrapper[i].productId);
        }
        System.debug('--lstProductIds--'+lstProductIds);
        //query pricebookentries and create a map
        List<PriceBookEntry> lstPriceBookEntries = [Select id, Product2Id from PriceBookEntry where product2Id IN:lstProductIds and isActive=true 
                                                    and Pricebook2.Name = 'Standard Price Book' and CurrencyIsoCode =:oppy.CurrencyIsoCode ];
        
        System.debug('--lstPriceBookEntries--'+ lstPriceBookEntries);
        if(lstPriceBookEntries!=null && lstPriceBookEntries.size()>0) {
            
            Map<Id,Id> mapProductPBEId = new Map<Id,Id>();
            for(PriceBookEntry pbe : lstPriceBookEntries) {
                mapProductPBEId.put(pbe.Product2Id, pbe.Id);
            }
            Integer index = 1;
            //traverse the wrapper and create OpportunityLineItem Schedule for each product schedule displayed
            for(ProductLineItemWrapper prodWrap : lstProductWrapper ) {
                
                OpportunityLineItem oli = new OpportunityLineItem();
                oli.OpportunityId = opportunityId;
                oli.PricebookEntryId = mapProductPBEId.get(prodWrap.productId);
                oli.Quantity = prodWrap.productQty;
                oli.UnitPrice = 0;
                oli.FirstYear__c = 0.0;
                oli.Status__c = 'New';//by default all products added will be set to 'New'
                oli.LicenseType__c = prodWrap.licenseType;
                
                //add a flag to determine if pro-ration needs to be done or not
                //to be uncommented for phase 1.3
                /*
                Boolean shouldProRate = false;
                if(prodWrap.productType!=null && prodWrap.productType=='Subscription' && oppy.IsProRated__c=='Yes' && oppy.ContractStartDate__c!=null && oppy.ContractEndDate__c!=null) {
                    shouldProRate = true;
                    oli.isProRated__c='Yes';
                }*/
                //process through the line item
                lstOpportunityProductSchedules = new List<OpportunityLineItemSchedule__c>();
                for(Integer i=0; i<prodWrap.lstProductsSelected.size(); i++) {
                    
                    //oli.UnitPrice = prodWrap.lstProductScheduleDisplayed[i].ListPrice__c;//sales price
                    //oli.UnitListPrice__c = prodWrap.lstProductScheduleAll[i].ListPrice__c;// list price
                    OpportunityLineItemSchedule__c olis = new OpportunityLineItemSchedule__c();
                    olis.Opportunity__c = opportunityId;
                    olis.CurrencyIsoCode = oppy.CurrencyIsoCode;
                    olis.ProductSchedule__c = prodWrap.lstProductsSelected[i].productScheduleId;
                    olis.ExternalListPrice__c = prodWrap.lstProductsSelected[i].externalListPrice;
                    olis.SalesPrice__c = prodWrap.lstProductsSelected[i].salesPrice;
                    olis.TotalPrice__c = prodWrap.lstProductsSelected[i].totalPrice;
					olis.DiscountType__c = prodWrap.discountType;
					olis.DiscountPercent__c = prodWrap.lstProductsSelected[i].discountPercent;
					olis.DiscountAmount__c = prodWrap.lstProductsSelected[i].discountAmount;
					olis.PriceBookListPrice__c = prodWrap.lstProductsSelected[i].priceBookListPrice;                    
                    olis.Product__c = prodWrap.productId;
                    olis.InstallmentYears__c =prodWrap.lstProductsSelected[i].installmentYear;
                    //olis.OpportunityProductScheduleKey__c = oppy.Name + ' - ' +  prodWrap.productName+' - ' +prodWrap.lstProductsSelected[i].InstallmentYear ;
                    olis.Quantity__c = prodWrap.productQty;
                    //olis.LicenseType__c = prodWrap.licenseType;
                    olis.Status__c = 'New';
                    //roll up values
                    //pro-rate the olis if the related product is scheduled
                    //to be uncommented for phase 1.3
                    /*
                    if(shouldProRate) {
                        olis = proRateBeforeInsert(olis, oppy, oli.Quantity);    
                    }
                    */
                    
                    lstOpportunityProductSchedules.add(olis);
                }
                mapOppyLineItem.put(index,oli);
                mapOppyLineItemSchedules.put(index,lstOpportunityProductSchedules);
                mapOpportunityProducts.put(prodWrap.productId,oli);
                index++;
            }
            Savepoint sp = Database.setSavepoint();
            try {
                if(mapOppyLineItem!=null && mapOppyLineItem.size()>0) {
                    List<OpportunityLineItemSchedule__c> listOppySchedulesToInsert = new List<OpportunityLineItemSchedule__c>();
                    insert mapOppyLineItem.values();
                    //now traverse olis and add opportunity product ids
                    for(Integer i : mapOppyLineItemSchedules.keySet()) {
                        for(OpportunityLineItemSchedule__c olis : mapOppyLineItemSchedules.get(i)) {
                            olis.OpportunityProductID__c = mapOppyLineItem.get(i).Id;
                            listOppySchedulesToInsert.add(olis);
                        }
                    }
                    insert listOppySchedulesToInsert;
                    //update legal entity on opportunity
                    if(oppy.LegalEntity__c!=legalEntity) {
                        oppy.LegalEntity__c = legalEntity;
                        update oppy;
                    }
                    
                    message = 'Records added successfully';
                }
            }catch(Exception e) {
                message = 'Error occurred while creating records :'+e.getMessage();
                Database.rollback(sp);
            }
            
        } else {
             message = 'Error occurred no pricebookentries found';
        }
       
        return message;
    }
    /**
    * @Author : Paras Dhingra
    * @date: 25th Sep 2017
    * @description : SFDC1-2043 fetch custom picklist values for licenseType
    * @company : IHS Markit
    * @param : null
    * @return : List<String>
    */
    @AuraEnabled
    public static List<String> getLicenseTypes() {
        return UtilityClass.getselectOptions(new OpportunityLineItem(), 'LicenseType__c' );
    }
    
    /**
    * @Author : Paras Dhingra
    * @date: 27th Sep 2017
    * @description : SFDC1-4353 Get converted currency for a value
    * @company : IHS Markit
    * @param : null
    * @return : Decimal
    */
     public static Decimal getConvertedCurrencyRate(String currentCurrency, String convertedCurrency, Decimal value)
        {
            
            Decimal convertedValue = value;
            if(currentCurrency != convertedCurrency && mapCurrencyType != null && !mapCurrencyType.isEmpty()) {
                if(mapCurrencyType.containsKey(currentCurrency) && mapCurrencyType.containsKey(convertedCurrency)) {				
                    convertedValue *= ((1 / mapCurrencyType.get(currentCurrency)) * (mapCurrencyType.get(convertedCurrency)));
                }
            }
        Decimal convertedValueRounded = convertedValue.setScale(2);
        System.debug('--roundedValue--'+convertedValueRounded);
        return convertedValueRounded;
    }
    //
    //@author Paras Dhingra
    //@date 30th May 2018
    //@description SFDC1-7082 Method to pro-rate schedule if the parent
    //                  opportunity is pro-rated
    //@param TriggerParameters
    //@return void
    //@companyname IHS Markit
    //
    //to be uncommented for phase 1.3
    /*
    public static OpportunityLineItemSchedule__c proRateBeforeInsert(OpportunityLineItemSchedule__c ops, Opportunity Oppy,Decimal qty) {
        //pro-rate the opportunity product scheduled is opportunity is prorate and contract start and end date are not null
        Double proRatedDays = UtilityClass.getDays360(Oppy.ContractStartDate__c, Oppy.ContractEndDate__c);
        //copy existing unit price to annualized unit price and discount
        ops.AnnualizedUnitPrice__c = ops.ExternalListPrice__c;
        ops.AnnualizedDiscountAmount__c = ops.DiscountAmount__c;
        ops.ProRatedUnitPrice__c = (ops.AnnualizedUnitPrice__c / 360) * proRatedDays;
        ops.ProRatedDiscountAmount__c = (ops.AnnualizedDiscountAmount__c / 360) * proRatedDays;
        //set precision to 2
        ops.ProRatedUnitPrice__c = ops.ProRatedUnitPrice__c.setScale(2);
        ops.ProRatedDiscountAmount__c = ops.ProRatedDiscountAmount__c.setScale(2);
        //move values from proRated to unit price
        ops.ExternalListPrice__c = ops.ProRatedUnitPrice__c;
        ops.DiscountAmount__c = ops.ProRatedDiscountAmount__c;
        ops.SalesPrice__c = (ops.ExternalListPrice__c - ops.DiscountAmount__c).setScale(2);
        ops.TotalPrice__c = (ops.SalesPrice__c * qty).setScale(2);
        return ops;
        
    }*/
    public class ProductLineItemWrapper {
        @AuraEnabled public String productName;
        @AuraEnabled public String materialCode;
        @AuraEnabled public String productId;
        @AuraEnabled public String currencyCode;
        @AuraEnabled public String recordTypeName;
        @AuraEnabled public String productTermSelected;
        @AuraEnabled public List<OpportunityLineItemScheduleWrapper> lstProductsSelected;
        @AuraEnabled public Map<String, List<OpportunityLineItemScheduleWrapper>> mapProductsAll;
        @AuraEnabled public List<String> lstMapProductIndex;
        @AuraEnabled public Integer productQty;
        @AuraEnabled public String discountType;
        @AuraEnabled public String licenseType;
        @AuraEnabled public String productType;
    }
    public class OpportunityLineItemScheduleWrapper {
        
        @AuraEnabled public Decimal priceBookListPrice;
        @AuraEnabled public Decimal externalListPrice;
        @AuraEnabled public Decimal discountPercent;
        @AuraEnabled public Decimal discountAmount;
        @AuraEnabled public Decimal salesPrice;
        @AuraEnabled public Decimal totalPrice;
        @AuraEnabled public String installmentYear;
        @AuraEnabled public String productScheduleId;
    }
    
}