src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>JobTitle__c</fullName>
        <description>Creating Job Title as of SFDC1-863; Titles have been taken from Markit QA org</description>
        <inlineHelpText>If you are unable to find a suitable job title please contact your Salesforce Administrator</inlineHelpText>
        <label>Job Title</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Assistant Vice President</fullName>
                </value>
                <value>
                    <fullName>Associate</fullName>
                </value>
                <value>
                    <fullName>CCO - Chief Compliance Officer</fullName>
                </value>
                <value>
                    <fullName>CDO - Chief Data Officer</fullName>
                </value>
                <value>
                    <fullName>CEO - Chief Executive Officer</fullName>
                </value>
                <value>
                    <fullName>CFO - Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Analyst</fullName>
                </value>
                <value>
                    <fullName>CIO - Chief Investment Officer</fullName>
                </value>
                <value>
                    <fullName>COO - Chief Operating Officer</fullName>
                </value>
                <value>
                    <fullName>CTO - Chief Technology Officer</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Executive Director</fullName>
                </value>
                <value>
                    <fullName>Executive Vice President</fullName>
                </value>
                <value>
                    <fullName>Intern</fullName>
                </value>
                <value>
                    <fullName>Managing Director</fullName>
                </value>
                <value>
                    <fullName>Portfolio Manager</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Senior Analyst</fullName>
                </value>
                <value>
                    <fullName>Senior Director</fullName>
                </value>
                <value>
                    <fullName>Senior Managing Director</fullName>
                </value>
                <value>
                    <fullName>Senior Vice President</fullName>
                </value>
                <value>
                    <fullName>Vice President</fullName>
                </value>
                <value>
                    <fullName>CRO - Chief Risk Officer</fullName>
                </value>
                <value>
                    <fullName>DirectorExecutive Director</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>InternManaging Director</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MeetingAttendee__c.object
<CustomObject>
    <description>SFDC1-863; Meeting Attendee Object to Capture details of the Attendees</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IHSMarkitEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IHS Markit Employee?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>When__c</fullName>
        <formula>MeetingNote__r.When__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>When</label>
        <type>Date</type>
    </fields>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>MAT-{000000000}</displayFormat>
        <label>Meeting Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MeetingNote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-863; Lookup to the Account</description>
        <inlineHelpText>Please Select the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Achieved__c</fullName>
        <description>SFDC1-863; Long text field for Achieved</description>
        <label>Achieved</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AttendeeNames__c</fullName>
        <inlineHelpText>Please Enter Client Attendee&apos;s Name</inlineHelpText>
        <label>Client Attendee Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Attendees</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IHSMarkitAttendeeNames__c</fullName>
        <inlineHelpText>Please Enter IHS Markit Attendee&apos;s Name</inlineHelpText>
        <label>IHS Markit Attendee Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Info__c</fullName>
        <label>Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NextSteps__c</fullName>
        <label>Next Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductFamilyLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-3843 : This field will hold the values from the Product Family field</description>
        <inlineHelpText>Please Enter the Product Family</inlineHelpText>
        <label>Product Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StateProvince__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>When__c</fullName>
        <label>When</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ZipPostalCode__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Meeting Note</label>
    <nameField>
        <label>Meeting Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Notes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-7525 product family calculated from related products
SFDC1-8785 : updating the field type to Long Text Area</description>
        <inlineHelpText>Product family of related products automatically populated by system</inlineHelpText>
        <label>Product Family</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RelatedOpportunity__c.object
<CustomObject>
    <description>SFDC1-863; Related Opportunity Object is a Junction Object between Opportunities and Meeting Note</description>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>When__c</fullName>
        <formula>MeetingNote__r.When__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>When</label>
        <type>Date</type>
    </fields>
    <label>Related Opportunity</label>
    <nameField>
        <displayFormat>RO-{000000000}</displayFormat>
        <label>Related Opportunity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateMeetingNoteEvent.cls
/**
 * @Author: Twan v.d. Loo
 * @Date: 24-09-2015
 * @Purpose: Adds meeting note to Event
 * 
 * @author Modified By: Vishnu Vardhan
 * @date: 7 Jul 2017
 * @description: Migrated class from existing Markit System and added comments. 
 * @lastModifiedBy: Prachi Bhasin for SFDC1-2017 bug fix
 * @lastModifiedSprint: Sprint 7
 * @lastModifiedBy: Mohit Modi ,10 April 2018
 * @lastmodified description : SFDC1-3843, Changing the Field Type of ProductFamily__c from Picklist to Lookup
**/
public class CreateMeetingNoteEvent {
    
    public List<cAttendee> attendeeList {get;set;}
    public List<cRelatedOpportunity> relatedOpportunitiesList {get;set;}
    
    public Integer deleteNum {get;set;}
    public Integer deleteOpp {get;set;}
    
    public string infoType {get;set;}
    public Account account {get;set;}
    public string eventId {get;set;}
    public Opportunity opportunity {get;set;}
    public MeetingNote__c meeting {get;set;}
    public Boolean displayOppySelection {get;set;}
    public Event event {get;set;}
    
    
    // OPPY RELATED
    public List<Opportunity> oppyList = new List<Opportunity>();
    public String selectedOpportunity {get;set;}
    
    public CreateMeetingNoteEvent () {
        
        meeting = new MeetingNote__c();
        infoType = System.currentPageReference().getParameters().get('infoType');        
        eventId = System.currentPageReference().getParameters().get('eventId');
        
        event = [select Id, Owner.Email, Location, StartDateTime, /*ProductFamily__c*/ ProductFamilyLookup__c, Street__c, ZipPostalCode__c, StateProvince__c, City__c, Country__c from Event where id =: eventId]; 
        
        if(event != null) {
            meeting.Street__c = event.Street__c;
            meeting.ZipPostalCode__c = event.ZipPostalCode__c;
            meeting.StateProvince__c = event.StateProvince__c;
            meeting.City__c = event.City__c;
            meeting.Country__c = event.Country__c;
            meeting.When__c = Date.valueof(event.StartDateTime);
        }
        
        if(infoType == 'accOnly') {
            account = [select id, name from Account where id =: System.currentPageReference().getParameters().get('accId')];
            meeting.Name = 'Meeting with '+account.name;
            
            oppyList = [select Id, AccountId, Account.Name, Name, RecordType.Name, StageName from Opportunity where AccountId =: account.Id and IsClosed = false LIMIT 100]; 
            
            displayOppySelection = true;            
        } else if (infoType == 'oppOnly' || infoType == 'bothFilled') {
            opportunity = [select Id, AccountId, Account.Name, Name, RecordType.Name, StageName from Opportunity where id =: System.currentPageReference().getParameters().get('oppId')];            
            meeting.Name = System.now().date().format() +': Meeting for Opportunity: '+opportunity.name;
            displayOppySelection = false;
            oppyList = [select Id, AccountId, Account.Name, Name, RecordType.Name, StageName from Opportunity where AccountId =: opportunity.AccountId and Id != :opportunity.Id and IsClosed = false LIMIT 100];
        }          
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method adds a recipient to the list.
     * @param: null
     * @return: void
     */
    public void addRow() {
        List<Contact> cList = [select Id, Name, JobTitle__c, Title, Email, Account.Name from Contact where Id =: meeting.ContactLookup__c and Account.Name != null];
        
        if(cList.size() == 1) {
            Contact c = cList[0];
            if(c.Email != null){
                if(c.Email.contains('markit.com') || c.Email.contains('markitserv.com') || c.Email.contains('ihsmarkit.com') || c.Email.contains('ihs.com')) {  
                    attendeeList.add(New cAttendee(new MeetingAttendee__c(),c,true)); 
                }else{
                    attendeeList.add(New cAttendee(new MeetingAttendee__c(),c,false));
                }
                attendeeList[attendeeList.size()-1].numberInList = attendeeList.size();            
                meeting.Contactlookup__c = null;
            }    
        }
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method adds a opportunity as related opportunity
     * @param: null
     * @return: void
     */
    public void addOppy() {
        if(meeting.Opportunity__c != null) {
            Opportunity o = [select Id, AccountId, Account.Name, Name, RecordType.Name, StageName from Opportunity where Id =: meeting.Opportunity__c];
            relatedOpportunitiesList.add(New cRelatedOpportunity(o,new RelatedOpportunity__c()));
            relatedOpportunitiesList[relatedOpportunitiesList.size()-1].numberInList = relatedOpportunitiesList.size();
            meeting.Opportunity__c = null;
        } else if(selectedOpportunity != null && selectedOpportunity != '--None--') {
            for(Opportunity o : oppyList) {
                if(o.Id == selectedOpportunity) {
                    relatedOpportunitiesList.add(New cRelatedOpportunity(o,new RelatedOpportunity__c()));
                    relatedOpportunitiesList[relatedOpportunitiesList.size()-1].numberInList = relatedOpportunitiesList.size();
                }
            }            
        }  
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method deletes a recipient from the list.
     * @param: null
     * @return: void
     */
    public void deleteRow() {
        System.debug('Now deleting number: '+deleteNum);
        System.debug('Which is Recipient: '+attendeeList[deleteNum-1]);        
        attendeeList.remove(deleteNum-1);
        
        for(cAttendee c : attendeeList) {
            if(c.numberInList >= deleteNum) {
                c.numberInList--;
            }   
        }        
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method deletes a related opportunity
     * @param: null
     * @return: void
     */
    public void deleteOppy() {
        System.debug('Now deleting number: '+deleteOpp);
        System.debug('Which is Recipient: '+relatedOpportunitiesList[deleteOpp-1]);        
        relatedOpportunitiesList.remove(deleteOpp-1);
        
        for(cRelatedOpportunity c : relatedOpportunitiesList) {
            if(c.numberInList >= deleteOpp) {
                c.numberInList--;
            }   
        }        
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method return a List of related opportunity
     * @param: null
     * @return: List<cRelatedOpportunity>
     */
    public List<cRelatedOpportunity> getRelatedOpportunities() {
        if(relatedOpportunitiesList == null) {
            relatedOpportunitiesList = new List<cRelatedOpportunity>();
            if(opportunity != null) {
                relatedOpportunitiesList.add(New cRelatedOpportunity(opportunity,new RelatedOpportunity__c()));
                relatedOpportunitiesList[relatedOpportunitiesList.size()-1].numberInList = relatedOpportunitiesList.size();
            }
        }
        return relatedOpportunitiesList;
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method return a List of recipients for a given event
     * @param: null
     * @return: List<cAttendee>
     */
    public List<cAttendee> getAttendees() {
        Set<Id> contactIdSet = new Set<Id>();
        if(attendeeList == null) {
            attendeeList = new List<cAttendee>();
            
            // get all contacts from a meeting
            for(EventRelation er : [select RelationId, EventId, Relation.FirstName, Relation.LastName, Relation.Email from EventRelation where IsWhat = false and EventId =: eventId]) {
                contactIdSet.add(er.RelationId);
            }
            
            List<Contact> currentUserContactList = [select Id, Name, JobTitle__c, Title, Email from Contact where Email =: event.Owner.Email];
            
            if(currentUserContactList.size() == 1) {
                attendeeList.add(New cAttendee(new MeetingAttendee__c(),currentUserContactList[0],true));
                attendeeList[attendeeList.size()-1].numberInList = attendeeList.size();
            }
            
            for(Contact c : [select Id, Name, JobTitle__c, Title, Email, Account.Name from Contact where Id IN: contactIdSet and Account.Name != null]) {
                System.debug(c);
                System.debug(attendeeList.size());
                if(attendeeList.size() == 1) {                    
                    if(c.Id != attendeeList[0].contact.Id) {
                        if(c.Email != null) {
                            if(c.Email.contains('markit.com') || c.Email.contains('markitserv.com') || c.Email.contains('ihsmarkit.com') || c.Email.contains('ihs.com')){
                                attendeeList.add(New cAttendee(new MeetingAttendee__c(),c,true));
                            } else {
                                attendeeList.add(New cAttendee(new MeetingAttendee__c(),c,false));
                            }
                                attendeeList[attendeeList.size()-1].numberInList = attendeeList.size();     
                        }
                                               
                    }
                } else {
                    if(c.Email != null) {
                        if(c.Email.contains('markit.com') || c.Email.contains('markitserv.com')) {
                            attendeeList.add(New cAttendee(new MeetingAttendee__c(),c,true));
                        } else {
                                attendeeList.add(New cAttendee(new MeetingAttendee__c(),c,false));
                        }
                        attendeeList[attendeeList.size()-1].numberInList = attendeeList.size();
                    }
                }                
            }
        }
        return attendeeList;
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method adds a newly created meeting.
     * @param: null
     * @return: PageReference
     */
    public PageReference save() {
        if (meeting.Achieved__c == null || meeting.Info__c == null || meeting.NextSteps__c == null) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please populate mandatory fields'));
                return null;
        }        
        // SAVE OPPY IN MEETING               
        if(infoType == 'oppOnly' || infoType == 'bothFilled') {
            meeting.Account__c = opportunity.AccountId;
            meeting.Opportunity__c =opportunity.Id;
        } else {
            meeting.Account__c = account.Id;
        }
        
        /* if(event.ProductFamily__c != null) {
            meeting.ProductFamily__c= event.ProductFamily__c;
        } */
        if(event.ProductFamilyLookup__c != null) {
            meeting.ProductFamilyLookup__c= event.ProductFamilyLookup__c;
        }
        insert meeting;
        
        // SAVE EVENT AS RELATED EVENT
        event.MeetingNote__c = meeting.Id;
        update event;
        
        List<MeetingAttendee__c> maList = new List<MeetingAttendee__c>();
        List<RelatedOpportunity__c> roList = new List<RelatedOpportunity__c>();
        
        meeting.IHSMarkitAttendeeNames__c = '';
        meeting.AttendeeNames__c = '';
        
        // SAVE RELATED OPPORTUNITIES
        for(cRelatedOpportunity ro : relatedOpportunitiesList) {
            ro.relatedOppy.MeetingNote__c = meeting.Id;
            ro.relatedOppy.Opportunity__c = ro.oppy.Id;
            roList.add(ro.relatedOppy);
        }
        
        
        for(cAttendee c : attendeeList) {
            c.attendee.MeetingNote__c = meeting.Id;
            maList.add(c.attendee);
            if(c.attendee.IHSMarkitEmployee__c) {
                meeting.IHSMarkitAttendeeNames__c += c.contact.Name + ' ('+c.contact.Title+'), ';
            } else {
                meeting.AttendeeNames__c += c.contact.Name + ' ('+c.contact.Title+'), ';
            }
        }
        
        insert maList;
        insert roList;
        update meeting;
        
        PageReference pRef = new PageReference('/' + meeting.Id);
        return pRef.setRedirect(true);
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: Removes all attendees from the meeting
     * @param: null
     * @return: void
     */
    public void clearList() {
        attendeeList.clear();
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: This method is called when cancelled button is clicked on the page.
     * @param: null
     * @return: pageReference
     */
    public pageReference cancel() {
        PageReference pRef = new PageReference('/'+eventId);
        return pRef.setRedirect(true);
    }
    
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: Returns list of opportunities available for account
     * @param: null
     * @return: List<SelectOption>
     */
    public List<SelectOption> getOpportunities() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('--None--', '--None--'));
        for(Opportunity o : oppyList) {
            options.add(new SelectOption(o.Id,o.Name));
        }        
        return options;
    }
    
    /**
     * @author Modified By: Vinod Merwade
     * @description Wrapper class
     * @date 7th Jul 2017
     */
    public class cRelatedOpportunity {
        public Opportunity oppy {get;set;}
        public RelatedOpportunity__c relatedOppy {get;set;}
        public Integer numberInList {get;set;}
        
        public cRelatedOpportunity(Opportunity o, RelatedOpportunity__c ro) {
            oppy = o;
            relatedOppy = ro;
        }
    }
    
    /**
     * @author Modified By: Vinod Merwade
     * @description Wrapper class
     * @date 7th Jul 2017
     */
    public class cAttendee {
        public MeetingAttendee__c attendee {get;set;}
        public Contact contact {get;set;}
        public Integer numberInList {get;set;}
        
        public cAttendee(MeetingAttendee__c ma, Contact con, boolean employee) {
            attendee = ma;
            contact = con;
            ma.Contact__c = con.Id;
            
            if(employee) {
                attendee.IHSMarkitEmployee__c = true;
            } else {
                attendee.IHSMarkitEmployee__c = false;
            }
        }
    }
}