src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-200 Determines if the Contact is active or inactive</description>
        <inlineHelpText>Please select contact&apos;s status</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DiscountOverThreshold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4275 Checkbox to indicate if any of the products related to opportunity have crossed discount threshold</description>
        <inlineHelpText>Checked if product(s) are discounted over threshold</inlineHelpText>
        <label>Discount Over Threshold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Shows red flag if any product related to opportunity is discounted over threshold</description>
        <formula>IF( 
DiscountOverThreshold__c, 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;, 
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Red flag when one or more products discounted over threshold</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ActiveInactiveNetUnitPrice__c</fullName>
        <description>SFDC1-487 Field to hold salesprice in case opportunity product is inactive</description>
        <inlineHelpText>Sales price for Opportunity product</inlineHelpText>
        <label>Active/Inactive Net Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualizedDiscountAmount__c</fullName>
        <description>SFDC1-7082 Annualized discount amount to be copied over from discount amount</description>
        <inlineHelpText>Annualized discount amount auto calculated by system</inlineHelpText>
        <label>Annualized Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualizedUnitPrice__c</fullName>
        <description>SFDC1-7082 annualized unit price for subscription products</description>
        <inlineHelpText>Annualized unit price calculated from unit price automatically</inlineHelpText>
        <label>Annualized Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DiscountOverThreshold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4275 Indicates whether the opportunity product has been discounted over threshold</description>
        <inlineHelpText>Checked when product has been discounted over threshold</inlineHelpText>
        <label>Discount Over Threshold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DiscountPercentage__c</fullName>
        <description>SFDC1-173 Denotes the discount percentage to be applied to the UnitPrice. Used in the pricing calculation customization.</description>
        <inlineHelpText>Please specify the discount percentage to be applied to the Updated List Price. Only required when the Discount Type is set to &quot;Percentage&quot;.</inlineHelpText>
        <label>Discount %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Discount threshold flag calculated from product and product schedules</description>
        <formula>IF(
DiscountPercentage__c &gt;  PricebookEntry.Product2.DiscountThreshold__c,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;,
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30)
)</formula>
        <inlineHelpText>The flag will set to Red if discount is over discount threshold on the Product</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DiscountType__c</fullName>
        <description>Specify what, if any, type of discount to be applied to the sales price.</description>
        <inlineHelpText>This field denotes the type of discount that is being applied.</inlineHelpText>
        <label>Discount Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Discount</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>SFDC1-173 Denotes the discount amount to be applied to the UnitPrice. Used in the pricing calculation customization.</description>
        <inlineHelpText>Please specify the discount amount to be applied to the Updated List Price. Only required when the Discount Type is set to &quot;Amount&quot;.</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FirstYear__c</fullName>
        <description>SFDC1-905 This fields holds the first year price for opportunity line items</description>
        <inlineHelpText>First Year Value</inlineHelpText>
        <label>First Year Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LicenseType__c</fullName>
        <description>SFDC1-4327 : Additional fields for Opportunity Product Detail - License Type</description>
        <inlineHelpText>Please enter the contracted license type with the customer</inlineHelpText>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client License</fullName>
                </value>
                <value>
                    <fullName>Departmental License</fullName>
                </value>
                <value>
                    <fullName>Divisional License</fullName>
                </value>
                <value>
                    <fullName>Enterprise Wide License</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>One Time License</fullName>
                </value>
                <value>
                    <fullName>Site License</fullName>
                </value>
                <value>
                    <fullName>Standalone License</fullName>
                </value>
                <value>
                    <fullName>User License</fullName>
                </value>
                <value>
                    <fullName>Departmental</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Site(s)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Standalone</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ListPrice__c</fullName>
        <description>SFDC1-173 Currency Field populated with the List Price from the Price Book at when a Product is added to an Opportunity. Used in customization for Pricing and Discounting.</description>
        <inlineHelpText>First Year Price Book List Price from Product Schedules</inlineHelpText>
        <label>PriceBook List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProRatedUnitPrice__c</fullName>
        <description>SFDC1-7082 field calculated if user decides to pro-rate the</description>
        <inlineHelpText>Field auto calculated for field subscription pro-rated products</inlineHelpText>
        <label>Pro-Rated Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UnitListPrice__c</fullName>
        <description>SFDC1-173 Currency field that displays the intial value pre discount as entered by the rep</description>
        <inlineHelpText>List Price for the product populated by sales from pricing tools or through renewal process</inlineHelpText>
        <label>Updated List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to schedule opportunity products in case of multi-year opportunities</description>
    <fields>
        <fullName>AnnualizedDiscountAmount__c</fullName>
        <description>SFDC1-7082 Annualized discount amount calculated for subscription products</description>
        <inlineHelpText>Annualized discount amount auto-calculated by system</inlineHelpText>
        <label>Annualized Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AnnualizedUnitPrice__c</fullName>
        <description>SFDC1-7082 Annualized unit price calculated for subscription product</description>
        <inlineHelpText>Annualized unit price auto-calculated by system</inlineHelpText>
        <label>Annualized Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DiscountAmount__c</fullName>
        <description>SFDC1-1837 Amount of discount if discount type = Amount</description>
        <inlineHelpText>Amount of discount given</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DiscountType__c</fullName>
        <description>SFDC1-1837 Type of discount being applied to the Product</description>
        <label>Discount Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>No Discount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ListPrice__c</fullName>
        <description>SFDC1-2043 List price derived from related Product schedule</description>
        <formula>TEXT(ProductSchedule__r.ListPrice__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>List Price of Product</inlineHelpText>
        <label>List Price</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityProductID__c</fullName>
        <description>SFDC1-2043 Opportunity product to relate OPS with related opportunity product line item.</description>
        <inlineHelpText>ID of related Opportunity Product</inlineHelpText>
        <label>Opportunity Product ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProRatedUnitPrice__c</fullName>
        <description>SFDC1-7082 Pro rated unit price to calculated based on product type</description>
        <inlineHelpText>Pro rated unit price calculated for subscription products</inlineHelpText>
        <label>Pro-Rated Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-487 Ghost status field to store status of related opportunity product</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Product Schedule</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Threshold for maximum percent of discount that can be provided on a product</description>
        <inlineHelpText>Maximum discount (percentage) able to be applied</inlineHelpText>
        <label>Discount Threshold%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LicenseType__c</fullName>
        <description>SFDC1-173 Displays the License type of this product.</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>One Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityLineItemScheduleMethods.cls
//
//@Author Paras Dhingra
//@Date 15th Sep 2017
//@Description SFDC1-4275 Trigger helper method class for OpportunityLineItemSchedule object 
//@company IHS Markit
//
public class OpportunityLineItemScheduleMethods {
    
    //
    //@author Paras Dhingra
    //@date 15th Sep 2017
    //@description SFDC1-4275 Method to rollup values from 
    //            Oppy product schedules to Oppy products
    //@param TriggerParameters
    //@return void
    //@companyname IHS Markit
    //
    public static void rollUpValuesToOppyProduct(TriggerParameters tp) {
        try {
            System.debug('Control Reached rollUpValuesToOppyProduct');
            Map<Id,OpportunityLineItemSchedule__c> mapOPSModified = new  Map<Id,OpportunityLineItemSchedule__c>();
        
            if(tp.tEvent == TriggerParameters.TriggerEvent.afterInsert ||
                tp.tEvent == TriggerParameters.TriggerEvent.afterUpdate) {
                    mapOPSModified = (Map<Id,OpportunityLineItemSchedule__c>)tp.newMap;
            }
            if(tp.tEvent == TriggerParameters.TriggerEvent.afterDelete) {
                
                mapOPSModified = (Map<Id,OpportunityLineItemSchedule__c>)tp.oldMap;
            }
            if(mapOPSModified!=null && !mapOPSModified.isEmpty()) {
                //traverse the map and extract opportunity product id
                Set<Id> setOppyProductId = new Set<Id>();
                for(OpportunityLineItemSchedule__c ops: mapOPSModified.values()) {
                    setOppyProductId.add(ops.OpportunityProductId__c);
                }
                if(setOppyProductId!=null && !setOppyProductId.isEmpty()) {
                    //query Opportunity prodcut which was to be updated
                    Map<Id, OpportunityLineItem> mapOppyProductId = new Map<Id, OpportunityLineItem>([Select id, DiscountPercentage__c, Discount_Amount__c, DiscountType__c,OpportunityId,FirstYear__c,
                                                                ListPrice__c,Quantity,UnitListPrice__c,UnitPrice, PricebookEntry.Product2.DiscountThreshold__c,LicenseType__c,
                                                                DiscountOverThreshold__c,Status__c, ActiveInactiveNetUnitPrice__c,AnnualizedUnitPrice__c, AnnualizedDiscountAmount__c,
                                                                    ProRatedUnitPrice__c, ProRatedDiscountAmount__c From OpportunityLineItem 
                                                                where Id IN: setOppyProductId]);
                    //query all OpportunityLinetITemSchedule related to Opportunity Products
                    //Cannot use inner query as there is no direct relation exists between the two Oppy product and Oppy product schedules
                    List<OpportunityLineItemSchedule__c> lstOPS = [Select id, DiscountPercent__c, DiscountAmount__c, DiscountType__c, ExternalListPrice__c,
                                                                    InstallmentYears__c, OpportunityProductId__c, PriceBookListPrice__c, Quantity__c, SalesPrice__c,
                                                                    TotalPrice__c,Status__c, AnnualizedUnitPrice__c, AnnualizedDiscountAmount__c,
                                                                    ProRatedUnitPrice__c, ProRatedDiscountAmount__c from OpportunityLineItemSchedule__c where OpportunityProductID__c IN:setOppyProductId
                                                                    order by InstallmentYears__c ASC];
                     System.debug('--lstOPS--' + lstOPS);
                     System.debug('--mapOppyProductId--' + mapOppyProductId);
                     if(lstOPS!=null && !lstOps.isEmpty() && mapOppyProductId!=null && !mapOppyProductId.isEmpty()) {
                         System.debug('--inside if--');
                         //create a map of Opportunity ID it's OppyProducts
                         Map<Id, List<OpportunityLineItemSchedule__c>> mapOppyProdAndScheds = new Map<Id, List<OpportunityLineItemSchedule__c>>();
                         List<OpportunityLineItem> lstOLIToUpdate = new List<OpportunityLineItem>();
                         for(OpportunityLineItemSchedule__c ops : lstOPS) {
                             if(mapOppyProdAndScheds.containskey(ops.OpportunityProductId__c)) {
                                 mapOppyProdAndScheds.get(ops.OpportunityProductId__c).add(ops);
                             }
                             else {
                                 List<OpportunityLineItemSchedule__c> tempLstOps = new List<OpportunityLineItemSchedule__c>();
                                 tempLstOps.add(ops);
                                 mapOppyProdAndScheds.put(ops.OpportunityProductId__c, tempLstOps);
                             }
                         }
                         System.debug('--mapOppyProdAndScheds--' + mapOppyProdAndScheds);
                         //process the map and update OpportunityProducts
                         
                         for( OpportunityLineItem oli : mapOppyProductId.values()) {
                             
                             List<OpportunityLineItemSchedule__c> lstCurrentOliScheds = new List<OpportunityLineItemSchedule__c>();
                             lstCurrentOliScheds = mapOppyProdAndScheds.get(oli.Id);
                             //reset all values
                             oli.DiscountPercentage__c = 0.0;
                             oli.Discount_Amount__c = 0.0;
                             oli.DiscountType__c = 'No Discount';
                             oli.FirstYear__c = 0.0; // First Year Total Price
                             if(lstCurrentOliScheds!=null && lstCurrentOliScheds.size()>0) {
                                 oli.FirstYear__c = lstCurrentOliScheds[0].TotalPrice__c;
                                 oli.Status__c = lstCurrentOliScheds[0].Status__c;
                                 oli.Quantity = lstCurrentOliScheds[0].Quantity__c;// Always fetch Quantity from Opportunity Line Item Schedule
                                 oli.DiscountType__c = lstCurrentOliScheds[0].DiscountType__c;
                                 oli.ListPrice__c = lstCurrentOliScheds[0].PriceBookListPrice__c; //Price book List Price first year
                                 //oli.LicenseType__c = lstCurrentOliScheds[0].LicenseType__c;// LicenseType__c copied from Opportunity Line item schedule
                                 
                             }
                             oli.UnitListPrice__c = 0.0; //Total external list price
                             oli.UnitPrice = 0.0;//Total Sales Price
                             //traverse the opportunity line item children
                             oli.AnnualizedUnitPrice__c = 0.0;
                             oli.AnnualizedDiscountAmount__c = 0.0;
                             oli.ProRatedUnitPrice__c = 0.0;
                             oli.ProRatedDiscountAmount__c = 0.0;
                             for( OpportunityLineItemSchedule__c ops : lstCurrentOliScheds) {
                                  oli.Discount_Amount__c += ops.DiscountAmount__c==null?0:ops.DiscountAmount__c;
                                 oli.DiscountPercentage__c+=ops.DiscountPercent__c==null?0:ops.DiscountPercent__c;
                                 oli.UnitListPrice__c+=ops.ExternalListPrice__c==null?0:ops.ExternalListPrice__c;
                                 oli.UnitPrice +=ops.SalesPrice__c==null?0:ops.SalesPrice__c;
                                 oli.ActiveInactiveNetUnitPrice__c = oli.UnitPrice==null?0:oli.UnitPrice;
                                 oli.AnnualizedUnitPrice__c += ops.AnnualizedUnitPrice__c==null?0:ops.AnnualizedUnitPrice__c;
                                 oli.AnnualizedDiscountAmount__c += ops.AnnualizedDiscountAmount__c==null?0:ops.AnnualizedDiscountAmount__c;
                                 oli.ProRatedUnitPrice__c += ops.ProRatedUnitPrice__c==null?0:ops.ProRatedUnitPrice__c;
                                 oli.ProRatedDiscountAmount__c += ops.ProRatedDiscountAmount__c==null?0:ops.ProRatedDiscountAmount__c;
                             }
                             if(oli.Status__c=='Lost') {
                                 oli.UnitPrice=0;
                             }
                             oli.DiscountPercentage__c = oli.DiscountPercentage__c/(lstCurrentOliScheds.size());
                             oli.DiscountOverThreshold__c = oli.DiscountPercentage__c>oli.PricebookEntry.Product2.DiscountThreshold__c?true:false;
                             lstOLIToUpdate.add(oli);
                         }
                         //update Opportunity Line Items
                         if(lstOLIToUpdate!=null && !lstOLIToUpdate.isEmpty()) {
                             update lstOLIToUpdate;
                         }
                     }
                    
                }
            }
            
        } catch(Exception ex) {
            System.debug('Exception caught' + ex);
            UtilityClass.createApexLogRecord(ex, 'OpportunityLineItemScheduleMethods', 'rollUpValuesToOppyProduct');
            throw new GenericCustomException('Error occurred. Please contact salesforce helpdesk for assistance');

        }

        
    }
    //
    //@author Paras Dhingra
    //@date 11th Jul 2018
    //@description SFDC1-9058 Method to populate annualized values
    //@param TriggerParameters tp
    //@return void
    //@companyname IHS Markit
    //
    public static void populateAnnualizedValues(TriggerParameters tp) {
        try {
            //traverse oppy schedules and copy values to annualized fields
            for(OpportunityLineItemSchedule__c olis : (List<OpportunityLineItemSchedule__c>)tp.newList) {
                olis.AnnualizedUnitPrice__c = olis.ExternalListPrice__c;
                olis.AnnualizedDiscountAmount__c = olis.DiscountAmount__c;
            }
        }
        catch(Exception ex) {
            UtilityClass.createApexLogRecord(ex, 'OpportunityLineItemScheduleMethods', 'populateAnnualizedValues');
        }
    }

}