src/objects/ContractAttachment__c.object
<CustomObject>
    <description>SFDC1-662 Object to define what kind of attachment users are adding to a Contract</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-662 to define what kind of attachment users are adding to a Contract
SFDC1-7080: Updating Attachment Type picklist field on the Contract Attachments object,</description>
        <inlineHelpText>Please select the kind of attachment you are adding to a Contract</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Certificate of Purge</fullName>
                </value>
                <value>
                    <fullName>Client Signed Contract</fullName>
                </value>
                <value>
                    <fullName>Client Usage Reports</fullName>
                </value>
                <value>
                    <fullName>Contribution Addendum</fullName>
                </value>
                <value>
                    <fullName>Contribution Schedule</fullName>
                </value>
                <value>
                    <fullName>Countersigned Contract</fullName>
                </value>
                <value>
                    <fullName>Escrow Agreement</fullName>
                </value>
                <value>
                    <fullName>Fee Waiver</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Amended Annex Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Fee Letter</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Super Access Coordinators Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV Supplemental Agreement Form</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User/Broker Terms</fullName>
                </value>
                <value>
                    <fullName>MarkitSERV User Agreement / Key Contacts</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
                <value>
                    <fullName>Notice of Non-Renewal</fullName>
                </value>
                <value>
                    <fullName>Novation Letter</fullName>
                </value>
                <value>
                    <fullName>Online Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Price Increase Letter</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Sales RAD Approval Form</fullName>
                </value>
                <value>
                    <fullName>Signed Continuation Letter</fullName>
                </value>
                <value>
                    <fullName>Signed Master Agreement</fullName>
                </value>
                <value>
                    <fullName>Signed NDA</fullName>
                </value>
                <value>
                    <fullName>Signed Trial</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt Certificate</fullName>
                </value>
                <value>
                    <fullName>Termination Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-662 Contract to which this contact attachment is associated</description>
        <inlineHelpText>Please select the contract to which this contact attachment is associated</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>ContractAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DocuSignEnvelopeId__c</fullName>
        <description>SFDC1-662 DocuSign envelope ID if the contract  attachment is of DocuSign type</description>
        <inlineHelpText>System managed: DocuSign envelope ID if the contract  attachment is of DocuSign type</inlineHelpText>
        <label>DocuSign Envelope Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDocuSignCert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-662: Checked if contract attachment is a DocuSign certificate</description>
        <inlineHelpText>System Managed: Checked  if contract attachment is a DocuSign certificate</inlineHelpText>
        <label>IsDocuSignCert?</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Contract Attachment Name (Client-Prod)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/dsfsDocuSignStatusMethods.cls
//-----------------------------
// @author: Tran-Vu Tran
// @date: 16 July 2018
// @param: NA
// @description: Class to hold trigger methods 
// @return: NA
//-----------------------------
public class dsfsDocuSignStatusMethods {

    //-----------------------------
    // @author: Tran-Vu Tran
    // @date: 16 July 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-7947 when DocuSign Status is created, insert one record for the Contract Attachment and one for the Certificate.
    // @return: None
    //------------------------------ 
    
    public static void createContractAttachment(TriggerParameters tp) {
        
        if (tp.tEvent == TriggerParameters.TriggerEvent.beforeInsert) {
            
            //System.debug('Executing createContractAttachment - tp.newList.size() = ' + tp.newList.size());

            Set<Id> contractIDs = new Set<Id>();
            
            for (dsfs__DocuSign_Status__c dss: (List<dsfs__DocuSign_Status__c>) tp.newList) {
                if (dss.dsfs__Contract__c != null) {
                    contractIDs.add(dss.dsfs__Contract__c);
                }
            }
            
            Map<Id, Contract> contractMap = new Map<Id,Contract>(
                [select Id, Status, OwnerID, Account.Name, RecordType.DeveloperName from Contract where Id in :contractIDs]
            );
            
            List <ContractAttachment__c> contractAttachmentsToInsert = new List <ContractAttachment__c>();  
            
            for (dsfs__DocuSign_Status__c dss: (List<dsfs__DocuSign_Status__c>) tp.newList){
                
                Contract contr = contractMap.get(dss.dsfs__Contract__c);
                //System.debug('Contract Account = ' + contr.Account.Name);
                //System.debug('Contract RecordType = ' + contr.RecordType.DeveloperName);
                //System.debug('Contract DocuSignEnvelopeId = ' + dss.dsfs__DocuSign_Envelope_ID__c);
                
                ContractAttachment__c ca = new ContractAttachment__c();

                ca.AttachmentType__c = 'Client Signed Contract';

                ca.Contract__c = dss.dsfs__Contract__c;
                ca.DocuSignEnvelopeId__c = dss.dsfs__DocuSign_Envelope_ID__c;
                ca.IsDocuSignCert__c = false;
                ca.Name = contr.Account.Name + ' - ' + contr.RecordType.DeveloperName;          
                contractAttachmentsToInsert.add(ca);
                
                // getting the matching Contract Attachment Certificates
                ContractAttachment__c caCertificate = new ContractAttachment__c();
                
                /* Since there is no requirement for the  DocuSign Certificates, comment out the code for now
                //if (caRecordTypeId != null)
                //	caCertificate.RecordType.DeveloperName = caRecordTypeId;
                caCertificate.AttachmentType__c = 'DocuSign Certificate';
                caCertificate.Contract__c = dss.dsfs__Contract__c;
                caCertificate.DocuSignEnvelopeId__c = dss.dsfs__DocuSign_Envelope_ID__c;
                caCertificate.IsDocuSignCert__c = true;
                caCertificate.Name = contr.Account.Name + ' - ' + contr.RecordType.DeveloperName + ' (DocuSign Certificate)';
    
                contractAttachmentsToInsert.add(caCertificate);
				*/
            }
    
           insert contractAttachmentsToInsert;
    
        }
    }
}