src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractOwner__c</fullName>
        <description>SFDC1-8125: Used in &quot;Contract Management&quot; case lightning layout</description>
        <formula>Owner.FirstName + &apos; &apos; + Owner.LastName</formula>
        <inlineHelpText>Contract Owner</inlineHelpText>
        <label>Contract Owner</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/InternalApproval__c.object
<CustomObject>
    <description>SFDC1-6282: New custom junction object to provide many-to-many relationship between Contracts and Contacts</description>
    <fields>
        <fullName>ApprovalType__c</fullName>
        <description>SFDC1-6282: Approval Type</description>
        <inlineHelpText>Select the Team that you require the approval from</inlineHelpText>
        <label>Approval Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Line Leader</fullName>
                </value>
                <value>
                    <fullName>Consulting Operations</fullName>
                </value>
                <value>
                    <fullName>Contract Management</fullName>
                </value>
                <value>
                    <fullName>Corporate Compliance</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Product Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Leader</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>SFDC1-6282: Contact</description>
        <inlineHelpText>Approver Comments</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Internal Approvals</relationshipLabel>
        <relationshipName>Internal_Approvals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ContractOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6282: Contract Owner</description>
        <inlineHelpText>Contract Created By</inlineHelpText>
        <label>Contract Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Internal_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>SFDC1-6282: Contract</description>
        <inlineHelpText>Contract Number</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Internal Approvals</relationshipLabel>
        <relationshipName>Internal_Approvals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Internal Approval</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>Internal Approval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LegalEntity__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 , This holds Legal Entity related to Products</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5806 : This field will hold the lookup to Country Object on Legal Entity</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Legal Entities (Country)</relationshipLabel>
        <relationshipName>LegalEntities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Legal Owning Entity</inlineHelpText>
        <label>Legal Entity</label>
        <referenceTo>LegalEntity__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>LegalEntityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestInternalApprovalMethods.cls
//-----------------------------
// @author: Jagadesh Kumar
// @date: 06 June 2018
// @param: NA
// @description: Test class for Internal Approval trigger methods 
// @return: NA
//-----------------------------
@isTest
public class TestInternalApprovalMethods {
	//-----------------------------
    // @author: Jagadesh Kumar
    // @date: 06 June 2018
    // @param: NA
    // @description: Test method for Internal Approval trigger methods populateContractOwner on insert
    // @return: NA
    //-----------------------------
    private static testMethod void testpopulateContractOwner() {
        Test.startTest();
        Account a = TestUtility.createTestAccount('Internal Approval Account', true);
        Contact c1 = new Contact();
        c1.firstname = 'Internal1';
        c1.lastname = 'Approval1';
        c1.Email = 'Internal.Approval@ihsmarkit.com';
        c1.AccountId = a.Id;
        insert c1;
        
        Product2 testProd = TestUtility.createProduct('Test Product', true);
        Id standardId = Test.getStandardPricebookId();
        LegalEntity__c legalEntity = TestUtility.createLegalEntity('testLegalEntity','USD');
        List<Country__c> lstCountry = TestUtility.loadCountryData();
        Country__c country = lstCountry.get(0);
        Contract contract1 = TestUtility.createContractWithInsertOptional(a.Id, legalEntity.Id, country.Id, standardId,TRUE);
        
        InternalApproval__c inApproval = new InternalApproval__c();
        inApproval.Contact__c = c1.Id;
        inApproval.Contract__c = contract1.Id;
        inApproval.ApprovalType__c = 'Business Line Leader';
        insert inApproval;
        InternalApproval__c ia = [SELECT Id,ContractOwner__c FROM InternalApproval__c WHERE ID =: inApproval.Id];
        System.assert(ia.ContractOwner__c != null);
        Test.stopTest();
    }
    
}