src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Licenses__c</fullName>
        <description>SFDC1-4329;It can be populated via the userxs integration for use by the marketing team to be passed to Eloqua.</description>
        <label>Licenses</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NumberOfLicenses__c</fullName>
        <description>SFDC1-4329;It can be populated via the userxs integration for use by the marketing team to be passed to Eloqua.</description>
        <label>Number of Licenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductUsageLast30days__c</fullName>
        <description>SFDC1-2446 Field for tracking product usage for the last 30 days</description>
        <inlineHelpText>Lists the product used for the last 30 days. Auto-calculated via the trigger.</inlineHelpText>
        <label>Product Usage Last 30 days</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductUsageLast60days__c</fullName>
        <description>SFDC1-2446 Field for tracking product usage for the last 60 days</description>
        <inlineHelpText>Lists the product used for the last 60 days. Auto-calculated via a trigger.</inlineHelpText>
        <label>Product Usage Last 60 days</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductUsageLast90days__c</fullName>
        <description>SFDC1-2446 Field for tracking product usage for the last 90 days</description>
        <inlineHelpText>Lists the product used for the last 90 days. Auto-calculated via a trigger.</inlineHelpText>
        <label>Product Usage Last 90 days</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductEntitlement__c.object
<CustomObject>
    <description>SFDC1-7972 Product Entitlement object is used to hold the details about the user entitlements and licenses.</description>
    <fields>
        <fullName>ProductLicense__c</fullName>
        <description>SFDC1-6785 Product License related to this entitlement</description>
        <inlineHelpText>Links the Product License related to this Entitlement record.</inlineHelpText>
        <label>Product License</label>
        <referenceTo>ProductLicense__c</referenceTo>
        <relationshipLabel>Product Entitlements</relationshipLabel>
        <relationshipName>ProductEntitlements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-7972 Product Login related to this entitlement</description>
        <inlineHelpText>Link the Product Login to this Entitlement record.</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Product Entitlements</relationshipLabel>
        <relationshipName>ProductEntitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>SFDC1-6785 Source of the entitlement data</description>
        <inlineHelpText>Data can be uploaded automatically from external entitlement and authentications systems or entered manually.</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>MSF</fullName>
                </value>
                <value>
                    <fullName>UserXS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>SFDC1-6785 Inital set-up date of the entitlement in the external source system</description>
        <inlineHelpText>Initial set-up date of the Entitlement in the external source system.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Entitlement</label>
    <nameField>
        <displayFormat>PEN-{000000}</displayFormat>
        <label>Product Entitlement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProductGroupLicenseAssociation__c.object
<CustomObject>
    <description>SFDC1-7972 This object links the Product Group to the related external system licenses [e.g. UserXS]</description>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-4386 Product Group related to this product License</description>
        <inlineHelpText>Link the related Product Group to this Product License</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipLabel>Product Group License Associations</relationshipLabel>
        <relationshipName>ProductGroupLicenseAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductLicense__c</fullName>
        <description>SFDC1-4386 Product License related to this Product Group</description>
        <inlineHelpText>Link the related Product License to this Product Group</inlineHelpText>
        <label>Product License</label>
        <referenceTo>ProductLicense__c</referenceTo>
        <relationshipLabel>Product Group License Associations</relationshipLabel>
        <relationshipName>ProductGroupLicenseAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Group License Association</label>
    <nameField>
        <displayFormat>PGLicense-{000000}</displayFormat>
        <label>Product Group License Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Group License Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductLicense__c.object
<CustomObject>
    <description>SFDC1-7972 License object is used to hold the details about the license and any additional parameters to get access to Documents and Solutions in Customer Portal.</description>
    <fields>
        <fullName>Source__c</fullName>
        <description>SFDC1-6785 Source of the licence data</description>
        <inlineHelpText>Data can be uploaded automatically from external entitlement and authentications systems or entered manually</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>UserXS</fullName>
                </value>
                <value>
                    <fullName>MSF</fullName>
                </value>
                <value>
                    <fullName>USERXS-MARKIT</fullName>
                </value>
                <value>
                    <fullName>USERXS-TRADE-MANAGER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>SFDC1-6785 Initial set-up date of the license in the external source system</description>
        <inlineHelpText>Initial set-up date of the license in the external source system</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product License</label>
    <nameField>
        <label>Product License Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductLogin__c.object
<CustomObject>
    <description>SFDC1-7972 This object will be used to store the information related to the user of the IHS Markit product.  Until the user has a usage they will never be converted to a contact.  The user record mostly will be created/updated by the integration system.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>SFDC1-6785 Email of the user used for Product Login.</description>
        <inlineHelpText>Email of the user used for Product Login.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>SFDC1-6785 First Name of the user used for Product Login.</description>
        <inlineHelpText>First Name of the user used for Product Login.</inlineHelpText>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>SFDC1-6785 Last Name of the user used for Product Login.</description>
        <inlineHelpText>Last Name of the user used for Product Login.</inlineHelpText>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>SFDC1-6785 Source of the user data. Data can be uploaded automatically from external entitlement and authentications systems or entered manually. If the User is manually entered this should be defaulted to Manual and cannot be overwritten.</description>
        <inlineHelpText>Source of the user data.</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>UserXS</fullName>
                </value>
                <value>
                    <fullName>MSF</fullName>
                </value>
                <value>
                    <fullName>USERXS-MARKIT</fullName>
                </value>
                <value>
                    <fullName>USERXS-TRADE-MANAGER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>SFDC1-6785 Initial set-up date of the user in the external source system</description>
        <inlineHelpText>Initial set-up date of the user in the external source system</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>SFDC1-6785 Username or Login name for this user</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the unique username or login name for this user.</inlineHelpText>
        <label>Username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Login</label>
    <nameField>
        <displayFormat>PLN-{000000}</displayFormat>
        <label>Product Login Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductUsageStatistics__c.object
<CustomObject>
    <description>SFDC1-7972 This object is created for capturing product usage by the user</description>
    <fields>
        <fullName>ProductLicense__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-6785 Link related to License to this usage</description>
        <inlineHelpText>Link the related Product License to this Usage record.</inlineHelpText>
        <label>Product License</label>
        <referenceTo>ProductLicense__c</referenceTo>
        <relationshipLabel>Product Usage Statistics</relationshipLabel>
        <relationshipName>ProductUsageStatistics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductLogin__c</fullName>
        <description>SFDC1-6785 User related to this usage</description>
        <inlineHelpText>Link the related Product Login to this Usage record.</inlineHelpText>
        <label>Product Login</label>
        <referenceTo>ProductLogin__c</referenceTo>
        <relationshipLabel>Product Usage Statistics</relationshipLabel>
        <relationshipName>ProductUsageStatistics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>SFDC1-6785 Source of the usage data</description>
        <inlineHelpText>Data can only be uploaded automatically from external entitlement and authentications systems.</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UserXS</fullName>
                </value>
                <value>
                    <fullName>MSF</fullName>
                </value>
                <value>
                    <fullName>USERXS-MARKIT</fullName>
                </value>
                <value>
                    <fullName>USERXS-TRADE-MANAGER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UsageDate__c</fullName>
        <description>SFDC1- 6785 Date of usage</description>
        <inlineHelpText>Usage can be tracked on a daily roll-up or can be insterted per instance or a Product Login.</inlineHelpText>
        <label>Usage Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Usage Statistics</label>
    <nameField>
        <displayFormat>USG-{000000}</displayFormat>
        <label>Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Usage Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestBatchToUpdateProductDetailsOnContact.cls
//-----------------------------
// @author: Sruti Srivastava
// @date: 11th June 2018
// @description: SFDC1-6833 This batch class will update license and product information on Contact
// @companyname: Vertiba
//------------------------------

@isTest
public class TestBatchToUpdateProductDetailsOnContact {
    
    //-----------------------------
    // @author: Sruti Srivastava
    // @date: 11th June 2018
    // @description: Test method for batch BatchToUpdateProductDetailsOnContact which
    // update license and product information on Contact
    // @return: NA
    //-------------------
    private static testMethod void testProductAndLicenseDetailUpdateOnContact() {
        
        Account accountObj = TestUtility.createTestAccount('Unknown Account', true);
        List<Contact> conList = new List<Contact>();
        Contact c1 = new Contact(firstname = 'Test1', lastname = 'Test1', Email = 'pl.contactExists@ihsmarkit.com', AccountId = accountObj.Id);
        conList.add(c1);
        Contact c2 = new Contact(firstname = 'Test2', lastname = 'Test2', Email = 'pl.contactNull@ihsmarkit.com', AccountId = accountObj.Id);
        conList.add(c2);
        
        insert conList;
        
        List<ProductLogin__c> plList = new List<ProductLogin__c>();
        
        ProductLogin__c pl1 = new ProductLogin__c(Email__c = 'pl.contactNull@ihsmarkit.com', Source__c = 'Manual', Username__c = 'pl.contactNull');        
        plList.add(pl1);
        ProductLogin__c pl2 = new ProductLogin__c(Email__c = 'pl.contactExists@ihsmarkit.com', Source__c = 'Manual', Username__c = 'pl.contactNull2',FirstName__c = 'Test11',LastName__c = 'Test22' );        
        plList.add(pl2);
        
        insert plList;
        
        List<ProductLicense__c> listProdLicenses = new List<ProductLicense__c>();
        listProdLicenses.add(new ProductLicense__c(Name = 'Securities'));
        listProdLicenses.add(new ProductLicense__c(Name = 'Operation'));
        insert listProdLicenses;
        
        List<ProductUsageStatistics__c> pusList = new List<ProductUsageStatistics__c>();
        
        ProductUsageStatistics__c usg1 = new ProductUsageStatistics__c(ProductLogin__c    = pl1.Id, Source__c = 'UserXS', ProductLicense__c = listProdLicenses[0].Id,  UsageDate__c = System.today().addDays(-45));
        pusList.add(usg1);
        ProductUsageStatistics__c usg2 = new ProductUsageStatistics__c(ProductLogin__c    = pl2.Id, Source__c = 'UserXS', ProductLicense__c = listProdLicenses[1].Id,  UsageDate__c = System.today().addDays(-45));
        pusList.add(usg2);
        ProductUsageStatistics__c usg3 = new ProductUsageStatistics__c(ProductLogin__c    = pl1.Id, Source__c = 'UserXS', ProductLicense__c = listProdLicenses[0].Id,  UsageDate__c = System.today().addDays(-88));
        pusList.add(usg3);
        ProductUsageStatistics__c usg4 = new ProductUsageStatistics__c(ProductLogin__c    = pl1.Id, Source__c = 'UserXS', ProductLicense__c = listProdLicenses[0].Id,  UsageDate__c = System.today().addDays(-10));
        pusList.add(usg4);
        insert pusList;
        
        List<ProductEntitlement__c> listProdEntitlement = new List<ProductEntitlement__c>();
        listProdEntitlement.add(new ProductEntitlement__c(ProductLogin__c= pl1.Id, ProductLicense__c = listProdLicenses[0].Id, StartDate__c = Date.today()));
        insert listProdEntitlement;
        
        List<ProductGroup__c> listProdGroup = new List<ProductGroup__c>();
        listProdGroup.add(new ProductGroup__c(Name = 'Data Center & Cloud'));
        listProdGroup.add(new ProductGroup__c(Name = 'Facilities Management'));
        listProdGroup.add(new ProductGroup__c(Name = 'Access Control & Fire'));
        insert listProdGroup;
        
        List<ProductGroupLicenseAssociation__c> listProdGroupGA = new List<ProductGroupLicenseAssociation__c>();
        listProdGroupGA.add(new ProductGroupLicenseAssociation__c(ProductGroup__c = listProdGroup[0].Id, ProductLicense__c = listProdLicenses[0].Id));
        listProdGroupGA.add(new ProductGroupLicenseAssociation__c(ProductGroup__c = listProdGroup[1].Id, ProductLicense__c = listProdLicenses[0].Id));
        listProdGroupGA.add(new ProductGroupLicenseAssociation__c(ProductGroup__c = listProdGroup[2].Id, ProductLicense__c = listProdLicenses[1].Id));
        insert listProdGroupGA;
        
        Test.startTest();
        database.executeBatch(new BatchToUpdateProductDetailsOnContact());
        Test.stopTest();
        Contact contact1 = [select NumberOfLicenses__c, Licenses__c, ProductUsageLast30days__c, ProductUsageLast60days__c, ProductUsageLast90days__c
                            FROM Contact where email ='pl.contactNull@ihsmarkit.com' limit 1];
        Contact contact2 = [select NumberOfLicenses__c, Licenses__c, ProductUsageLast30days__c, ProductUsageLast60days__c, ProductUsageLast90days__c
                            FROM Contact where email !='pl.contactNull@ihsmarkit.com' limit 1];
        system.debug('******'+contact1);
        system.debug('******'+contact2);
        //Verifying outputs for License nformation update on Contact
        system.assertEquals(contact1.NumberOfLicenses__c, 1);
        system.assertEquals(contact2.NumberOfLicenses__c, 0);
        system.assertNotEquals(contact1.Licenses__c, null);
        system.assertEquals(contact2.Licenses__c, null);
        
        //Verifying outputs for Product usage information for last 30 days update on Contact
        system.assertNotEquals(contact1.ProductUsageLast30days__c, null);
        system.assertEquals(contact2.ProductUsageLast30days__c, null);
        
        //Verifying outputs for Product usage information for last 60 days update on Contact
        system.assert(contact1.ProductUsageLast60days__c.contains('Data Center & Cloud'));
        system.assert(contact1.ProductUsageLast60days__c.contains('Facilities Management'));
        system.assert(contact2.ProductUsageLast60days__c.contains('Access Control & Fire'));
        
        //Verifying outputs for Product usage information for last 90 days update on Contact
        system.assert(contact1.ProductUsageLast90days__c.contains('Data Center & Cloud'));
        system.assert(contact1.ProductUsageLast90days__c.contains('Facilities Management'));
        system.assert(contact2.ProductUsageLast90days__c.contains('Access Control & Fire'));
        
    }
    
    //-----------------------------
    // @author: Sruti Srivastava
    // @date: 11th June 2018
    // @description: Test method for schedular class BatchToUpdateProductDetailsScheduler
    // update license and product information on Contact
    // @return: NA
    //-------------------
    static testMethod void TestSchedulerForBatchToUpdateProductDetailsOnContact(){
        Test.StartTest();        
        BatchToUpdateProductDetailsScheduler contactBatchScheduler = new BatchToUpdateProductDetailsScheduler(); //Schedule apex class name
        String sch = '0 0 0 * * ?'; 
        String jobId = system.schedule('Run Job for BatchToUpdateProductDetailsOnContact', sch, contactBatchScheduler); //scheduling apex class
        System.assert(jobId!=null);
        Test.stopTest();
    }
    
}