src/objects/Country__c.object
<CustomObject>
    <description>SFDC1-402 Country object serves as a lookup for other standard objects (Account, Contact, etc...) Country object contains attributes for business use in reporting and validation against countries.</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UserRegion__c</fullName>
        <description>SFDC1-199 Interpret from address based on country</description>
        <inlineHelpText>Interpret from address based on country</inlineHelpText>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UserMethods.cls
//-----------------------------
// @author: Tran-Vu Tran
// @date: 24 April 2018
// @param: NA
// @description: Class to hold User Account trigger methods 
// @return: NA
//-----------------------------

public class UserMethods {

    //-----------------------------
    // @author: Tran-Vu Tran
    // @date: 24 April 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-808 Whenever an User record is created, 
    //              this function populates the User's Region field from Address' Country picklist.
    // @return: None
    //------------------------------
    public static void updateUserRegionWhenAddressCountryChanges(TriggerParameters tp) {
        
        try {
            // Map of old values and new values
            List<User> listNewUsers = (List<User>) tp.NewList;
            Map<Id, User> mapOldUsers = (Map<Id, User>) tp.oldMap;

            if (tp.tEvent == TriggerParameters.TriggerEvent.beforeInsert || 
                tp.tEvent == TriggerParameters.TriggerEvent.beforeUpdate) {
                
                for (User newUser : listNewUsers) {

                    User oldUser = null;
                    
                    if (tp.tEvent == TriggerParameters.TriggerEvent.beforeUpdate) {
                        oldUser = mapOldUsers.get(newUser.Id);
                    }

                    if (oldUser == null // this is a new inserted record
                        || (oldUser != null && // for updating an existing user
                            (oldUser.CountryCode != newUser.CountryCode // Country picklist value changed
                             || (oldUser.CountryCode != null && oldUser.UserRegion__c == null))) // or Country was populated but User Region was not
                       ) {
                        
                        // update Region field
                        Country__c country = UtilityClass.getCountryByIsoCode(newUser.CountryCode);
                           
                        if (country != null) {
                            newUser.UserRegion__c = country.Region__c;
                        }
                    }
                }
            }
            
        } catch(Exception ex) {
            //this will happen if any exception apart from DML exception has occurred
            UtilityClass.createApexLogRecord(ex, 'UserMethods', 'updateUserRegionWhenAddressCountryChanges');
        }
    }
    
}