src/objects/CrossPlantStatus__c.object
<CustomObject>
    <description>JIRA : SFDC1-131 ,  This holds Cross Plant Status related to Products</description>
    <fields>
        <fullName>SAPCode__c</fullName>
        <label>SAP Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cross Plant Status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross Plant Status</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>OpportunityRecordType__c</fullName>
        <description>SFDC1-6174 Formula field that displays opportunity record type on page layout</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Opportunity Record Type</inlineHelpText>
        <label>Opportunity Record Type</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Gratis</fullName>
        <active>true</active>
        <businessProcess>Gratis Opportunity</businessProcess>
        <description>Opportunity with Zero Cost</description>
        <label>Gratis</label>
    </recordTypes>
    <recordTypes>
        <fullName>InnerYear</fullName>
        <active>true</active>
        <businessProcess>Inner Year Process</businessProcess>
        <description>Inner Year Record Type to see Inner Year opportunities</description>
        <label>Inner Year</label>
    </recordTypes>
    <recordTypes>
        <fullName>Placeholder</fullName>
        <active>true</active>
        <businessProcess>Forecasting Placeholder Process</businessProcess>
        <description>For Retail Business</description>
        <label>Forecasting Placeholder</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Determines Availability/Sellability</inlineHelpText>
        <label>Product Status</label>
        <referenceTo>CrossPlantStatus__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ProductsCrossPlantStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WarningMsgProductCrossPlantStatus.cls
//------------------------------------------------
// @author: Vertiba
// @company: VERTIBA
// @date: 13 Dec 2017
// @param: ApexPages.StandardController
// @description:  SFDC1-5326 -Opportunity Behavior - when a Future Disconnect Product is on the Oppy.
// @return: 
// @Last Updated: Anjani Shukla: SFDC1-8147-Product - New Cross Plant status = 'Renewal Only' SAP Code = '09' for 
//                               only renewal type opportunities.
//------------------------------------------------
public class WarningMsgProductCrossPlantStatus {
    
    
    public static List<String> errorMsgRecord = new List<String>();
    
	//------------------------------------------------
	// @author: Vertiba
	// @company: VERTIBA
	// @date: 13 Dec 2017
	// @description:  This method will get opprotunity product details which needs to be inactivated.
	// @Last Updated: 
	//------------------------------------------------ 
	@auraenabled
    public static List<String> getOptyProdLineDetails(Id oppRecordId) {
        //variables
        boolean flagtoshowMsg= false;
    	List<Id> productAssocWdOptyLnLst = new List<Id>();
        List<OpportunityLineItem> optyProdLineDetailsLst = new List<OpportunityLineItem>();
        List<Product2> product2DetailsLst = new List<Product2>();
        //errorMsgRecord = new Map<String,String>();
        //errorMsgRecord = new List<String>();
        
        // query 
        optyProdLineDetailsLst = [select id,name,Product2Id,ProductCode,Product2.Name,Opportunity.OpportunityRecordType__c,Status__c 
                                   from OpportunityLineItem where Opportunityid =: oppRecordId];
        
		//capture product2 id details from opportunity line item (opportunity product)
        if(optyProdLineDetailsLst.size() > 0) {
            for(OpportunityLineItem objOptyLineItem: optyProdLineDetailsLst) {
             	productAssocWdOptyLnLst.add(objOptyLineItem.Product2Id);	   
            }    
        }
        
        //get Product and Cross plant status.
        if(productAssocWdOptyLnLst.size() > 0) {
        	product2DetailsLst = [SELECT id,name,ProductStatus__r.name,ProductStatus__r.SAPCode__c FROM Product2 
                                  where id in: productAssocWdOptyLnLst];
        }
        
        //------------------------------------------------
		// @author: Vertiba
		// @company: VERTIBA
		// @date: 13 Dec 2017
		// @description: check whether we have cross plant status is not "Available for Sale" and SapCode not equals 04
        // 				 check for product and opportunity product.	
        // @modification: Anjani Shukla:SFDC1-8147-Product - New Cross Plant status and availability functionaliy				 	
		//------------------------------------------------ 
		
        if(optyProdLineDetailsLst.size() > 0 && product2DetailsLst.size() > 0) {
            for(OpportunityLineItem objOptyLineItem: optyProdLineDetailsLst) {
                for( Product2 objProd: product2DetailsLst ) {
                    system.debug('objOptyLineItem.Product2Id-->'+objOptyLineItem.Product2Id);
                    system.debug('objProd.id-->'+objProd.id);
					if(objOptyLineItem.Product2Id == objProd.id) {
                        /*if(objProd.ProductStatus__r.name != 'Available for Sale' && objProd.ProductStatus__r.SAPCode__c != '04') {
                        //errorMsgRecord.put(objOptyLineItem.name,objProd.name);
                        	errorMsgRecord.add(objOptyLineItem.Product2.Name);
                        } */
                        //SFDC1-8147-Product - New Cross Plant status and availability functionaliy
                        if((objOptyLineItem.Opportunity.OpportunityRecordType__c == 'Renewal'    || 
                            objOptyLineItem.Opportunity.OpportunityRecordType__c == 'InnerYear') && 
                           ((objProd.ProductStatus__r.name != 'Renewal Only' && objProd.ProductStatus__r.SAPCode__c != '09') && 
                            ( objProd.ProductStatus__r.name != 'Available for Sale' && objProd.ProductStatus__r.SAPCode__c != '04')) &&
                             objOptyLineItem.Status__c != 'Lost') 
                            { 
                        	   errorMsgRecord.add(objOptyLineItem.Product2.Name);
                        }
                        
                        //SFDC1-8147-Product - New Cross Plant status and availability functionaliy
                        
                        if((objOptyLineItem.Opportunity.OpportunityRecordType__c == 'New Business' || 
                            objOptyLineItem.Opportunity.OpportunityRecordType__c == 'Gratis' || 
                            objOptyLineItem.Opportunity.OpportunityRecordType__c == 'Forecasting Placeholder') &&
                           (objProd.ProductStatus__r.name != 'Available for Sale') && 
                           (objProd.ProductStatus__r.SAPCode__c != '04')) {
                        	    errorMsgRecord.add(objOptyLineItem.Product2.Name);
                        }
                    }    
                }            
            }
        }
        
        if(!errorMsgRecord.isEmpty()) {
        	flagtoshowMsg = true;    
        } 
		else {
            flagtoshowMsg = false;
        }
        system.debug('flagtoshowMsg'+flagtoshowMsg);
        return errorMsgRecord;
    }    
}