src/objects/CustomLink__c.object
<CustomObject>
    <description>SFDC1-5622 to Store the Custom Links, easily find things like clicktools, forms or user request forms.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-5622 To check the URL is active or not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomLinkName__c</fullName>
        <description>SFDC1-5622 Custom Link Name</description>
        <inlineHelpText>Please Enter Name of the Custom Link</inlineHelpText>
        <label>Custom Link Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>SFDC1-5622 - Custom Link&apos;s URL</description>
        <inlineHelpText>Please Enter the URL</inlineHelpText>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Custom Link</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Custom Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomLinkController.cls
//-----------------------------
// @author: Vinod Merwade
// @date: 3 Nov 2017
// @description:  SFDC1-5622 Custom Links, to have a list of useful links on lightning home page.
// @return: NA
// @Company: Vertiba
//-----------------------------
public without sharing  class CustomLinkController {
  
//-----------------------------
// @author: Vinod Merwade
// @date: 3 Nov 2017
// @description:  Method to check logged in user is System Admin
// @return: Boolean
// @Company: Vertiba
//-----------------------------
/* //admin check is not required as functionality is desired for all the users
    @AuraEnabled
    public static boolean checkUserIsAdmin() {
        system.debug('Admin Test'+UserInfo.getUserName());
        Id profileId = userInfo.getProfileId();
        system.debug('profileId----'+profileId);
        List<Profile> p = [select id, name from Profile where id=:profileId and name='System Administrator'];
        if(!p.isempty()) {
            system.debug('true');
            return true;
        }
        else {
            system.debug('false');
            return false;
        }
    }
*/
 //-----------------------------
// @author: Vinod Merwade
// @date: 3 Nov 2017
// @description:  SFDC1-5622 Custom Links, to have a list of useful links on lightning home page.
// @return: List of Custom Links
// @Company: Vertiba
//-----------------------------
    @AuraEnabled
    public static list<customLink__c> loadCustomLinks() {
        system.debug('custom Links');
        List<customLink__c> cl = [select CustomLinkName__c,url__c from customLink__c where active__c = true 
                                  order by CustomLinkName__c asc];
        system.debug('custom Links'+cl);
        return cl;
    }
    
}