src/objects/Family__c.object
<CustomObject>
    <description>SFDC1-131: This object holds Family related to Products</description>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-5469 Lookup to Product Group table.</description>
        <inlineHelpText>Lookup to Product Group table.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>ProductGroup__c</referenceTo>
        <relationshipName>Families</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Family</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MeetingAttendee__c.object
<CustomObject>
    <description>SFDC1-863; Meeting Attendee Object to Capture details of the Attendees</description>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>MAT-{000000000}</displayFormat>
        <label>Meeting Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MeetingNote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-863; Lookup to the Account</description>
        <inlineHelpText>Please Select the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Achieved__c</fullName>
        <description>SFDC1-863; Long text field for Achieved</description>
        <label>Achieved</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Info__c</fullName>
        <label>Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NextSteps__c</fullName>
        <label>Next Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductFamilyLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-3843 : This field will hold the values from the Product Family field</description>
        <inlineHelpText>Please Enter the Product Family</inlineHelpText>
        <label>Product Family</label>
        <referenceTo>Family__c</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Note</label>
    <nameField>
        <label>Meeting Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Notes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <description>SFDC1-7525 product family calculated from related products
SFDC1-8785 : updating the field type to Long Text Area</description>
        <inlineHelpText>Product family of related products automatically populated by system</inlineHelpText>
        <label>Product Family</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <description>SFDC1-5228 Account Overview Report, To store rollup comma separated unique Product Group values of related products at Opportunity record level.</description>
        <inlineHelpText>To display concatenated Product Groups in a single text field.</inlineHelpText>
        <label>Product Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProductGroup__c.object
<CustomObject>
    <description>Product Groups, previously known as product family in legacy Markit. 
A collection of high level product groups.</description>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestCreateMeetingNoteEventController.cls
/**
 * @Author:  Hemant Shukla
 * @Date:    2-Nov-2017
 * @description: Test class for CreateMeetingNoteEventController
**/

@IsTest
public class TestCreateMeetingNoteEventController {
    
    //
    // @Author: Hemant Shukla
    // @date: 2-Nov-2017
    // @description: To create a common Test records for all test methods
    // @param: null
    // @return: void
    // @Lastmodifiedby : Mohit Modi
    // @Lastupdated Date : 10 April 2018
    // @Lastupdated description: SFDC1-3843 : Changing the Field Type of ProductFamily__c from Picklist to Lookup
    //
    @testSetup static void setup() {
        
        Account a = TestUtility.createTestAccount('Meeting Notes Account 123',true);
        Opportunity o = TestUtility.createOpportunity(a.Id,'Test oppy meeting notes 123',null,true);
        
        Contact markitContact = TestUtility.createContact(a.Id,'hemant.shukla@ihsmarkit.com',true,'TestFirst','TestLast');
        Contact markitContact1 = TestUtility.createContact(a.Id,'testingmeetingnotes@gmail.com',true,'TestMFirst','TestMLast');
        
        //Assuming NRG recordtype exist in system
        ProductGroup__c pg = new ProductGroup__c();
        pg.Name = 'NRG';
        insert pg;

        //creating product family to test other scenarions
        Family__c pf = new Family__c();
        pf.Name = 'NRG Family';
        pf.ProductGroup__c = pg.Id;
        insert pf;
        
        Event e1 = new Event(whatId = o.Id, Subject = 'blabla', DurationInMinutes = 60, ActivityDateTime = Datetime.now(), ProductFamilyLookup__c =pf.id /* ProductFamily__c = '3rd Party Index Management' */);
        insert e1;
        
        Event e2 = new Event(whoId = markitContact.Id, Subject = 'blabla', DurationInMinutes = 60, ActivityDateTime = Datetime.now(), ProductFamilyLookup__c =pf.id /* ProductFamily__c = '3rd Party Index Management' */ );
        insert e2;
        
        Event e3 = new Event(Subject = 'blabla', DurationInMinutes = 60, ActivityDateTime = Datetime.now(), ProductFamilyLookup__c =pf.id /* ProductFamily__c = '3rd Party Index Management'*/);
        insert e3;
        
        EventRelation evr1 = new EventRelation(EventId = e1.Id, RelationId = markitContact.Id);
        insert evr1;
        
    }
    
    /**
     * @Author: Hemant Shukla
     * @date: 2-Nov-2017
     * @description: Test Method for validateEventForMeetingCreation() method
     * @param: null
     * @return: void
    */
    static testmethod void testValidateEventForMeetingCreation() {
        
        Test.startTest();
        //This will have WhatId
        Event e1 = [Select Id, WhatId, WhoId from Event where whatId != null];
        String message;
        message = CreateMeetingNoteEventController.validateEventForMeetingCreation(e1.Id);
        System.assertEquals('Create Meeting Note', message);
        
        //This will have AccoutId via whoId - contact
        Event e2 = [Select Id, WhatId, WhoId from Event where whoId != null];
        message = CreateMeetingNoteEventController.validateEventForMeetingCreation(e2.Id);
        System.assertEquals('Create Meeting Note', message);
        
        //This will neither have AccoutId not whatId
        Event e3 = [Select Id, WhatId, WhoId from Event where AccountId = null];
        message = CreateMeetingNoteEventController.validateEventForMeetingCreation(e3.Id);
        System.assertEquals('Please link this event to an Account or Opportunity.', message);
        Test.stopTest();
    }
    
    /**
     * @Author: Hemant Shukla
     * @date: 2-Nov-2017
     * @description: Test Method for getPrePopulatedMeetingNote() method
     * @param: null
     * @return: void
    */
    static testmethod void testGetPrePopulatedMeetingNote() {
        Test.startTest();
        
        //For Opportunity
        Event e1 = [Select Id, WhatId, WhoId from Event where whatId != null];
        Opportunity o = [Select Id, name from Opportunity limit 1];
        MeetingNote__c mnOpp = CreateMeetingNoteEventController.getPrePopulatedMeetingNote(e1.Id);
        
        String expectedName = System.now().date().format() +': Meeting for Opportunity: '+ o.name;
        System.assertEquals(expectedName , mnOpp.name);
        
        //For account
        Event e2 = [Select Id, WhatId, WhoId from Event where whoId != null];
        Account a = [Select Id, name from Account limit 1];
        MeetingNote__c mnAcc = CreateMeetingNoteEventController.getPrePopulatedMeetingNote(e2.Id);
        
        expectedName = 'Meeting with '+ a.name;
        System.assertEquals(expectedName , mnAcc.name);
        
        Test.stopTest();
         
    }    
    
    /**
     * @Author: Hemant Shukla
     * @date: 2-Nov-2017
     * @description: Test Method for getOpportunititesListToAdd() method
     * @param: null
     * @return: void
    */
    static testmethod void testGetOpportunititesListToAdd() {
        Test.startTest();
        
        Opportunity o = [Select Id, name from Opportunity limit 1];
        Account a = [Select Id, name from Account limit 1];
        
        //The blank option only
        List<Opportunity> opps = CreateMeetingNoteEventController.getOpportunititesListToAdd(new MeetingNote__c(Opportunity__c = o.id, Account__c = a.Id));
        System.assertEquals(1 , opps.size());
        
        List<Opportunity> opps1 = CreateMeetingNoteEventController.getOpportunititesListToAdd(new MeetingNote__c(Account__c = a.Id));
        System.assertEquals(2 , opps1.size());
        System.assertEquals(opps1[1].name, o.name);
        
        Test.stopTest();
    }    
    
    /**
     * @Author: Hemant Shukla
     * @date: 2-Nov-2017
     * @description: Test Method for addRelatedOpportunitiesForMeetingId() method
     * @param: null
     * @return: void
    */
    static testmethod void testAddRelatedOpportunitiesForMeetingId() {
        Test.startTest();
        Opportunity o = [Select Id, name from Opportunity limit 1];
        CreateMeetingNoteEventController.addRelatedOpportunitiesForMeetingId(null, o.id); 
        Test.stopTest();
    }
    
    /**
     * @Author: Hemant Shukla
     * @date: 2-Nov-2017
     * @description: Test Method for addMeetingAttendee() method
     * @param: null
     * @return: void
    */
    static testmethod void testAddMeetingAttendee() {
        Test.startTest();
        List<Contact> lstCon = [Select Id, name from Contact];
        CreateMeetingNoteEventController.addMeetingAttendee(lstCon[0].id);
        CreateMeetingNoteEventController.addMeetingAttendee(lstCon[1].id);
        Test.stopTest();
    }    
    
    /**
     * @Author: Hemant Shukla
     * @date: 2-Nov-2017
     * @description: Test Method for getMeetingAttendees() method
     * @param: null
     * @return: void
    */
    static testmethod void testGetMeetingAttendees() {
        Test.startTest();
        Event e1 = [Select Id, WhatId, WhoId from Event where whatId != null];
        CreateMeetingNoteEventController.getMeetingAttendees(e1.id, new MeetingNote__c());
        Test.stopTest();
    }
    
    /**
     * @Author: Hemant Shukla
     * @date: 2-Nov-2017
     * @description: Test Method for saveMeetingNotesAndRelatedData() method
     * @param: null
     * @return: void
    */
    static testmethod void testSaveMeetingNotesAndRelatedData() {
        Test.startTest();
        Event e1 = [Select Id, WhatId, WhoId from Event where whatId != null];
        MeetingNote__c mn1 = new MeetingNote__c(Name = 'TestMN', NextSteps__c = 'NS', Achieved__c = 'AC', Info__c = 'info');
        MeetingNote__c mn2 = new MeetingNote__c(Name = 'TestMN', NextSteps__c = 'NS', Achieved__c = 'AC', Info__c = 'info');
        MeetingNote__c mn3 = new MeetingNote__c(Name = 'TestMN', NextSteps__c = 'NS', Achieved__c = 'AC', Info__c = 'info');
        //First Screen
        CreateMeetingNoteEventController.saveMeetingNotesAndRelatedData(mn1, null, null, e1.Id); 
        
        //Second Screen
        Opportunity o = [Select Id, name from Opportunity limit 1];
        CreateMeetingNoteEventController.saveMeetingNotesAndRelatedData(mn2, new list<String>{o.Id}, null, e1.Id);
        
        //Third Screen
        List<cAttendee> attendeeList = new List<cAttendee>();
        List<Contact> lstCon = [Select Id, name from Contact limit 1];
        attendeeList.add(New cAttendee(new MeetingAttendee__c() , lstCon[0] , true)); 
        String jsonLstAttendees = JSON.serialize(attendeeList);
        CreateMeetingNoteEventController.saveMeetingNotesAndRelatedData(mn3, new list<String>{o.Id}, jsonLstAttendees, e1.Id);
        
        Test.stopTest();
    }
}