src/objects/InputFile__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.</description>
    <fields>
        <fullName>AdditionalInformation__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Additional Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NumberOfRecords__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Number Of Records</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Input Files</relationshipLabel>
        <relationshipName>InputFiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Input File</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Input Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkRequestForm__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.  Work Request Form Table</description>
    <label>Work Request Form</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InputFilesTabCE.cls
//-----------------------------
// @author: Legacy POLK Application
// @company: VERTIBA/POLK
// @date: 17 Oct 2017
// @param: NA
// @description:  This Class is related to Legacy POLK application.
// @return: NA
//----------------------------- 
public with sharing class InputFilesTabCE {
   
    public workrequestform__c wrf {get; set;}
    Public Attachment myfile;
    Public String wrfid {get; set;}
    Public String delid {get; set;}
    public List<InputFile__c> InputFileList;
    public MultiAttachmentController aMultiAttachmentController { get; set; }

    //-----------------------------
// @author: Legacy POLK Application
// @company: VERTIBA/POLK
// @date: 17 Oct 2017
// @param: NA
// @description:  This method is the contructor.
// @return: NA
//----------------------------- 
    public InputFilesTabCE ()
    { 
        aMultiAttachmentController = new MultiAttachmentController();
        wrfid='';
    }
      //-----------------------------
// @author: Legacy POLK Application
// @company: VERTIBA/POLK
// @date: 17 Oct 2017
// @param: NA
// @description:  This is a  refrerence method to reset the attachment  value.
// @return: Null
//-----------------------------   
    public PageReference reset() {
        if(wrf<>null){wrfid=wrf.id;}
        InputFileList = [Select i.NumberofRecords__c, i.AdditionalInformation__c ,
                         (select id,name,description,bodylength from Attachments) From InputFile__c i
                        where workrequestForm__c=:wrfid];
        
        for ( InputFile__c each : InputFileList )
        {
            aMultiAttachmentController.idAttachmentListMap.put ( each.Id, new list < Attachment > () );
            
            if ( each.Attachments != null )
            {
                aMultiAttachmentController.idAttachmentListMap.put ( each.Id, each.Attachments );
            }
        }
        
        return null;
    }
      //-----------------------------
// @author: Legacy POLK Application
// @company: VERTIBA/POLK
// @date: 17 Oct 2017
// @param: NA
// @description:  This add methods a new file to the wrf
// @return: Null
//-----------------------------  

    public PageReference add() {
        system.debug ( 'work request form id - ' + wrfid );
        InputFileList.add(new InputFile__c(workrequestForm__c=wrfid));
        return null;
    }

      //-----------------------------
// @author: Legacy POLK Application
// @company: VERTIBA/POLK
// @date: 17 Oct 2017
// @param: NA
// @description:  This is a save Input Files method
// @return: Null
//----------------------------- 
    public PageReference save() {
        upsert InputFileList;
        reset ();
        return null;
    }

      //-----------------------------
// @author: Legacy POLK Application
// @company: VERTIBA/POLK
// @date: 17 Oct 2017
// @param: NA
// @description:  This method helps retrieve input files
// @return: Input Files
//----------------------------- 
    public List<InputFile__c> getinputFiles() {
        if(InputFileList==null){
            reset();
        }
        return InputFileList;
    } 

    /*Public Attachment getmyfile(){
        myfile = new Attachment();
        return myfile;
    }
   
    Public Pagereference Savedoc()
    {
        String wid = wrfid;

        Attachment a = new Attachment(parentId = wid, name=myfile.name, body = myfile.body);
         */
         /* insert the attachment */
        /* insert a;
        return NULL;
    }*/

       //-----------------------------
// @author: Legacy POLK Application
// @company: VERTIBA/POLK
// @date: 17 Oct 2017
// @param: NA
// @description:  This method deletes input files
// @return: NA
//----------------------------- 
    public void DeleteAccount()
   {
      // if for any reason we are missing the reference 
      if (delid== null) {
      
         return;
      }
     
      // find the account record within the collection
      InputFile__c tobeDeleted = null;
      for(InputFile__c c : InputFileList)
       if (c.Id == delid) {
          tobeDeleted = c;
          break;
       }
      
      //if account record found delete it
      if (tobeDeleted != null) {
       Delete tobeDeleted;
      }
     
      //refresh the data
      reset();
   }
 
}