src/objects/InputFile__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.</description>
    <fields>
        <fullName>AdditionalInformation__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Additional Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NumberOfRecords__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Number Of Records</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Input Files</relationshipLabel>
        <relationshipName>InputFiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Input File</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Input Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkRequestForm__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.  Work Request Form Table</description>
    <label>Work Request Form</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestInputFilesTabCE.cls
//-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This test class is used in POLK WRF.
    // @return: NA
    //----------------------------- 
@isTest
private class TestInputFilesTabCE {
    
    public static testMethod void testInputFiles() {
        InputFilesTabCE controller = new InputFilesTabCE();
        controller.wrf = TestUtility.newWRF();
        controller.wrfid = controller.wrf.Id;
        controller.reset();
        controller.add();
         controller.InputFileList[0].NumberofRecords__c=500;
         controller.InputFileList[0].AdditionalInformation__c='test';
        controller.save();
        List<InputFile__c> testlist = [select id from InputFile__c where WorkRequestForm__c=:controller.wrf.id];
        system.assert(testlist.size()==1,'ERROR SAVING Input Files');
        controller.delid=testlist[0].id;
        controller.DeleteAccount();
        List<InputFile__c> testlist2 = [select id from InputFile__c where WorkRequestForm__c=:controller.wrf.id];
        system.assert(testlist2.size()==0,'ERROR DELETING INput FIle');
        controller.getinputFiles();
    }
   
    
}