src/objects/InternalData__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.</description>
    <fields>
        <fullName>ExpectedOutputQuanity__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Expected Output Quanity</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ManufacturerDivision__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Manufacturer/Division</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Internal Data</relationshipLabel>
        <relationshipName>InternalData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Internal Data</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Internal Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkRequestForm__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.  Work Request Form Table</description>
    <label>Work Request Form</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestInternalDataTabCE.cls
@isTest
private class TestInternalDataTabCE {
 
    public static testMethod void testInternalData() {
        InternalDataTabCE controller = new InternalDataTabCE();
        controller.wrf = TestUtility.newWRF();
        controller.wrfid = controller.wrf.Id;
        controller.reset();
        controller.add();
         controller.InternalDataList[0].ExpectedOutputQuanity__c='500';
         controller.InternalDataList[0].ManufacturerDivision__c='test';
        controller.save();
        List<InternalData__c> testlist = [select id from InternalData__c where WorkRequestForm__c=:controller.wrf.id];
        system.assert(testlist.size()==1,'ERROR SAVING Input Files');
        controller.delid=testlist[0].id;
        controller.DeleteAccount();
        List<InternalData__c> testlist2 = [select id from InternalData__c where WorkRequestForm__c=:controller.wrf.id];
        system.assert(testlist2.size()==0,'ERROR DELETING INput FIle');
        controller.getinternalData();
    }

    
}