src/objects/JobTask__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all PLC Jobs Tasks.</description>
    <fields>
        <fullName>JobName__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>PLCJob__r.JobName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PLCJob__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>PLC Job</label>
        <referenceTo>PLCJob__c</referenceTo>
        <relationshipLabel>Job Task</relationshipLabel>
        <relationshipName>JobTask</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Task</label>
    <nameField>
        <displayFormat>JT-{0000}</displayFormat>
        <label>Job Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PLCJob__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all PLC Jobs.</description>
    <fields>
        <fullName>CreateDocumentationTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Create Documentation Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreatePeerReviewTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Create Peer Review Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateSetupMeetingTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Create Setup Meeting Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobName__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>text(JobStatusOverride__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team1__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Programmer&apos;s Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aftersales-Chrysler</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>ESS-Delivery</fullName>
                </value>
                <value>
                    <fullName>Forecasting</fullName>
                </value>
                <value>
                    <fullName>MCM-Analytics</fullName>
                </value>
                <value>
                    <fullName>MCM-Marketing Databases</fullName>
                </value>
                <value>
                    <fullName>MCM-Market Research</fullName>
                </value>
                <value>
                    <fullName>MCM-Target Marketing Services</fullName>
                </value>
                <value>
                    <fullName>MEL-Delivery</fullName>
                </value>
                <value>
                    <fullName>MR-Aftermarket</fullName>
                </value>
                <value>
                    <fullName>MR-Commercial</fullName>
                </value>
                <value>
                    <fullName>MR-Loyalty</fullName>
                </value>
                <value>
                    <fullName>MR-Market Reporting BI</fullName>
                </value>
                <value>
                    <fullName>MR-Network Management</fullName>
                </value>
                <value>
                    <fullName>PolkConnect Analytics</fullName>
                </value>
                <value>
                    <fullName>PolkConnect System</fullName>
                </value>
                <value>
                    <fullName>VIN-Recall</fullName>
                </value>
                <value>
                    <fullName>VIN-VIN Decoders</fullName>
                </value>
                <value>
                    <fullName>VIN-VVS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PLC Job</label>
    <nameField>
        <displayFormat>PLC-{0000}</displayFormat>
        <label>PLC Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PLC Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPLCJobUtility.cls
//-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This is a test class  used in POLK WRF.
    // @return: NA
    //----------------------------- 
@isTest
private class TestPLCJobUtility {
      //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
    public static testMethod void testPLC() {  
        PLCJob__c plc = new PLCJob__c(JobName__c = 'Test', Team1__c = 'Test');
        insert plc;
        PLCJob__c plc2 = new PLCJob__c();
        insert plc2;
        
        PLCJobUtility controller = new PLCJobUtility(new ApexPages.StandardController(plc));
        apexPages.currentPage().getParameters().put('id',plc.id);
        
        controller.p = plc;
        controller.p.CreateSetupMeetingTask__c=true;
        controller.p.CreateDocumentationTask__c=true;
        controller.p.CreatePeerReviewTask__c=true;
        controller.save_and_edit();
        controller.edit();
        controller.createTasks();
        JobTask__c[] jtlist = [select id from JobTask__c where plcjob__c =:plc.id];
        system.assert(jtlist.size()>0);
        controller.Create_Cyclical_Jobs();
        controller.Create_Multipart_Jobs();
        
        controller.p = plc2;
        controller.save_and_edit(); 
    }
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
    public static testMethod void testValidPLC() {
        PLCJob__c plc = TestUtility.newCompletedPLC(TestUtility.newWRF(true));
        PLCJobUtility controller = new PLCJobUtility(new ApexPages.StandardController(plc));
        apexPages.currentPage().getParameters().put('id',plc.id);
        controller.p = plc;
        System.assertEquals(true, XedeUtility.validatePLC(plc));
        controller.save_and_edit();
        List<JobTask__c> openTasks = [SELECT Id FROM JobTask__c WHERE PLCJob__c=:plc.id AND Status__c <> 'Complete'];
        System.assertEquals(0, openTasks.size());
    }
       
}