src/objects/JobTask__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all PLC Jobs Tasks.</description>
    <fields>
        <fullName>PLCJob__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>PLC Job</label>
        <referenceTo>PLCJob__c</referenceTo>
        <relationshipLabel>Job Task</relationshipLabel>
        <relationshipName>JobTask</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Task</label>
    <nameField>
        <displayFormat>JT-{0000}</displayFormat>
        <label>Job Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PLCJob__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all PLC Jobs.</description>
    <fields>
        <fullName>CreateDocumentationTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Create Documentation Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreatePeerReviewTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Create Peer Review Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateSetupMeetingTask__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Create Setup Meeting Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobCompletedDelivered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Completed &amp; Delivered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>text(JobStatusOverride__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>PLC Job</label>
    <nameField>
        <displayFormat>PLC-{0000}</displayFormat>
        <label>PLC Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PLC Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PLCJobUtility.cls
//-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This class is used in POLK WRF.

    //----------------------------- 
public with sharing class PLCJobUtility {

    public PLCJob__C p {get; set;} 
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: String
    //----------------------------- 
    public String showMessage {

                get;
                set;

        }

    public ApexPages.StandardController con;
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: ApexPages.StandardController
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
    public PLCJobUtility(ApexPages.StandardController controller) {
        con  = controller;
        this.p = (PLCJob__C)Controller.getRecord();
        
    }
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: PageReference 
    //----------------------------- 
    public PageReference save_and_edit() {
        
        showMessage = 'False';
        boolean valid = XedeUtility.ValidatePLC(p);
        
        if (valid) {
                //System.debug('In Valid:'+valid);
                //return con.save();
                
                if(p.JobCompletedDelivered__c)
                    closeTask();
                
                upsert p;
                //PageReference pageRef = ApexPages.currentPage();
                PageReference pageRef = Page.PLCJobView;
                pageRef.getParameters().put('id',con.getId());
                pageRef.setRedirect(true);
                return pageRef;
                
        }
                
        else {
                //System.debug('In Else:'+valid);
                //upsert p;
                PageReference pageRef = ApexPages.currentPage();
                return pageRef;

        }
             
    } 
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
    private void closeTask() {
        List<JobTask__c> tasks = [
            SELECT Id, Status__c
            FROM JobTask__c
            WHERE Status__c <> 'Complete'
            AND PLCJob__c = :p.Id
        ];
        
        if(tasks.size() > 0) {
            tasks[0].Status__c='Complete';
            update tasks[0];
        }
    }
    
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: PageReference 
    //----------------------------- 
    public PageReference edit(){
        con.save();
        
        PLCJob__C p = [Select id From PLCJob__C Where Id = :ApexPages.currentPage().getParameters().get('id')];
        PageReference editPage = Page.PLCJobEdit;
        editPage.getParameters().put('id',p.id);
        editPage.setRedirect(true);
        return editPage; 
        
    }
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: PageReference 
    //----------------------------- 
    public pageReference CreateTasks(){
        
        con.save();
        
        PLCJob__C p = [Select id, ownerid,CreateSetupMeetingTask__c, 
                        CreateDocumentationTask__c, CreatePeerReviewTask__c //,
                        From PLCJob__C 
                        Where Id = :ApexPages.currentPage().getParameters().get('id')];
        
        if (p.CreateSetupMeetingTask__c == true) {
        
        XedeUtility.CreatePLCTask(p, 'Setup Meeting');
        
        }
        
        if (p.CreateDocumentationTask__c == true) {
        
        XedeUtility.CreatePLCTask(p, 'Documentation');
        
        }
        
        if (p.CreatePeerReviewTask__c == true) {
        
        XedeUtility.CreatePLCTask(p, 'Peer Review');
        
        }
        
                p.CreateDocumentationTask__c = false;
                p.CreatePeerReviewTask__c = false;
                p.CreateSetupMeetingTask__c = false;
                upsert p;
                showMessage = 'True';
                PageReference pageRef = ApexPages.currentPage();
                return pageRef;

    }
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: PageReference 
    //----------------------------- 
    public PageReference Create_Cyclical_Jobs() {
        
        con.save();
        PLCJob__C p = [Select id From PLCJob__C Where Id = :ApexPages.currentPage().getParameters().get('id')];

        PageReference nextPage = Page.PLCJobCloneCyclical;
        nextPage.getParameters().put('id',p.id);
        nextPage.setRedirect(true);
        return nextPage;     
    } 
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: PageReference 
    //----------------------------- 
    public PageReference Create_Multipart_Jobs() {
        
        con.save();
        PLCJob__C p = [Select id From PLCJob__C Where Id = :ApexPages.currentPage().getParameters().get('id')];

        PageReference nextPage = Page.PLCJobCloneMultipart;
        nextPage.getParameters().put('id',p.id);
        nextPage.setRedirect(true);
        return nextPage;     
    } 

}