src/objects/MeetingAttendee__c.object
<CustomObject>
    <description>SFDC1-863; Meeting Attendee Object to Capture details of the Attendees</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IHSMarkitEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IHS Markit Employee?</label>
        <type>Checkbox</type>
    </fields>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>MAT-{000000000}</displayFormat>
        <label>Meeting Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/cAttendee.cls
/**
 * @Author:  Hemant Shukla
 * @Date:    08-Jan-2018
 * @description: Wrapper class to show the attendees on Meeting Notes Lightning component
**/
public class cAttendee {
    @AuraEnabled
    public MeetingAttendee__c attendee;
    @AuraEnabled
    public Contact contact ;
    @AuraEnabled
    public String isIHSEmployee ;
    
    public cAttendee(MeetingAttendee__c ma, Contact con, boolean employee) {
        attendee = ma;
        contact = con;
        ma.Contact__c = con.Id;
        
        if(employee) {
            attendee.IHSMarkitEmployee__c = true;
            isIHSEmployee = 'Yes';
        } else {
            attendee.IHSMarkitEmployee__c = false;
            isIHSEmployee = 'No';
        }
    }
}