src/objects/MeetingAttendee__c.object
<CustomObject>
    <description>SFDC1-863; Meeting Attendee Object to Capture details of the Attendees</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IHSMarkitEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IHS Markit Employee?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Meeting Attendees</relationshipLabel>
        <relationshipName>MeetingAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>MAT-{000000000}</displayFormat>
        <label>Meeting Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MeetingNote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-863; Lookup to the Account</description>
        <inlineHelpText>Please Select the Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttendeeNames__c</fullName>
        <inlineHelpText>Please Enter Client Attendee&apos;s Name</inlineHelpText>
        <label>Client Attendee Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IHSMarkitAttendeeNames__c</fullName>
        <inlineHelpText>Please Enter IHS Markit Attendee&apos;s Name</inlineHelpText>
        <label>IHS Markit Attendee Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InternalContactLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Add non-salesforce users</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only send meeting notes to internal customers.</errorMessage>
            <filterItems>
                <field>Contact.Email</field>
                <operation>contains</operation>
                <value>@ihsmarkit.com</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Meeting Notes (Add non-salesforce users)</relationshipLabel>
        <relationshipName>MeetingNotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Meeting Notes</relationshipLabel>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Recipients</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MeetingNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Note</label>
    <nameField>
        <label>Meeting Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Notes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RelatedOpportunity__c.object
<CustomObject>
    <description>SFDC1-863; Related Opportunity Object is a Junction Object between Opportunities and Meeting Note</description>
    <fields>
        <fullName>MeetingNote__c</fullName>
        <label>Meeting Note</label>
        <referenceTo>MeetingNote__c</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>RelatedOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Opportunity</label>
    <nameField>
        <displayFormat>RO-{000000000}</displayFormat>
        <label>Related Opportunity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSendMeetingNote.cls
/**
 * @author Modified By: Vishnu Vardhan
 * @date: 7 Jul 2017
 * @description: Migrated class from existing Markit System and added comments. 
 * 		Class to Test SendMeetingNoteToAccountTeam and SendMeetingNoteToOpportunityTeam
 * @Updated By: Hemant Shukla
 * @Updated On: 23 Jan, 2018
 * @Description: SFDC1-6727, Updated the lookup filter for InternalContactLookup__c hence need to change the email of contact. 
 **/
@IsTest(SeeAllData=false)
public class TestSendMeetingNote {
	
    /**
     * @Author: Vishnu Vardhan
     * @date: 7 Jul 2017
     * @description: method to test weather meeting note is sent to opportunity and account team.
     * @param: null
     * @return: void
     */
    static testmethod void testCreateMeetingNoteFromAccount() {

        User u = TestUtility.createAdminUser('testmeetingnotesuser@markit.com',true);
        User u2 = TestUtility.createAdminUser('testmeetingnotesuserother@markit.com',true);
        
        System.runAs(u) {
            Account a = TestUtility.createTestAccount('Meeting Notes Account 123',true);
            Opportunity o = TestUtility.createOpportunity(a.id, 'Test Opportunity',null,true);
            TestUtility.createOpportunityTeamMember(o.Id, u2.Id, 'Edit',true);
            Contact markitContact = TestUtility.createContact(a.Id,'testingmeetingnotes@ihsmarkit.com',true, 'FirstName', 'LastName');
            Contact sfAdmin = TestUtility.createContact(a.id,'sfadmin@markit.com',true, 'NameFirst', 'NameLast');
            MeetingNote__c mn = new MeetingNote__c(Account__c = a.Id, Name = 'test1243', Opportunity__c = o.Id,InternalContactLookup__c = markitContact.Id);
            insert mn;
            RelatedOpportunity__c testRO = new RelatedOpportunity__c(MeetingNote__c=mn.Id,Opportunity__c=o.Id);
            insert testRO;
            MeetingAttendee__c ma = new MeetingAttendee__c(IHSMarkitEmployee__c = true, MeetingNote__c = mn.Id, Contact__c = markitContact.Id);
            insert ma;
            AccountTeamMember atm = new AccountTeamMember(AccountId = a.Id ,TeamMemberRole = 'Pending Update',UserId = u2.Id);
            insert atm;
            Test.startTest();
            
            Test.setCurrentPage(Page.SendMeetingNoteToAccountTeam);
            Apexpages.currentPage().getParameters().put('meetingId', mn.Id);
            
            SendMeetingNoteToAccountTeam ctrl = new SendMeetingNoteToAccountTeam();
            
            List<SendMeetingNoteToAccountTeam.cRecipient> assertRecepients= ctrl.getRecipients();
            System.assertNotEquals(0,assertRecepients.size());
            ctrl.meeting.UserLookup__c = u2.Id;
            
            ctrl.addRow();
            Integer listSize = ctrl.recipientList.size();
            system.assert(listSize>2);
            ctrl.sendEmail();
            MeetingNote__c assertMeeting = [Select id, AttendeeNames__c, IHSMarkitAttendeeNames__c from MeetingNote__c where id =: mn.Id limit 1];
            System.debug('assertMeeting'+assertMeeting);
            system.assertEquals(null, assertMeeting.AttendeeNames__c);
            System.assertNotEquals(null, assertMeeting.IHSMarkitAttendeeNames__c);
            ctrl.deleteNum = 1;
            ctrl.deleteRow();
            System.debug('ctrl '+ctrl);
            system.assert(ctrl.recipientList.size()<listSize);
            ctrl.cancel();
            Test.setCurrentPage(Page.SendMeetingNoteToOpportunityTeam);
            Apexpages.currentPage().getParameters().put('meetingId', mn.Id);
            
            SendMeetingNoteToOpportunityTeam ctrl2 = new SendMeetingNoteToOpportunityTeam();
            
            List<SendMeetingNoteToOpportunityTeam.cRecipient> assertRecepients2= ctrl2.getRecipients();
            System.assertNotEquals(0,assertRecepients2.size());
            ctrl2.meeting.UserLookup__c = u2.Id;
            ctrl2.addRow();
            Integer listSize2 = ctrl2.recipientList.size();
            system.assert(listSize2>2);
            ctrl2.sendEmail();
            ctrl2.deleteNum = 1;
            ctrl2.deleteRow();
            system.assert(ctrl2.recipientList.size()<listSize2);
            ctrl2.cancel();
            Test.stopTest();
        }
    }
}