src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MISAttachmentAdded__c</fullName>
        <description>SFDC1-2243 Whenever an Attachment is added to an opportunity,  MISAttachmentAdded field is auto populated with the current timestamp.</description>
        <inlineHelpText>System Managed Field. This field is used for MIS pipeline reporting. Whenever an Attachment is added to an opportunity,  MISAttachmentAdded field is auto populated with the current timestamp.</inlineHelpText>
        <label>MIS Attachment Added</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityAttachment__c.object
<CustomObject>
    <description>SFDC1-661 Object to define what kind of attachment users are adding to an Opportunity</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>SFDC1-661 to define what kind of attachment users are adding to an Opportunity</description>
        <inlineHelpText>Please select the kind of attachment you are adding to an Opportunity</inlineHelpText>
        <label>Attachment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Discount Approval</fullName>
                </value>
                <value>
                    <fullName>End User Certificate</fullName>
                </value>
                <value>
                    <fullName>Final Proposal</fullName>
                </value>
                <value>
                    <fullName>Pricing Sheet</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Quote Created</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>SFDC1-661 Opportunity to which this contact attachment is associated</description>
        <inlineHelpText>Please select an opportunity to which this contact attachment is associated</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Attachments</relationshipLabel>
        <relationshipName>OpportunityAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Attachment</label>
    <nameField>
        <label>Opportunity Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAttachmentMethods.cls
// @author: Uttam Arya
// @date: 31 Aug 2017
// @param: NA
// @description: Test class for Attachment trigger methods 
// @return: NA
//-----------------------------

@isTest
private class TestAttachmentMethods {
    
    //-----------------------------
    // @author: Uttam Arya
    // @date: 31 Aug 2017
    // @param: NA
    // @description: SFDC1-2243 Test method for Attachment trigger methods populateAttachmentAddedInOpportunityWhenAttachmentIsInserted on insert
    // @return: NA
    // @Modifiedby: Mohit Modi
    // @Modified Description: 06 Nov 2017 : Updated Test Method logic to capture the attahment added on Opportunity Attachment as well.
    //-----------------------------
    private static testMethod void testpopulateAttachmentAddedInOpportunityWhenAttachmentIsInserted() {
        
        Account acct = TestUtility.createTestAccount('Test Attachmnet Insertion', true);
        Opportunity oppt = TestUtility.createOpportunity(acct.Id, 'Test Oppy Attachment', true);
        
        OpportunityAttachment__c oppAtt = new OpportunityAttachment__c(AttachmentType__c = 'Final Proposal',Opportunity__c =oppt.id );
        insert oppAtt ;
        
        Blob attachBody = Blob.valueOf('attachment body');
        Attachment attach = new Attachment(Name = 'TestAttachment', ParentId = oppt.Id, Body = attachBody);
        Attachment attach1 = new Attachment(Name = 'TestAttachment1', ParentId = oppAtt.Id, Body = attachBody);
        insert new list<Attachment>{attach,attach1};
        
        //Assert if MIS field is inserted
        Opportunity opp = [select MISAttachmentAdded__c from Opportunity where Id =: oppt.Id];
        
        System.assertNotEquals(opp.MISAttachmentAdded__c, null);
        
    }
}