src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>GAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-412 Global Account Manager can only be updated by System Administrators and GAM Administrators.
SFDC1-4204 : Updated Lookup filter to allow only Salesforce Users.
SFDC1-6960:  Relabeling the GAM field to Account Manager</description>
        <inlineHelpText>Global Account Manager can only be updated by System Administrators and GAM Administrators.</inlineHelpText>
        <label>Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Placeholder</fullName>
        <active>true</active>
        <businessProcess>Forecasting Placeholder Process</businessProcess>
        <description>For Retail Business</description>
        <label>Forecasting Placeholder</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Business</businessProcess>
        <description>For Renewal use only</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ADID__c</fullName>
        <description>SFDC1-199 Unique ID for the employee used also for Single Sign On</description>
        <inlineHelpText>Unique Id for the employee generated by HR</inlineHelpText>
        <label>AD ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>SFDC1-8976 : As standard &apos;Employee Number&apos; Field can not be marked as External Id, creating new custom field for the same.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Workday ID of any IHS Markit Employees, consultants and channel partners. This field is used to synch HR data with the quota database and workday system to Salesforce.</inlineHelpText>
        <label>Employee Number</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HRManager__c</fullName>
        <description>SFDC1-199 HR managers full name as defined in the HR file</description>
        <inlineHelpText>Managers full name to be provided by HR</inlineHelpText>
        <label>HR Manager</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestOpportunityNewButtonOverrideCE.cls
//-----------------------------
// @author Prachi Bhasin
// @date 7 July 2017
// @description:  Test class for OpportunityNewButtonOverrideCE class
// @return: NA
//-----------------------------
@isTest
private class TestOpportunityNewButtonOverrideCE {
    //-----------------------------
    // @author: Prachi Bhasin
    // @date: 7 July 2017
    // @param: NA
    // @description: Test method for PageLoad method
    // @return: NA
    //-----------------------------
    private static testMethod void testPageLoad() {
        
        Account a = TestUtility.createTestAccount('Account testSetCaseAdditionalFieldsObject', true);
        
        Contact c = new Contact();
        c.firstname = 'Test';
        c.lastname = 'testSetCaseAdditionalFieldsObject';
        c.AccountId = a.Id;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', firstName='test',HRManager__c='manager',LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@ihs456789.com',ADID__c='test'+system.now().millisecond(),EmployeeNumber=String.valueOf(Math.round(Math.random()*10000)),EmployeeNumber__c=String.valueOf(Math.round(Math.random()*10000)));
        insert u;
        
        
        Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Business').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId=a.id;
        opp.RecordTypeId = devRecordTypeId;
        opp.CloseDate = System.today()+2;
        opp.Amount = 123;
        opp.GAM__c = u.id;       
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        OpportunityNewButtonOverrideCE oppCntrl = new OpportunityNewButtonOverrideCE(sc);
        
        PageReference pg = oppCntrl.PageLoadEvent();
        
        Id renewalRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'Test Opp';
        opp1.AccountId=a.id;
        opp1.RecordTypeId = renewalRecordTypeId;
        opp1.CloseDate = System.today()+2;
        opp1.Amount = 123;
        opp1.GAM__c = u.id;     
        
        ApexPages.StandardController sc1 = new ApexPages.StandardController(opp1);
        OpportunityNewButtonOverrideCE oppCntrl1 = new OpportunityNewButtonOverrideCE(sc1);
        
        PageReference pg1 = oppCntrl1.PageLoadEvent();
        
        Id placeholderRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Forecasting Placeholder').getRecordTypeId();
        Opportunity opp2 = new Opportunity();
        opp2.Name = 'Test Opp';
        opp2.AccountId=a.id;
        opp2.RecordTypeId = placeholderRecordTypeId;
        opp2.CloseDate = System.today()+2;    
        
        ApexPages.StandardController sc2 = new ApexPages.StandardController(opp2);
        OpportunityNewButtonOverrideCE oppCntrl2 = new OpportunityNewButtonOverrideCE(sc2);
        
        PageReference pg2 = oppCntrl2.PageLoadEvent();
    }
}