src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>OpportunityName__c</fullName>
        <description>SFDC1-8125: Used in &quot;Contract Management&quot; case lightning page layout</description>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Opportunity Name</inlineHelpText>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PLCJob__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all PLC Jobs.</description>
    <fields>
        <fullName>CycleStart__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cycle__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Week Days</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Semi-Monthly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Six Week Cycle</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JobName__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobNumber__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ad Hoc</fullName>
                </value>
                <value>
                    <fullName>Ad-Hoc (non-cyclical)</fullName>
                </value>
                <value>
                    <fullName>Cyclical</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Estimate only</fullName>
                </value>
                <value>
                    <fullName>Internal Ad-Hoc</fullName>
                </value>
                <value>
                    <fullName>Internal Cyclical</fullName>
                </value>
                <value>
                    <fullName>Lights Out Process</fullName>
                </value>
                <value>
                    <fullName>Non-Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfCycles__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>MAX Number of Cycles = 50. You can repeat creating cyclical jobs if you need to add more than 50.</inlineHelpText>
        <label>Number Of Cycles</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PLC Jobs</relationshipLabel>
        <relationshipName>PLCJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Requested Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubmittedDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>PLC Jobs</relationshipLabel>
        <relationshipName>PLCJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PLC Job</label>
    <nameField>
        <displayFormat>PLC-{0000}</displayFormat>
        <label>PLC Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PLC Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>WRApprover__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC1-4349 User Fields for Polk Work Request Form</description>
        <label>WR Approver</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WorkRequestForm__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.  Work Request Form Table</description>
    <fields>
        <fullName>ApprovalDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CycleStart__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cycle__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Week Days</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Semi-Monthly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Six Week Cycle</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FormType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Form Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK. Denotes if a work request is internal</description>
        <label>Internal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSubmitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobNumber__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>if( Internal__c = True, &quot;I&quot;+InternalJob__c, RIGHT( OpportunityName__r.Opportunitynum__c , 8) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Internal Job Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ad Hoc</fullName>
                </value>
                <value>
                    <fullName>Cyclical</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
                <value>
                    <fullName>Non-Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfCycles__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Number Of Cycles</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OpportunityName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Work Request Forms</relationshipLabel>
        <relationshipName>Work_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OutputType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>Scroll down to see all of the selected values</inlineHelpText>
        <label>Output Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Comma Delimited (CSV)</fullName>
                </value>
                <value>
                    <fullName>Cube</fullName>
                </value>
                <value>
                    <fullName>Excel</fullName>
                </value>
                <value>
                    <fullName>Online System Access</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PDF</fullName>
                </value>
                <value>
                    <fullName>PowerPoint</fullName>
                </value>
                <value>
                    <fullName>Tableau VIZ</fullName>
                </value>
                <value>
                    <fullName>Text - Delimited by</fullName>
                </value>
                <value>
                    <fullName>Text - Fixed</fullName>
                </value>
                <value>
                    <fullName>Text - Fixed &amp; Comma</fullName>
                </value>
                <value>
                    <fullName>Word</fullName>
                </value>
                <value>
                    <fullName>XML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimarySalesContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Primary Sales Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProgrammerAssigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>The programmer to be assigned to the job.  If this field is left blank the user approving and/or assigning the job will be the programmer assigned.</inlineHelpText>
        <label>Programmer Assigned</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work_Request_Forms4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RejectionComments__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Rejection Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RequestStatus__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequestedDueDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>This is the date the customer requested the delivery</inlineHelpText>
        <label>Customer Requested Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubmittedDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>Work Request Form</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WRApprovalController.cls
/** -----------------------------------------------------------
 * Class Name: WRApprovalController
* -----------------------------------------------------------
* Description: Class which supports the approval, rejection, 
* and assign pending of submitted work requests.
* - ---------------------------------------------------------
* Created by: Xede Consulting Group, Inc.
* Modified by: 
* Date Modified: 
*/


public with sharing class WRApprovalController {
    
    public boolean isView{get; set;}
    public boolean rejected = false;
    public WorkRequestForm__c wrf {get; set;}
    public WRApprovalController(){
         
    }
    //Displays a form message if a work request has been submitted.     
    public String getPmsg() {
        if(wrf<>null && rejected == false){    
        return 'This '+wrf.FormType__c+' request ('+wrf.name+'), has been submitted for approval and processing.  It must be approved or rejected to proceed. \n PLEASE NOTE: Rejection comments are required when rejecting a WRF. ';
        }else if(wrf<>null && rejected == true) {
            return 'Error: Rejection comments are required when rejecting a WRF.';
        }else{
            return 'You have recieved this screen in error';
        }
    }

    //Checks to see if someone should see the approve, reject, approval pending buttons on a submitted work request.
   public boolean getcanApproveRecords() {
        boolean canApprove = false;
        User currentUser = new User();
        id currentUserID = UserInfo.getUserId();
        currentUser = [Select u.Username, u.UserType, u.UserRoleId, u.UserRole.name, profileid, profile.name, WRApprover__c from User u where id = :currentUserID];
        canApprove = (currentUser.wrapprover__c);
        system.debug('Testing: WRF ID::::' + wrf.OutputType__c);      
        return canApprove;       
    }
    
    //When someone "rejects" a work request submission, here's what happens.
    public PageReference rejected() {
        
        WorkRequestForm__c updatedWRF = [select id, requeststatus__c, programmerassigned__c, ownerID from WorkRequestForm__c where id = :wrf.id];
        
        rejected = true; 
        
        updatedWRF.requeststatus__c='Rejected';
        updatedWRF.RejectionComments__c = wrf.RejectionComments__c;
        
        string wrID = wrf.PrimarySalesContact__c;
        
        if(wrID == '' || wrID == null) {
            updatedWRF.ownerid = UserInfo.getUserId();
        }
        
        else {
            
            updatedWRF.ownerid=wrf.PrimarySalesContact__c;   
        }
        
        System.debug('The rejection comments value is: x' + wrf.RejectionComments__c + 'x');
        if(wrf.RejectionComments__c == '')
        {           
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Rejection comments are required when rejecting a WRF.'));
            //wrf.addError('WRF Status - Rejection comments are required when rejecting a WRF.');
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Rejection comments are required when rejecting a WRF.');
            ApexPages.addMessage(myMsg);
            
            
            System.debug('The rejection comments are blank ' + wrf.RejectionComments__c + 'x');
            
            //PageReference wrForm = Page.wrEdit;
            //wrForm.getParameters().put('ID',wrf.ID);
            //wrForm.setRedirect(True);
            //return wrForm;
            
        } else
        {               
            
            System.debug('The rejection comments are not blank ' + wrf.RejectionComments__c + 'x');
            
            updatedWRF.isSubmitted__c = false;
            updatedWRF.SubmittedDate__c = null;
            update updatedWRF;
            

            
        }

        System.debug('I got here.');

            PageReference wrForm = Page.WRFRedirect;
            wrForm.getParameters().put('id',wrf.ID);
            wrForm.setRedirect(True);
            return wrForm;
             

    }
    

    
    
    //When someone chooses assign pending, here's what happens.
    public PageReference assigned_pending() {
        
        WorkRequestForm__c updatedWRF = [select id, requeststatus__c, programmerassigned__c, ownerID from WorkRequestForm__c where id = :wrf.id];
                
        updatedWRF.requeststatus__c='Approval Pending';
        if (wrf.ProgrammerAssigned__c == NULL) {
            updatedWRF.OwnerId = UserInfo.getuserid();
        }
        
        else {
            
            updatedWRF.OwnerId = wrf.ProgrammerAssigned__c;
        }
        updatedWRF.ProgrammerAssigned__c = null;
        //updatedWRF.Rejection_Comments__c = 'N/A';
        update updatedWRF;
        
        PageReference wrForm = Page.WRFRedirect;
        wrForm.getParameters().put('ID',wrf.ID);
        wrForm.setRedirect(True);
        return wrForm;
    }
    
    //When someone approves a work request, here's what happens.
    public PageReference approved() {
        
        WorkRequestForm__c updatedWRF = [select id, requeststatus__c, programmerassigned__c, ownerID from WorkRequestForm__c where id = :wrf.id];
        
        updatedWRF.requeststatus__c='Approved';
        updatedWRF.ownerid=UserInfo.getuserid();
        updatedWRF.ApprovalDate__c=system.today();
        
        //Figure out who we should assign the job to
        if (wrf.ProgrammerAssigned__c == NULL) {
            wrf.OwnerId = UserInfo.getuserid();
        }
        
        else {
            
           wrf.OwnerId = wrf.ProgrammerAssigned__c;
        }
        
        updatedWRF.ProgrammerAssigned__c = null;
        //updatedWRF.Rejection_Comments__c = 'N/A';
        PLCJob__c newJob;
        
        newJob = new PLCJob__c();
        newJob.RequestedDate__c = wrf.RequestedDueDate__c;
        newJob.Opportunity__c = wrf.OpportunityName__c;
        newJob.JobName__c = wrf.Name;
        newJob.JobType__c = wrf.JobType__c;
        newJob.WorkRequestForm__c = wrf.ID;
        newJob.OwnerID = wrf.OwnerID;
        newJob.Cycle__c = wrf.Cycle__c;
        newJob.CycleStart__c = wrf.CycleStart__c;
        newJob.NumberofCycles__c = wrf.NumberofCycles__c;
        newJob.JobNumber__c = wrf.Internal__c ? wrf.JobNumber__c : null;
        
        //convert to datetime, then assign to submitted date
        Datetime dt = datetime.newInstance(wrf.SubmittedDate__c.year(), wrf.SubmittedDate__c.month(),wrf.SubmittedDate__c.day());
        newJob.SubmittedDate__c = dt;
    
        
        
        //Here we set the job number from the opportunity, with the old/new number format, EU/US org merge, etc. we have some checking to do!

        //if (wrf.JobNumber__c.StartsWith('I')) {
        //  
        //  string newJobNumber = wrf.JobNumber__c;
        //  newJob.Job_Number__c = newJobNumber;

        //}     

        //else if (wrf.Opportunity_Number__c<> null && wrf.Opportunity_Number__c.length() == 12) {
        //   string newJobNumber = wrf.Opportunity_Number__c;
        //     newJob.Job_Number__c = newJobNumber.substring(4,12);
        //}  
        //  
        //else if (wrf.Opportunity_Number__c<> null && wrf.Opportunity_Number__c.length() == 8) {
        //   string newJobNumber = wrf.Opportunity_Number__c;
        //     newJob.Job_Number__c = newJobNumber;
        //     newJob.Job_Number__c = wrf.Opportunity_Number__c;
        //}
        
        //else if (wrf.Opportunity_Number__c<> null && wrf.Opportunity_Number__c.StartsWith('NA')) {
        //  string newJobNumber = wrf.Opportunity_Number__c;
        //    newJob.Job_Number__c = newJobNumber.Replace('NA', '');
            
        //}
        
        //else if (wrf.Opportunity_Number__c<> null && wrf.Opportunity_Number__c.StartsWith('EU')) {
        //  
        //  string newJobNumber = wrf.Opportunity_Number__c;
        //    newJobNumber = newJobNumber.Replace('-','0');
        //  newJobNumber = newJobNumber.Replace('EU', '');           
        //   
        //}
        
        //If we have something crazy 
        //else newJob.Job_Number__c = 'Other';
            
     
        insert newJob;        
        update updatedWRF;
        
        PageReference jobPage = Page.PLCJobEdit;
        jobPage.getParameters().put('ID',newJob.ID);
        jobPage.setRedirect(True);
        return jobPage; 
    }

  
}