src/objects/OpportunityLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to schedule opportunity products in case of multi-year opportunities</description>
    <fields>
        <fullName>DiscountAmount__c</fullName>
        <description>SFDC1-1837 Amount of discount if discount type = Amount</description>
        <inlineHelpText>Amount of discount given</inlineHelpText>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DiscountPercent__c</fullName>
        <description>SFDC1-1837 percentage of discount if discount type = Percentage</description>
        <label>Discount %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DiscountType__c</fullName>
        <description>SFDC1-1837 Type of discount being applied to the Product</description>
        <label>Discount Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>No Discount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalListPrice__c</fullName>
        <description>SFDC1-1837 List price entered manually or in Markit&apos;s case = Price book list price</description>
        <inlineHelpText>Updated List Price</inlineHelpText>
        <label>Updated List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InstallmentYears__c</fullName>
        <description>SFDC1-1837 To store year of schedule of Opportunity product fetched from Product Schedule</description>
        <label>Installment Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityProductID__c</fullName>
        <description>SFDC1-2043 Opportunity product to relate OPS with related opportunity product line item.</description>
        <inlineHelpText>ID of related Opportunity Product</inlineHelpText>
        <label>Opportunity Product ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityProductScheduleKey__c</fullName>
        <description>SFDC1-2043 Unique key for Opportunity Product schedule. Combination of related Product Schedule + Related Oppy + Year of schedule</description>
        <inlineHelpText>Unique Identifier</inlineHelpText>
        <label>Opportunity Product Schedule Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriceBookListPrice__c</fullName>
        <description>SFDC1-1837 The list price populated from the Product schedule record</description>
        <inlineHelpText>List price of product from Product Schedules</inlineHelpText>
        <label>Price Book List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 related product schedule</description>
        <label>Product Schedule</label>
        <referenceTo>ProductSchedule__c</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-1843 Product related to Opportunity product schedule</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>SFDC1-1837 Redundant field to capture all info in OPS.</description>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesPrice__c</fullName>
        <description>SFDC1-1843 Sales price of the product on which product is being sold</description>
        <label>Net Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <description>SFDC1-1843 Total price of the producte. (External List Price - Discount) * qty</description>
        <inlineHelpText>Total Sales Price</inlineHelpText>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Opportunity Product Schedule</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ProductSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to hold multi-year product information</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 Product for which product schedule is created</description>
        <inlineHelpText>Related Product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Schedules</relationshipLabel>
        <relationshipName>ProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OppyProductSchedulesListController.cls
/**
 * @author: Paras Dhingra
 * @date : 17th Sep 2017
 * @description: SFDC1-101 Controller for lightning component to fetch related
 * 				Opportunity product schedules
*/

public class OppyProductSchedulesListController {
	@AuraEnabled
    public static List<OpportunityLineItemSchedule__c> getOppyProdSchedules(String oppyProdId){
        List<OpportunityLineItemSchedule__c> lstOppyProductSchds = [Select id, DiscountPercent__c,DiscountAmount__c,DiscountType__c,ExternalListPrice__c,
                                         InstallmentYears__c, OpportunityProductID__c, OpportunityProductScheduleKey__c,
                                         PriceBookListPrice__c, Product__c,ProductSchedule__c, SalesPrice__c, TotalPrice__c, Quantity__c, CurrencyISOCode from
                                         OpportunityLineItemSchedule__c where OpportunityProductID__c=:oppyProdId order by InstallmentYears__c ASC];
        //process percentages
        for(OpportunityLineItemSchedule__c ops : lstOppyProductSchds) {
            if(ops.DiscountPercent__c!=null) {
             	ops.DiscountPercent__c= ops.DiscountPercent__c/100;   
            }
        }
        return lstOppyProductSchds;
    }
}