src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Shows red flag if any product related to opportunity is discounted over threshold</description>
        <formula>IF( 
DiscountOverThreshold__c, 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;, 
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Red flag when one or more products discounted over threshold</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Discount threshold flag calculated from product and product schedules</description>
        <formula>IF(
DiscountPercentage__c &gt;  PricebookEntry.Product2.DiscountThreshold__c,
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &apos;red&apos;, 30,30) + &quot; This discount is higher than the discount threshold and will trigger an alert to your supervisor once you move the Opportunity into the negotiation stage!&quot;,
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &apos;green&apos;, 30,30)
)</formula>
        <inlineHelpText>The flag will set to Red if discount is over discount threshold on the Product</inlineHelpText>
        <label>Discount Threshold</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to schedule opportunity products in case of multi-year opportunities</description>
    <fields>
        <fullName>ProductSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 related product schedule</description>
        <label>Product Schedule</label>
        <referenceTo>ProductSchedule__c</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Product Schedule</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>DiscountThreshold__c</fullName>
        <description>SFDC1-4275 Threshold for maximum percent of discount that can be provided on a product</description>
        <inlineHelpText>Maximum discount (percentage) able to be applied</inlineHelpText>
        <label>Discount Threshold%</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to hold multi-year product information</description>
    <label>Product Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestOpportunityLineItemMYData.cls
//-----------------------------
// @author: Paras Dhingra
// @date: 15th May 2018
// @param: NA
// @description: SFDC1-7976 Test class for OpportunityLineItemMYData
// @company: IHS Markit
// @return: None
//------------------------------
@isTest
public class TestOpportunityLineItemMYData {
    //-----------------------------
    // @author: Prachi Bhasin
    // @date: 3 July 2017
    // @param: NA
    // @description: Test method for Opportunity trigger methods updateGAMOnOpportunityTeam on insert
    // @return: NA
    //-----------------------------
    private static testMethod void testOpportunityLineItemMYData() {
        //create test data
        OpportunityLineItemMYData oliMData = new OpportunityLineItemMYData();
        Loop.ExternalData.QueryRequestInfo requestInfo = new Loop.ExternalData.QueryRequestInfo();
        Account testAccount = TestUtility.createTestAccount('Test Account 1', true);
        Opportunity testOppy = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity 1',true);
        Product2 p1 = TestUtility.createProduct('Test Product 1', false);
        p1.DiscountThreshold__c = 10;
        Product2 p2 = TestUtility.createProduct('Test Product 2', false);
        p2.DiscountThreshold__c = 12;
        insert new List<Product2>{p1,p2};
        Id stdPricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe1 = TestUtility.createPriceBookEntry(stdPricebookId, p1.Id, false);
        PricebookEntry pbe2 = TestUtility.createPriceBookEntry(stdPricebookId, p2.Id, false);
        insert new List<PricebookEntry>{pbe1,pbe2};
        //Now create product schedules
        ProductSchedule__c ps1 = TestUtility.createProductSchedule(1223.23, '2017', '1 Year', '2017', p1.Id, false);
        ProductSchedule__c ps2 = TestUtility.createProductSchedule(2223.23, '2017', '3 Years', '2017', p2.Id, false);
        ProductSchedule__c ps3 = TestUtility.createProductSchedule(2323.23, '2018', '3 Years', '2017', p2.Id, false);
        ProductSchedule__c ps4 = TestUtility.createProductSchedule(2423.23, '2019', '3 Years', '2017', p2.Id, false);
        insert new List<ProductSchedule__c>{ps1,ps2,ps3,ps4};
        
        OpportunityLineItem oli1 = TestUtility.createOpportunityLineItem(testOppy.id, pbe1,false);
        OpportunityLineItem oli2 = TestUtility.createOpportunityLineItem(testOppy.id, pbe2,false);
        insert new List<OpportunityLineItem>{oli1,oli2};
        Test.startTest();
        //create Opportunity product schedules
        OpportunityLineItemSchedule__c ops1 = TestUtility.createOpportunityProductSchedule(testOppy.Id,ps1.Id,1223.23,1000,
                                                                                            'Amount', 223.23, 0.0, p1.Id, '2017', 2, 
                                                                                            oli1.Id,false);
        OpportunityLineItemSchedule__c ops2 = TestUtility.createOpportunityProductSchedule(testOppy.Id,ps2.Id,2223.23,2000,
                                                                                            'Amount', 223.23, 0.0, p2.Id, '2017', 1, 
                                                                                            oli2.Id,false);
        OpportunityLineItemSchedule__c ops3 = TestUtility.createOpportunityProductSchedule(testOppy.Id,ps3.Id,2323.23,2000,
                                                                                            'Amount', 323.23, 0.0, p2.Id, '2018', 1, 
                                                                                            oli2.Id,false);
        OpportunityLineItemSchedule__c ops4 = TestUtility.createOpportunityProductSchedule(testOppy.Id,ps4.Id,2323.23,2000,
                                                                                            'Amount', 423.23, 0.0, p2.Id, '2019', 1, 
                                                                                            oli2.Id,false);
        insert new List<OpportunityLineItemSchedule__c>{ops1,ops2,ops3,ops4};
        //start test
        requestInfo.RecordId = testOppy.id;
        oliMData.describeObjects(new List<String>(oliMData.getGlobalDescribe()));
        oliMData.getChildRelationships('OppyLineItem');
        List<Loop.ExternalData.Relationship> Relationships = new List<Loop.ExternalData.Relationship>();
        for(String str: oliMData.getGlobalDescribe()) {
            Loop.ExternalData.Relationship relationship = new Loop.ExternalData.Relationship();
            relationship.Name = str;
            Relationships.add(relationship);
        }
        requestInfo.Relationships = Relationships;
        Loop.ExternalData.QueryResultSet queryRS = oliMData.query(requestInfo);
        System.assert(queryRS!=null);
        Test.stopTest();
    }
}