src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <description>SFDC1-173 This formula field pulls in the material code from the related product.</description>
        <formula>PricebookEntry.Product2.MaterialCode__c</formula>
        <inlineHelpText>Material Code from Product Master</inlineHelpText>
        <label>Material Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Is this an existing, add on, or removal of this product compared to the previous opportunity?</description>
        <inlineHelpText>Status for that opportunity product - New, Existing or Lost</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Removal</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/OpportunityLineItemSchedule__c.object
<CustomObject>
    <description>SFDC1-2043 Object to schedule opportunity products in case of multi-year opportunities</description>
    <fields>
        <fullName>InstallmentYear__c</fullName>
        <description>SFDC1-1837 Field to fetch installment year from Product Schedule</description>
        <formula>ProductSchedule__r.InstallmentYear__c</formula>
        <label>Installment Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityProductID__c</fullName>
        <description>SFDC1-2043 Opportunity product to relate OPS with related opportunity product line item.</description>
        <inlineHelpText>ID of related Opportunity Product</inlineHelpText>
        <label>Opportunity Product ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-2043 Related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Product Schedules</relationshipLabel>
        <relationshipName>OpportunityProductSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFDC1-487 Ghost status field to store status of related opportunity product</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Product Schedule</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Product Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>GoverningExhibit__c</fullName>
        <description>SFDC1-7828: This field holds the Governing Exhibit value</description>
        <inlineHelpText>Governing Exhibit</inlineHelpText>
        <label>Governing Exhibit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityLineItemMYData.cls
//-----------------------------
// @author: Paras Dhingra
// @date: 15th May 2018
// @param: NA
// @description: SFDC1-7976 Generate relationship between opportunitylineitem and schedules to generate drawloop document
// @company: IHS Markit
// @return: None
//------------------------------
global class OpportunityLineItemMYData implements Loop.IApexDataSource {
    //-----------------------------
    // @author: Paras Dhingra
    // @date: 15th May 2018
    // @param: void
    // @description: SFDC1-7976 Method to declare objects for Drawloop
    // @company: IHS Markit
    // @return: Set<String> Set of objects setup for Drawloop
    //------------------------------
    public Set<String> getGlobalDescribe() {
        return new Set<String> {'OpportunityLineItemMYSchedules','OppyLineItem'};
    }
    //-----------------------------
    // @author: Paras Dhingra
    // @date: 15th May 2018
    // @param: List <string >objNames list of objects to be defined
    // @description: SFDC1-7976 Method to create definition of Opportunity related objects for Drawloop
    // @company: IHS Markit
    // @return: List <Loop.ExternalData.DataObject > a list of objects defined using loop api
    //------------------------------
    public List <Loop.ExternalData.DataObject >describeObjects(List <string >objNames) {
        List <Loop.ExternalData.DataObject > output = new List <Loop.ExternalData.DataObject >();
         for (string objectName :objNames) {
            List <Loop.ExternalData.FieldInfo > outputFields = new List <Loop.ExternalData.FieldInfo >();
            if (objectName == 'OpportunityLineItemMYSchedules') {
                //add standard opportunity product schedules fields and establish relationship
                Map<string, Schema.SObjectField> fields = Schema.sObjectType.OpportunityLineItemSchedule__c.fields.getMap();
                outputFields.addAll(createOutPutFields(fields));
                Loop.ExternalData.FieldInfo outputInfo = new Loop.ExternalData.FieldInfo('OLIReference', Schema.DisplayType.REFERENCE);
                outputInfo.referenceTo = 'OppyLineItem';
                outputFields.add(outputInfo);
                
            }
            else if(objectName == 'OppyLineItem') {
                Map<string, Schema.SObjectField> fields = Schema.sObjectType.OpportunityLineItem.fields.getMap();
                outputFields.addAll(createOutPutFields(fields));
                outputFields.add(new Loop.ExternalData.FieldInfo('Product2.Name', Schema.DisplayType.STRING));
                outputFields.add(new Loop.ExternalData.FieldInfo('ProductGoverningExhibit', Schema.DisplayType.STRING));
                
            }
            output.add(new Loop.ExternalData.DataObject(objectName, outputFields));
        }
        return output;
    }
    //-----------------------------
    // @author: Paras Dhingra
    // @date: 15th May 2018
    // @param: String Objectname object name for which children object are to be fetched
    // @description: SFDC1-7976 Method to establish parent-child relationship 
    //              between Opportunityp prod and oppy prod schedules
    // @company: IHS Markit
    // @return: Set<String> return a list of children object related to an object defined via Loop API
    //------------------------------
    public Set <string >getChildRelationships(string objectName) {
        Set<string> childObjectNames = new Set<string>();
        if (objectName == 'OppyLineItem') {
            childObjectNames.add('OpportunityLineItemMYSchedules');
        }
            
        return childObjectNames;
    }
    //-----------------------------
    // @author: Paras Dhingra
    // @date: 15th May 2018
    // @param: Loop.ExternalData.QueryRequestInfo requestInfo loop request param
    // @description: SFDC1-7976 Method to establish parent-child relationship 
    //              between Opportunityp prod and oppy prod schedules
    // @company: IHS Markit
    // @return: Loop.ExternalData.QueryResultSet resultset contains all the data required to establish relationship
    //------------------------------
    public Loop.ExternalData.QueryResultSet query(Loop.ExternalData.QueryRequestInfo requestInfo) {
        Loop.ExternalData.QueryResultSet results = new Loop.ExternalData.QueryResultSet();
        Loop.ExternalData.QueryResult opportunityLineItems = new Loop.ExternalData.QueryResult('OppyLineItem', new List<string>());
        Loop.ExternalData.QueryResult OLISchedules = new Loop.ExternalData.QueryResult('OpportunityLineItemMYSchedules', new List<string>());
        if (string.valueOf(requestInfo.RecordId).startswith(Schema.sObjectType.Opportunity.keyprefix)) {
            
            //fetch and process OpportunitylineItem fields
            List<String> opportunityLineItemFields = new List<String>(Schema.sObjectType.OpportunityLineItem.fields.getMap().keySet());
            List<String> OppyScheduleFields = new List<String>(Schema.sObjectType.OpportunityLineItemSchedule__c.fields.getMap().keySet());
            opportunityLineItemFields.add('Product2.Name');
            
            List<String> queryOpportunityLineItemFields = new List<String>();
            queryOpportunityLineItemFields.addAll(opportunityLineItemFields);
            queryOpportunityLineItemFields.add('PriceBookEntry.Product2.GoverningExhibit__c');
            opportunityLineItemFields.add('ProductGoverningExhibit');
            opportunityLineItems = new Loop.ExternalData.QueryResult('OppyLineItem', opportunityLineItemFields);
            for(OpportunityLineItem oli : (List<OpportunityLineItem>)queryCreator(
                queryOpportunityLineItemFields,'OpportunityLineItem','OpportunityId',requestInfo.RecordId,'=',' AND Status__c!= \'Lost\'','SortOrder, MaterialCode__c ASC')
            ) {
                List<string> oliFieldValues = new List<string>();
                    for (string field : queryOpportunityLineItemFields) {
                        oliFieldValues.add(getFieldValue(oli, field));
                    }
                    opportunityLineItems.rows.add(oliFieldValues);
            }
            //fetch and process opportunityLineItemschedules fields
            List<String> listOLISFields = new List<String>(OppyScheduleFields);
            listOLISFields.add('OLIReference');
            OLISchedules = new Loop.ExternalData.QueryResult('OpportunityLineItemMYSchedules', listOLISFields);
            for(OpportunityLineItemSchedule__c olis : (List<OpportunityLineItemSchedule__c>)queryCreator(
                OppyScheduleFields,'OpportunityLineItemSchedule__c','Opportunity__c',requestInfo.RecordId ,'=','','InstallmentYear__c ASC')
                ) {
                    List<string> olisFieldValues = new List<string>();
                    String OppyProductId = '';
                    for(String field : OppyScheduleFields) {
                        String fieldValue = getFieldValue(olis,field);
                        olisFieldValues.add(fieldValue);
                        if(field=='opportunityproductid__c') {
                            OppyProductId = fieldValue;
                        }
                    }
                    olisFieldValues.add(OppyProductId);
                    OLISchedules.rows.add(olisFieldValues);
                }
                
        }
        for (string objectName : requestInfo.GetObjectNames()) {
            if (objectName == 'OppyLineItem')
                results.add(opportunityLineItems);
            else if (objectName == 'OpportunityLineItemMYSchedules')
                results.add(OLISchedules);
        }
        return results;
    }
    //-----------------------------
    // @author: Paras Dhingra
    // @date: 15th May 2018
    // @param: Map<string, Schema.SObjectField> fields
    // @description: SFDC1-7976 convert salesforce fields into Loop API compatible fields
    // @company: IHS Markit
    // @return: List <Loop.ExternalData.FieldInfo > 
    //------------------------------
    private List <Loop.ExternalData.FieldInfo > createOutPutFields (Map<string, Schema.SObjectField> fields) {
        List <Loop.ExternalData.FieldInfo > outputFields = new List <Loop.ExternalData.FieldInfo >();
        for(string key: fields.keySet()) {
            Schema.DescribeFieldResult info = fields.get(key).getDescribe();
            Loop.ExternalData.FieldInfo outputInfo = new Loop.ExternalData.FieldInfo(info.getName(), info.getType());
            outputInfo.referenceTo = info.getReferenceTo().size() > 0 ? string.valueOf(info.getReferenceTo()[0]) : null;
            outputInfo.scale = info.getScale();
            outputInfo.label = info.getLabel();
            outputFields.add(outputInfo);
        }
        return outputFields;
    }
    private string getFieldValue(sObject obj, string field) {
        if (obj == null) return '';
        string[] fieldParts = field.split('\\.');
        if (fieldParts.size() == 3) {
            sObject sobj = obj.getSObject(fieldParts[0]);
            if (sobj == null) return '';
            sobj = sobj.getSObject(fieldParts[1]);
            if (sobj == null) return '';
            return string.valueOf(sobj.get(fieldParts[2]));
        }
        else if (fieldParts.size() == 2) {
            sObject sobj = obj.getSObject(fieldParts[0]);
            if (sobj == null) return '';
            return string.valueOf(sobj.get(fieldParts[1]));
        }
        return string.valueOf(obj.get(field));
    }
    //-----------------------------
    // @author: Paras Dhingra
    // @date: 15th May 2018
    // @param: Map<string, Schema.SObjectField> fields
    // @description: SFDC1-7976 this method generates a generice query and return requested records
    // @company: IHS Markit
    // @return: List<sObject> list of records searched through query
    //------------------------------
    private List<sObject> queryCreator(List<string> fields, string objectName, string idName, string recordId, string inOrEquals, string additionalfilters, string orderBy) {
        string soql = string.format(
            'SELECT {0} FROM {1} WHERE {2} {3} {4} {5} {6}',
            new List<string>{
                string.join(fields, ','),
                objectName,
                idName,
                inOrEquals,
                '\''+recordId+'\'',
                string.isBlank(additionalfilters)?'':additionalfilters,
                string.isBlank(orderBy) ? '' : 'ORDER BY '+orderBy
            }
        );
        return Database.query(soql);
    }
}