src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MISAttachmentAdded__c</fullName>
        <description>SFDC1-2243 Whenever an Attachment is added to an opportunity,  MISAttachmentAdded field is auto populated with the current timestamp.</description>
        <inlineHelpText>System Managed Field. This field is used for MIS pipeline reporting. Whenever an Attachment is added to an opportunity,  MISAttachmentAdded field is auto populated with the current timestamp.</inlineHelpText>
        <label>MIS Attachment Added</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1 -171; Look up field for any related opportunity on opportunity record/ pagelayout</description>
        <inlineHelpText>Please select a related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityAttachment__c.object
<CustomObject>
    <description>SFDC1-661 Object to define what kind of attachment users are adding to an Opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>SFDC1-661 Opportunity to which this contact attachment is associated</description>
        <inlineHelpText>Please select an opportunity to which this contact attachment is associated</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Attachments</relationshipLabel>
        <relationshipName>OpportunityAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Attachment</label>
    <nameField>
        <label>Opportunity Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AttachmentMethods.cls
//-----------------------------
// @author: Uttam Arya
// @date: 29 Aug 2017
// @param: NA
// @description: SFDC1-2243 Class to hold Attachment trigger methods 
// @return: NA
//-----------------------------
public class AttachmentMethods {

//-----------------------------
// @author: Uttam Arya
// @date: 22 Aug 2017
// @param: TriggerParameters tp
// @description: SFDC1-2243 Whenever an Attachment is added to an opportunity,  
//                  MISAttachmentAdded field is auto populated with the current timestamp. 
//                  This is used for MIS pipeline reporting.
//
// @return: None
// @Modifiedby: Mohit Modi
// @Modified Description: 06 Nov 2017 : Added the logic to capture the attahment added on Opportunity Attachment as well.
//------------------------------
    public static void populateAttachmentAddedInOpportunityWhenAttachmentIsInserted(TriggerParameters tp) {
    
        //List of Opportunity that needs to be updated    
        List <Opportunity > OpportunityToUpdate = new List <Opportunity>(); 
        set<id> setOpportunityAttId = new set<id>();
        
        String OppAttachmentkeyPrefix = UtilityClass.getObjectKeyPrefix('OpportunityAttachment__c');
        set<id> setOpportunityId = new set<id>();
        
        for(Attachment attachment: (List <Attachment>) tp.newList) {
            if(attachment.ParentId != null && String.valueOf(attachment.ParentId).startsWith('006')) {
               setOpportunityId.add(attachment.ParentId);
            }
            // Checking if attachment is added to Opportunity Attachment Record.
            if(attachment.ParentId != null && OppAttachmentkeyPrefix != NULL && String.valueOf(attachment.ParentId).startsWith(OppAttachmentkeyPrefix)) {
                setOpportunityAttId.add(attachment.ParentId);
                
            }
        }
        
        if(!setOpportunityAttId.isEmpty()) {
            for(OpportunityAttachment__c tempOppAttach : [select id,Opportunity__c from OpportunityAttachment__c where id in : setOpportunityAttId]) {
                setOpportunityId.add(tempOppAttach.Opportunity__c);
            }
        }
        
        for(id oppid : setOpportunityId) {
            OpportunityToUpdate.add(new Opportunity(Id = oppid , MISAttachmentAdded__c = Datetime.now()));
        }
        
        //update if list has any records
        if(OpportunityToUpdate != null && OpportunityToUpdate.size() > 0) {
            update OpportunityToUpdate;
        }
    }
}