src/objects/OrderRequest__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.</description>
    <fields>
        <fullName>ProductionComments__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Production Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WorkRequestForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Work Request Form</label>
        <referenceTo>WorkRequestForm__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Order Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkRequestForm__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.  Work Request Form Table</description>
    <fields>
        <fullName>FormType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Form Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Work Request Form</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestMultiAttachmentController.cls
/******************************************************
 * @author Ankita Singh
 * @date 10thOct 2017
 * @description Test class for unit testing on MultiAttachmentController
    ******************************************************/
    
@isTest(seeAllData=false)
private class TestMultiAttachmentController {  

    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //-----------------------------     
    public static testMethod void testMultiAttachment() {
        
        WorkRequestForm__c newWrf = new WorkRequestForm__c();
        newWrf.FormType__c = 'TLAS';
        upsert newWrf;
        
        List<orderrequest__c> orList = new List<orderrequest__c>();

        OrderRequest__c o = new orderrequest__c();
        o.ProductionComments__c = 'Test';
        o.WorkRequestForm__c = newWrf.id;
        insert o;
        
         MultiAttachmentController con = new MultiAttachmentController ();
        con.attacher = 'true';
        con.sobjId=o.id;
        
        //System.assertEquals ( 0, con.getAttachments ().size () );
        
        System.assertEquals ( 1, con.newAttachments.size () );
        
        con.addMore ();
        
    //    System.assertEquals ( 1 + NUM_ATTACHMENTS_TO_ADD, con.newAttachments.size () );
        
        // populate the first and third new attachments
        List < Attachment > newAtts = con.newAttachments;
        newAtts [ 0 ].Name = 'Unit Test 1';
        newAtts [ 0 ].Description = 'Unit Test 1';
        newAtts [ 0 ].Body = Blob.valueOf ( 'Unit Test 1' );

        newAtts [ 2 ].Name = 'Unit Test 2';
        newAtts [ 2 ].Description = 'Unit Test 2';
        newAtts [ 2 ].Body = Blob.valueOf ( 'Unit Test 2' );
        
        con.save ();
        

   
  Attachment attachments=[select id, name from Attachment where parent.id=:o.id Limit 1];     
  MultiAttachmentController.DeleteAttachment(attachments.id);
con.reset();
        con.done();

   }
    
}