src/objects/PLCJob__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to track all PLC Jobs.</description>
    <fields>
        <fullName>CycleOccurance__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle Occurance</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CycleStart__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cycle__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Week Days</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Semi-Monthly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Six Week Cycle</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EncryptionKey__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Encryption Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EncryptionRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>Encryption Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FTPInformationInWRF__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP Information In WRF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FTPPassword__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP Password</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FTPPath__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP Path</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FTPRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FTPUserID__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>FTP User ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobName__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ad Hoc</fullName>
                </value>
                <value>
                    <fullName>Ad-Hoc (non-cyclical)</fullName>
                </value>
                <value>
                    <fullName>Cyclical</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Estimate only</fullName>
                </value>
                <value>
                    <fullName>Internal Ad-Hoc</fullName>
                </value>
                <value>
                    <fullName>Internal Cyclical</fullName>
                </value>
                <value>
                    <fullName>Lights Out Process</fullName>
                </value>
                <value>
                    <fullName>Non-Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NegotiatedDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>If no Negotiated Date was provided, use the date from Requested Due Date to populate this required field</inlineHelpText>
        <label>Negotiated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NumberOfCycles__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>MAX Number of Cycles = 50. You can repeat creating cyclical jobs if you need to add more than 50.</inlineHelpText>
        <label>Number Of Cycles</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OpportunityValue__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <formula>Opportunity__r.Amount</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PLC Jobs</relationshipLabel>
        <relationshipName>PLCJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OtherCostEstimate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <inlineHelpText>Royalties and other data cost</inlineHelpText>
        <label>Other Cost Estimate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ParentJob__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Job</label>
        <referenceTo>PLCJob__c</referenceTo>
        <relationshipLabel>PLC Jobs</relationshipLabel>
        <relationshipName>PLCJob</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PeerReviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used for WRF-POLK.</description>
        <label>Peer Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PLCJobs3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProcessToUse__c</fullName>
        <description>POLK-WRF: This field is used for WRF related feature on PLC Job object.</description>
        <label>Process To Use</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Analytics Custom Solution</fullName>
                </value>
                <value>
                    <fullName>Analytics Loyalty</fullName>
                </value>
                <value>
                    <fullName>Analytics Loyalty Compilation</fullName>
                </value>
                <value>
                    <fullName>Analytics Mapping</fullName>
                </value>
                <value>
                    <fullName>Analytics Modeling</fullName>
                </value>
                <value>
                    <fullName>Analytics Profile</fullName>
                </value>
                <value>
                    <fullName>China data-CV</fullName>
                </value>
                <value>
                    <fullName>China data-Polkinsight</fullName>
                </value>
                <value>
                    <fullName>Commercial Account File</fullName>
                </value>
                <value>
                    <fullName>Custom Solutions-OEM List</fullName>
                </value>
                <value>
                    <fullName>Custom Solutions-OEM Stat</fullName>
                </value>
                <value>
                    <fullName>Custom Solutions-Other</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Global NewReg</fullName>
                </value>
                <value>
                    <fullName>Global PARC</fullName>
                </value>
                <value>
                    <fullName>IFOF</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>NVPP</fullName>
                </value>
                <value>
                    <fullName>NVPP Online</fullName>
                </value>
                <value>
                    <fullName>PMC</fullName>
                </value>
                <value>
                    <fullName>PolkInsight</fullName>
                </value>
                <value>
                    <fullName>Recall</fullName>
                </value>
                <value>
                    <fullName>RSD</fullName>
                </value>
                <value>
                    <fullName>TIP</fullName>
                </value>
                <value>
                    <fullName>TIPNet System</fullName>
                </value>
                <value>
                    <fullName>TLAS</fullName>
                </value>
                <value>
                    <fullName>VIN Decoding Products Cyclical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequestedDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Requested Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TotalJobEstimate__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Programming Hours Estimate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WRFQuality__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Setup</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved, Set-up Required</fullName>
                </value>
                <value>
                    <fullName>Approved, No Set-up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PLC Job</label>
    <nameField>
        <displayFormat>PLC-{0000}</displayFormat>
        <label>PLC Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PLC Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PLCJobCloneUtility.cls
//-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This class is used in POLK WRF.
    // @return: NA
    //----------------------------- 
public with sharing class PLCJobCloneUtility {
 
    public list<PLCJob__C> newJobs {get; set;}
    private final PLCJob__C masterPLC;
    private final PLCJob__C clonedPLC;
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: ApexPages.StandardController
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
    public PLCJobCloneUtility(ApexPages.StandardController controller) {

    masterPLC = (PLCJob__C) controller.getRecord();
    clonedPLC = [select id, ownerid, jobname__c, JobType__c, NumberofCycles__c, 
        cyclestart__c, cycle__c, opportunity__c, opportunityvalue__c, processtouse__c,
        totaljobestimate__c, othercostestimate__c, currencyisocode, peerreviewer__c, encryptionrequired__c,
        encryptionkey__c, ftprequired__c, ftpinformationinwrf__c, ftppath__c, ftpuserid__c, ftppassword__c
        from PLCJob__C where id = :masterPLC.ID];
        
    id cloneID = clonedPLC.ID;
    date nextDate = clonedPLC.cyclestart__c;
    string nextDateDOW;
    newJobs = new list<PLCJob__C>();
    
        for (integer i = 1; i <= masterPLC.NumberofCycles__c; i++) {

            PLCJob__C tempPLC = clonedPLC.clone(false);
    
            if (tempPLC.Cycle__c == 'Week Days' && i <> 1) {
                nextDate = nextDate.addDays(1);
            }
            
            else if (tempPLC.Cycle__c == 'Weekly' && i <> 1) {
                nextDate = nextDate.addDays(7);
            }
            
            else if (tempPLC.Cycle__c == 'Semi-Monthly' && i <> 1) {
                nextDate = nextDate.addDays(15);
            }
            
            else if (tempPLC.Cycle__c == 'Monthly' && i <> 1) {
                nextDate = nextDate.addMonths(1);
            }
            
            else if (tempPLC.Cycle__c == 'Six Week Cycle' && i <> 1) {
                nextDate = nextDate.addDays(42);
            }
            
            else if (tempPLC.Cycle__c == 'Quarterly' && i <> 1) {
                nextDate = nextDate.addMonths(3);
            }
            
            else if (tempPLC.Cycle__c == 'Semi-Annually' && i <> 1) {
                nextDate = nextDate.addMonths(6);
            }
            
            else if (tempPLC.Cycle__c == 'Annually' && i <> 1) {
                nextDate = nextDate.addYears(1);
            }
            
            else if (tempPLC.Cycle__c == 'Other'&& i <> 1 ) {
                nextDate = nextDate.addDays(0);
            }
            
            datetime nextDateTime = datetime.newInstance(nextDate.year(), nextDate.month(),nextDate.day());
            nextDateDOW = nextDateTime.format('EEEE');
            
            //Backdate if Saturday or Sunday
            
            if (nextDateDOW == 'Saturday') {
                nextDate = nextDate.addDays(-1);
            }
            
            if (nextDateDOW == 'Sunday') {
                nextDate = nextDate.addDays(-2);
            }
            
            tempPLC.cycleoccurance__c = i;
            tempPLC.StartDate__c = nextDate;
            tempPLC.NegotiatedDate__c = nextDate;
            tempPLC.RequestedDate__c = nextDate;
            tempPLC.OwnerID = tempPLC.OwnerID;
            tempPLC.WRFQuality__c = 'No Set-up Required';
            tempPLC.ParentJob__c = cloneID;
            
            newJobs.add (tempPLC);
            
            //Since we want the next date to be based on the standard, not backdated next date, we'll reverse what we did
            //For the next loop
            
            if (nextDateDOW == 'Saturday') {
                nextDate = nextDate.addDays(1);
            }
            
            if (nextDateDOW == 'Sunday') {
                nextDate = nextDate.addDays(2);
            }

        }
    
    }
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: PageReference 
    //----------------------------- 
        public PageReference Cancel() {
        
        PLCJob__C p = [Select id From PLCJob__C Where Id = :ApexPages.currentPage().getParameters().get('id')];
        PageReference backPage = Page.PLCJobEdit;
        backPage.getParameters().put('id',p.id);
        backPage.setRedirect(true);
        return backPage;     
    } 
    
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: PageReference 
    //----------------------------- 
        public PageReference Create_Jobs() {
        
        insert newJobs;
        
        PLCJob__C p = [Select id From PLCJob__C Where Id = :ApexPages.currentPage().getParameters().get('id')];
        PageReference backPage = Page.PLCJobEdit;
        backPage.getParameters().put('id',p.id);
        backPage.setRedirect(true);
        return backPage;     
            
    }
     
    
}