src/objects/Queue__c.object
<CustomObject>
    <description>This object is used for WRF-POLK. Object to store all Production Team queues for the Work Request process.</description>
    <fields>
        <fullName>Queues__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Queues</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>APAC WRF</fullName>
                </value>
                <value>
                    <fullName>Australia WRF</fullName>
                </value>
                <value>
                    <fullName>Autonews</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>European WRF</fullName>
                </value>
                <value>
                    <fullName>Market Reporting - Analytics</fullName>
                </value>
                <value>
                    <fullName>Market Reporting - CAP</fullName>
                </value>
                <value>
                    <fullName>Market Reporting - Loyalty</fullName>
                </value>
                <value>
                    <fullName>Market Reporting - OEM Stat</fullName>
                </value>
                <value>
                    <fullName>MCM - Analytics</fullName>
                </value>
                <value>
                    <fullName>PolkConnect Analytics</fullName>
                </value>
                <value>
                    <fullName>PolkConnect System</fullName>
                </value>
                <value>
                    <fullName>VFACTS</fullName>
                </value>
                <value>
                    <fullName>VINtelligence - Recall</fullName>
                </value>
                <value>
                    <fullName>VINtelligence - SWS</fullName>
                </value>
                <value>
                    <fullName>Visualization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Queues</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkRequestForm__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.  Work Request Form Table</description>
    <fields>
        <fullName>FormType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Form Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Work Request Form</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestQueueViewCE.cls
//----------------------------- 
// @Author : Legacy POLK 
// @date: 11 Oct 2017 
// @description: Migrated from Legacy POLK 
// @PROGRAMMER: Anjani Shukla 
//-----------------------------
@isTest(SeeAllData=true)
private class TestQueueViewCE {
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
    static testMethod void myUnitTest() {
        Queue__c q = new queue__c();
        q.Queues__c = 'Market Reporting - Analytics';       
        ApexPages.StandardController sc = new ApexPages.StandardController(q);
        QueueViewCE myPageCon = new QueueViewCE(sc);  
        workrequestform__c w = new workrequestform__c();
        w.FormType__c = 'Analytics';
        upsert w;
        myPageCon.updateView();
        myPageCon.getWRFRecords();
        myPageCon.getCLRecords();
        myPageCon.getORRecords();
        
        
        
    }
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
      static testMethod void myUnitTest2() {
        Queue__c q = new queue__c();
        q.Queues__c = null;       
        ApexPages.StandardController sc = new ApexPages.StandardController(q);
        QueueViewCE myPageCon = new QueueViewCE(sc);  
        workrequestform__c w = new workrequestform__c();
        w.FormType__c = 'Analytics';
        upsert w;
        myPageCon.updateView();
        myPageCon.getWRFRecords();
        myPageCon.getCLRecords();
        myPageCon.getORRecords();
        
        
        
    }
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
         static testMethod void myUnitTest3() {
        Queue__c q = new queue__c();
        q.Queues__c = 'All';       
        ApexPages.StandardController sc = new ApexPages.StandardController(q);
        QueueViewCE myPageCon = new QueueViewCE(sc);  
        workrequestform__c w = new workrequestform__c();
        w.FormType__c = 'Analytics';
        upsert w;
        myPageCon.updateView();
        myPageCon.getWRFRecords();
        myPageCon.getCLRecords();
        myPageCon.getORRecords();
        
        
        
    }
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
    static testMethod void myUnitTest4() {
        Queue__c q = new queue__c();
        q.Queues__c = '';       
        ApexPages.StandardController sc = new ApexPages.StandardController(q);
        QueueViewCE myPageCon = new QueueViewCE(sc);  
        workrequestform__c w = new workrequestform__c();
        w.FormType__c = 'Analytics';
        upsert w;
        myPageCon.updateView();
        myPageCon.getWRFRecords();
        myPageCon.getCLRecords();
        myPageCon.getORRecords();
        
        
        
    }

}