src/objects/RenewalatRisk__c.object
<CustomObject>
    <description>SFDC1-4160 This object is used to identify a renewal at risk from an opportunity.
SFDC1-6706, label has been changed to &quot;Opportunity at Risk&quot;.</description>
    <fields>
        <fullName>OpportunityAtRisk__c</fullName>
        <description>SFDC1-4160 This field holds the Opportunity at Risk</description>
        <label>Opportunity At Risk</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity at Risk</relationshipLabel>
        <relationshipName>Renewals_at_Risk</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RiskCustomerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC1-4160 This field holds the name of the Customer&apos;s Name</description>
        <label>Risk Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Renewals_at_Risk</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity at Risk</label>
    <nameField>
        <displayFormat>OaR-{000000}</displayFormat>
        <label>Opportunity at Risk Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities at Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RenewalatRiskMethods.cls
//-----------------------------
// @author: Harshit Singhal
// @date: 19 Jun 2018
// @param: NA
// @description: SFDC1-8545 Class to hold RenewalatRiskTrigger methods 
// @return: NA
//-----------------------------
public class RenewalatRiskMethods {
	
    //-----------------------------
    // @author: Harshit Singhal
    // @date: 19 Jun 2018
    // @param: TriggerParameters tp
    // @description: SFDC1-8545 Convert Process Builder flow "UpdateRiskCustomerContactinOpportunityatRisk" on RenewalatRisk__c object created in SFDC1-6707(Updates to Opportunity at Risk Object when a new record is created) to a trigger
    // 				 This methods sets Risk Customer Contact field with Primary Contact of parent opportunity during before insert transactions.
    // 
    // @return: None
    //------------------------------
    public static void setRiskCustomerContactinOppatRisk(TriggerParameters tp) {        
        Set<Id> oppIdSet = new Set<Id>();
        Map<Id,Id> oppIdContactIdMap = new Map<Id,Id>();
        //Collect unique opportunity Ids
        for(RenewalatRisk__c newOaR: (List<RenewalatRisk__c>)tp.newList) {            
            if(newOaR.OpportunityAtRisk__c != null) {
                oppIdSet.add(newOaR.OpportunityAtRisk__c);
            }
        }        
        //Get Primary Contact of opportunities
        if(oppIdSet.size() > 0) {
            for(OpportunityContactRole oppConRole: [Select ContactId,OpportunityId From OpportunityContactRole Where isPrimary = true and OpportunityId In :oppIdSet]) {
                oppIdContactIdMap.put(oppConRole.OpportunityId, oppConRole.ContactId);
            }
        }        
        //Set Risk Customer Contact on Opportunity at Risk records
        for(RenewalatRisk__c newOaRtoUpdate: (List<RenewalatRisk__c>)tp.newList) {
            if(oppIdContactIdMap.containsKey(newOaRtoUpdate.OpportunityAtRisk__c)) {
                newOaRtoUpdate.RiskCustomerContact__c = oppIdContactIdMap.get(newOaRtoUpdate.OpportunityAtRisk__c);                
            }
        }        
    }
}