src/objects/WorkRequestForm__c.object
<CustomObject>
    <description>This object is used for WRF-POLK.  Work Request Form Table</description>
    <fields>
        <fullName>CarAndLightTruckDisplay__c</fullName>
        <description>This field is used for WRF-POLK. Holds value data for Car and Light Truck picklists displayed on VF page</description>
        <label>Car and Light Truck Display</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FormType__c</fullName>
        <description>This field is used for WRF-POLK.</description>
        <label>Form Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Work Request Form</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCarsNTrucks.cls
//-----------------------------
// @author: Legacy POLK Application
// @company: VERTIBA/POLK
// @date: 17 Oct 2017
// @param: 
// @description:  This class is used in POLK WRF.
// @return: NA
//----------------------------- 
@isTest
private class TestCarsNTrucks {
    //-----------------------------
    // @author: Legacy POLK Application
    // @company: VERTIBA/POLK
    // @date: 17 Oct 2017
    // @param: 
    // @description:  This method is used in POLK WRF.
    // @return: NA
    //----------------------------- 
    public static testMethod void testCarsNTrucksMethod() {
        WorkRequestForm__c wrf = new WorkRequestForm__c();
        wrf.FormType__c = 'TLAS';
        wrf.CarAndLightTruckDisplay__c = ';;;;;;;;;;;;;;;;;;;;;;;;;';
        insert wrf;
        CarsNTrucks ct = new CarsNTrucks(wrf.CarAndLightTruckDisplay__c);
        ct.gethasValues();
        
    }
}